src/components/alert-banner/index.tsx, src/components/alert-banner/style.module.css, src/components/product-switcher/style.module.css, src/layouts/docs/docs-layout.module.css, src/pages/_app.tsx, src/pages/style.css
🔎  [Preview link](https://dev-portal-git-ambadd-wip-banner-hashicorp.vercel.app/waypoint/docs)
🎟️  Asana tickets
- [Create AlertBanner component](https://app.asana.com/0/0/1201490161340315/f)
- [Add work in progress banner](https://app.asana.com/0/0/1201530235872969/f)
---
This PR adds a very basic `AlertBanner` component and renders one globally at the top of every page with a link to a feedback form. Questions about that form should be directed to @jescalan.
The colors introduced in the new component come from these `AlertBox` designs: https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/?node-id=1498%3A43240. The color for the globally rendered banner is a new one that isn't in those designs but was specifically requested in Slack. At the time of writing, it's called …
=> Add global WIP banner

next.config.js, src/components/swingset-color-token/docs.mdx, src/components/swingset-color-token/index.tsx, src/swingset-docs/color.mdx
👀 [Preview](https://dev-portal-git-zsadd-color-docs-hashicorp.vercel.app/swingset/docs/color)
This PR adds a rough docs page on color tokens to `/swingset`.
Preview:
> Note: Rendering this page in Swingset required a bit of an inconvenient workaround, using `peerComponents` in the `docs` page as Swingset does not yet support the `{ components }` option for docs pages. Intent here with this workaround was to avoid starting a yak-shaving session by trying to fix the underlying issue in `swingset`.
=> docs: add color page to swingset

.env
This PR restores `VERCEL_ENV="production"`. Without this, devs working locally would have to manually set this variable in order for Waypoint's remote content to work as expected.
=> fix: restore VERCEL_ENV to fix local dev experience

src/components/docs-anchor/__tests__/docs-anchor.test.tsx, src/components/docs-anchor/index.tsx, src/pages/waypoint/commands/[[...page]].tsx, src/pages/waypoint/docs/[[...page]].tsx, src/pages/waypoint/plugins/[[...page]].tsx
👀 [Preview](https://dev-portal-git-brkfeat-docs-anchor-hashicorp.vercel.app/waypoint/docs/intro)
Adding `DocsAnchor` to rewrite internal links so that they have the right product path segment. In the future it'd be ideal if we had some sort of `NavigationContext` which contained the current product and relevant base paths so that we didn't have to pass them in.
Usage:
```ts
import makeDocsAnchor from 'components/docs-anchor'
const components = {
a: makeDocsAnchor('waypoint', ['docs', 'commands', 'plugins'])
}
```
=> feat: Add DocsAnchor to fix internal links

src/components/breadcrumb-bar/index.tsx
👀 [Preview](https://dev-portal-git-zspatch-breadcrumb-html-issue-hashicorp.vercel.app/waypoint/docs/waypoint-hcl/build)
This PR fixes an issue with `<code>` element rendering in the `<BreadcrumbBar />` component.
<details>
<summary>Alternate treatment</summary>
This treatment renders the `<code>` element rather than stripping it out. It felt like more of a departure from the appearance of the rest of the breadcrumb bar, so was dropped in favour of stripping out HTML tags from titles when rendering them in the breadcrumb bar.
</details>
=> fix: patch code render in breadcrumbs

src/components/product-switcher/index.tsx, src/components/product-switcher/style.module.css
🔎 [Preview link](https://dev-portal-git-ambfix-product-switcher-hover-hashicorp.vercel.app/)
🎟️ [Asana ticket](https://app.asana.com/0/1201010428539925/1201602267333025/f)
This PR fixes an issue where it was possible to hover over a `ProductSwitcher` option around its edges but not be able to click on it. This was because of the padding within the `<li>` elements containing the clickable `<a>` elements.
I removed the padding within the `<li>` elements, increased the padding of the `<a>` elements to achieve the desired height, added a `<span>` directly within the `<a>` element for each switcher option, and then when the `<a>` receives focus that `<span>` gets the custom focus outline applied to match the "inset" style that's been specified in the designs.
=> Fix product switcher non-clickable edges

next.config.js
this should allow us to remove the pw protection and operate under security through obscurity
to test:
- load https://developer.hashi-mktg.com and view the response headers. notice `x-robots-tag` is not present
- load https://developer.hashi-mktg.com/waypoint and view the response headers. notice `x-robots-tag` is properly set
- load https://dev-portal-ebuuwrs0f-hashicorp.vercel.app/ and see `x-robots-tag` is now properly set on the homepage 
- load https://dev-portal-ebuuwrs0f-hashicorp.vercel.app/waypoint and see `x-robots-tag` is still properly set on sub paths
=> fix noindex regex to include homepage

.github/PULL_REQUEST_TEMPLATE.md
- Not applicable, just adding PR template
- Not applicable, no Asana task associated
- Not applicable, no Asana task associated
- Not applicable, just adding PR template
---
- Preview link 🔎 - Not applicable
- Asana task - Not applicable
This PR checks out our wonderful PR template from `main`.
So that PRs onto `assembly-ui-v1` benefit from the template as well.
`git checkout main .github/PULL_REQUEST_TEMPLATE.md`
Not sure that testing is required, but we could open a new PR onto this PR as a base, I guess?
Nope.
=> chore: checkout PR template from main

next.config.js
---
Updates our regex to ensure that waypointproject.io will **NOT** get the `noindex` header.
With the migration, we definitely want the site to be indexed.
Some good ol' regex magic.
A bit cumbersome to validate, here's how I did it locally.
=> feat: exclude waypointproject from the noindex header

next.config.js
---
- [Preview link](https://dev-portal-git-zsadd-segment-write-key-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201630385846486/f) 🎟️
This PR adds `SEGMENT_WRITE_KEY` to `next.config`, which allows us to configure this variable [for ConsentManager](https://github.com/hashicorp/react-components/blob/f802a62bc4bdeabd2c7fbff004896da5c1a07426/packages/consent-manager/loader/index.tsx#L17) through our environment variable settings.
Allows data to be written to Segment, once consent is given.
Takes a similar approach as we do on other sites, but relies on [ConsentManager's internal production vs development switching](https://github.com/hashicorp/react-components/blob/f802a62bc4bdeabd2c7fbff004896da5c1a07426/packages/consent-manager/loader/index.tsx#L45).
I …
=> feat: add segment write key for ConsentManager

src/layouts/_proxied-dot-io/waypoint/index.tsx, src/lib/consent-manager-services/waypoint.ts
---
- [Preview link](https://dev-portal-git-nq-add-demandbase-tag-waypoint-hashicorp.vercel.app/_proxied-dot-io/waypoint) 🔎
- [Asana task](https://app.asana.com/0/346384260719996/1201528651665558/f) 🎟️
This PR adds a Demandbase tag to the local consent manger services for `waypointproject.io`.
=> enhance(waypoint): Add Demandbase tag

src/components/_proxied-dot-io/common/preview-product-select/index.tsx
---
Adjust z-index on the product switcher popover element
Some elements were showing up on top of the switcher, when in reality it should be above everythin
More z-index!
=> fix(io switcher): adjust z-index

src/components/sidecar/index.tsx, src/components/sidecar/use-active-section.ts, src/contexts/device-size.tsx, src/layouts/docs/docs-layout.module.css, src/lib/get-css-variable-from-document.ts
---
- [Preview link](https://dev-portal-git-ambimprove-sidecar-scrolling-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201508675437098/f) 🎟️
- Updates `Sidecar` to completely ignore headings with level 3 or greater
- Tweaks the `rootMargin` and `threshold` values in `IntersectionObserver` in `use-active-section`
- Ignoring headings with level 3 or greater is something we only did halfway at the time it was added. We stopped rendering the headings in `Sidecar` but we didn't have `use-active-section` ignoring them. It was setting headings that weren't visible in the `Sidecar` as active, making it look like there was no active heading in some pages while scrolling.
- The `rootMargin` and `threshold` tweaks are hopefully refining the accuracy of detecting …
=> Improve sidecar scrolling

.github/workflows/nextjs_bundle_analysis.yml
---
This PR updates the Next.js Bundle Analysis workflow to source the node version from `.nvmrc` and install the latest version of npm.
Next.js v12 uses features of npm v7 and up, but GitHub's runners only come with npm v6.
=> Use .nvmrc and latest npm in bundle analysis

package-lock.json, package.json, src/components/product-switcher/style.module.css
---
- [Preview link](https://dev-portal-git-ambupdate-vault-icon-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201829867097121/f) 🎟️
- Updates `flight-icons` to the latest, `2.1.0`
- Removes the CSS that sets the color of the Vault icon to white in `ProductSwitcher`
The Vault icon color was updated to yellow a little while ago so it's been time to update. This has been the first chance to get to it. 😊 
Upgraded a package, deleted some code. 🤩
Nope!
=> Upgrading flight-icons and Vault icon

config/development.json, config/preview.json, config/production.json, src/lib/fetch-release-data.ts, src/pages/waypoint/downloads/index.tsx, src/views/placeholder-product-downloads-view/index.tsx, src/views/placeholder-product-downloads-view/placeholder-product-downloads-view.module.css, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/product-downloads-view.module.css
---
- [Preview link](https://dev-portal-git-ambset-up-downloads-view-flag-hashicorp.vercel.app/waypoint/downloads) 🔎
- Adds the `enable_new_downloads_view` flag to the `development`, `preview`, and `production` JSON files under `/config`
- Adds a `GeneratedProps` interface in `lib/fetch-release-data.js` that can be used where the props it generates can be consumed (used in `src/pages/waypoint/downloads/index.tsx` in this PR)
- Updates `WaypointDownloadsPage` to conditionally render content based on the new `enable_new_downloads_view` flag
- Adds a `PlaceholderDownloadsView` component that renders placeholder content for a downloads page and without any props sent to it
- Removes placeholder content from `ProductDownloadsViewProps`
This is a test of feature flags for creating new views, …
=> Set up enable_new_downloads_view flag

src/layouts/sidebar-sidecar/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/product-downloads-view.module.css, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambadd-waypoint-downloads-header-hashicorp.vercel.app/waypoint/downloads) 🔎
- Adds the Breadcrumb, IconTileLogo, page title, and page subtitle of the new Waypoint downloads page
- Updates `SidebarSidecarLayout` to export `SidebarSidecarLayoutProps`. Useful in `src/views/product-downloads-view/helpers.ts`.
- Adds `src/views/product-downloads-view/helpers.ts` to house the helper functions that generate some sidebar items and some of the page text. Added to keep the main component file clean. I'm sure there will be more helpers added to this file!
- Updates `ProductDownloadsView` to use `useMemo` for some generated items based on `currentProduct`. This seems like a valuable optimization so that initializer helpers aren't called multiple times when …
=> Add Waypoint downloads header

src/data/waypoint-install.json, src/lib/fetch-release-data.ts, src/pages/waypoint/downloads/index.tsx, src/views/product-downloads-view/components/sidecar-marketing-card/index.tsx, src/views/product-downloads-view/components/sidecar-marketing-card/sidecar-marketing-card.module.css, src/views/product-downloads-view/components/sidecar-marketing-card/types.ts, src/views/product-downloads-view/index.tsx
---
- [Preview link](https://dev-portal-git-ambadd-waypoint-downloads-sidec-c83119-hashicorp.vercel.app/waypoint/downloads) 🔎
- Adds `src/data/waypoint-install.json` file for housing the customizable data shown in the new view
- `sidecarMarketingCard` name is up for debate!
- Adds `pageContent` prop to `ProductDownloadsView`. My intention is to keep this as a single prop so the `ProductDownloadsView` interface doesn't have to be updated every time we want to add more customized data to the view.
- Adds new `SidecarMarketingCard` component local to `ProductDownloadsView`. I think we can move it to the main components folder if it's needed. For now I'm trying to keep that folder as small as possible.
Nope!
=> Add Waypoint downloads sidecar content

package-lock.json, package.json
---
- [Asana task](https://app.asana.com/0/1100423001970639/1200794405240290/f) 🎟️
This PR bumps `@hashicorp/react-docs-page` to the latest stable version.
To bring in a Firefox-specific fix for manual copying of `code-block` contents, as detailed in hashicorp/react-components#503
Bumps `npm` dependency.
When using [Firefox](https://www.mozilla.org/en-US/firefox/new/):
- Note that you'll need to select `Vault` from the dropdown for the specific preview links shown. The underlying fix should apply to any product's code-blocks on any docs page.
Nope!
[preview]: https://dev-portal-git-zsbump-docs-page-hashicorp.vercel.app
[live]: https://www.vaultproject.io/docs/configuration
=> chore: bump to latest docs-page

src/components/download-standalone-link/docs.mdx, src/components/download-standalone-link/index.tsx, src/components/download-standalone-link/types.ts, src/components/standalone-link/docs.mdx, src/components/standalone-link/index.tsx, src/components/standalone-link/types.ts, src/data/waypoint-install.json, src/data/waypoint.json, src/pages/waypoint/downloads/index.tsx, src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/downloads-section/helpers.ts, src/views/product-downloads-view/components/downloads-section/index.tsx, src/views/product-downloads-view/components/downloads-section/types.ts, src/views/product-downloads-view/components/sidecar-marketing-card/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/product-downloads-view.module.css, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambadd-waypoint-downloads-tabbed-card-hashicorp.vercel.app/waypoint/downloads) 🔎
- Adds new `DownloadsSection` portion of the page that handles the whole downloads card where links and information can be changed based on the version selected from the switcher.
- Adds `textSize` prop to `DownloadStandaloneLink` with a default value of `200`. Can undo these changes if we feel it's unneeded, but since the component is in the main `components` directory (readily available for reuse), I figured it would be a helpful prop for future-proofing.
- Adds `openInNewTab` prop to `StandaloneLink`. There are a few instances of pairing an external link icon with a `StandaloneLink` in the new install view, so this seemed like a useful addition in those cases.
- …
=> Add install view DownloadsSection

src/data/waypoint-install.json, src/lib/get-truncated-text.ts, src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/downloads-section/index.tsx, src/views/product-downloads-view/components/featured-tutorials-section/featured-tutorials-section.module.css, src/views/product-downloads-view/components/featured-tutorials-section/index.tsx, src/views/product-downloads-view/components/official-releases-section/index.tsx, src/views/product-downloads-view/components/official-releases-section/official-releases-section.module.css, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambadd-remaining-install-view-sections-hashicorp.vercel.app/waypoint/downloads) 🔎
- Adds `OfficialReleasesSection` and `FeaturedTutorialsSection` subcomponents local to `ProductDownloadsView`. The `FeaturedTutorialsSection` may become reusable in the future across many pages, but I think we can move it to the main components folder when necessary. 
- Adds data for the "Featured Tutorials" section in `src/data/waypoint-install.json`
- Adds a `getTruncatedText` helper function under `src/lib/get-truncated-text.ts`, used for truncating the Learn Tutorial descriptions before rendering them in the "Featured Tutorials" section
Nothing too interesting here. 😊 
There's something wrong with the hover state of the card under Official Releases and I'm not …
=> Add remaining Waypoint install view sections

src/data/consul-landing.json, src/data/consul.json, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts, src/layouts/sidebar-sidecar/utils/product-url-adjusters.ts, src/pages/consul/api-docs/[[...page]].tsx, src/pages/consul/commands/[[...page]].tsx, src/pages/consul/docs/[[...page]].tsx
---
- [Preview link][docs] 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201647459964504/f) 🎟️
This PR adds `docs-page` routes for `/consul`.
To iterate towards supporting all product docs content within the `dev-portal` project.
- Re-uses existing templates, as used for `vault` and `waypoint`
- Builds on work done for `vault` to rewrite `/consul/api/*` links to `/consul/api-docs/*` with a `remark` plugin
- We have [a related task for Vault](https://app.asana.com/0/1100423001970639/1201655704127120/f) that details a longer-term fix - for example, doing this transform as part of our content pipeline.
One known issue is that on the [/consul/docs][docs] view, the links in the sidebar to `API` and `Commands (CLI)`, with the "external" icons, did not initially function as …
=> feat: add consul docs routes

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
---
- [Preview link](https://dev-portal-git-ambfix-card-link-hover-hashicorp.vercel.app/waypoint/downloads) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201885695157827/f) 🎟️
Replaces `::before` pseudo element styling on headings under `tempContentStyles` to use `scroll-margin-top` instead.
Previously, the affected heading elements are so tall with their `::before` elements styled that they overlap with other elements on the page and can interfere with their hover states.
Asked for review on my previous proposal of using `pointer-events: none` in our team channel and @alexcarpenter shared a CSS-tricks article which I then used as a reference: [Fixed Headers and Jump Links? The Solution is scroll-margin-top](https://css-tricks.com/fixed-headers-and-jump-links-the-solution-is-s …
=> Setting scroll-margin-top on heading elements

src/components/breadcrumb-bar/utils/get-docs-breadcrumbs.ts, src/data/nomad-landing.json, src/data/nomad.json, src/pages/nomad/api-docs/[[...page]].tsx, src/pages/nomad/docs/[[...page]].tsx, src/pages/nomad/intro/[[...page]].tsx, src/pages/nomad/plugins/[[...page]].tsx, src/pages/nomad/tools/[[...page]].tsx
---
- [Preview link](https://dev-portal-git-zsadd-nomad-docs-views-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201647459964518/f) 🎟️
This PR adds `docs-page` routes for `/nomad`.
To iterate towards supporting all product docs content within the `dev-portal` project.
- Re-uses existing templates, as used for `vault`, `waypoint`, and [`consul`](https://github.com/hashicorp/dev-portal/pull/131)
- Fixes an issue in breadcrumb generation, where an unusual edge case in `/nomad` content broke typical generation
- Previously, if there were no matches for a given nav node to be displayed in a breadcrumb bar, we would throw an error
- In what looks like a content mishap, Nomad has a [`/docs/autoscaling/agent/source`](https://www.nomadproject.io/docs/autoscaling/a …
=> feat: add nomad docs views

Dockerfile
This aims to fix failing `arm64` docker builds
- see https://github.com/imagemin/optipng-bin/issues/118
Local repro:
`docker buildx build --platform=linux/arm64 -t dev-portal:local .`
<details>
<summary>Logs</summary>
```console
#12 53.73 npm ERR! code 1
#12 53.73 npm ERR! path /app/node_modules/optipng-bin
#12 53.73 npm ERR! command failed
#12 53.73 npm ERR! command sh -c node lib/install.js
#12 53.74 npm ERR! ⚠ Command failed: /app/node_modules/optipng-bin/vendor/optipng --version
#12 53.74 npm ERR! qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
#12 53.74 npm ERR! 
#12 53.74 npm ERR! 
#12 53.74 npm ERR!   ⚠ optipng pre-build test failed
#12 53.74 npm ERR!   ℹ compiling from source
#12 53.74 npm ERR!   ✖ Error: Command failed: /bin/sh -c make install …
```
=> fix: Docker arm64

src/data/consul-install.json, src/pages/consul/downloads/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambadd-consul-install-view-hashicorp.vercel.app/consul/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201893669632604/f) 🎟️
- Adds `src/data/consul-install.json`, it contains all of the data needed for Consul's `ProductDownloadsView`, plus some placeholder data
- Adds `src/pages/consul/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
- Adds the `generateDefaultPackageManagers`, which is something I mostly copied from [react-components/product-download-page](https://github.com/hashicorp/react-components/blob/HEAD/packages/product-download-page/package-managers.ts).
- The only change I made was for it to accept a whole product object instead of just a slug. I see this is …
=> Add new install view for Consul

scripts/content-repo-preview/build.ts
---
`isDirectory` is a function which returns a boolean, not a boolean. Calling it so that it correctly returns `false` for non directories.
ref: https://nodejs.org/api/fs.html#direntisdirectory
=> fix(content-repo-preview/build): call isDirectory

src/data/packer-install.json, src/pages/packer/downloads/index.tsx
---
- [Preview link](https://dev-portal-git-ambadd-packer-install-view-hashicorp.vercel.app/packer/downloads) 🔎
- [Asana task](https://app.asana.com/0/1201147515801429/1201893669632606/f) 🎟️
- Adds `src/data/packer-install.json`, which contains the data needed for Packers `ProductDownloadsView`
- Adds `src/pages/packer/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
Using the same process as #140, #143, and #148 😊
Nope!
=> Add new install view for Packer

src/data/vault-install.json, src/data/waypoint-install.json, src/views/product-downloads-view/components/downloads-section/helpers.ts, src/views/product-downloads-view/components/downloads-section/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambupdate-install-view-package-c5529e-hashicorp.vercel.app/) 🔎
- Updates `ProductDownloadsView` to render always package managers using `generateDefaultPackageManagers`
- Removes the `packageManagers` property from:
- `src/data/vault-install.json`
- `src/data/waypoint-install.json`
- Adds two new interfaces in `src/views/product-downloads-view/types.ts`:
- `GroupedPackageManagers`
- `SortedReleases` (this was actually moved from `src/views/product-downloads-view/helpers.ts`)
- Improves the TypeScript in:
- `src/views/product-downloads-view/components/downloads-section/helpers.ts`
- `src/views/product-downloads-view/components/downloads-section/index.tsx`
While working on #151, I noticed that Vagrant uses the `packageManagerOverrides` prop from …
=> Update install view package managers

next.config.js, package-lock.json, package.json, src/data/sentinel-landing.json, src/data/sentinel.json, src/layouts/sidebar-sidecar/server.ts, src/layouts/sidebar-sidecar/utils/product-url-adjusters.ts, src/lib/remark-sentinel.js, src/pages/sentinel/docs/[[...page]].tsx, src/pages/sentinel/intro/[[...page]].tsx
---
- [Preview link][docs] 🔎
- [Asana task](https://app.asana.com/0/0/1201650734121658/f) 🎟️
This PR adds `docs-page` routes for `/sentinel`.
To iterate towards supporting all product docs content within the `dev-portal` project.
- Re-uses existing templates, as used for `vault` and `waypoint`, `nomad`, `packer`, etc.
- The `/sentinel/changelog` route has not been added, because it's not really a docs route (it's not in the content API), and because I think it's worth taking a minute to discuss our approach to rendering changelogs at a slightly higher level
- I'm hopeful we can come up with a consistent approach that matches the seemingly consistent convention of having a `CHANGELOG.md` at the root of each product repository. 
- 🎟️ Asana task: [[sentinel] Add changelog …
=> feat: add sentinel docs views

src/components/_proxied-dot-io/packer/badge/index.tsx, src/components/_proxied-dot-io/packer/badge/style.module.css, src/components/_proxied-dot-io/packer/plugin-badge/index.tsx, src/components/_proxied-dot-io/packer/remote-plugin-docs/server.js, src/components/_proxied-dot-io/packer/remote-plugin-docs/utils/resolve-nav-data.js
---
- [Preview link]() 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201908607457939/f) 🎟️
Pulls in work from https://github.com/hashicorp/packer/pull/11622. This adds support for new `pluginTier` options.
At first, to make sure the ported code from `packer/website` in this repo is in sync with upstream work.
Now that https://github.com/hashicorp/packer/pull/11622 has merged, realized this has actually broken builds (since we included use of the new plugin tier types in that PR), so also to make it so that `dev-portal` builds stop failing.
Replicates work from https://github.com/hashicorp/packer/pull/11622.
> Note: links below will 404 at first, you'll need to ensure you're in "Packer" mode with the fancy preview dropdown thing in the bottom left of each view.
Visit the …
=> chore: sync work from hashicorp/packer#11622

package-lock.json, package.json, src/pages/_proxied-dot-io/waypoint/downloads/index.tsx
---
- [Preview link][waypoint-downloads] 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201915132498455/f) 🎟️
Removes the need to pass `enterpriseMode` and `merchandisingSlot` props to `@hashicorp/react-product-download-page`.
To remove the need for optional props that aren't necessary or fun to write.
Bumps the `product-download-page` dependency to pull in changes from hashicorp/react-components#526.
- Will 404 at first. Use the switcher in the bottom left and select "Waypoint"
Nope!
[waypoint-downloads]: https://dev-portal-git-zsbump-product-downloads-page-hashicorp.vercel.app/downloads
[waypoint-downloads-main]: https://test-wp.hashi-mktg.com/downloads
=> chore: bump product-downloads-page

src/components/author-primitives/packer/badge/index.tsx, src/components/author-primitives/packer/badge/style.module.css, src/components/author-primitives/packer/plugin-badge/index.tsx, src/pages/packer/docs/[[...page]].tsx
---
- [Preview link][docs/plugins] 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201939256242568/f) 🎟️ 
This PR fixes a build error issue where `/packer/docs` fails to render due to the `PluginBadge` component not being up to date.
A change upstream in the hashicorp/packer repo, merged in https://github.com/hashicorp/packer/pull/11643, used a new plugin tier label we recently added in a `/packer/docs` route. We updated the source code here in `main` in #163, but missed updating `assembly-ui-v1`, so now we're seeing broken builds.
Pulls in work from `main` (see #163 for reference).
Sorry! 🇨🇦 Excited to get out of this one-foot-in-both-worlds stage we're in, and will try to be more diligent in the future around these types of "not-yet-covered-by-checks" changes 🙇‍♂️ 
---
- To …
=> fix: packer docs plugin-badge issue

package-lock.json, package.json, src/components/disclosure/disclosure.module.css, src/components/footer/style.module.css, src/components/icon-tile/style.module.css, src/components/inline-link/inline-link.module.css, src/components/sidebar/components/sidebar-nav/sidebar-nav-menu-item/style.module.css, src/components/sidebar/components/sidebar-nav/style.module.css, src/components/standalone-link/standalone-link.module.css, src/components/tabs/tabs.module.css, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css, src/layouts/sidebar-sidecar/utils/_local_platform-docs-mdx/style.module.css, src/views/placeholder-product-downloads-view/placeholder-product-downloads-view.module.css, src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/featured-tutorials-section/featured-tutorials-section.module.css, src/views/product-downloads-view/components/official-releases-section/official-releases-section.module.css, src/views/product-downloads-view/components/sidecar-marketing-card/sidecar-marketing-card.module.css, src/views/product-downloads-view/product-downloads-view.module.css, src/views/product-landing/components/get-started/style.module.css, src/views/product-landing/style.module.css
---
- [Preview link](https://dev-portal-git-hdscrupdate-color-tokens-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201687774781544/1201850678682258) 🎟️
Updates the DevDot codebase to use the new/updated "semantic" design tokens for colors.
In https://github.com/hashicorp/design-system-tokens/pull/78 the HDS team has re-organized and re-named all of the "semantic" color tokens, and released them with the version `0.5.0` of the `@hashicorp/design-system-tokens` package.
The old color/semantic tokens have been deprecated and will be soon removed. All of the pages I tested (homepage, terraform, packer, packer-docs, packer-docs-commands, packer-downloads, hcp) didn't see a diff.
In this PR I have:
- bumped the `@hashicorp/design-system-tokens` dependency to version `0.5.1` …
=> chore: update DevDot to use new "semantic" colors

src/data/vagrant-install.json, src/pages/vagrant/downloads/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/types.ts
---
- [Preview link](https://dev-portal-git-ambadd-vagrant-install-view-hashicorp.vercel.app/vagrant/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201893669632605/f) 🎟️
- Adds `src/data/vagrant-install.json`, which contains the data needed for Vagrant's `ProductDownloadsView`
- Adds `src/pages/vagrant/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
- Adds support for `packageManagerOverrides`
- Adds `generatePackageManagers` helper
- Using the same process as #140, #143, #148, and #150 😊
- Referenced how [`ProductDownloadsPage` handles `packageManagerOverrides`](https://github.com/hashicorp/react-components/blob/main/packages/product-download-page/index.tsx#L70-L103)
- The current Vagrant downloads page shows …
=> Add new install view for Vagrant

package-lock.json, package.json, src/views/product-downloads-view/components/downloads-section/index.tsx
---
- [Preview link][waypoint/downloads] 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201881376116200/f) 🎟️
This PR bumps `@hashicorp/react-code-block` to pull in a bug fix, and a tabs alignment change, as implemented in https://github.com/hashicorp/react-components/pull/532.
- Fixes a bug that was preventing use of `CodeTabs` on "Install" views
- Updates tabs to be left-aligned when no `heading` is present, to match a design ask
Bumps a dependency, work was mainly done in the the `code-block` package in https://github.com/hashicorp/react-components/pull/532.
Compare to the same page prior to bump the dependency:
- The page built successfully, and works fine for static builds...
- But it fails with ISR, as it fails to re-hydrate on the client due to the (inaccurate) …
=> chore: bump code-block, resolve related TODO

src/layouts/core-dev-dot-layout/core-dev-dot-layout.module.css
> N / A - [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
> N / A - [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
---
- [Preview link](https://dev-portal-git-zstest-main-merge-tweaks-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201937065225337/f) 🎟️
Fixes a bug where `font-family` was not inherited as expected in #175.
So that we can have our "system UI" font stack working correctly in `dev-portal`, without having to re-declare `font-family` on every individual element.
Adds a `font-family` declaration to `CodeDevDotLayout`'s `.root` element.
- Delete the `io_preview` cookie if it is present, otherwise you'll see a preview for some dot-io page
- None of the elements on the page …
=> fix: test fix for --font-body

src/pages/waypoint/tutorials/[collectionSlug].tsx, src/views/collection-view/helpers.ts, src/views/collection-view/index.tsx, src/views/collection-view/server.ts
---
- [Preview link](https://dev-portal-git-kslearn-collection-page-scaffold-hashicorp.vercel.app/waypoint/tutorials/get-started-docker) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201957666036481) 🎟️
This PR adds a proper collection page scaffold. It sets up all the data fetching for the known components that will render, creates a `CollectionView`, and generates the static paths for all waypoint collections. 
The collection view now renders the tutorial list with basic links so we can start navigating through the various tutorials more easily. 
Note this is still 🛹 and all the interfaces / naming will be adjusted as we refine the views with components.
To get the data and collection page foundations set up so that when were ready to build components we can 🛳️ 
- visit …
=> feat: collection page scaffold

src/lib/learn-client/api/product/formatting.ts, src/lib/learn-client/api/product/index.ts, src/pages/waypoint/tutorials/index.tsx, src/views/collection-view/helpers.ts, src/views/collection-view/server.ts, src/views/product-tutorials-view/helpers.ts, src/views/product-tutorials-view/index.tsx, src/views/product-tutorials-view/server.ts
---
- [Preview link](https://dev-portal-git-ksadds-product-scaffold-hashicorp.vercel.app/waypoint/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201957666036489) 🎟️
This PR adds basic data fetching to the waypoint product tutorials hub page. I created a simple skeleton component without styles to list all the collections. Also, the final bit of the [learn client](https://github.com/hashicorp/learn/tree/master/client) is copied over in this PR, with the product methods. 
The purpose here is to get the basic Learn pages for waypoint in a navigable state. Listing out all the collections will help us QA the tutorial views better instead of needing to enter the manual route. 
There is now a: `ProductTutorialsView` directory, with the component and server file (houses …
=> feat: adds product scaffold

package-lock.json, package.json
---
ksmy-branch
-->
This PR opts us into a canary release of `nextjs-bundle-analysis` that supports a new option `minimumChangeThreshold`.
Previous versions of `nextjs-bundle-analysis` would report any page that changed in size, leading to noisy PRs and a low signal-to-noise ratio, thus reducing the likelihood that a PR author would notice a significant change in page size. This PR adds a 1,000 byte minimum change threshold, which should at least make the changed pages list more accurate to the changes that are being made in the PR.
Upgrades the package and defines `minimumChangeThreshold` in `package.json`
N/A
=> Upgrade nextjs-bundle-analysis and add `minimumChangeThreshold`

src/components/sidebar/style.module.css, src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css, src/layouts/sidebar-sidecar/types.ts, src/pages/waypoint/tutorials/[...tutorialSlug]/index.tsx, src/views/placeholder-product-downloads-view/index.tsx, src/views/product-downloads-view/index.tsx, src/views/tutorial-view/index.tsx
---
- [Preview link](https://dev-portal-git-ambadd-sidebar-slot-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201959792840189/f) 🎟️
1. Adds `sidebarSlot` prop to `SidebarSidecarLayout`
2. Updates `src/pages/waypoint/tutorials/[...tutorialSlug]/index.tsx` to use `CoreDevDotLayout`
3. Updates `src/views/tutorial-view/index.tsx` to render `SidebarSidecarLayout` with custom `Sidebar` content
4. Moves `Sidebar` padding style from `Sidebar` component to `SidebarSidecarLayout`
5. Renames `sidecarChildren` prop to `sidecarSlot`
6. Adds two inner components to `src/layouts/sidebar-sidecar/index.tsx`
a. `SidebarContent`
b. `SidecarContent`
1. `sidebarSlot` will be useful for rendering unique sidebars in Learn …
=> Add sidebarSlot prop to SidebarSidecarLayout

src/components/sidebar/components/sidebar-nav/sidebar-nav-menu-item/index.tsx, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
---
- [Preview link](https://dev-portal-git-ambquick-sidebar-fixes-hashicorp.vercel.app/) 🔎
- Asana tasks 🎟️
- [[bug] `<code>` in sidebar category items](https://app.asana.com/0/1201010428539925/1201955800586848/f)
- [SidebarNavMenuItem does not handle `hidden` property](https://app.asana.com/0/1201010428539925/1201893667095310/f)
- Updated `SidebarNavSubmenu` to use `dangerouslySetInnerHTML` so that we no longer see HTML code for submenu nav items
- Updated `prepareNavDataForClient` to filter out nodes with `{ "hidden": true }`, so that those nodes are no longer rendered in the sidebar
Nope!
=> Sidebar: fixing <code> in submenus and adding support for hidden property

package-lock.json, package.json, src/pages/style.css
---
- [Preview link](https://dev-portal-o3x9vc355-hashicorp.vercel.app/) 🔎
Updates to consume @hashicorp/design-system-tokens@0.6.0 and updates the import path for assets
In order to have what's published to npm match what is actually on disk in our monorepo we've moved the published assets to `/dist` in https://github.com/hashicorp/design-system/pull/70
=> chore: update @hashicorp/design-system-tokens and new import path

src/data/README.md
---
- [Preview link ` - src/data/README`](https://github.com/hashicorp/dev-portal/tree/zs.add-product-landing-json-docs/src/data#product-slug-landingjson) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201959792840200/f) 🎟️
This PR adds author-oriented documentation on the `src/data/<product slug>-landing.json` files.
To make it easier for authors to understand and edit `<product slug>-landing.json` files.
Adds collapsible `<details>` section to the README. Similar approach to [the `hashicorp/tutorials` product landing page docs](https://github.com/hashicorp/tutorials#editing-product-pages).
Nope!
---
- https://app.asana.com/0/0/1201959792840200
=> docs: add product-landing.json authoring details

package-lock.json, package.json, src/components/_proxied-dot-io/packer/remote-plugin-docs/server.ts, src/components/_proxied-dot-io/packer/remote-plugin-docs/utils/resolve-nav-data.js, src/pages/_proxied-dot-io/packer/plugins/[...page].tsx
---
This PR fixes the TypeScript types for the Packer plugins page so that we don't need to rely on a `@ts-expect-error` directive.
=> fix: remove usage of @ts-expect-error

scripts/content-repo-preview/build.ts
---
Adjust copy command for the public folder in the source repository.
This is currently reversed, so it's copying the public folder out of `website-preview` and into the source repository.
=> fix(content-repo-preview/build): fix public folder copy logic

src/pages/vault/tutorials/[...tutorialSlug]/index.tsx, src/pages/vault/tutorials/[collectionSlug].tsx, src/pages/vault/tutorials/index.tsx, src/views/collection-view/helpers.ts, src/views/collection-view/server.ts, src/views/tutorial-view/server.ts, src/views/tutorial-view/utils/get-collection-context.ts, src/views/tutorial-view/utils/serialize-content.ts
---
- [Preview link](https://dev-portal-git-ksadd-vault-tutorials-hashicorp.vercel.app/vault/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201985183395374) 🎟️
This sets up vault tutorials hub, collection, and individual tutorial views. 
Trying to pressure test the set-up with a bigger / more complicated dataset. Also I want to get both products in ASAP so we're building for both as we refine. To limit late-stage surprises!
See my code comments for full context on decisions. There were some unexpected slug wrangling issues. 
visit these links and click around 😄 
- [Test tutorial](https://dev-portal-git-ksadd-vault-tutorials-hashicorp.vercel.app/vault/tutorials/cross-products/vault-cred-brokering-quickstart) view. Click on some other tutorials to make sure everything …
=> feat: adds vault routes

package.json
---
Use `npx` for our `build:deploy-preview` script as it runs before `npm install`. This is necessary because we do some file moving related to `node_modules` based on the state of the build cache during a Vercel build.
=> fix: use npx for build:deploy-preview as it runs before npm install

src/layouts/_proxied-dot-io/boundary/index.tsx, src/layouts/_proxied-dot-io/nomad/index.tsx, src/layouts/_proxied-dot-io/packer/index.tsx, src/layouts/_proxied-dot-io/sentinel/index.tsx, src/layouts/_proxied-dot-io/vagrant/index.tsx, src/layouts/_proxied-dot-io/waypoint/index.tsx, src/layouts/base/index.tsx, src/pages/_proxied-dot-io/boundary/community/index.jsx, src/pages/_proxied-dot-io/consul/community/index.jsx, src/pages/_proxied-dot-io/consul/consul-on-kubernetes/index.tsx, src/pages/_proxied-dot-io/nomad/community/index.jsx, src/pages/_proxied-dot-io/packer/community/index.jsx, src/pages/_proxied-dot-io/vagrant/community/index.jsx, src/pages/_proxied-dot-io/waypoint/community/index.jsx, src/views/_proxied-dot-io/security/index.jsx
---
This PR cleans up our `<meta>` tags, removing explicit tags in favor of using `HashiHead` for consistency.
Using `HashiHead` ensures that updated values are correctly overwritten, and makes rolling out larger changes easier since each `<head>` element is derived from a single component.
Our pages that use `renderMetaTags` to render tags from Dato continue to use `next/head` since in those cases it's preferred to use a lower-level of abstraction since Dato gives a large number of `<meta>` tags.
---
- https://app.asana.com/0/0/1201910552708627
=> fix: clean up `<meta>` tag usage

.github/workflows/playwright.yml, playwright.config.ts, src/__tests__/e2e/redirects.spec.ts, src/__tests__/e2e/rewrites.spec.ts
---
This PR switches our E2E test for glob-based redirects to use `/security/index.html` instead of a docs page.
In E2E tests, the site is running in preview mode, which generates pages on the fly. Due to a combination of factors, this leads to sometimes exceeding the default timeout for page load when we try to hit a `/docs` route (since it needs to fetch the page from the content API). This test failure leads to a flaky test, which isn't a good thing since we want PR authors to have confidence that their changes haven't broken something.
By switching to `/security/index.html`, we can load a page that's generated from local data as opposed to remote data.
A passing E2E test …
=> fix: use faster URL to test glob redirects

package-lock.json, package.json, src/lib/fetch-release-data.ts, src/pages/terraform/downloads/index.tsx
---
- [Preview link](https://dev-portal-git-zsfix-semver-filter-versions-hashicorp.vercel.app/terraform/downloads) 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1202035288193775/f) 🎟️
Fixes an issue where the `filterVersions` function for `terraform/downloads` let through pre-release versions.
With pre-releases included after `filterVersions`, we'd end up with `undefined` values in the staticProps result, which causes build errors.
- Switches from `semverGte` to `semverSatisfies`. This seems to fix the issue, though requires us to specify a range (eg `>=1.0.11`) rather than a version (eg `1.0.11`) as we did previously.
- If desired we could retain the prop as a version eg `1.0.11` and prefix it with `>=` within `filterVersions`. However I felt passing a range instead felt a …
=> fix: filterVersions for terraform page

src/views/tutorial-view/server.ts
---
Patch a build error for non themed collection tutorials being built even if they feature a current product. This is related to the [WAF rollout](https://github.com/hashicorp/learn/pull/4461)
=> patch: only build tutorials where collection is also theme

src/components/icon-tile-logo/docs.mdx, src/components/icon-tile-logo/index.tsx, src/components/icon-tile-logo/types.ts, src/components/product-card-grid/index.tsx, src/components/product-icon/docs.mdx, src/components/product-icon/index.tsx, src/components/product-icon/types.ts, src/components/product-switcher/index.tsx, src/components/tutorial-meta/components/badges/components/badge/index.tsx, src/components/version-context-switcher/index.tsx, src/views/product-downloads-view/components/featured-tutorials-section/index.tsx, src/views/product-downloads-view/components/page-header/index.tsx, src/views/product-landing/components/get-started/index.tsx
---
- [Preview link](https://dev-portal-git-ambrename-product-props-hashicorp.vercel.app) 🔎
- Renames `ProductIcon`'s `product` prop to `productSlug`
- Renames `IconTileLogo`'s `product` prop to `productSlug`
- This refactor makes these component APIs clearer and prevents having to look beyond the name of the prop.
First renamed the prop in the component APIs, then did a codebase search for uses of the components to update them.
The following should have no change in functionality:
This PR is part of the work I did in #228, but separating out so that PR isn't so large.
=> Renaming IconTileLogo and ProductIcon product props to productSlug

src/components/video-embed/docs.mdx, src/components/video-embed/index.tsx, src/components/video-embed/types.ts, src/components/video-embed/video-embed.module.css, src/views/tutorial-view/index.tsx, src/views/tutorial-view/utils/mdx-components.tsx
---
- [Preview - at top of page][preview-in-meta] 🔎
- [Preview - inline in MDX][preview-inline] 🔎
This PR adds the `VideoEmbed` component for `/tutorials` views.
To move the `/tutorials` views towards matching design specifications.
- Ports over existing logic from `learn` on using `video.videoInline` to determine whether to display the `VideoEmbed` component at the top of the tutorial (right after `TutorialMeta`), or instead inline in the tutorial (if authors have used `VideoEmbed` inline)
- Ports of the existing `VideoEmbed` component from `learn` (mainly `react-player` under the hood)
- Adds minor styling details based on most recent design specs
- Adds `6px` border radius
- Adds `--token-surface-base-box-shadow`
- Example: …
=> feat: add VideoEmbed to tutorial view

package-lock.json, package.json
---
Regenerates the `package-lock.json` file with npm `v8.6.0`
npm `v8.6.0` included a few changes to dependency resolution. When using a `package-lock.json` file generated from a previous version, `v8.6.0` will correctly detect missing dependencies whereas previously they were silently ignored.
`rm -rf node_modules/ && npx npm@latest install`
=> fix: generate package-lock with npm v8.6.0

src/components/_proxied-dot-io/packer/checklist/style.module.css
---
- [Asana task](https://app.asana.com/0/1100423001970639/1202043114644951/f) 🎟️
Increases the specificity of the `ul` declaration for Packer's `<Checklist>` component.
Our content styles had a list selector with a higher specificity, causing rendering errors.
By mirroring our convention to only apply styles to elements matching `:not([class])`. This matches the specificity of our content styles, and since our component styles are loaded later, they are used.
- Go to preview URL
- Choose Packer in product selector
- Go to this URL
- Scroll to "Checklist" heading
- Ensure that the blue checkmarks don't look funky
=> fix: increase packer checklist specificity

postcss.config.js, src/pages/style.css, src/styles/custom-media.css, src/views/product-downloads-view/components/featured-tutorials-section/featured-tutorials-section.module.css
---
- [Preview link](https://dev-portal-git-zsimport-postcss-custom-media-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1202080355906373/f) 🎟️
Adds our `custom-media` queries specific to `dev-portal` to our `postcss.config.js`.
So that we can more reliably use `postcss-custom-media`. For example, `@media (--dev-dot-tablet-up) {}`.
Clones and modifies the imported config from `@hashicorp/platform-postcss-config`
- On viewports larger than 1000px, you should see some media-query styles applied. These indicate that `custom-media` is working as expected
- Note: specific `@media` styles will only be visible on viewports less than `1000px`. At viewports wider than `1000px`, there's no expectation to see `@media` styles.
Nothing urgent. We may later want to …
=> fix: importFrom to expose custom-media for use

src/components/card-link/index.tsx, src/components/card-link/types.ts, src/components/maybe-internal-link/index.tsx, src/components/maybe-internal-link/types.ts, src/components/text/index.tsx, src/views/tutorial-view/components/next-previous/components/directional-link-box/directional-link-box.module.css, src/views/tutorial-view/components/next-previous/components/directional-link-box/index.tsx, src/views/tutorial-view/components/next-previous/components/directional-link-box/types.ts, src/views/tutorial-view/components/next-previous/index.tsx, src/views/tutorial-view/components/next-previous/next-previous.module.css
---
- [Preview link][/vault/tutorials/tokens/token-management] 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1202016460396717/f) 🎟️
Refines styling and implementation of "Next / Previous" links in the `tutorials` end-of-page UX.
To match design specs as we build out the chromed UI for the `/tutorials` view.
- Adds support for `ariaLabel` and `next/link` `as` to `CardLink`
- Refactors `DirectionalLinkBox` to use `CardLink` under the hood
- Refactors `DirectionalLinkBox` to use React icons from Flight rather than `InlineSvg`
> Note: next & previous functionality has been validated in #226. Additional validation is never a bad thing, but for the purpose of this PR, feel free to focus on the design spec only.
Visit pages with each of the "Next / Previous" end-of-page variations, …
=> feat: next prev tutorial chrome

src/layouts/sidebar-sidecar/index.tsx, src/views/docs-view/index.tsx, src/views/placeholder-product-downloads-view/index.tsx, src/views/product-downloads-view/index.tsx, src/views/product-landing/index.tsx, src/views/tutorial-view/index.tsx
---
- [Preview link](https://dev-portal-git-zsreorganize-content-style-wrapper-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1202088592959488/f) 🎟️
Refactors `SidebarSidecarLayout` so that it does not wrap all `children` in `DevDotContent`.
To mitigate style leaks, as encountered in eg #257 .
For all views that use `SidebarSidecarLayout`, use `DevDotContent` to wrap whatever would previously have been passed as `children`.
Visit a page representing each of the views that uses `SidebarSidecarLayout`:
[docs-view]: https://dev-portal-git-zsreorganize-content-style-wrapper-hashicorp.vercel.app/vault/docs/what-is-vault
[tutorial-view]: https://dev-portal-git-zsreorganize-content-style-wrapper-hashicorp.vercel.app/vault/tutorials/getting-start …
=> refactor: move DevDotContent out of SidebarSidecarLayout

config/development.json, config/preview.json, config/production.json, src/views/tutorial-view/index.tsx, src/views/tutorial-view/utils/get-collection-context.ts, src/views/tutorial-view/utils/index.ts
---
- [Preview link](https://dev-portal-git-kstutorial-canonical-url-hashicorp.vercel.app/vault/tutorials/getting-started/getting-started-intro) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202016460311406) 🎟️
This PR adds a canonical url tag and title tag to the tutorial view. 
Tutorials can belong to numerous collections, the canonical url will ensure that this duplication of pages does not affect SEO by setting the tutorial in the _default_ collection context is referenced as the canonical url. 
- [Visit this page](https://dev-portal-git-kstutorial-canonical-url-hashicorp.vercel.app/vault/tutorials/getting-started/getting-started-intro) and check in `head` that the canonical url is set to this page
- [Visit another …
=> chore: adds canonical url to tutorial view

src/views/collection-view/helpers.ts, src/views/product-tutorials-view/helpers.ts, src/views/product-tutorials-view/index.tsx
---
- [Preview link](https://dev-portal-git-kshandle-non-beta-collection-links-hashicorp.vercel.app/vault/tutorials/cross-products/kubernetes-consul-vault-pipeline#next-steps) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1201991101510148) 🎟️
This PR makes a small workaround so that featured collections in tutorial views don't link to 404 pages. If the product referenced in the collection is not a part of the beta rollout, the featured collection card links externally to Learn. 
This isn't ideal UX, but I think it's _ok_ for the sake of beta. These cards linked to a mix of external and internal routes is a bit odd, but since its not a long term solution I don't think we necessarily need to adjust the cards to support true external linking. Open to feedback on that though. …
=> chore: address broken featured collection links

src/views/tutorial-view/components/featured-in-collections/featured-in-collections.module.css
---
- [Preview link](https://dev-portal-git-zspatch-featured-collections-layout-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1201999966887523/f) 🎟️
Makes a small layout modification to `FeaturedInCollections`.
Design feedback, spec is now defined for previously undefined scenario.
Switches from `flex` layout to `grid` layout.
- I couldn't find such a page, so I set up [a story in Storybook][three-cards-storybook] so that I could test the use case, while also seeing responsive behaviour
- Storybook may also be useful for reviewing responsive behaviour for one-up and two-up layouts.
Not at the moment.
[one-card]: https://dev-portal-git-zspatch-featured-collections-layout-hashicorp.vercel.app/vault/tutorials/getting-started-ui/getting-started-install …
=> fix: featured-in-collections with empty-slot layout

src/lib/learn-client/api/collection/fetch-product-collections.ts, src/lib/learn-client/api/collection/index.ts, src/lib/learn-client/types.ts, src/pages/vault/tutorials/[...tutorialSlug]/index.tsx, src/pages/vault/tutorials/[collectionSlug].tsx, src/pages/vault/tutorials/index.tsx, src/pages/waypoint/tutorials/[...tutorialSlug]/index.tsx, src/pages/waypoint/tutorials/[collectionSlug].tsx, src/pages/waypoint/tutorials/index.tsx, src/types/products.ts, src/views/collection-view/index.tsx, src/views/collection-view/server.ts, src/views/product-tutorials-view/server.ts, src/views/tutorial-view/server.ts
---
- [Preview link](https://dev-portal-git-kscollection-page-skeleton-hashicorp.vercel.app/vault/tutorials/adp) 🔎
This PR adds sidebar sort order functionality to the `getAllCollections` call, which is used for the collection and tutorial product page views. 
It also adds a basic list of the sorted sidebar items for the collection view. 
To wire up this data properly for UI consumption.
- [Visit this page](https://dev-portal-git-kscollection-page-skeleton-hashicorp.vercel.app/vault/tutorials/adp) and look at the list of the sidebar items. It should match the [Learn version](https://learn.hashicorp.com/collections/vault/getting-started) today (even though categories aren't listed yet).
- [Same with Waypoint](https://dev-portal-git-kscollection-page-skeleton-hashicorp …
=> feat: collection page sidebar data

config/development.json, config/preview.json, config/production.json, config/products.ts, src/contexts/all-product-data.tsx, src/contexts/index.ts, src/layouts/sidebar-sidecar/server.ts, src/lib/get-is-beta-product.ts, src/pages/_app.tsx
---
- [Preview link](https://dev-portal-git-ambadd-use-is-beta-hook-hashicorp.vercel.app/waypoint) 🔎
- Renames `products_with_content_preview_branch` config variable to `beta_product_slugs`
- Exports existing `productSlugsToNames` from existing `config/products.ts` file
- Adds `AllProductData` context, which exposes a `useIsBetaProduct` hook
- Updates `src/pages/_app.tsx` to wrap much of the app in `AllProductDataProvider`
- Adds `getIsBetaProduct` utility under `src/lib`
- Uses `getIsBetaProduct` in `src/layouts/sidebar-sidecar/server.ts`
- In a Slack conversation, it was decided that `beta_product_slugs` is a clearer name than  `products_with_content_preview_branch` in config
- `productSlugsToNames` is needed in the new `AllProductData` Context
- We need a global, DRY, optimized way to …
=> Add AllProductData context, useIsBetaProduct hook, and getIsBetaProduct utility

src/components/sidebar/components/sidebar-nav/index.tsx, src/components/sidebar/components/sidebar-nav/sidebar-nav-menu-item/index.tsx, src/components/sidebar/components/sidebar-nav/sidebar-nav-menu-item/sidebar-nav-menu-item.module.css, src/components/sidebar/components/sidebar-nav/sidebar-nav.module.css, src/components/sidebar/components/sidebar-nav/skip-to-main-content/index.tsx, src/components/sidebar/components/sidebar-nav/skip-to-main-content/skip-to-main-content.module.css, src/components/tutorials-sidebar/docs.mdx, src/components/tutorials-sidebar/index.tsx, src/components/tutorials-sidebar/tutorials-sidebar.module.css, src/components/tutorials-sidebar/types.ts
---
- [Preview link](https://dev-portal-git-zstutorial-sidebar-hashicorp.vercel.app/swingset/components/tutorialssidebar) 🔎
- [Asana task](https://app.asana.com/0/1201987349274776/1201999966887514/f) 🎟️
Implements the tutorial view sidebar.
To continue with tutorial view chroming work.
- Takes an approach that relies composition of smaller existing elements from the existing docs `Sidebar`, rather than adding complexity to the props API of the existing docs `Sidebar`
- Looking at the markup in each `LiveComponent` may be helpful to get a sense of component use. Of course, in practice we'll be able to `map` over incoming sections and links within those sections rather than manually repeating them. But hopefully the general idea around composition is clear.
- Focus in this PR is …
=> feat: build tutorial sidebar

scripts/content-repo-preview/build.ts
---
Basically reverting https://github.com/hashicorp/dev-portal/pull/191
I had originally misunderstood the logic here, @zchsh you were correct initially! Vercel uploads the `public/` directory from the root directory of the project, so we want to pull dev-portals public files out of `website-preview` up a level.
=> fix: adjust copy command for public dir

build-libs/__tests__/redirects.test.ts, build-libs/redirects.js, src/__tests__/e2e/redirects.spec.ts, src/pages/_middleware.ts
---
- [Preview link](https://dev-portal-pagpypbxe-hashicorp.vercel.app) 🔎
Adds handling for simple redirects that don't use a `has` condition (which means they're redirects for Dev Portal).
We want Dev Portal to be able to support its own redirects :)
Define redirects without a `has` condition as belonging to the `'*'` product, signifying Dev Portal. Incoming requests without one of the various .io signifiers will be reported as `'*'` for the product.
- Go to preview URL: https://dev-portal-pagpypbxe-hashicorp.vercel.app
- Go to `/hashicorp-cloud-platform`
- Ensure you're redirected to `/hcp`
=> feat: handle simple dev portal redirects

config/production.json
Fixes an issue where the new downloads view is disabled in production instead of the new home page view.
---
=> fix: patch homepage flag in production

src/components/navigation-header/components/dropdown-menu/dropdown-menu.module.css, src/components/navigation-header/components/dropdown-menu/index.tsx, src/components/navigation-header/components/product-page-content/index.tsx, src/components/navigation-header/components/product-page-content/product-page-content.module.css, src/components/navigation-header/types.ts
---
- [Preview link](https://dev-portal-git-ambfix-nav-dropdowns-hashicorp.vercel.app/waypoint) 🔎
The adjustments I made earlier today in #308 were made in a way that affected _all_ primary nav menus instead of just the H menu in the product nav headers. These changes ensure that only the H menu is affected, via a new `dropdownClassName` prop I added to `NavigationHeaderDropdownMenu`.
Nope!
=> Fix custom dropdown styling for H menu

src/pages/vault/tutorials/[collectionSlug].tsx, src/pages/waypoint/tutorials/[collectionSlug].tsx, src/views/collection-view/components/collection-view-sidebar.tsx, src/views/collection-view/helpers.ts, src/views/collection-view/helpers/format-sidebar-sections.ts, src/views/collection-view/helpers/get-slug.ts, src/views/collection-view/helpers/index.ts, src/views/collection-view/index.tsx, src/views/collection-view/server.ts, src/views/product-tutorials-view/helpers.ts, src/views/product-tutorials-view/server.ts, src/views/tutorial-view/server.ts, src/views/tutorial-view/utils/get-tutorials-breadcrumb.ts
---
- [Preview link](https://dev-portal-git-kscollection-view-layout-hashicorp.vercel.app/vault/tutorials/adp) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202095033465927) 🎟️
This PR adds the basic sidebar / sidecar layout to the collection view. This PR isn't meant to implement the collection sidebar to spec, but just getting things in place so that style refinement is easier. 
Setting things up so we can just focus on component development for this view!
I adjusted the `server.js` file to organize the sidebar sections according to the collection categories. These props are passed as `layoutProps` to the view. 
- [Visit this link](https://dev-portal-git-kscollection-view-layout-hashicorp.vercel.app/vault/tutorials/adp) and double check that the collection list matches that …
=> collection view: adds stubbed layout

src/components/navigation-header/components/primary-nav-link/index.tsx, src/components/navigation-header/components/primary-nav-link/primary-nav-link.module.css
---
- [Preview link](https://dev-portal-git-ambfix-nav-menu-heights-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202111590267544/f) 🎟️
- Fixes the height of the `PrimaryNavLink` items that show in product page headers (non home page headers)
- `PrimaryNavSubmenu` items where taller than `PrimaryNavLink` by 2 pixels, so headers that have a mix of the two components did not have vertical alignment
- `display: flex` on the `span`s rendered by the `Text` component in `PrimaryNavLink`
- Nope!
=> Fixing primary nav link heights

src/pages/_proxied-dot-io/packer/community-tools.jsx
---
Adds `includesRoot` option when rendering Packer from local content.
Ensures that the `community-tools` page can render when `dev-portal` is used in the `hashicorp/packer` repo.
=> fix(packer): add includesRoot when loading the community tools page

vercel.json
> Note: quoted lines are not applicable
> - [ ] The Vercel preview link has been added to this PR's description
> - [ ] The Asana task has been added to this PR's description
> - [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
> - [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
---
> - Preview link 🔎
> - Asana task 🎟️
Sets the Vercel bot `silent` setting to `false`.
So that we get PR comments with the long-lived deploy preview link, which can otherwise be cumbersome to track down.
Edits `vercel.json` at the project root.
Nope! We had a Slack thread establishing consensus on this change, seemed there was a decent amount of support & no opposition, so figured it was a good time to open this PR as a next step 👍
=> chore: switch off vercel github bot silent mode

src/views/product-landing/server.ts
---
- [Preview link](https://dev-portal-git-ambremove-product-landing-back-to-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202139025976458/f) 🎟️
Removes the `SidebarBackToLink` from product landing pages.
Details are in the comments of the [[Question][Sidebar] What are the requirements for the StandaloneLink on product landing pages?](https://app.asana.com/0/1202110981600689/1202125080890160/f) ticket.
Removed the `sidebarProps.backToLinkProps` property that was being set in `src/views/product-landing/server.ts`.
Nope!
=> Removing SidebarBackToLink on product landings (/vault, /waypoint, etc.)

src/layouts/sidebar-sidecar/server.ts, src/lib/get-version-from-path.ts, src/views/docs-view/components/no-index-tag-if-versioned.tsx, src/views/docs-view/index.tsx
---
- [Asana task](https://app.asana.com/0/1201903760348480/1202150565840117/f) 🎟️
Support rendering of versioned docs paths
For versioned docs support!
This is already baked into the underlying content loader, just needed to set `enableVersionedDocs: true` and pass along the `versions` array. We can use the `versions` array to build out the version select after this.
=> feat: support versioned URLs

src/components/tabs/components/tab-button-controls/index.tsx, src/components/tabs/components/tab-button-controls/tab-button-controls.module.css, src/components/tabs/components/tab-dropdown-controls/tab-dropdown-controls.module.css
---
- [Preview link](https://dev-portal-git-zsstyle-tabs-hashicorp.vercel.app/swingset/components/tabs) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202151178802272) 🎟️
Implements revised styles for `Tabs`.
To finish building out components for the tutorials views, which includes tabs.
- Modifies styles for existing `tab-buttons-controls` & `tab-dropdown-controls` components
- There's a longer list of these pages in the PR description of #104, if we want to be thorough! ☺️ 
> Note: Mobile behaviour & look & feel may be hard to test in situ & in Swingset due to layout constraints. A [Storybook preview][storybook-tabs] is available just in case (I found it helpful during development). Here's a preview of the mobile behaviour:
The switch from `400` to `500` `font-weight` on …
=> feat: style tabs

package-lock.json, package.json
---
- [Preview link](https://dev-portal-git-zsbump-content-for-table-align-fix-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201999608008890/f) 🎟️
Fixes an issue where `table`s in `docs-page` content were not left-aligned by default.
Left-aligned cells are generally more scan-able, so we'l like them to be our default.
Adds `text-align: left` to `th` cells which do not have an `align` attribute set. See hashicorp/react-components#562 for details.
A couple of Consul content examples:
> Note: to get preview links to show `consulproject.io`, you must select `Consul` in the product dropdown in the lower left of the screen.
- [/api-docs/txn](https://dev-portal-git-zsbump-content-for-table-align-fix-hashicorp.vercel.app/api-docs/txn#kv-operations) vs …
=> chore: bump docs-page for table align fix

src/components/tabs/hooks/use-synced-tab-groups.ts
---
- [Preview link](https://dev-portal-git-zsfix-tab-group-sync-hashicorp.vercel.app/swingset/components/tabs) 🔎
- [Asana task](https://app.asana.com/0/1202001387788447/1202149167439221/f) 🎟️
Fixes an issue in #343 where tab group sync broke functionality of non-`group`-using tabs.
Tabs are broken.
Avoids building a `group → index` map with `undefined: 0` entries, which were the result of not checking if individual `group` values were defined before trying to build this map.
N / A, purely a code bug fix.
[swingset-tabs]: https://dev-portal-git-zsfix-tab-group-sync-hashicorp.vercel.app/swingset/components/tabs
[tutorials-page]: https://dev-portal-git-zsfix-tab-group-sync-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-docker …
=> fix: avoid tab group sync breaking other tabs

src/components/tutorial-card/helpers.ts, src/components/tutorial-card/types.ts, src/views/collection-view/components/collection-tutorial-list/collection-tutorial-list.module.css, src/views/collection-view/components/collection-tutorial-list/index.tsx, src/views/collection-view/components/collection-tutorial-list/types.ts, src/views/collection-view/index.tsx
---
- [Preview link](https://dev-portal-git-zscollection-tutorial-list-hashicorp.vercel.app/waypoint/tutorials/get-started-docker) 🔎
- [Asana task](https://app.asana.com/0/1202001387788447/1202149167439225/f) 🎟️
Implements a `CollectionTutorialList` component, and uses it on all collection views.
To continue building out our `collection-view` in dev-dot.
- Uses existing `tutorial-card` component in a `display: grid` layout
- Accepts an `isOrdered` prop, as different collection types have different grid characteristics
<details>
<summary>Ordered CollectionTutorialList</summary>
TO DO
TO DO
</details>
<details>
<summary>Unordered CollectionTutorialList</summary>
TO DO
TO DO
</details>
> Note: you can also review [in Storybook][storybook], which I found helpful for testing responsive …
=> feat: build collection-tutorial-list for collection views

src/layouts/sidebar-sidecar/index.tsx, src/views/collection-view/index.tsx, src/views/collection-view/server.ts, src/views/product-tutorials-view/server.ts
---
- [Asana task][asana] 🎟️
This PR finishes the UI implementation of `views/collection-view`. With recent work completed in #363 , the only remaining UI change needed is to remove the `Tutorials` heading and the sidecar to match design specs.
To match the `collection-view` implementation to design specs.
- Makes a change in `SidebarSidecarLayout` to allow `sidecarSlot` to be falsy
- Passes `null` to `sidecarSlot` in order to not render a sidecar content
- Removes `heading` generation for `collection-view` as it is now unused
- Makes related TypeScript updates to removal of `headings` from `collection-view` props
<details>
<summary>Implementation before this PR</summary>
</details>
<details>
<summary>Design spec</summary>
</details>
<details> …
=> feat: match collection view to spec

package-lock.json, package.json, src/components/tooltip/docs.mdx, src/components/tooltip/index.tsx, src/components/tooltip/style.module.css, src/components/tooltip/types.ts, src/components/tutorial-card/helpers/build-aria-label.ts, src/components/tutorial-card/helpers/format-tutorial-card.ts, src/components/tutorial-card/helpers/index.ts, src/components/tutorial-card/index.tsx, src/components/tutorial-card/types.ts, src/components/tutorial-collection-cards/components/card-badges/index.tsx
---
- [Preview link][swingset] 🔎
Builds a `Tooltip` component, uses it for `TutorialCard` via `CardBadges`, and provides an accessible equivalent by implementing a custom `aria-label` for `TutorialCard` links.
To make `TutorialCard`'s product & "content type" icons more accessible to all visitors who might not be familiar with them already.
- Implements `components/tooltip`
- Uses `Tooltip` in `CardBadges`
- For `TutorialCard`, currently each badge in `CardBadges` is not focus-able (as there is no action to be taken on activating a non-interactive badge). With this in mind, rather than try to make the tooltips on `CardBadges` accessible to screen readers, we've implemented a descriptive `aria-label` for `TutorialCard` links, which includes the information conveyed …
=> feat: add tooltip component, use for tutorial-card

src/views/product-tutorials-view/components/product-view-content/components/branded-callout/branded-callout.module.css, src/views/product-tutorials-view/components/product-view-content/components/branded-callout/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/branded-callout/types.ts, src/views/product-tutorials-view/components/product-view-content/components/collections-stack/collections-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/collections-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/collections-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/featured-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/components/index.ts, src/views/product-tutorials-view/components/product-view-content/components/logo-card-list/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/logo-card-list/logo-card-list.module.css, src/views/product-tutorials-view/components/product-view-content/components/logo-card-list/types.ts, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/tutorials-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/index.tsx, src/views/product-tutorials-view/components/product-view-content/types.ts, src/views/product-tutorials-view/components/sitemap/index.tsx, src/views/product-tutorials-view/components/sitemap/sitemap.module.css, src/views/product-tutorials-view/helpers/get-inline-content.ts, src/views/product-tutorials-view/index.tsx
---
- [Preview link][waypoint] 🔎
Stubs in the `ProductViewContent` component, and all sub-components, for `ProductTutorialsView`.
Chunking the relatively big task of implementing `ProductTutorialsView` into many smaller pieces.
- Makes a new folder for `ProductTutorialsView`
- Adds a `components` subfolder within, and stubs out all "block" components
- Uses existing types (will iterate on these in individual component PRs)
Not applicable, aim of this PR is to stub in placeholder components. Subsequent per-component PRs will be more relevant to design specs.
I've broken down the broader 🎟️ [Integrate Tutorial Product Landing Pages](https://app.asana.com/0/1201903760348480/1201932088339401/f) into subtasks; those might be relevant for context on the intended scope of …
=> feat: stub in product-view-content components

src/components/cards-grid-list/cards-grid-list.module.css, src/components/cards-grid-list/docs.mdx, src/components/cards-grid-list/index.tsx, src/components/tutorial-card/helpers/format-tutorial-card.ts, src/components/tutorial-card/index.tsx, src/views/collection-view/components/collection-tutorial-list/collection-tutorial-list.module.css, src/views/collection-view/components/collection-tutorial-list/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/featured-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/tutorials-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/index.tsx, src/views/product-tutorials-view/components/product-view-content/product-view-content.module.css
---
- [Preview link][waypoint-tutorials] 🔎
- [Asana task - `FeaturedStack`](https://app.asana.com/0/0/1202182325935207/f) 🎟️
- [Asana task - `TutorialsStack`](https://app.asana.com/0/0/1202182325935210/f) 🎟️
Implements the `TutorialsStack` component for `views/product-tutorials-view`.
To build out the UI for `views/product-tutorials-view`.
- Adds a `CardsGridList` component
- Used here in `TutorialsStack
- Replaces duplicate CSS in `CollectionTutorialList` with `CardListGrid` (for `views/collection-view`)
- Styles FeaturedStack component
- Modifies `formatTutorialCard` to fallback to default collection context, to simplify logic in `TutorialsStack`
- Implements `TutorialsStack`, which is `CardsGridList` + `TutorialCard` + data massaging
- Adds some basic spacing to items in …
=> feat: implement Featured and Tutorials Stacks

src/pages/_proxied-dot-io/vagrant/index.jsx
> - [ ] The Asana task has been added to this PR's description (N / A)
> - [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task  (N / A)
> - [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task  (N / A)
---
- [Preview link](https://dev-portal-git-zsfix-vagrant-homepage-link-hashicorp.vercel.app/) 🔎
>  [Asana task](url) 🎟️ (Not applicable)
Fixes the `Get Started` button on the home page of https://www.vagrantup.com.
Fixes link
`/intro/index` becomes `/intro`
> Not applicable
Nope
=> fix: vagrant homepage link

src/lib/learn-client/types.ts, src/pages/style.css, src/views/product-tutorials-view/components/product-view-content/components/branded-callout/branded-callout.module.css, src/views/product-tutorials-view/components/product-view-content/components/branded-callout/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/branded-callout/types.ts, src/views/product-tutorials-view/components/product-view-content/components/collections-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/components/featured-stack/featured-stack.module.css, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/types.ts, src/views/product-tutorials-view/components/product-view-content/index.tsx, src/views/product-tutorials-view/components/sitemap/sitemap.module.css, src/views/product-tutorials-view/helpers/heading-helpers.ts, src/views/product-tutorials-view/index.tsx, src/views/product-tutorials-view/product-tutorials-view.module.css, src/views/product-tutorials-view/server.ts
---
- [Preview link][/vault/tutorials] 🔎
Fixes an issue on product tutorial landing views, such as [/waypoint/tutorials][/waypoint/tutorials] and [/vault/tutorials][/vault/tutorials], where headings were not reflected correctly in the sidecar table-of-contents due to lack of `scroll-margin-top`.
To fix an issue on product tutorial landing views where the sidecar table-of-contents highlighting is not working as expected.
- Adds a new global helper class, `.g-offset-scroll-margin-top`
- Uses `.g-offset-scroll-margin-top` for all heading elements on the product tutorial landing view
- Visually hides the top-level `"Overview"` page heading, to match mockups
- Rendering this heading element seems necessary for our table-of-contents to work as expected
- Refactors some …
=> fix: tutorial landings table-of-contents 

analytics/spec/events/_index.yaml, analytics/spec/events/beta_opted_in.yaml, analytics/spec/events/beta_opted_out.yaml
Includes Analytics Tracking plans for both opting in & opting out of the DevDot experience.
This will enable us to track the lifecycle of users who have opted in for the beta, which will enable us to perform analysis of data that is sandwiched between these two events.
These events will be ephemerally added into Dev Portal, only for the length of our public beta.
**Note:** this is only the specification, and is not the implementation of the analytics.
=> Adds opt-in / opt-out analytics tracking

.github/workflows/cache.yml
Changes the name of the .io cache job from `test` to `cache`.
=> fix: change name of cache job

src/lib/learn-client/types.ts, src/views/product-landing/components/get-started-card/get-started-card.module.css, src/views/product-landing/components/get-started-card/index.tsx, src/views/product-landing/components/get-started-card/types.ts, src/views/product-landing/components/hero-heading-visual/hero-heading-visual.module.css, src/views/product-landing/components/hero-heading-visual/index.tsx, src/views/product-landing/components/hero-heading-visual/types.ts, src/views/product-landing/components/overview-cta/index.tsx, src/views/product-landing/components/overview-cta/overview-cta.module.css, src/views/product-landing/components/overview-cta/types.ts, src/views/product-landing/components/product-landing-blocks/blocks/heading-block/heading-block.module.css, src/views/product-landing/components/product-landing-blocks/blocks/heading-block/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/heading-block/types.ts, src/views/product-landing/components/product-landing-blocks/blocks/index.ts, src/views/product-landing/components/product-landing-blocks/blocks/linked-cards/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/linked-cards/linked-cards.module.css, src/views/product-landing/components/product-landing-blocks/blocks/linked-cards/types.ts, src/views/product-landing/components/product-landing-blocks/blocks/tutorial-cards/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/tutorial-cards/tutorial-cards.module.css, src/views/product-landing/components/product-landing-blocks/blocks/tutorial-cards/types.ts, src/views/product-landing/components/product-landing-blocks/index.tsx, src/views/product-landing/components/product-landing-blocks/types.ts, src/views/product-landing/helpers/__tests__/make-heading-slug-scope.test.ts, src/views/product-landing/helpers/extract-headings.ts, src/views/product-landing/helpers/index.ts, src/views/product-landing/helpers/make-heading-slug-scope.ts, src/views/product-landing/helpers/transform-raw-content-to-prop.ts, src/views/product-landing/index.tsx, src/views/product-landing/server.ts, src/views/product-landing/types.ts
---
- [Preview link][/waypoint] 🔎
Implements sidecar table-of-contents functionality for `views/product-landing`.
To build out `views/product-landing`.
- Adds a helper `transform-raw-content-to-prop`, which is hopefully clearly named.
- This includes adding `headingSlug` elements where we need to include a heading in our table of contents.
- This will later include fetching tutorial and collection data, and transforming it to card props
- Adds a helper `make-heading-slug-scope`, intent is to make it easy & clean to generate unique-on-the-page `headingSlug` values
- Adds all planned components as placeholders; this accounts for the majority of the lines-of-code
- Adds prop types needed for the UI, which are referenced by `transform-raw-content-to-prop` (the …
=> feat: hook up product landing sidecar

src/components/navigation-header/navigation-header.module.css, src/layouts/base-new/base-new-layout.module.css, src/layouts/core-dev-dot-layout/core-dev-dot-layout.module.css, src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
---
- [Preview link][preview-sidebar-sidecar] 🔎
Fixes an issue where the top border of our `footer` component caused horizontal overflow and scroll in both our core layout, and in our sidebar-sidecar layout.
Horizontal scroll is unintentional, unexpected to visitors, and quite janky.
In our designs, the footer needs to be aligned with main content, but its top border needs to span all the way across the main content and sidecar area:
Various approaches were attempted without changing markup, and I hit dead ends in all of them. In brief, I think the fundamental challenge with the current implementation's markup is that `overflow: hidden` and `position: sticky` [don't work together](https://css-tricks.com/dealing-with-overflow-and-position-sticky/):
To work around …
=> fix: footer overflow issues

package-lock.json, package.json
This PR fixes an issue where `@hashicorp/react-subnav`'s `overflow: hidden` means the mobile menu would not be visible.
=> fix: roll back subnanv

src/components/tutorial-meta/components/badges/badges.module.css, src/components/tutorial-meta/components/badges/components/badge/badge.module.css, src/components/tutorial-meta/components/badges/index.tsx
- [Preview link](https://dev-portal-git-kstutorial-page-qa-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro) 🔎
- [Asana task](https://app.asana.com/0/1202001387788447/1202287572319161) 🎟️
Addressing a QA ticket to update the readtime to no longer be a badge. See ticket for full context.
=> style: fix tutorial badge readtime

src/components/footer/footer.module.css, src/layouts/sidebar-sidecar/components/table-of-contents/index.tsx, src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css, src/styles/custom-media.css
---
- [Preview link](https://dev-portal-git-ambfix-sidecar-rendering-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202001387788447/1202287572319130/f) 🎟️
- Renamed a couple of CSS classes in `SidebarSidecarLayout` for extra clarity:
- `contentWrapper` -> `root`
- `sidebar` -> `sidebarWrapper`
- `mainAreaAndFooter` -> `contentWrapper`
- `mainArea` -> `mainAreaWrapper`
- `sidecar` -> `sidecarWrapper`
- `footerArea` -> `footerAreaWrapper`
- Replaced the `footer::after` pseudoelement with an empty `div`. I think something about the changes I made caused the pseudoelement approach to no longer work.
- Added `--dev-dot-sidecar-up` custom media and set it to the new `1280px` breakpoint. Sidecar styles are applied at this breakpoint and the `main` and `footer` classes also use …
=> Adjusting SidebarSidecarLayout spacing and sidecar breakpoint

analytics/spec/events/product_downloaded.yaml, src/components/download-standalone-link/index.tsx, src/components/download-standalone-link/types.ts, src/components/standalone-link/index.tsx, src/components/standalone-link/types.ts, src/lib/analytics.ts, src/views/product-downloads-view/components/downloads-section/index.tsx
---
- [Preview link](https://dev-portal-git-ambproduct-downloaded-analytics-hashicorp.vercel.app/waypoint/downloads) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202207336073931/f) 🎟️
- Renamed `Product Downloaded` event name to `Download` in `analytics/spec/events/product_downloaded.yaml` to match the existing events we've tracked on .io sites.
- Adds `onClick` prop to both `StandaloneLink` and `DownloadStandaloneLink`
- Updates `DownloadStandaloneLinkProps['ariaLabel']` to reference `StandaloneLinkProps['ariaLabel']`
- Updates `StandaloneLinkProps` to reference `JSX.IntrinsicElements['a']` props for props that end up passed directly to the rendered `<a>` element
- Adds `src/lib/analytics.ts` with three functions:
- `canTrackAnalytics` (not exported for wide reuse)
- …
=> Track product download analytics

src/layouts/sidebar-sidecar/server.ts
---
- [Preview link](https://dev-portal-git-ambreturn-not-found-on-docs-404-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202286782903644/f) 🎟️
- Wraps the `loader.loadStaticProps` call in `src/layouts/sidebar-sidecar/server.ts` with a `try/catch`
- The server error we see when going to not-found routes under docs pages is happening inside of the `loader.loadStaticProps` call. Wrapping it in a try/catch enables us to check the status of the error to see if it's a 404 or not.
The following pages should still work as expected (just tossing a few in here):
The following pages should show the 404 page rather than the server error page:
I think we may need to update the current `if (error.status === 404) { ... }` to be an `if/else`?
=> Return 404 page if error loading static props for docs pages

src/layouts/sidebar-sidecar/components/table-of-contents/index.tsx
- [Preview link](https://dev-portal-git-kshide-sidecar-one-item-hashicorp.vercel.app/http://localhost:3000/waypoint/tutorials/get-started-docker/get-started-intro) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202213086993158) 🎟️
As per design's request this PR adds a check for the number of headings in the table of contents component (default for sidecar). If there's only one heading, the component doesn't render.
=> chore: hide TOC if only one heading

src/components/navigation-header/components/dropdown-menu/dropdown-menu.module.css, src/components/navigation-header/components/product-page-content/product-page-content.module.css
- [Preview link](https://dev-portal-git-ksfix-mobile-logo-position-hashicorp.vercel.app/vault/docs) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202292475408421) 🎟️
This PR fixes a bug where left margin on the product logo was offsetting the product logo on mobile and tablet when the dropdown wasn't rendering. See the ticket for full context / screenshots. 
- [Visit a page](https://dev-portal-git-ksfix-mobile-logo-position-hashicorp.vercel.app/vault/docs) that renders the product logo and drop down. Ensure that the spacing is correct on both desktop and mobile.
=> style-fix: move nav product logo margin

src/views/docs-view/components/product-docs-search/index.tsx
- [Preview link](https://dev-portal-git-kscapitalize-product-search-hashicorp.vercel.app/vault/docs) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202309283074052) 🎟️
This PR adjusts the search placeholder to use the product name, instead of the slug — this way the product is properly capitalized.
=> chore: use product name for search placeholder

src/views/product-root-docs-path-landing/components/marketing-content/index.tsx, src/views/product-root-docs-path-landing/components/marketing-content/marketing-content.module.css
- Fixes the `scroll-margin-top` on the headings in the marketing section of the root docs path landing pages
- Composes the handy dandy `g-offset-scroll-margin-top` global helper. 😊
Nope!
=> Fixing scroll-margin-top on /vault/docs and /waypoint/docs

src/components/_proxied-dot-io/packer/section-break-cta/index.tsx, src/pages/_proxied-dot-io/packer/index.jsx
Removes beta badge from HCP packer section.
Preview (switch to packer homepage via product select): https://dev-portal-git-acpacker-remove-beta-badge-hashicorp.vercel.app/
=> chore(packer.io): removes beta badge from HCP packer section

src/components/dev-dot-content/dev-dot-content.module.css
- [Preview link](https://dev-portal-git-ksfix-alert-bottom-margin-hashicorp.vercel.app/vault/docs/concepts/username-templating#examples) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202309283074066) 🎟️
Fixes an issue where the alert component had no bottom margin. 
- Visit this PR and verify that the bottom margin is properly applied. See screenshot below for the previous view 
- Also click around a few more docs pages to verify that the alert spacing looks fine.
=> chore: fix margin-bottom on alert component

src/components/toast/index.tsx
---
- [Asana task](https://app.asana.com/0/1202097197789424/1202332432700512/f) 🎟️
Ensures a welcome toast shows up when opting in to the dev-portal beta from docs sites.
To display a welcome toast to visitors when they opt-in to the dev-portal beta. Specifically, ensure this toast appears when coming from docs sites.
Replaces the existing `useEffect` which relied on `routeChangeComplete` with a new hook that relies on `router.asPath`. 
Monitoring the URL in this way seems to give a more accurate reflection of when the URL changes from the initial `router.asPath` to a new `router.asPath`. With `routeChangeComplete`, this detection did not seem to work as expected, and the toast would auto-dismiss as soon as the page mounted, resulting in the experience of not …
=> fix: issue with toast route change detection

package-lock.json, package.json
---
Bumps `@hashicorp/react-error-view`.
To fix contrast issue.
[task]: https://app.asana.com/0/1100423001970639/1202349999400572/f
[preview]: https://dev-portal-git-zsfix-dot-io-404-contrast-hashicorp.vercel.app/yeehaw
=> chore: bump react-error-view to fix contrast issue

src/components/cards-grid-list/docs.mdx, src/views/error-views/dev-dot-404/index.tsx, src/views/product-downloads-view/components/featured-tutorials-section/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/collection-cards/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/linked-cards/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/tutorial-cards/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/collections-stack/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/logo-card-list/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/index.tsx
- [Preview - product landing][/waypoint] 🔎
- [Preview - downloads view][/waypoint/downloads] 🔎
- [Preview - product tutorials view][/waypoint/tutorials] 🔎
Fixes an issue where `<CardsGridList />` had children which were not `<li />`, resulting in incorrect HTML structure (since `<CardsGridList />` renders a `<ul />` or `<ol />`.
[preview]: https://dev-portal-git-zsfix-missing-card-grid-li-hashicorp.vercel.app
[task]: https://app.asana.com/0/1202097197789424/1202368770478995/f
[/waypoint]: https://dev-portal-git-zsfix-missing-card-grid-li-hashicorp.vercel.app/waypoint
[/waypoint/downloads]: https://dev-portal-git-zsfix-missing-card-grid-li-hashicorp.vercel.app/waypoint/downloads
[/waypoint/tutorials]: https://dev-portal-git-zsfix-missing-card-grid-li-hashicorp.vercel …
=> fix: missing li with CardsGridList uses

package-lock.json, package.json
- [Preview - /waypoint/downloads][/waypoint/downloads] 🔎
Bumps `@hashicorp/react-code-block` to fix an issue with overflow detection when nested within tabs.
For details, see the `react-components` PR:
- https://github.com/hashicorp/react-components/pull/600
[/waypoint/downloads]: https://dev-portal-git-zsbump-code-block-fix-use-overflow-ref-hashicorp.vercel.app/waypoint/downloads
[task]: https://app.asana.com/0/1202114367927919/1202350092732470/f
=> chore: bump code-block for use-overflow-ref fix

src/components/sidebar/components/sidebar-mobile-controls/index.tsx, src/components/sidebar/components/sidebar-mobile-controls/sidebar-mobile-controls.module.css
- [Asana task](https://app.asana.com/0/1202022787106817/1202307248480199/f) 🎟️
Updates `LevelDownButton` to be right-aligned at the top-level mobile sidebar.
=> [mobile Sidebar] Right aligning lonely level down button

src/components/sidebar/components/sidebar-nav-menu-item/index.tsx
Noticed a react key error being logged in development. Tracked it down and it looks like we were using the wrong `id` value when rendering nested `SidebarNavMenuItem`s.
=> fix: key error in sidebar-nav-menu-item due to incorrect id used for key

src/components/breadcrumb-bar/utils/get-docs-breadcrumbs.ts, src/components/mobile-standalone-link/mobile-standalone-link.module.css, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
- Removes old `70px` padding for mobile sidebar since that's fixed
- Adds `150px` padding to the bottom of sidebar content
- This makes it so the version switcher doesn't cut off the content anymore
- This is also nice so that sidebar content isn't always at the bottom of a window/screen
- Fixes the link of the third docs breadcrumb item when a past version is selected
=> Small polishing fixes

src/components/algolia-search/index.tsx
- [Preview link](https://dev-portal-git-ksclose-search-panel-on-blur-hashicorp.vercel.app/waypoint/docs) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202390857238416) 🎟️
Fixes the issue where the search panel would stay open when the mobile sidebar menu is opened. The default `onBlur` is overridden for the `autocomplete` props so we should validate that this doesn't break other behavior. 
- Visit a docs page, enter some search input, open the hamburger menu. The search panel should close.
=> chore: fix search results on blur

src/components/navigation-header/components/home-page-content/home-page-content.module.css, src/components/navigation-header/navigation-header.module.css
Fixes minor issues in the top nav bar that caused it to have an unexpected height on certain viewport sizes and on certain pages.
To fix issues related to layouts that rely on the sticky top nav bar being a known, consistent height.
- adjusts top nav padding so that height is accurate
- adjusts home page logo padding so nav height is consistent between product-specific and home pages
[task]: https://app.asana.com/0/1202114367927919/1202316169578550/f
[preview]: https://dev-portal-git-zsfix-top-bar-height-hashicorp.vercel.app
[/waypoint]: https://dev-portal-git-zsfix-top-bar-height-hashicorp.vercel.app/waypoint
=> fix: nav bar height mismatch

src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
- [Preview link](https://dev-portal-git-ksfix-vault-tutorial-links-hashicorp.vercel.app/vault/docs) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202394505015462) 🎟️
Adjusting the docs nav item paths to be more resilient if the data already contains the expected base path. Such as with [tutorial links](https://github.com/hashicorp/vault/blob/dev-portal/website/data/docs-nav-data.json#L14-L19)
- Visit the [docs page](https://dev-portal-git-ksfix-vault-tutorial-links-hashicorp.vercel.app/vault/docs), open the Getting Started dropdown, click one of those tutorial links. It should link to the proper tutorial within dev dot (previously it was 404'ing).
=> chore: don't add base path if its present

src/components/sidebar/components/sidebar-filter-input/sidebar-filter-input.module.css, src/styles/sizing.css
- [Preview link](https://dev-portal-git-ksfix-input-outline-hashicorp.vercel.app/waypoint/docs) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202317183612796) 🎟️
Fixes an issue where the sidebar filter input box shadow wasn't rendering on iOS browsers.  
At first I thought it was related to this known issue. See this note from [can-i-use](https://caniuse.com/?search=box-shadow), apparently this is a known issue with iOS safari and we can't use the `blur-radius` as 0. I updated it to 1px and it didn't seem to fix the issue. 
> [Also see this stack overflow discussion.](https://stackoverflow.com/questions/28245254/box-shadow-inset-doesnt-work-in-ios)
~~I ended up moving the box shadow up to the container div and that seems to solve it. Perhaps there some iOS input issue with …
=> fix: adjust filter input box shadow

src/pages/style.css, src/views/homepage/homepage.module.css, src/views/homepage/index.tsx
Fixes two issues on the homepage:
- Mobile menu icon shown on large viewports, even though intent is not to show it
- Mobile menu not layering correctly when open
- Adds `!important` to global helper classes, this seems necessary to account for potential loading order differences with classes applied through CSS modules
- Adds `z-index` to allow mobile menu to layer above content on homepage, even though it appears earlier in the DOM
- The mobile menu icon should not appear on desktop viewports
- The mobile menu should be layered correctly when open on mobile viewports
[task]: https://app.asana.com/0/1202114367927919/1202428126706761/f
[preview]: https://dev-portal-git-zsfix-home-mobile-menu-hashicorp.vercel.app/
=> fix: homepage menu issues

src/components/sidebar/components/sidebar-nav-menu-item/index.tsx, src/components/sidebar/index.tsx, src/components/sidebar/sidebar.module.css, src/layouts/sidebar-sidecar/server.ts, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
- Updates `prepareNavDataForClient` to generate unique IDs for each item (including dividers and headings) so we don't have `React` unique `key` warnings and so that we don't have to rely on an array `index` (which breaks rendering when a user is searching the sidebar)
- Updates reference to `prepareNavDataForClient` in `sidebar-sidecar`'s `server` code
- Adds suffixes to the `<button>` and `<ul>` element `id`s in `SidebarNavSubmenuItem` for more verbose/clear `id` names
- Updates `Sidebar` to not render the `Overview` menu item if the search input has a search value since this item won't be searched for
- Fixes a typo I noticed in the `filerInputWrapper` class name (was missing a `t`)
From #329, where I originally did the work for generating unique IDs:
> There are block comments above …
=> Miscellaneous Sidebar adjustments/fixes

src/components/mobile-menu-container/mobile-menu-container.module.css, src/layouts/base-new/base-new-layout.module.css
Fixes an issue where mobile menu would appear below search input.
- Also ensure the footer still layers correctly with the sidebar on desktop, as the sidebar uses "mobileMenuContainer"
[preview]: https://dev-portal-git-zsfix-mobile-menu-z-index-hashicorp.vercel.app/waypoint/docs/
=> fix: z-index on mobile-menu

build-libs/proxy-settings.js, build-libs/redirects.js, src/__tests__/e2e/rewrites.spec.ts
Fixes this: https://www.vaultproject.io/vault
Exposing dev portal routes for the same product under its .io domain. Not something we want to do! Added a test case to validate that you can't hit a dev portal route for the same product. I also removed an unused block of redirect generation.
=> fix: dev portal routes visible under io domains for same product

src/pages/boundary/downloads/index.tsx, src/pages/consul/downloads/index.tsx, src/pages/nomad/downloads/index.tsx, src/pages/packer/downloads/index.tsx, src/pages/sentinel/downloads/index.tsx, src/pages/terraform/downloads/index.tsx, src/pages/vagrant/downloads/index.tsx, src/views/collection-view/index.tsx, src/views/product-tutorials-view/index.tsx
Fixes an issue where buttons in ConsentManager would stack and break.
To prevent unexpected layout in `ConsentManager`
Removes duplicate `CoreDevDotLayout`. Already used in `SidebarSidecarLayout`, so no need to set twice - and doing so wraps `ConsentManager` in font-family settings which alter layout and cause button stacking.
[task]: https://app.asana.com/0/1202114367927919/1202448714497715/f
[preview]: https://dev-portal-git-zsfixup-layout-again-hashicorp.vercel.app/vault/tutorials
=> fix: clean up more duplicate CoreDevDotLayouts

src/components/dev-dot-content/dev-dot-content.module.css
Tweaks font size of inline code within content headings.
Adjusts font-size for inline `<code />` in content headings from `0.6em` to `0.8em`.
[task]: https://app.asana.com/0/1202114367927919/1202439831418480/f
[preview]: https://dev-portal-git-zstweak-inline-code-hashicorp.vercel.app/vault/docs/configuration/listener/tcp
=> fix: tweak heading > code font-size

src/data/vault-landing.json, src/data/waypoint-landing.json
- [Preview link - /waypoint][preview] 🔎
- [Preview link - /vault][/vault] 🔎
Adjusts content on `/waypoint` and `/vault` landing pages to create separate `Featured Tutorials` and `Featured Collections` sections.
See [ticket][task], in some cases the layouts felt odd with these sections separated by card type, but not separated with headings.
Modifies content to add a heading.
[preview]: https://dev-portal-git-zsseparate-waypoint-land-card-sections-hashicorp.vercel.app/waypoint
[/vault]: https://dev-portal-git-zsseparate-waypoint-land-card-sections-hashicorp.vercel.app/vault
[task]: https://app.asana.com/0/1202114367927919/1202440154783258/f
=> fix: separate card sections on waypoint landing

src/components/dev-dot-content/dev-dot-content.module.css
Fixes an issue with `letter-spacing` in custom alert boxes in `docs` and `tutorial` content.
To match design spec - we don't want tracked out letter-spacing when using system fonts.
Adds CSS override with high specificity.
- Also confirm the alerts look as expected otherwise
Note: this is a relatively temporary fix. We have a broader platform task to move style transforms to content consumers: 🎟️ [[mktg-content] move style transforms such as paragraphCustomAlerts to load stage (rather than current extract stage)](https://app.asana.com/0/1100423001970639/1202448738938137/f)
[task]: https://app.asana.com/0/1202114367927919/1202439831418498/f
[preview]: https://dev-portal-git-zsfix-alert-box-letter-spacing-hashicorp.vercel.app/vault/tutorial …
=> fix: dev-dot-content alert letter-spacing

src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/downloads-section/index.tsx, src/views/product-downloads-view/components/page-header/index.tsx, src/views/product-downloads-view/components/page-header/page-header.module.css
This PR refines mobile styling for the top section of our install views.
- Removes product icon on mobile, for topmost area
- Refactors version-select + heading layout, to avoid cut-off version select text
https://user-images.githubusercontent.com/4624598/173732880-275adcb2-61ca-4ded-a82a-48fc131e8336.mp4
- Desktop appearance should be unchanged, apart from a minor spacing tweak
[task]: https://app.asana.com/0/1202114367927919/1202439831418522/f
[preview]: https://dev-portal-git-zsinstall-view-mobile-tweaks-hashicorp.vercel.app/waypoint/downloads
=> fix: tweak install view mobile styles

package-lock.json, package.json
Pulls in a fix from https://github.com/hashicorp/react-components/pull/612 to adjust `<CodeTabs />` alignment when code tabs are in dropdown form _and_ there is no title for the code tabs.
Previously, alignment was not correct - the dropdown should be left-aligned, but was right aligned.
- Ensure alignment of the dropdown matches on which side the dropdown is aligned (the dropdown should NOT extend outside the boundaries of the code block)
- Ensure the code block is otherwise the same
We never bumped to [@hashicorp/react-code-block@6.0.0](https://github.com/hashicorp/react-components/releases/tag/%40hashicorp%2Freact-code-block%406.0.0). I think this is okay, I don't believe there are any uses of the affected `onCopyCallback` prop in …
=> fix: code-block dropdown alignment

src/layouts/base-new/base-new-layout.module.css, src/layouts/base-new/index.tsx, src/views/homepage/homepage.module.css, src/views/homepage/index.tsx
- [Preview link](https://dev-portal-git-amb404-mobile-menu-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1202474624444935/f) 🎟️
Moves mobile menu previously in `src/views/homepage/index.tsx` to `src/layouts/base-new/index.tsx`, so it can be used for all pages that do not use `SidebarSidecarLayout`. Such as the error views.
Test the following pages at 2 viewport widths (`<= 728px` and `>= 729px`) and make sure the correct mobile menu appears when expected:
=> Moving non-product mobile menu to BaseNewLayout

src/pages/_document.tsx
Preload Segment in the head w/o enabling it to enable analytics events to be fired off when the page initially loads.  This is notably important for our 404/error pages so we can send an analytics event for that.
This will enable Segment to hold onto analytics requests that would have been sent.  As soon as the consent manager is accepted, Analytics events will be sent through.
Visit the following page https://dev-portal-git-brpreload-segment-hashicorp.vercel.app/some-404-page, while observing the network tab.  No network requests will be sent, but then as soon as you accept the consent manager, a track will be sent.
=> Preload Segment (w/o enabling it)

src/components/opt-in-out/helpers/platform-options.ts
We need the `betaOptOut=true` query parameter set when redirecting back to an .io site from the opt-out flow, otherwise a user would just get redirected back to Hashi Developer on opt-out
=> fix(beta opt-out): add betaOptOut query param to io site opt-out

src/views/product-downloads-view/components/page-header/index.tsx, src/views/product-downloads-view/components/page-header/page-header.module.css
When `IconTileLogo` is hidden (viewports <= `728px` wide), there is still a `margin-left` on the page header text container. This moves the margin from that element to the `IconTileLogo` element instead.
<table>
<tr>
<td>before<img src="https://user-images.githubusercontent.com/43934258/174689702-68fba631-c043-4b2b-934f-15e01c3bcb7c.png" /></td>
<td>after<img src="https://user-images.githubusercontent.com/43934258/174689712-2d290195-01e6-4d4b-97d8-68eb8ec6ffbb.png" /></td>
</tr>
</table>
=> [install view] Fixing margin when IconTileLogo is hidden

src/components/mobile-menu-container/mobile-menu-container.module.css
Fixes scrolling of `MobileMenuContainer` when the viewport is too vertically short to show all the content.
=> Fixing MobileMenuContainer scroll

src/data/nomad.json, src/data/packer.json, src/data/sentinel.json, src/data/vagrant.json, src/data/vault.json
HashiConf is no longer live, so this turns off the generic alert banners (leaving Boundary, Waypoint & Consul as they're promoting specific announcements)
=> turn off generic hashiconf alert banners

package-lock.json, package.json, src/__tests__/e2e/seo.spec.ts, src/components/head-metadata/index.tsx
Bumps `@hashicorp/react-head` to pull in updates from:
- https://github.com/hashicorp/react-components/pull/623
To ensure metadata for Twitter cards is correctly populated.
[task]: https://app.asana.com/0/1100423001970639/1202415308965256/f
[preview]: https://dev-portal-git-zsbump-head-hashicorp.vercel.app
[validator]: https://cards-dev.twitter.com/validator
=> chore: bump head

src/layouts/sidebar-sidecar/components/table-of-contents/use-active-section.ts
Fixing this error: https://developer.hashicorp.com/vault/docs/platform/k8s/helm/examples/standalone-tls
This is caused by a query selector which has a leading digit, which is not valid as a CSS selector. Using the built-in [`CSS.escape()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) method to properly escape the selector.
=> fix: escape query selector to ensure it doesn't break

src/data/waypoint.json
Turns off waypointproject.io alert banner. Confirmed with PMM that they have enough sign-ups for the private beta program.
=> disable waypoint alert banner

src/components/head-metadata/index.tsx, src/components/head-metadata/types.ts, src/lib/get-deployed-url.ts, src/pages/_app.tsx
- [Preview link](https://dev-portal-git-zspatch-local-dev-img-url-issue-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202555939973908/f) 🎟️
Fixes an issue related to `@hashicorp/react-head`, where aggressive validation of image URLs passed to the component would cause errors in local development.
Gets the `host` value in `_app.tsx` `getInitialProps`.
An alternate solution might be to hard-code the `PORT` and read that from `process.env`, as suggested [here](https://github.com/hashicorp/dev-portal/pull/664#discussion_r911359822). However, that would mean we'd sacrifice NextJS's dynamic port selection (which automatically chooses a port other than `3000` if that port is already in use).
=> fix: use host in get-deployed-url

src/views/error-views/dev-dot-404/index.tsx
Fixes up the 404 page to support any and all products that are marked as in `"beta"`.
To ensure the 404 page will automatically work as expected as new products are added to the beta.
- Imports `ProductIcon` to allow any product icon to be rendered
- Uses `getIsBetaProduct` to filter products list
- Maps all products to necessary data for the `IconCardLinkGridList` "ViewModel"-ish component
- Visit [the preview of a 404 page][preview], and ensure it looks as expected
- Review the analogous work in #686, which makes identical changes but also flags Nomad as `"beta"`, and confirm the [404 preview from that PR][nomad-beta-preview] looks as expected (with Nomad added)
[task]: …
=> fix: support all products on 404 page

src/components/navigation-header/components/product-page-content/index.tsx
Adds in remaining product logos to the `product-page-content` portion of `navigation-header`.
To ease onboarding of new products, one less place to edit as we add new products to the beta.
Visit each of the stubbed product routes, and ensure the logo in the top navigation looks as expected:
- [/boundary][/boundary]
- [/consul][/consul]
- [/nomad][/nomad]
- [/packer][/packer]
- [/terraform][/terraform]
- [/vagrant][/vagrant]
- [/vault][/vault]
- [/waypoint][/waypoint]
Note that `sentinel` and `hcp` are excluded for now, as we do not yet have a clear design spec for the top navigation bar for those "products".
[task]: https://app.asana.com/0/1202097197789424/1202591099445242/f
[preview]: …
=> feat: expand PRODUCT_SLUGS_TO_LOGOS

config/base.json, src/layouts/sidebar-sidecar/server.ts
Moves `content_preview_branch` out of config, and into a function in the one area where `content_preview_branch` config was previously used. 
We intend to onboard further products to "beta" mode, but we do not intend to add `dev-portal` branches for these products.
[task]: https://app.asana.com/0/1202097197789424/1202594381568855/f
[preview]: https://dev-portal-git-zscontent-branch-config-hashicorp.vercel.app
[/vault]: https://dev-portal-git-zscontent-branch-config-hashicorp.vercel.app/vault
[/waypoint]: https://dev-portal-git-zscontent-branch-config-hashicorp.vercel.app/waypoint
=> fix: move content_preview_branch config to function

src/pages/boundary/index.tsx, src/pages/consul/index.tsx, src/pages/hcp/index.tsx, src/pages/nomad/index.tsx, src/pages/packer/index.tsx, src/pages/sentinel/index.tsx, src/pages/terraform/index.tsx, src/pages/vagrant/index.tsx, src/pages/vault/index.tsx, src/pages/waypoint/index.tsx, src/views/product-landing/index.tsx, src/views/product-landing/server.ts
- This is the first PR for breaking up #701 into smaller PRs.
- Adds a `generateGetStaticProps` to `ProductLandingView`'s server
- Updates the generated `getStaticProps` to generate the page content file path from the given `product.slug`
- Updates each page component that has `export default ProductLandingView` to use the new `generateGetStaticProps`
- Overall, this reduces the boilerplate needed in each page component that renders `ProductLandingView`
- The generated `getStaticProps` was updated to generate the page content file path from the given `product.slug` to:
- simplify the API of `generateGetStaticProps`
- increase maintainability by having only one place to update the file path structure (rather than 1 for each product)
The following pages should have no change in content or …
=> Reduce ProductLandingView boilerplate

src/components/navigation-header/index.tsx
- Updates the main navigation header to render the non-product header on `/_error` routes (such as 404)
- When we updated `PRODUCT_SLUGS_TO_LOGOS` in #699, it made non-beta product logos start showing up on 404 routes nested under non-beta product slugs (example: https://developer.hashicorp.com/boundary/not-a-page)
- Just updated the logic of when the non-product header is rendered, to include a check for `router.route === '/_error'`
This might just be a bandaid until we've released all products in beta / GA. I figured it's better overall to not show non-beta product slugs on 404 pages until we've confirmed a long term plan.
=> Rendering generic nav header on /_error

src/components/opt-in-out/helpers/get-io-redirect-path.ts, src/components/opt-in-out/helpers/platform-options.ts, src/components/opt-in-out/types.ts, src/layouts/docs-view-layout/index.tsx
Builds out opt-in opt-out config for all remaining products.
To reduce boilerplate needed when onboarding a new product to HashiCorp Developer.
- Adds new function `generateGetIoRedirectPath`, which returns a `getRedirectPath` function for a given dot-io baseUrl.
- Uses `generateGetIoRedirectPath` to set up `PLATFORM_OPTIONS` for all remaining products
- Not sure this is really possible to fully test without this work being in production? 🤔 Open to ideas on how to best test this work.
[task]: https://app.asana.com/0/1202097197789424/1202606978405428/f
[preview]: https://dev-portal-git-zsopt-in-out-config-hashicorp.vercel.app/
[/vault]: https://dev-portal-git-zsopt-in-out-config-hashicorp.vercel.app/vault
[/waypoint]: …
=> feat: all-product opt-in-out config

scripts/remove-non-beta-product-pages.ts, src/__tests__/remove-non-beta-product-pages.test.ts
Adds a short test case for `remove-non-beta-product-slugs` to ensure that any time the list of
removed directories changes we need to address it via a snapshot update, which should give us a signal as to whether or not the change is expected.
We accidentally deleted the new dynamic tutorials routes, which didn't manifest until the production build.
=> feat(test): test case for remove-non-beta-product-pages

global.d.ts, src/hooks/use-authentication.ts, src/lib/auth/cloud-idp-provider.ts, src/pages/auth.tsx, src/types/auth.ts
- [Preview link](https://dev-portal-git-ambadd-auth-abstractions-hashicorp.vercel.app/auth) 🔎
- [Asana task](https://app.asana.com/0/1201147515801429/1202621516737909/f) 🎟️
- Adds `ValueOf` global utility type (in `global.d.ts`)
- Adds high-level types for auth (in `src/types/auth.ts`)
- `SessionData`: similar to next-auth's `Session` object, but we remove `user` from and add `id`
- `UserData`: similar to next-auth's `Session['user']` object, but we add `nickname` to it
- `ValidAuthProviderId`: an readonly object of valid auth provider IDs, useful in the `signInWrapper` signature
- Adds `useAuthentication` hook with a few derived values, re-organized data, and helpers
- `isAuthenticated`: prevents needing to type out `status === 'authenticated'`
- `isLoading`: prevents needing to type out …
=> Add useAuthentication hook

src/views/product-root-docs-path-landing/components/icon-card-link-grid/index.tsx
Fixes the `IconCardLink` components in the hero of the `/docs` pages
=> [hotfix] Fixing IconCardLink urls on /docs

src/hooks/use-authentication.ts
- [Asana task](https://app.asana.com/0/1201147515801429/1202651576734176/f) 🎟️
- Adds `signOutWrapper`, similar to `signInWrapper`
- Sets default `callbackUrl` for `signOut` to be the home page
- On SignOut, we currently get re-logged back in because the `/profile` page gets reloaded
- The `signOutWrapper` makes it possible for us to easily customize this experience (Not sure if `/` is the longterm place to redirect to, but it's a good temporary place)
- The [`signOut` docs](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl-1) were particularly helpful
=> Add signOutWrapper in useAuthentication

src/content/vault/install-landing.json, src/content/waypoint/install-landing.json
Removes Tutorials links from both Vault and Waypoint's /downloads sidecar marketing cards.
The Tutorials links were listed under "Featured docs", and the link is not a featured doc.
=> Remove Tutorials links from Vault and Waypoint sidecar marketing cards

src/components/button-link/index.tsx, src/components/button-link/types.ts, src/components/button/index.tsx, src/components/button/types.ts, src/components/navigation-header/components/give-feedback-button/index.tsx, src/views/collection-view/components/collection-meta/index.tsx
- Refactors `ButtonProps` to inherit native `<button>` props without re-casing them (aka `aria-label` to `ariaLabel`)
- Wraps `Button` in `forwardRef` for future use
- Updates `ButtonLinkProps` with the refactored `ButtonProps` it references
- Updates `ButtonLink` references as needed
- Primarily, this makes it easier to spread props over `Button` or `<button>` in single component that chooses which element it needs to render.
This PR is the first in creating the new `DropdownDisclosure` component. Some of these changes are needed in order for that component to use this one.
=> Refactor ButtonProps and ButtonLinkProps

config/base.json, config/development.json, config/preview.json, config/production.json, src/hooks/use-authentication.ts, src/views/authenticated-view/index.tsx
- [Asana task](https://app.asana.com/0/1202097197789424/1202664135851182/f) 🎟️
- Adds `enable_auth` flag to `base` and `production` configs
- Adds `isEnabled` derived boolean to our `useAuthentication` return value
- Updates `AuthenticationView` to return `ErrorView` if `isEnabled` is `false`
- The `enable_auth` flag is necessary for us to build authenticated user features in isolation without showing these features in production.
- The `isEnabled` boolean from `useAuthentication` will be really nice for conditionally rendering elements such as the Sign In and Sign Out buttons that will live in the navigation header / mobile sidebar.
- Updating `AuthenticationView` to return `ErrorView` if `isEnabled` is `false` is an easy test for checking if the flag is working as expected. And if any …
=> Add enable_auth flag

src/components/tutorial-meta/index.tsx, src/components/tutorial-meta/tutorial-meta.module.css, src/hooks/use-authentication.ts, src/views/authenticated-view/index.tsx, src/views/collection-view/components/collection-meta/collection-meta.module.css, src/views/collection-view/components/collection-meta/index.tsx
- Asana Tasks 🎟️ 
- [[CollectionView] Add "Create an account" CTA below collection description](https://app.asana.com/0/1202097197789424/1202661920988675/f)
- [[TutorialView] Add "Create an account" CTA below badges and "Show Terminal" button](https://app.asana.com/0/1202097197789424/1202661920988679/f)
- Renames `useAuthentication`'s `isEnabled` property in the returned object to `isAuthEnabled` for clarity
- Adds Create Account CTAs to both `CollectionView` and `TutorialView`
- The `useAuthentication` `isAuthenticated` and `isAuthEnabled` properties were particularly useful here.
<details>
<summary>CollectionView CTA</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11440%3A114695">Figma link</a>
</details>
<details>
<summary>TutorialView …
=> Add Create Account CTA to CollectionView and TutorialView

src/components/navigation-header/index.tsx, src/components/navigation-header/navigation-header.module.css, src/components/user-dropdown-disclosure/index.tsx, src/components/user-dropdown-disclosure/types.ts, src/hooks/use-authentication.ts
- Adds `className` prop to `UserDropdownDisclosure` to enable custom styling in some cases (like the dark navigation header)
- Adds `showAuthenticatedUI` and `showUnauthenticatedUI` booleans to the return object of `useAuthentication` (shout out to @kendallstrautman for the idea in a PR from this week! 🙌🏻)
- Updates `NavigationHeader` to render `UserDropdownDisclosure` for authenticated users on wide viewports (narrow viewports coming soon)
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11357%3A114658)
=> Render UserDropdownDisclosure for authenticated users in wide viewports

src/components/mobile-menu-container/components/index.ts, src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx, src/components/mobile-menu-container/components/mobile-user-disclosure/mobile-user-disclosure.module.css, src/components/mobile-menu-container/components/mobile-user-disclosure/types.ts, src/components/mobile-menu-container/index.tsx, src/components/navigation-header/index.tsx, src/components/user-dropdown-disclosure/index.tsx, src/lib/auth/user.tsx
- Asana tasks 🎟️
- [Build mobile version of UserDropdown (attempt just CSS changes)](https://app.asana.com/0/1202097197789424/1202665629707465/f)
- [[Mobile Sidebar] Render mobile UserDropdown (behind enable_auth flag) on narrow viewports when a user is authenticated](https://app.asana.com/0/1202097197789424/1202665629707469/f)
- Adds several helpers in `src/lib/auth/user.tsx` that provide a content source of truth for consistent rendering between `MobileUserDisclosure` and `UserDropdownDisclosure`
- Adds new `MobileUserDisclosure` under `MobileMenuContainer`
- Updates `MobileMenuContainer` to show `MobileUserDisclosure` for authenticated users
- Updates `NavigationHeader` to source `UserDropdownDisclosure` items from new `getUserMenuItems` helper
- Updates `UserDropdownDisclosure` to …
=> Add mobile UserDropdownDisclosure; render in mobile sidebar for authenticated users

.editorconfig
Adds an https://editorconfig.org/ file to ensure portability of our tab preference
=> Adds editorconfig to use tab by default

src/components/_proxied-dot-io/common/dev-dot-opt-in/index.tsx, src/components/_proxied-dot-io/common/docs-page/index.tsx, src/layouts/_proxied-dot-io/nomad/index.tsx, src/pages/_proxied-dot-io/nomad/docs/index.tsx, src/pages/_proxied-dot-io/vault/docs/index.tsx
- Asana tasks 🎟️ 
- [Stage adding "nomad" production beta_product_slugs array](https://app.asana.com/0/1202097197789424/1202632199481601/f)
- [[DevDotOptIn] Cookie is not correctly set on VaultProject.io](https://app.asana.com/0/1202097197789424/1202699829872281/f)
- Adds `ProductMetaProvider` to `NomadIoLayout`
- Adds `optInBanner` prop passed to `DocsPageInner` by `NomadDocsLandingPage`
- Delegates rendering logic of `DevDotOptIn` to the body of the component since the logic is always the same
- Updates `DevDotOptIn` to use a `<a>` instead of a `<button>` since clicking the element causes navigation
- Fixes the cookie set by `DevDotOptIn` to no longer be hardcoded to `"waypoint"` (this is a bug)
- NOTE: the 404 error will show but that's OK since Nomad isn't in production beta yet 
The …
=> Stage Nomad opt-in banner on .io site

src/components/sidebar/components/sidebar-nav-menu-item/index.tsx, src/components/sidebar/docs.mdx, src/components/sidebar/types.ts
- [Preview link](https://dev-portal-git-ambenable-submenu-load-open-hashicorp.vercel.app/swingset/components/sidebar) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1202710659957129/f) 🎟️
- Adds new `isOpen` property to `MenuItem`
- Handles `item.isOpen` in `SidebarNavSubmenuItem`
- This is part of the request for nesting `rootDocsPaths` under a new `Documentation` submenu in Sidebar. See #762 for more context on the other part of this ask.
=> Adding isOpen ability to SidebarNavSubmenuItem

scripts/content-repo-preview/start.sh
We got a report that local preview was regularly erroring for folks. This was because new packages weren't getting installed when they already had the `website-preview` directory locally. This adjustment should ensure that `npm install` always gets run, regardless of the local state.
=> fix: always run npm install on local preview start

src/components/sidebar/helpers/generate-product-landing-nav-items.ts
- [Asana task](https://app.asana.com/0/1202097197789424/1202710659957128/f) 🎟️
- Updates `generateProductLandingSidebarMenuItems` to nest `rootDocsPaths` items under a new `Documentation` submenu, rather than list each item as an item at the root level
- This is an update in our designs
| Nomad  | Terraform |
| - | - |
| [Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11227%3A114199)  | [Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11253%3A106817) |
| <img width="458" alt="CleanShot 2022-08-03 at 11 31 05@2x" src="https://user-images.githubusercontent.com/43934258/182648297-c961c4cc-b94b-4da6-b43e-da66c4044082.png"> | <img width="286" alt="CleanShot 2022-08-03 at 11 32 13@2x" …
=> Nesting rootDocsPaths under new Documentation sidebar item

src/views/tutorial-view/components/next-previous/next-previous.module.css
- Fixes the alignment of the Next/Previous `CardLink` elements that show at the bottom of `TutorialView`s, which was introduced in #764
=> [TutorialView] Fixing next/previous at bottom of page

src/components/_proxied-dot-io/packer/remote-plugin-docs/server.ts, src/pages/_proxied-dot-io/packer/plugins/[...page].tsx
Fixes an issue where Packer `/plugin` routes that could not be resolved would 500, rather than produce a more expected 404 status.
- It may be unexpected that a resource can't be resolved, but we should handle this more gracefully that the Vercel default 500 error page currently visible at URLs such as https://www.packer.io/plugins/builders/huaweicloud
- This fix will hopefully also get our `Cache io & tutorials path` check working again, which is [currently failing for reasons that seem related](https://github.com/hashicorp/dev-portal/runs/7662061150?check_suite_focus=true) to URLs such as https://www.packer.io/plugins/builders/huaweicloud
- We currently [throw errors in CI for …
=> fix: avoid 500 when Packer plugins navNode cannot be matched

src/lib/remark-plugins/rewrite-tutorial-links/index.ts, src/views/collection-view/helpers/get-slug.ts
After #795, were getting a bunch of build log warnings because the onboarding tutorial paths are being rewritten in the tutorial map generation. This is a small fix for that warning.  
Also removed an accidental log that crept in.
=> chore: fix onboarding link rewrites

src/components/video-embed/__tests__/video-embed.test.tsx
This PR comments out the `VideoEmbed` test that causes seg faults locally and sometimes in PR checks. It adds a block comment above the test that references a new ticket for replacing Jest tests with integration tests: [[VideoEmbed] Rewrite tests as integration tests](https://app.asana.com/0/1202097197789424/1202765914032430/f).
=> [VideoEmbed] Commenting out test that causes seg faults

src/layouts/sidebar-sidecar/utils/__tests__/prepare-nav-data-for-client.test.ts, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
- [Preview link][/terraform/plugin] 🔎
Fixes an issue where some sidebar links on [/terraform/plugin][/terraform/plugin] did not function as expected.
- We want to ensure sidebar links work as expected
- Our source `nav-data` may have relative `href` values without leading slashes
- Example: [`plugins-nav-data.json` in `terraform-docs-common`](https://github.com/hashicorp/terraform-docs-common/blob/main/website/data/plugin-nav-data.json#L35)
Tweaks `fullPath` construction when dealing with navNodes with relative `href` values. 
- Example: `Back to documentation` link on [/vagrant/vagrant-cloud][/vagrant/vagrant-cloud] uses non-absolute `href` ([source](https://github.com/hashicorp/vagrant/blob/main/website/data/vagrant-cloud-nav-data.json))
- Example: many `Task …
=> fix: tweak fullPath from relative href logic

src/layouts/sidebar-sidecar/index.tsx, src/views/docs-view/server.ts, src/views/docs-view/utils/get-root-docs-path-generation-functions.ts
This PR fixes an issue where the version select is shown unintentionally on pages.
Showing a version select with a single `0.0.x` version is not our desired user experience.
- Previously, in #817, we introduced a `getShowVersionSelect` function
- Currently, `showVersionSelect` defaults to `true` even if there is only one `0.0.x` version
- This PR revises the approach in an attempt to simplify version select hiding for many cases
- If `showVersionSelect` has not explicitly been set, rather than default to `true`, we only show the version selector if:
- there is more than one version
- _or_ if the single version is any version other than `0.0.x`
- Note that we still retain `getShowVersionSelect`
- For the Packer plugins case, we do have …
=> fix: only show version select for meaningful versions

src/data/terraform.json, src/views/docs-view/server.ts, src/views/docs-view/utils/__tests__/get-back-to-link.test.ts, src/views/docs-view/utils/get-back-to-link.ts
Updates "nested" docs categories to have a "back to" link in the sidebar that leads to the parent category, rather than the product home page.
To match designs.
- Splits out a new utility `get-back-to-link` under `views/docs-view/utils` to handle some revised logic
- In `get-back-to-link`, if the current `rootDocsPath` is "nested", looks for the parent `rootDocsPath`, and if it can find one, uses it to build the `backToLinkProps`
> **Note**: the scope of this PR is to address the "back to" link only. There are other changes we need to make to match designs, these are list as subtasks of 🎟️  [Implement design updates for Terraform](https://app.asana.com/0/1202097197789424/1202663176963860/f) and will be handled separately.
Confirm that …
=> fix: terraform nested docs backToLinkProps

src/views/docs-view/server.ts
Fixes an issue where `Edit on GitHub` links are being displayed for HCP and Sentinel docs. The content repositories are private, so these links aren't of much use to the public.
To only show useful, functioning `Edit on GitHub` links.
Conditionally adds `layoutProps.githubFileUrl` only if the current product slug is not `hcp` or `sentinel`.
- 🙈 The `Edit on GitHub` link should not be shown.
- Example: [/hcp/docs/create-account][/hcp/docs/create-account]
- 🙈 The `Edit on GitHub` link should not be shown.
- Example: [/sentinel/docs/writing][/sentinel/docs/writing]
- 👀 The `Edit on GitHub` link should still be visible.
- Example: [/vault/docs/use-cases][/vault/docs/use-cases]
[preview]: …
=> fix: hide edit-on-github for HCP and Sentinel

src/components/card-link/index.tsx
Fixes a spacing issue at the top of some CardLink elements.
Was introduced when `{children}` was moved after `<Link>` to fix the TAB order of elements. Have created a follow-up ticket to fix the TAB order in a different way: https://app.asana.com/0/1202097197789424/1202822098515463/f.
=> [hotfix] Fixing CardLink <a> order and spacing issue

src/components/bookmark-button/helpers/connected-bookmark-button.tsx, src/components/bookmark-button/index.tsx, src/components/tutorial-card/helpers/index.ts, src/components/tutorial-card/helpers/with-bookmark.tsx, src/components/tutorial-card/index.tsx, src/views/collection-view/components/collection-tutorial-list/index.tsx, src/views/product-downloads-view/components/featured-tutorials-section/index.tsx, src/views/product-landing/components/product-landing-blocks/blocks/tutorial-cards/index.tsx, src/views/product-tutorials-view/components/product-view-content/components/tutorials-stack/index.tsx
- [Preview link](https://dev-portal-git-ksadjust-bookmark-controller-hashicorp.vercel.app/) 🔎
Renamed the `withDialog` component to be `ConnectedBookmarkComponent` to reflect that it controls state, along with the dialog rendering. 
Renamed `ConnectedTutorialCard` to `TutorialCardWithBookmark` since it doesn't manage state, and just renders the bookmark in the eyebrow slot.
=> refactor: renaming bookmark components

src/components/button-link/index.tsx, src/components/button-link/types.ts, src/views/profile/bookmarks-view/components/empty-state/empty-state.module.css, src/views/profile/bookmarks-view/components/empty-state/index.tsx, src/views/profile/bookmarks-view/index.tsx
- [Preview link](https://dev-portal-git-ksadds-empty-state-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202832753754548) 🎟️
This PR adds a styled 'empty state' to the bookmarks profile view. 
- Pull this branch down locally, start the dev server and sign in.
- Navigate to /profile/bookmarks
- You should see the test empty state below the card grid (if you already have bookmarks). 
Since the bookmark cards don't let you remove them atm, I opted to stage the test component below the card grid. I guess I could add it to swingset but it is only used in one place so seems more suited nested under the /views structure.
=> feat: adds bookmark page empty state

src/components/navigation-header/navigation-header.module.css, src/contexts/mobile-menu.tsx, src/layouts/core-dev-dot-layout/core-dev-dot-layout.module.css, src/layouts/sidebar-sidecar/contexts/sidebar-nav-data.tsx, src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css, src/styles/custom-media.css
- Fixes the mobile menu on tablet viewports, with some custom logic pulled from `useDeviceSize`, since this is the only place where we have customized a special breakpoint.
- When we updated the nav header breakpoint recently, we did catch that we needed to update the breakpoint used by `MobileMenuProvider` as well.
=> Fix tablet width mobile menu

src/components/dropdown-disclosure/components/activator/index.tsx, src/components/dropdown-disclosure/dropdown-disclosure.module.css, src/views/profile/bookmarks-view/bookmarks-view.module.css, src/views/profile/bookmarks-view/helpers/card-sort-data.ts, src/views/profile/bookmarks-view/index.tsx
- [Preview link](https://dev-portal-git-ksadds-bookmarks-sort-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202832753754546) 🎟️
This PR adds a sort feature to the tutorial card view. This sort occurs based on `created_date` for the bookmark.
=> feat: adds bookmarks sort

src/__tests__/remove-non-beta-product-pages.test.ts, src/data/onboarding.json, src/pages/onboarding/[collectionSlug].tsx, src/views/onboarding/collection-view/index.tsx, src/views/onboarding/types.ts
- [Preview link](https://dev-portal-git-ksonboarding-pages-hashicorp.vercel.app/onboarding/terraform-enterprise-week-1) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202885494551261) 🎟️
This PR adds all onboarding collections. 
I reused a lot of code from the waf implementation. There's room to abstract to create a generic collection or tutorial view, I will note that for follow up work. 
- visit a few onboarding collection urls
- https://dev-portal-git-ksonboarding-pages-hashicorp.vercel.app/onboarding/terraform-enterprise-week-1
- https://dev-portal-git-ksonboarding-pages-hashicorp.vercel.app/onboarding/hcp-vault-week-1
- https://dev-portal-git-ksonboarding-pages-hashicorp.vercel.app/onboarding/tfcb-week-3
- https://dev-portal-git-ksonboarding-pages-hashicorp.vercel.app/onbo …
=> feat: onboarding collection pages

src/components/navigation-header/components/home-page-content/index.tsx, src/views/well-architected-framework/tutorial-view/index.tsx
- [Preview link](https://dev-portal-git-ksupdate-nav-hashicorp.vercel.app/well-architected-framework) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202863899279051) 🎟️
To improve the UX for the waf pages, this link needed to be added to the base nav header. 
To allow for ease of navigation between the waf views and the home page. 
- visit the [waf page](https://dev-portal-git-ksupdate-nav-hashicorp.vercel.app/well-architected-framework), click the link to the home page
- no styles should be affected
=> chore: adds link to 'HashiCorp Developer' nav icon

src/views/homepage/components/product-nav/index.tsx, src/views/homepage/components/product-nav/product-nav.test.tsx, src/views/homepage/index.tsx
- [Preview link](https://dev-portal-git-kevin-conditionally-render-prod-7da094-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202772453379361/f) 🎟️
This adds logic to conditionally render the `ProductNav.notice` 
- View the deploy preview, and validate that the notice is **not** present (because all products are _in beta_ in preview environments)
=> feat: conditionally render `ProductNav.notice`

src/components/command-bar/components/activator/index.tsx, src/components/command-bar/index.tsx, src/components/command-bar/types.ts
- [Asana task](https://app.asana.com/0/0/1202932738893664/f) 🎟️
- Renames `setIsOpen` to `toggleIsOpen` and abstracts the toggling logic
- Adds `currentCommand` property to `CommandBarContext`'s state
- Exposes `setCurrentCommand` function from `CommandBarContext`
- Breaks `CommandBarState` `interface` into two new ones:
- `CommandBarContextState`
- `CommandBarContextValue`
- Renders a small demo in the `CommandBarDialog` body for testing `setCurrentCommand`
This approach does some of the groundwork for supporting additional commands, with our current default being `"search"` since we don't have other commands yet.
=> Adding currentCommand to CommandBarContext

src/components/toast/components/toast-display/toast-display.module.css, src/hooks/progress/index.ts, src/hooks/progress/use-collection-progress.ts, src/hooks/progress/use-tutorial-progress-mutations/index.ts, src/hooks/use-previous.ts, src/lib/learn-client/api/progress/formatting.ts, src/lib/learn-client/api/progress/get-all-progress.ts, src/lib/learn-client/api/progress/index.ts, src/views/tutorial-view/index.tsx, src/views/tutorial-view/utils/make-progress-toast/index.tsx, src/views/tutorial-view/utils/make-progress-toast/progress-toast.module.css, src/views/tutorial-view/utils/use-progress-toast.ts
When a tutorial changes to `"complete"` on a tutorial view, displays a tutorial progress toast notification.
To continue user progress implementation, for feature parity with <https://learn.hashicorp.com/>
- Adds `get-all-progress` `learn-client` utility, to allow fetching batched progress data from the Learn API
- Adds `use-collection-progress` hook, to query collection progress by ID, using `get-all-progress`
- Adds `use-previous` utility function, to track changes in a variable (same as existing `learn` implementation)
- Adds `use-progress-toast` hook
- Uses `use-previous` to detect when progress status for a tutorial changes
- Uses `use-collection-progress` to detect when completing a specific tutorial means the collection is …
=> feat: tutorial progress toasts

src/components/command-bar/command-bar.module.css, src/components/command-bar/commands/index.ts, src/components/command-bar/commands/search.tsx, src/components/command-bar/commands/settings.tsx, src/components/command-bar/components/dialog/command-bar-dialog.module.css, src/components/command-bar/components/dialog/index.tsx, src/components/command-bar/components/dialog/types.ts, src/components/command-bar/index.tsx, src/components/command-bar/types.ts
- [Asana task](https://app.asana.com/0/1201147515801429/1202932738893668/f) 🎟️
- Adds support for two commands:
- `search`
- `settings` (not used, just to demonstrate future flexibility)
- Updates `setCurrentCommand` to accept a command name for pulling the new current command from the `commands` map
- Updates `CommandBarDialogHeader` to render content based on `currentCommand`
- Updates `CommandBarDialogBody` to render a temporary button for switching between commands
- Updates `CommandBarContext`'s value to be memoized with `useMemo`
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12514%3A144676)
=> [CommandBarDialog] Render icon, text input, and Badges in header

package-lock.json, package.json, src/pages/_proxied-dot-io/vault/not-found/index.jsx, src/views/404/index.jsx
🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1202865459293217/f)
---
This PR leverages the new `useErrorPageAnalytics` hook (see [this PR](https://github.com/hashicorp/web-platform-packages/pull/86)) for pushing 404-related data to Segment. This PR replaces the `window.analytics.track` call on the 404 page with said hook.
It was recently discovered that, across our various web properties, we make the following call:
`window.analytics.track(window.location.href, { ... } )`
The first parameter of the `track` method is used downstream in our various data warehouses to create a new table. Since we're using `window.location.href`, we're creating a table for _every_ URL that 404s. This is not ideal for analytics.
=> Use `useErrorPageAnalytics` hook on 404 page

src/views/docs-view/index.tsx, src/views/product-root-docs-path-landing/index.tsx
- [Asana task](https://app.asana.com/0/1202097197789424/1202954349649032/f) 🎟️
- Hides `ProductDocsSearch` when global search is enabled
- We do not want both searches to show at the same time
- The `enable_global_search` feature flag 🤩
=> Hiding ProductDocsSearch when enable_global_search is true

src/lib/remark-plugins/rewrite-tutorial-links/utils/handle-learn-links.ts
This is a follow up to #1001. After it was merged, @BRKalow found `URL.search` would be useful for the query string.
There should be no functional or visual changes since #1001.
=> [handleTutorialLink] Using URL.search property for query string

src/views/product-landing/components/overview-cta/overview-cta.module.css
- [Preview link](https://dev-portal-git-ksfix-overview-item-space-hashicorp.vercel.app/packer) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202954349649039) 🎟️
Adds row gap to the overview item component for landing pages. 
- Go to a [product landing page](https://dev-portal-git-ksfix-overview-item-space-hashicorp.vercel.app/consul)
- shrink down to mobile view, verify the spacing between the image and the overview text.
=> chore: fix overview item row gap

src/data/packer.json
Updates `/plugins` `rootDocsPath` name to `"External Plugins"`.
VQA item.
Updates `src/data/packer.json`.
- This PR also removes `packer.json` `subnavItems`
- These previously powered the dot-io site, but we've since moved to managing subnav items in Dato for Packer.
[task]: https://app.asana.com/0/1202702246158644/1202975892434100/f
[preview]: https://www.hashicorp.com
=> chore(packer): rename Plugins to External Plugins

src/lib/remark-plugins/rewrite-tutorial-links/index.ts, src/lib/remark-plugins/rewrite-tutorial-links/utils/handle-learn-links.ts, src/views/product-tutorials-view/helpers/__tests__/detect-and-reformat-learn-url.test.ts
- Primarily updates the checks in `rewriteTutorialsLink` to be stronger
- Adds an error check (that doesn't break builds) for links that meet multiple link-type conditions (only one should be met)
- In cases where a product's .io hostname is within a value for a query string param, the link is being detected as both a learn link _and_ a docs link. Because the `isDocsPath` check was being handled first, the link was always being handled as a docs link even if it was actually a learn link.
=> [rewriteTutorialsLink] Handle links with complex query params

src/views/product-downloads-view/components/sidecar-marketing-card/index.tsx
- [Preview link](https://dev-portal-git-ambremove-learn-more-links-hashicorp.vercel.app/waypoint/downloads) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202981777114622/f) 🎟️
- Removes "Learn more" links from `SidecarMarketingCard`
=> [SidecarMarketingCard] Removing Learn more link

src/components/breadcrumb-bar/breadcrumb-bar.module.css, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
- [Preview link](https://dev-portal-git-ksfix-double-space-docs-hashicorp.vercel.app/nomad/docs/commands/recommendation/list) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202983574737104/f) 🎟️
Refactored where the breadcrumb margin lives so that things collapse properly with or without the docs searchbar (for previews and current prod) 
To test for the prod view pull this down locally and set `enable_global_search` to false in the development config.
=> fix: adjust breadcrumb margin

src/content/terraform/docs-landing.json
Terraform homepage mistakenly said "Transform CLI" instead of Terraform CLI.
=> fix typo on terraform docs homepage

src/components/author-primitives/shared/button/index.tsx, src/views/docs-view/index.tsx, src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts, src/views/docs-view/utils/product-url-adjusters.ts
- [Preview link](https://dev-portal-git-ksfix-vmware-downloads-link-hashicorp.vercel.app/vagrant/docs/providers/vmware/installation) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202794559462712) 🎟️
This link is broken in content and is a one-off compared to other docs links since we did restructure the path.
- [Visit this page](https://dev-portal-git-ksfix-vmware-downloads-link-hashicorp.vercel.app/vagrant/docs/providers/vmware/installation) and click the vmware utility downloads page link. It should resolve to the correct dev portal path.
=> chore: fix vagrant vmware link

src/components/navigation-header/components/product-page-content/utils/__tests__/get-nav-items.test.ts, src/data/terraform.json, src/types/products.ts, src/views/docs-view/server.ts
Switches from `visuallyHideSidebarTitle` config options, which need to be manually maintained, to automatic detection to meet similar ends.
- Some `rootDocsPath` `nav-data.json` starts with a `heading` node, making the added sidebar title look odd
- Manually maintaining which `rootDocsPath` this condition applies to is brittle
- This brittleness puts content folks in a bind where removing those edge-case headings would result in no headings at all appearing in the sidebar.
- By automatically detecting this condition, we can fix the underlying content inconsistency at any time, with confidence that thing will look the way we expect.
- Uses `firstItemIsHeading` from #1037 to replace `"visuallyHideSidebarTitle"`
- Removes …
=> feat: auto detect for visuallyHideSidebarTitle

src/content/packer/docs-landing.json
Removes icon cards from [/packer/docs][preview].
Updates `src/content/packer/docs-landing.json`.
[task]: https://app.asana.com/0/1202097197789424/1203016864094230/f
[preview]: https://dev-portal-git-zsrm-packer-docs-links-hashicorp.vercel.app/packer/docs
=> feat: rm packer docs icon grid cards

src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-external-tutorial-link.test.ts, src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-tutorial-links.test.ts, src/lib/remark-plugins/rewrite-tutorial-links/utils/rewrite-external-learn-link.ts, src/lib/remark-plugins/rewrite-tutorial-links/utils/rewrite-external-tutorial-link.ts
- Fixes the part of the tutorial link rewriting where the `TUTORIAL_MAP` lookup is happening for `hcp` tutorials. The map stores `cloud`, but `hcp` was being used.
- Fixes valid `SectionOption`s not being rewritten, and updates the `get-is-beta-product` mock to be more restrictive so the tests were no longer false positives.
=> [rewriteTutorialLinksPlugin] Fixing tutorial lookup and section rewriting

next.config.js, src/components/image/index.tsx
This PR updates our usage of `next/image` to `next/future/image` in the single place where we were using an experimental property (`layout="raw"`) that is no longer available as of Next 12.2.
=> fix: migrate to next/future/image

src/content/packer/docs-landing.json, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts, src/pages/packer/plugins/[...page].tsx, src/pages/packer/plugins/index.tsx, src/views/docs-view/server.ts
- [Asana task](https://app.asana.com/0/1202097197789424/1202981777114602/f) 🎟️
- Sourcegraph searches
- [learn.hashicorp.com](https://hashicorp-mktg.sourcegraph.com/search?q=context:global+learn.hashicorp.com+lang:json+&patternType=standard)
- [boundaryproject.io](https://hashicorp-mktg.sourcegraph.com/search?q=context:global+boundaryproject.io+lang:json+&patternType=standard)
- [consul.io](https://hashicorp-mktg.sourcegraph.com/search?q=context:global+consul.io+lang:json+&patternType=standard)
- [cloud.hashicorp.com](https://hashicorp-mktg.sourcegraph.com/search?q=context:global+cloud.hashicorp.com+lang:json+&patternType=standard)
- [nomadproject.io](https://hashicorp-mktg.sourcegraph.com/search?q=context:global+nomadproject.io+lang:json+&patternType=standard)
- …
=> Rewrite docs sidebar links to external Learn/Docs sites

src/pages/packer/plugins/[...page].tsx
Fixes an issue where the docs sidebar on `/packer/plugins/*` pages would display duplicate `Overview` items, and duplicate headings (since those routes do _not_ have the same "automatic" overview item and visually-hide-title logic as other docs pages).
=> fix: /packer/plugins/* duplicate overview item

src/components/command-bar/components/dialog/command-bar-dialog.module.css
- [Preview link](https://dev-portal-git-ambcommand-bar-input-focus-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1203052996378512/f) 🎟️
- Adds a focus state for the command bar text input
=> [CommandBar] Adding focus ring to input

src/components/accordion-disclosure/accordion-disclosure.test.tsx, src/components/algolia-search/index.tsx, src/components/command-bar/index.tsx, src/components/disclosure/index.tsx, src/components/navigation-header/components/dropdown-menu/index.tsx, src/hooks/use-on-route-change-start.ts
- [Asana task](https://app.asana.com/0/1202520168081556/1203053381984279/f) 🎟️
- Adds `useOnRouteChangeStart` hook
- Leverages new hook to make `CommandBarDialog` close on `routeChangeStart` (like other disclosures do)
- Refactors references to `routeChangeStart` listeners to use the new hook
- `AlgoliaSearch`
- `Disclosure`
- `NavigationHeaderDropdownMenu`
- Updates `AccordionDisclosure` tests to mock `next/router`
- Without this listener, the `CommandBarDialog` remains open in many navigation interactions
- The hook feels like a nice abstraction since it's very repetitive logic
=> [CommandBar] Close on navigation start

src/components/command-bar/commands/search/helpers/generate-suggested-pages.tsx
- [Preview link](https://dev-portal-git-ambgs-tutorial-library-link-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1203053381984286/f) 🎟️
- Fixes the link for the Tutorial Library suggested page under the HCP product context
=> [Global Search] Fixing Tutorial Library suggested page link

src/components/command-bar/commands/search/components/dialog-body/search-command-bar-dialog-body.module.css
- [Preview link](https://dev-portal-git-ambgs-tabs-spacing-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1203053381984287/f) 🎟️
- Updates the spacing above the `Tabs` that show when a search query is typed in the command bar input
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-11425%2C2763%2C2.06)
=> [Global Search] Fixing tabsWrapper padding

src/components/command-bar/components/dialog/footer.tsx
- [Preview link](https://dev-portal-git-ambgs-missing-return-key-badge-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1203053381984289/f) 🎟️
- Adds missing `Badge` for the enter key in the command bar dialog footer
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-6265%2C2683%2C1.15)
=> [CommandBar] Rendering missing icon badge in footer

src/content/boundary/install-landing.json, src/content/boundary/product-landing.json, src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-tutorial-links.test.ts
This updates a collection slug, which was renamed in 
- https://github.com/hashicorp/tutorials/pull/791
=> `boundary/oss-vault-cred-brokering-quickstart`

src/components/badge/index.tsx, src/components/badge/types.ts
- Removes two properties from our `Badge` component
- `ariaDescribedBy`
- `ariaLabelledBy`
- Adds a `g-screen-reader-only` `<span>` next to the regular `Badge` span that handles labelling `Badge` for screen reader users
- `<span>` doesn't actually accept `aria-label`, so it's not presented to users
- before these changes, the elements were announced as "<aria label>, group"
- In VoiceOver, this is VO + Arrow Right
No-audio demonstration:
https://user-images.githubusercontent.com/43934258/193285422-26fd7309-1bd3-49aa-b4fc-0f15db53c28a.mov
=> [Badge] Use g-screen-reader-only class for ariaLabel

src/layouts/sidebar-sidecar/components/table-of-contents/table-of-contents.module.css
Removes the `font-weight` shift for active items from the sidecar `TableOfContents`.
Intent here is prevent layout jank. Have confirmed using `400` as the consistent weight via Slack DM.
https://user-images.githubusercontent.com/4624598/193311975-7a3f43df-1629-4762-87c8-7368f6da8673.mp4
https://user-images.githubusercontent.com/4624598/193311998-ca04630d-a4d7-49b6-a6b0-903d879d90a2.mp4
=> fix: rm font-weight shift from sidecar

src/components/dev-dot-content/mdx-components/mdx-heading-permalink/mdx-heading-permalink.module.css
Fixes the height of `MdxHeadingPermalink`
In Safari, the component was rendering too tall and affecting the text below it.
`display: flex` 😊
=> [Safari bug] Fixing height of MdxHeadingPermalink

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
Fixes a bug in progress bar positioning.
Sets `min-height` on `SidebarSidecar` layout main area, to ensure content always occupies the area leading up to the footer.
- Any `SidebarSidecar` layout should still behave as expected. Short pages should look identical
- On short tutorials, such as [/consul/tutorials/getting-started/get-started-learn-more][/consul/tutorials/getting-started/get-started-learn-more], the progress bar should always be at the bottom of the page
[preview]: https://dev-portal-git-zsfix-short-tutorial-progress-b-7081a6-hashicorp.vercel.app/consul/tutorials/getting-started/get-started-learn-more
[task]: https://app.asana.com/0/1202702246158644/1203102626996732/f …
=> fix: progress bar posn on short tutorials

src/content/boundary/product-landing.json
This fixes a broken card link, caused by a collection-rename
- https://github.com/hashicorp/tutorials/commit/c9afc6c705ac5a59456b90931bd2d2332c6dc0c7#diff-704f3a51444e5f1ed6037cd1092a864210b3d8c84e6a20ee16e4b038d69d4893
=> fix(boundary): Broken renamed collection

src/components/tabs/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
- [Preview link](https://dev-portal-git-ambfix-tabs-controls-rendering-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203100487715425/f) 🎟️
- Moves the `overflowTargetRef ` from the `div` that contains both tab controls and panels to the `div` containing the tab controls.
- Overflow was being detected due to the content of a tab panel, but we really only care about overflow in the element where the controls live.
=> [Tabs] Moving overflowTargetRef placement

src/data/boundary.json, src/data/nomad.json, src/data/packer.json, src/data/sentinel.json, src/data/vagrant.json, src/data/vault.json, src/data/waypoint.json
- [Preview link](https://dev-portal-git-nq-update-alert-banners-hc-gl-2-2d870e-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1203117040758968/f) 🎟️
This PR removes alert banners showcasing HashiConf Global, after it closes. **This PR should merge no earlier than October 6 at 1:30pm PST / 4:30pm ET.**
=> feat(AlertBanners): Update for HashiConf Global closing

src/pages/terraform/downloads/index.tsx
We do some custom filtering on Terraform downloads filtering. This ensures that two different server-side values are in-sync with each other
https://dev-portal-git-kevin-fix-tf-downloads-hashicorp.vercel.app/terraform/downloads
=> fix(terraform): downloads

src/components/sidebar/docs.mdx, src/components/sidebar/helpers/add-nav-item-meta-data.ts, src/components/sidebar/types.ts
- [Preview link](https://dev-portal-git-ambreplace-sups-with-badge-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203115842976140/f) 🎟️
- Creates `badge` properties for nav items that hav `<sup>` tags in their `titles`
- Removes the `<sup>` tags from the nav item titles if they're present
- When the `dev-portal` branches were present, we handled this manually in the JSON files. Since we don't have those branches anymore, and some of the manual changes had to be undone, the changes proposed in this PR enable either the old or new format to work.
- This should also enable the new format that renders `Badge`s to work in old versions of docs.
Make sure the sidebars render as expected on these pages:
=> [addNavItemMetaData] Replace <sup> tags with Badges

src/lib/datadog/index.tsx
Disables DataDog Session Replay recording on the site.
Makes changes to the DataDog script body:
- changes `premiumSampleRate: 100` to `premiumSampleRate: 0`
- deletes the `DD_RUM.startSessionReplayRecording()` call
- Datadog → UX Monitoring in sidebar → Sessions → Filter by `Version` for this preview's commit SHA (`2fc019601ff56c0b34a620a7aff18439dac870df` at time of writing)
[preview]: https://dev-portal-git-zsdisable-datadog-rum-hashicorp.vercel.app/
[task]: https://app.asana.com/0/1202097197789424/1203111074373616/f
=> feat: disable-datadog-rum-session-replay

src/components/sidebar/helpers/generate-resources-nav-items.ts, src/views/tutorial-library/constants.ts
Adds a `Tutorial Library` link to the `Resources` section of all sidebars.
To increase discoverability of [/tutorials/library][/tutorials/library]
- Adds a function `getTutorialLibraryUrl`, that returns links to `/tutorials/library` with specific filters applied based on the current "product" (which may actually be a non-`product` filter in the context of tutorials, eg `hcp` is really an `edition` filter)
- Adds a `Tutorial Library` link to the generated sidebar resource links, using `getTutorialLibraryUrl` for the URL
- A `Tutorial Library` link should appear at the top of the `Resources` section in the sidebar
- The link should lead to [/tutorials/library?edition=hcp][/tutorials/library?edition=hcp]
- A `Tutorial Library` link should …
=> feat: add Tutorial Library to resources section

src/components/card/components/card-title/card-title.module.css
- Fixes the `line-height` of `CardTitle`s that go multiple lines
- `display: block` 😎
=> Fixing line-height of CardTitle

src/components/user-dropdown-disclosure/index.tsx
Fixes a React key error in `UserDropdownDisclosure`.
=> [UserDropdownDisclosure] Fixing key error

src/components/accordion-disclosure/accordion-disclosure-context.ts, src/components/command-bar/index.tsx, src/components/disclosure/index.tsx, src/components/feedback-form/index.tsx, src/components/tabs/helpers/tab-nesting-context.tsx, src/components/tabs/provider.tsx, src/contexts/current-content-type.tsx, src/contexts/current-product.tsx, src/contexts/device-size.tsx, src/contexts/instruqt-lab/index.tsx, src/contexts/mobile-menu.tsx, src/layouts/sidebar-sidecar/contexts/sidebar-nav-data.tsx, src/views/product-downloads-view/contexts/current-version-context.tsx
Sets the `displayName` property for all of our `Context`s.
It's helpful when debugging with React devtools: https://reactjs.org/docs/context.html#contextdisplayname.
- Note: some `Context`s do not have a display name because they are rendered by third-party code
=> Adding displayName to Contexts for devtools debugging

src/components/breadcrumb-bar/__tests__/breadcrumb-bar.test.tsx, src/components/breadcrumb-bar/index.tsx
This removes items with no URL from our breadcrumbs' structure data, but retains the UI element.
- [Test result](https://search.google.com/test/rich-results/result/r%2Fbreadcrumbs?id=qwE8BAr1FVZJMwQvqwpPhA)
=> fix(breadcrumb-bar): Structured Data

build-libs/__tests__/build-beta-opt-in-redirect.test.ts, config/base.json, config/production.json
This PR removes `"nomad"` from `beta_product_slugs`, as part of launching Nomad into GA. 
[task]: https://app.asana.com/0/0/1203168563666033/f
[preview]: https://dev-portal-git-zsrm-nomad-from-beta-hashicorp.vercel.app
=> feat: rm nomad from beta slugs

src/constants/hostname-map.ts
=> chore: fix nomad domain typo

src/components/_proxied-dot-io/nomad/subnav/index.jsx, src/constants/hostname-map.ts, src/layouts/_proxied-dot-io/nomad/index.tsx
Updates Nomad subnav items that redirect to <https://developer.hashicorp.com>, to use direct URLs rather than URLs that we know will be redirected.
[task]: https://app.asana.com/0/0/1203168563666038/f
[preview]: https://dev-portal-git-zspost-nomad-ga-subnav-links-hashicorp.vercel.app
=> chore: update Nomad subnav links post-dev-dot-GA

package-lock.json, package.json
Bumps `@hashicorp/react-code-block` to pull in a fix for `shell-session` `CodeTabs` from https://github.com/hashicorp/react-components/pull/768.
Fixes a bug where `shell-session` snippets within `CodeTabs` would copy correctly via the `Copy` button, but would still include the `$` character when selected and copied by clicking and dragging.
- The `Copy` button should copy without the leading `$` or leading space that follows it
- Selecting and copying all the text (eg by triple-clicking) should copy without the leading `$`.
- Note the leading space will be copied, this is a difficult thing to optimize, and we haven't yet had the bandwidth to scope out a more holistic and robust approach to authoring and rendering `shell-session` snippets …
=> chore: bump code-block for shell-sesh fix

src/content/packer/install-landing.json
Fixes a broken link to Packer CLI docs.
=> fix: broken Packer CLI link

src/components/_proxied-dot-io/packer/subnav/index.tsx, src/layouts/_proxied-dot-io/packer/index.tsx
Updates Packer subnav items that redirect to <https://developer.hashicorp.com>, to use direct URLs rather than URLs that we know will be redirected.
[task]: https://app.asana.com/0/0/1203184381727446/f
[preview]: https://dev-portal-git-zsupdate-packer-subnav-links-hashicorp.vercel.app
=> chore: update Packer subnav links post-GA

next.config.js
This PR adds a `noindex` header for <https://tip.waypointproject.io>
=> fix: add noindex,nofollow header for tip.waypoint

next-sitemap.config.js
Reverts hashicorp/dev-portal#1286
Reverting since #1286 has a bigger blast radius than expected.
=> Revert "chore: add '/_next' paths to 'disallow' in robots.txt"

next-sitemap.config.js
Adds `/_next/data/*.json` paths to the 'disallow' list in `robots.txt`. This was previously addressed in #1286 but reverted because `/_next/` was added to 'disallow' in there which was too broad. The goal here is to limit crawling and indexing of Nextjs JSON URLs
It seems search engine bots are crawling `/_next/data/*.json` paths when they should not be. Adding those paths to 'disallow' signals to crawlers that they should not be doing so.
Current `robots.txt` at developer.hashicorp.com/robots.txt:
```
User-agent: *
Allow: /
Host: https://developer.hashicorp.com
Sitemap: https://developer.hashicorp.com/sitemap.xml
```
New `robots.txt` via this PR, to be tested at …
=> chore: add Nextjs JSON paths to 'disallow' in robots.txt

next-sitemap.config.js
Reverts hashicorp/dev-portal#1292
Reverting #1292 as it still breaks the site in Google's crawl, just not as bad as #1286
=> Revert "chore: add Nextjs JSON paths to 'disallow' in robots.txt"

src/components/navigation-header/index.tsx
- Renders sign in/up elements in the navigation header by default to reduce flashing for the majority of our users
=> [NavigationHeader] Show sign in/up elements by default

src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/downloads-section/index.tsx
Fixes a visual bug where code blocks are spaced `4px` from their associated code tabs bar on install views.
Removes class that adds spacing.
- Open the "Linux" tab, which has code tabs within it
- There should be no gap between the code tabs bar and the code block
[task]: https://app.asana.com/0/1202097197789424/1203252444555503/f
[preview]: https://dev-portal-git-zsfix-code-space-on-install-view-hashicorp.vercel.app
[/terraform/downloads]: https://dev-portal-git-zsfix-code-space-on-install-view-hashicorp.vercel.app/terraform/downloads
=> fix: gap in install view code tabs

src/content/consul/install-landing.json
- Fixes a link to a renamed tutorial on /consul/downloads
=> Fixing link on /consul/downloads

src/lib/auth/cloud-idp-provider.ts, src/pages/api/auth/[...nextauth].ts, src/types/auth.ts
- Configures a `signOut` function in NextAuth's `events` configuration object
- Persists the `id_token` on `account` in `jwt()` for the new `signOut` event function
- According to https://github.com/nextauthjs/next-auth/discussions/3938, NextAuth does not log out of an auth provider entirely for us. So we need to do an extra step on `signOut` in order to completely log out of Cloud IDP.
- [`NextAuth.options.events.signOut`](https://next-auth.js.org/configuration/options#events)
=> [NextAuth] Adding signOut event to sign out of provider

src/components/_proxied-dot-io/common/docs-page/index.tsx
- [Asana task](https://app.asana.com/0/1202097197789424/1203239476053454/f) 🎟️
- Removes the `optInBanner` slot in `DocsPage` (`src/components/_proxied-dot-io/common/docs-page/index.tsx`) if the current product's slug is `"sentinel"`
- It's not possible to opt in to sentinel docs on developer right now
- Sentinel's docs are served from this repo, so I made the change in the shared `DocsPage` component
=> Removing optInBanner for sentinel

src/components/_proxied-dot-io/packer/remote-plugin-docs/fixup-plugin-urls.test.ts, src/components/_proxied-dot-io/packer/remote-plugin-docs/fixup-plugin-urls.ts, src/components/_proxied-dot-io/packer/remote-plugin-docs/server.ts
Fixes up Packer plugin links.
- "the plugins move" - Packer plugins were moved from `/docs/:type/:slug` to `/plugins/:type/:slug`, before Dev Dot move
- "the Dev Dot move" - Packer plugins and other docs were moved onto Dev Dot, URLs need to be `/packer/docs/...etc` or `/packer/plugins/...etc`
- For "the plugins move", this PR sets up a regex to fix up the old `/docs` URLs to the new `/plugins` URL format
- For "the Dev Dot move", this PR adds in the remark "URL fixer upper" plugin that we use for all other products. This was missed earlier for Packer plugins (separate server-side function strikes again).
- Packer plugin links on the page should be corrected to the `/packer/plugins` format, docs links should be corrected to the …
=> fix: transform URLs for Packer plugins

src/components/_proxied-dot-io/packer/remote-plugin-docs/fixup-redirected-plugin-urls.ts, src/components/_proxied-dot-io/packer/remote-plugin-docs/server.ts
This PR adds a step to the Packer plugins URL corrector that fixes up links that previously would have been redirected.
To ensure links that we render on our site do not 404.
- Links should work, and not 404!
- If there are broken links, it might make sense to add more specific link corrections... or perhaps we may need to ask authors to fix them in source.
[task]: https://app.asana.com/0/1202097197789424/1203260848279095/f
[preview]: https://dev-portal-git-zspatch-packer-plugin-redirected-urls-hashicorp.vercel.app
[/packer/plugins/builders/virtualbox]: https://dev-portal-git-zspatch-packer-plugin-redirected-urls-hashicorp.vercel.app/packer/plugins/builders/virtualbox
=> fix: add Packer plugin redirect fixes

src/views/tutorial-view/utils/serialize-content.ts
- [Asana task](https://app.asana.com/0/1202097197789424/1202941566536490/f) 🎟️
These changes remove `rewriteTutorialLinksPlugin` from `TutorialView`'s `serializeContent` utility.
All links in tutorial content have been updated to be internal dev dot paths, and we also have added a PR check in hashicorp/tutorials that notifies when legacy Learn link formats are found in a PR's diff. So there is no longer a need to rewrite these links in `TutorialView`.
Go to several tutorial pages and make sure that links to other tutorials, collections, and product tutorial landing pages in the content all go to the right places.
`DocsView` still uses `rewriteTutorialLinksPlugin`, but the plan is to remove it after some other content work has been completed.
=> [TutorialView] Removes rewriteTutorialLinksPlugin

src/pages/api/auth/[...nextauth].ts
- Prefixes our custom `RefreshAccessTokenError` message with `"[next-auth]"`
- So an existing log monitor picks these errors up
- To group this error with others in hopes that it makes debugging the actual error easier
Nothing to test ✅
=> Prefixing RefreshAccessTokenError message with "[next-auth]"

src/pages/api/auth/[...nextauth].ts, src/types/auth.ts
Moves the `"[next-auth]"` prefix on `RefreshAccessTokenError` to the definition of the error. The string equality check in `useAuthentication` was broken in #1329.
=> Prefixing actual RefreshAccessTokenError message for string equality checks

src/lib/strip-undefined-props.ts, src/pages/onboarding/[collectionSlug].tsx, src/pages/well-architected-framework/index.tsx, src/views/collection-view/server.ts, src/views/onboarding/tutorial-view/server.ts, src/views/product-tutorials-view/server.ts, src/views/tutorial-library/utils/router-state.ts, src/views/tutorial-view/server.ts, src/views/well-architected-framework/tutorial-view/server.ts
Modifies `stripUndefinedProperties` so that it better retains type information.
To ensure we don't lose valuable type information when using `stripUndefinedProperties`.
Takes the approach mentioned in [the task][task]:
```ts
export function stripUndefinedProperties<T = any>(obj: T): T {
return JSON.parse(JSON.stringify(obj))
}
```
- Adding a bunch of `$TSFixMe` was necessary to prevent type errors. Intent is to handle these, and add more accurate types, in future "someday" work.
- Maybe a co-ordinated effort to root out `$TSFixMe` in the repo could be good, and could tie in with [`no-implicit-any` work](https://app.asana.com/0/1100423001970639/1202025665826439/f) or something
[task]: …
=> chore: typing for strip-undefined-props

package-lock.json, package.json, src/layouts/sidebar-sidecar/components/table-of-contents/types.ts, src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/utils/filter-table-of-contents-headings.ts
This PR is nearly identical to #1344. The difference is that this PR uses a fixed version of `remark-plugins` to handle multi-level `<Tabs />` nesting correctly.
Previously, if multiple subsequent `<Tabs />` JSX were in a single block of JSX, tab depth was not calculated correctly. This has been fixed in https://github.com/hashicorp/remark-plugins/pull/49.
Displaying headings nested within `<Tabs />` can create a table-of-contents that is both overwhelming, due to the sheer number of headings, and duplicative and confusing, as content between tabbed sections often contains parallel headings.
- Pulls in an updated & patched release of `remark-plugins`, where the `anchor-links` plugin now provides `tabbedSectionDepth` property for all …
=> Upgrade remark-plugins for tabbedSectionDepth

src/components/authentication-error-dialog/authentication-error-dialog.module.css, src/components/authentication-error-dialog/helpers/guess-method-of-dismissal.ts, src/components/authentication-error-dialog/helpers/index.ts, src/components/authentication-error-dialog/index.tsx, src/components/dialog/types.ts, src/hooks/use-authentication/index.ts, src/hooks/use-authentication/types.ts, src/layouts/base-new/index.tsx, src/pages/api/auth/[...nextauth].ts
- [Preview link](https://dev-portal-git-ambadd-auth-error-dialog-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203346078532406/f) 🎟️
- Adds new `AuthenticationErrorDialog` component
- Renders `AuthenticationErrorDialog` in `BaseNewLayout`
- Adds `error` and `hasError` properties to `UseAuthenticationResult`
- Removes from `useAuthentication` the effect that auto signed out users on `AuthErrors.RefreshAccessTokenError`
- Updates `DialogProps["onDismiss"]` to reference Reach's `DialogProps["onDismiss"]`
- Adds debug log to `NextAuth.events.signOut` in `src/pages/api/auth/[...nextauth].ts`
The purpose of this dialog is to give a notice to authenticated users that their authentication state has changed. There are multiple analytics events added to the …
=> Add auth error dialog

src/hooks/use-authentication/index.ts
Removes `name` from the recently added (#1353) `analytics.identify` call that sends sign-ins to Marketo. Name is problematic because it's never set as part of the sign-in process, and so Auth0 populates it with the user's email address. This results in name fields in Marketo getting overwritten with email addresses for existing records.
=> remove name from payload per MOPS

package-lock.json, package.json
Pulls in this code block change to address hydration issues: https://github.com/hashicorp/react-components/pull/834
Fixes #1401
=> fix: code block hydration mismatches

src/lib/integrations-api-client/index.ts, src/views/product-integration/components/header/index.tsx, src/views/product-integration/index.tsx
Updates the integrations demo front-end to hide the version selector when the integration in question has `hide_versions` set to `true`.
I imagine there might be more we might want to do in the future.
For example, if we start rendering versioned integration docs with `v0.0.0` or whatnot in the URL, similar to docs (eg <https://developer.hashicorp.com/vault/docs/v1.10.x/secrets/kv>), then there might be some `getStaticProps` logic needed to prevent not-latest-version URLs of `hide_versions` integrations from rendering. Though maybe it's possible we go with the approach we took with downloads pages, where the version selector doesn't change the URL, and so the version selector being hidden is all we need? 🤷 
[task]: https://app.asana.com/0/0/1203401870478721/f
=> chore: hide_versions hides version selector

package-lock.json, package.json, scripts/list-open-prs-with-docs-changes.ts
- Adds new `scripts/list-open-prs-with-docs-changes.ts` that uses the [GitHub REST API JavaScript client](https://github.com/octokit/rest.js/) to list open PRs that affect docs content (MDX and nav data) for a given repo
- Adds the newly used `@octokit/rest` and `yargs` as dev dependencies
- Not all of our content repos use the same labeling to denote a PR as having docs changes. This script provides an automated way to get the list regardless of how PRs are named or labeled for a repo.
- In the short term, this is most useful for the docs content link rewrite project so that it's easier to estimate rollout schedules and runbooks.
=> Adding script for listing open docs PRs

src/components/try-hcp-callout/components/try-hcp-callout/index.tsx
- ~Asana task~ N/A 🎟️
This PR fixes an issue where the `<Description />` part of `TryHcpCallout` was missing. I slipped up and introduced this issue was during a refactor in https://github.com/hashicorp/dev-portal/pull/1373.
Not at the moment.
[preview]: https://dev-portal-git-zsfix-hcp-callout-description-hashicorp.vercel.app/
[/boundary]: https://dev-portal-git-zsfix-hcp-callout-description-hashicorp.vercel.app/boundary
=> fix: add back description to try-hcp-callout

src/components/button-link/button-link.module.css
Removes the default underline style from `ButtonLink`. Maintains the underline when `ButtonLink` is hovered or focused.
To match HDS.
https://user-images.githubusercontent.com/4624598/206786196-158797f0-799b-4e0e-8fa8-d9a9f0e9186c.mp4
https://user-images.githubusercontent.com/4624598/206786216-b7764bc5-8a9d-49a5-b303-41fe14fa94bf.mp4
- By default, `ButtonLink` should not show an underline
- When hovered or focused, `ButtonLink` should show an underline
[task]: https://app.asana.com/0/1202097197789424/1202355923167674/f
[preview]: https://dev-portal-git-zsrm-button-link-underline-hashicorp.vercel.app/
[/terraform/tutorials/aws-get-started]: https://dev-portal-git-zsrm-button-link-underline-hashicorp.vercel.app/terraform/ …
=> chore: rm default underline from button-link

src/components/command-bar/commands/search/components/tutorials-tab-contents/tutorial-hit.tsx, src/components/command-bar/commands/search/components/tutorials-tab-contents/types.ts, src/views/tutorial-library/utils/get-tutorial-card-props-from-hit.ts
- [Preview link](https://dev-portal-git-ksremove-name-tutorial-search-hashicorp.vercel.app/tutorials/library) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1203525052057390) 🎟️
Follow up from #1423 to fully remove the reference to name. After merging this, will merge the [update in mktg-content-workflows](https://github.com/hashicorp/mktg-content-workflows/pull/279) to remove the property from the index.
- Visit the tutorials library page, interact with the search functions, see there are no errors
- Use the global search component, hit the tutorials tab, validate there are no errors.
=> chore: removes reference to `name` in tutorial search object

package-lock.json, package.json, src/middleware.ts, src/pages/_proxied-dot-io/vault/without-cta-links.tsx
When HappyKit returns, it's possible that `cookies` is `null`, in which case we are not handling this and silently erroring when we call `setHappyKitCookie()`. A side-effect seems to be that our experiments are not getting properly served. I've updated the logic to handle this.
We should no longer see treatments incorrectly flashing on our .io sites.
=> fix: ensure we don't error when setting the happykit cookie

package-lock.json, package.json, src/content/README.md, src/content/certifications/README.md, src/content/certifications/exam-faqs/consul-associate-002.mdx, src/content/certifications/exam-faqs/terraform-associate-002.mdx, src/content/certifications/exam-faqs/terraform-associate-003.mdx, src/content/certifications/exam-faqs/vault-associate-002.mdx, src/content/certifications/exam-faqs/vault-operations-professional.mdx, src/content/certifications/programs/infrastructure-automation.json, src/content/certifications/programs/networking-automation.json, src/content/certifications/programs/security-automation.json, src/views/certifications/content/schemas/certification-program.ts, src/views/certifications/content/utils/collect-md-content-by-heading.ts, src/views/certifications/content/utils/get-faqs-from-mdx.ts, src/views/certifications/content/utils/index.ts, src/views/certifications/types.ts, src/views/certifications/views/[slug]/server.ts, src/views/certifications/views/[slug]/types.ts, src/views/certifications/views/[slug]/utils/prepare-page-content.ts
This PR implements content loading for the `exam` items on each individual certification program page.
- Installs some `unified`-related utilities
- Sets up content utilities for working with FAQ content in MDX
- `collect-md-content-by-heading` splits an MDX string into an array of `{ title, content }` items, where `title` is the heading of a section, and `content` is the MDX string for content within that section
- `get-faqs-from-mdx` uses `collect-md-content-by-heading` to split an MDX document on `## Heading Two` headings, and also transforms the `content` string into `mdxSource` using `next-mdx-remote`
- Adds in `exams` to each Certification program's content schema
- `exams` content will drive …
=> feat: add full program and exam content

src/components/sidebar/helpers/generate-product-landing-nav-items.ts, src/lib/enabled-integration-products.ts, src/pages/[productSlug]/integrations/index.tsx, src/views/product-landing/helpers/get-icon-cards.tsx
Appropriately show the Integrations navigation items when enabled.
=> Product Landing Page navigational links

src/content/certifications/README.md, src/content/certifications/landing-faq.mdx, src/content/certifications/landing.json, src/content/certifications/programs/infrastructure-automation.json, src/content/certifications/programs/networking-automation.json, src/content/certifications/programs/security-automation.json, src/views/certifications/content/schemas/certification-program.ts, src/views/certifications/content/schemas/landing-page.ts, src/views/certifications/content/utils/get-certifications.ts, src/views/certifications/types.ts, src/views/certifications/views/landing/index.tsx, src/views/certifications/views/landing/server.ts, src/views/certifications/views/landing/types.ts, src/views/certifications/views/landing/utils/format-program-summaries.ts
This PR implements content loading for the remaining landing page content. Specifically:
- Loads and formats program data into program summaries, for display on the landing page
- Loads and formats FAQ content for the landing page from `src/content/certifications/landing-faq.mdx`
- Adds docs to the `content/certifications/README.md`
- Adds stubbed content to `content/certifications/landing-faq.mdx`
- Adds `programSummarySlugs` to the landing page content schema (and add that content)
- Adds `summary` to the individual program page content schemas (and add that content)
- Process FAQ content in the landing page `getStaticProps`, and pass `faqItems` to the view
- Process programs into summary data with …
=> feat: add remaining landing content

src/components/dev-dot-content/mdx-components/mdx-p/index.tsx, src/content/certifications/README.md, src/content/certifications/landing.json, src/views/certifications/components/accordion-with-mdx-content/accordion-with-mdx-content.module.css, src/views/certifications/components/accordion-with-mdx-content/index.tsx, src/views/certifications/components/accordion-with-mdx-content/types.ts, src/views/certifications/components/index.tsx, src/views/certifications/content/schemas/landing-page.ts, src/views/certifications/views/landing/index.tsx, src/views/certifications/views/landing/landing.module.css
This PR implements the FAQ section on the [/certifications][/certifications] landing page.
- Adds a new `accordion-with-mdx-content` component
- This uses existing `dev-dot-content` MDX components to render accordion content
- This component will be re-used on individual program pages
- Adds `faqHeading` to the landing schema
- Adds the FAQ section, and associated spacing styles, to the home page
- I've adjusted some styles related to overlapping sections to try to make things more clear & maintainable. Open to alternate suggestions 🙇
- Updates content `README` with short note on `faqHeading` for the landing page
🎨 [Figma mockups](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=1659 …
=> feat: add landing faq section

src/components/dev-dot-content/mdx-components/mdx-p/index.tsx, src/views/certifications/components/accordion-with-mdx-content/accordion-with-mdx-content.module.css, src/views/certifications/components/accordion-with-mdx-content/index.tsx
This PR reverts a change to the text color of `MdxP` within accordion content.
The original commit that introduced this change was [e6a8304](https://github.com/hashicorp/dev-portal/pull/1463/commits/e6a8304f756cc4e85f39de09632aee347643687d).
This change was made due to some uncertainty about the implications of Figma designs (see [this PR comment](https://github.com/hashicorp/dev-portal/pull/1463#discussion_r1049079449)). I've since clarified & confirmed the desired output via Slack DMs.
| Page | Before | After |
| - | - | - |
| Landing | <img width="1256" alt="landing-before" src="https://user-images.githubusercontent.com/4624598/208172613-a5bf5636-4de8-4b96-b9d1-844f1680d462.png"> | <img …
=> fix: revert text color change in MDX FAQs

src/content/certifications/programs/infrastructure-automation.json, src/content/certifications/programs/networking-automation.json, src/content/certifications/programs/security-automation.json, src/views/certifications/content/schemas/certification-program.ts, src/views/certifications/views/[slug]/index.tsx, src/views/certifications/views/landing/components/certification-program-summary-card/index.tsx, src/views/certifications/views/landing/types.ts, src/views/certifications/views/landing/utils/format-program-summaries.ts
This PR fixes an issue where brackets were not used in exam title display in the expected way.
The ask from the Certifications stakeholder side is to display exam codes in brackets where the full title is shown, but display exam codes not in brackets where the short title is shown. For example, for the Terraform Associate 002 exam:
- Full title: `HashiCorp Certified: Terraform Associate (002)`
- Short title: `Terraform Associate 002`
This PR updates the `CertificationExamSchema` to contain separate fields for `title` and `examCode`. Note that not all exams have an `examCode`.
This PR also updates content to match the new schema. Examples:
- For the Terraform Associate 002 exam, `title` is `Terraform …
=> feat: separate exam code in titles

src/content/certifications/programs/infrastructure-automation.json, src/views/certifications/views/[slug]/components/exam-details-card/index.tsx, src/views/certifications/views/landing/components/certification-program-summary-card/index.tsx, src/views/certifications/views/landing/components/exam-card/exam-card.module.css, src/views/certifications/views/landing/components/exam-card/index.tsx, src/views/certifications/views/landing/components/exam-card/types.ts, src/views/certifications/views/landing/types.ts, src/views/certifications/views/landing/utils/format-program-summaries.ts
This PR adds a "prepare" URL for the `Terraform Associate 003` exam. It also updates the exam overview card on the [/certifications][/certifications] landing page to ensure that exams that have a "prepare" URL but no "register" URL show _both_ a `Coming Soon` badge and a `Prepare for the exam` linked card.
- Adds "prepare" URL for `terraform-associate-003` exam in `content/certifications/infrastructure-automation.json`
- Adds optional `showComingSoon` prop to the `ExamCard` component, and display the badge when `true`
- If the "prepare" URL is defined, we'll use the linked `ExamCard` component
- When using `ExamCard`, if the "register" URL is not defined, we'll set `showComingSoon` to `true`
- Adjusts …
=> feat: show coming soon badge if no register URL

src/views/certifications/views/landing/components/certification-program-summary-card/certification-program-summary-card.module.css
This PR tweaks the vertical alignment of `heading` and `description` in the landing page program overview card.
- Each overview card should appear to have their `heading` and `description` top-aligned 
[/certifications]: https://dev-portal-git-zscert-exam-card-align-hashicorp.vercel.app/certifications
=> fix: tweak alignment in landing card

src/components/footer/index.tsx
This PR adds a link to `/certifications` to the Dev Dot footer.
- [/certifications][/certifications]
- [/certifications/infrastructure-automation][/certifications/infrastructure-automation]
- [/certifications/networking-automation][/certifications/networking-automation]
- [/certifications/security-automation][/certifications/security-automation]
- There should be a `Certifications` link in the footer, which links to [/certifications][/certifications]
[preview]: https://dev-portal-git-zscert-footer-link-hashicorp.vercel.app/
[/certifications]: https://dev-portal-git-zscert-footer-link-hashicorp.vercel.app/certifications
[/certifications/infrastructure-automation]: …
=> feat: add footer link to /certifications

src/content/home-page.json
This PR updates the home page "Certifications" section URL to link to  `/certifications`.
https://user-images.githubusercontent.com/4624598/208542104-b1183965-d996-49c4-92fc-9e23dc2bb211.mp4
https://user-images.githubusercontent.com/4624598/208542130-74b84897-ef46-49a4-84ff-dd0c73dcc7b3.mp4
- The link the the `Certifications` slot should link to [/certifications][/certifications]
Note that we have a home page section update to make, which will update the visual style and content of the section shown in screen grabs above. This update will be made in a subsequent PR.
<details>
<summary>Preview of home page section update</summary> 
</details>
[preview]: …
=> chore: update home page link

src/components/sidebar/helpers/generate-resources-nav-items.ts, src/views/certifications/content/schemas/certification-program.ts, src/views/certifications/content/utils/program-slug-map.ts
Adds certification links to product page sidebars where applicable. This new link is located under the `Resources` section of the sidebar.
- Modifies program schema types to make them easier to use as variables, not just as types
- Adds a map utility to get a certification program slug from a valid product slug
- Uses the above utilities to add certifications links in `get-resources-nav-items`
- Minor updates (remove unused import, fix a typo'd comment)
| - | - |
| ![before](https://user-images.githubusercontent.com/4624598/208785752-d91b2161-89b1-44eb-b087-967ccc04955a.png) | ![after](https://user-images.githubusercontent.com/4624598/208785754-502381f9-c7c9-4d25-931f-64c88343e2da.png) |
- [/consul][/consul], …
=> feat: add certifications to resources links

Dockerfile
Add chown to node_modules copy
See linked ticket for more information; npm packages appear to have all sorts of weird user/group combinations, which will occasionally break containers. Given that we're executing as a single user, and given that we used to provision these with root/root, it should be safe to chown all of these files on copy.
This should fix issues pulling the container with Podman 3.4.4 on Ubuntu 22.04.
Resolves: #1491
Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>
=> Add chown to node_modules copy

src/views/product-integrations-landing/components/tag-list/index.tsx
---
- https://app.asana.com/0/0/1203548351779955
=> Adds support for enterprise icon for enterprise tags

src/views/product-integrations-landing/components/integrations-list/index.tsx, src/views/product-integrations-landing/components/integrations-list/style.module.css, src/views/product-integrations-landing/components/tag-list/index.tsx
Improves the mobile layout for integration cards, specifically when there's a good amount of content in these cards.
Might be best to just open the [🔍 Preview](https://dev-portal-git-brmobile-breakpoints-hashicorp.vercel.app/vault/integrations) to see if it feels right.  Search `KMIP` for a good one with a good amount of Flags.
=> Mobile optimizations for Integration Card

scripts/docs-content-link-rewrites/helpers/get-mdx-and-nav-data-directories-for-repo.ts
- Fixes the `navDataPrefix` set for `cloud.hashicorp.com` in `getMdxAndNavDataDirectoriesForRepo`, which is used when loading data for the link rewrites e2e workflow.
=> [e2e] Fixing navDataPrefix for cloud.hashicorp.com

.github/workflows/docs-content-link-rewrites-e2e.yml
- Explicitly sets the `GITHUB_TOKEN` under `env` for the `docs-content-link-rewrites-e2e` job, using `github.token` (which is automatically passed by the calling workflow)
- This workflow was failing in `cloud.hashicorp.com` ([see example run](https://github.com/hashicorp/cloud.hashicorp.com/actions/runs/3840700738/jobs/6543024622#step:6:16)) because it's an internal repo and it requires a token to get the contents of files.
Nothing to manually test here, other than confirming that the test workflow call in `cloud.hashicorp.com` was successful in the "Load data for e2e tests" step here: https://github.com/hashicorp/cloud.hashicorp.com/actions/runs/3842269576/jobs/6543412397#step:6:1
=> Setting GITHUB_TOKEN explicitly for use in docs-content-link-rewrites-e2e workflow

src/__tests__/e2e/docs-content-link-rewrites.spec.ts
Updates the strings that the `docs-content-link-rewrites` e2e tests compare to be formatted JSON so the output of failed tests is easier to read.
=> Making docs-content-link-rewrites assertions more readable

scripts/docs-content-link-rewrites/rewrite-links.ts
- Removes error that was happening in the link rewrites script due to copy-pasting the functionality from another block of code. We don't actually want the workflow that runs this to error if unrewriteable links are found. This block is for debugging purposes when running the script locally.
=> Removing error on unrewriteable links

scripts/docs-content-link-rewrites/generate-page-paths-for-repo-and-base-path.ts
- Uses a `Set` when building up a list of paths to test for the link rewrites e2e tests
Duplicate test names were found when trying to test Vagrant link rewrites ([link to failed workflow](https://github.com/hashicorp/vagrant/actions/runs/3851148750/jobs/6562039649#step:7:20)):
```
========================================
duplicate test titles are not allowed.
- title: docs-content-link-rewrites › Main assertions › docs › vagrant/docs/
- docs-content-link-rewrites.spec.ts:82
- docs-content-link-rewrites.spec.ts:82
- title: docs-content-link-rewrites › Main assertions › intro › vagrant/intro/
- docs-content-link-rewrites.spec.ts:82
- docs-content-link-rewrites.spec.ts:82
========================================
```
=> Fix duplicate link rewrites e2e test names

src/components/sidebar/helpers/generate-product-landing-nav-items.ts, src/contexts/__tests__/current-product.test.tsx, src/data/boundary.json, src/data/consul.json, src/data/hcp.json, src/data/nomad.json, src/data/packer.json, src/data/sentinel.json, src/data/terraform.json, src/data/vagrant.json, src/data/vault.json, src/data/waypoint.json, src/lib/enabled-integration-products.ts, src/pages/[productSlug]/integrations/[integrationSlug]/[integrationVersion]/components/[componentSlug]/index.tsx, src/pages/[productSlug]/integrations/[integrationSlug]/[integrationVersion]/index.tsx, src/pages/[productSlug]/integrations/[integrationSlug]/index.tsx, src/pages/[productSlug]/integrations/index.tsx, src/types/products.ts, src/views/product-landing/helpers/get-icon-cards.tsx, src/views/product-landing/index.tsx
Moves the `enabled` flag over to the actual config file rather than a JS util function.
Also adds support for specifying custom links that you can add to the sidebar on the integration landing page.
=> Adds Integration Config settings

src/components/callout-card/callout-card.module.css, src/components/card/components/card-description/card-description.module.css, src/components/card/components/card-description/index.tsx
Bumps the text size for card descriptions from `body-100` to `body-200`.
- In `CalloutCard`, bumps body `<p />` from `body-100` to `body-200`. Affects these components:
- `VagrantDownloadsPage`, in the merchandising slot
- `ProductLanding`, for the authored `get_started` block on all product pages, and for more freeform authored `callout` blocks
- `ProductRootDocsPathLandingMarketingContent`, for the authored `getting-started-card` blocks
- In `CardDescription`, bumps font from `body-100` to `body-200`. Affects these components:
- `CollectionCard`
- `TutorialCard`
- `LinkedCard` - author-facing component on `/<product>` landing pages, as a block with type `linked_cards`. Often used for docs page linked cards.
- `CardGrid` - author-facing …
=> feat: typography update for cards

.github/workflows/redeploy-content-repos.yml
- Adds a new workflow that triggers redeploys various content repos' `main` branches.
- This will speed up some of the process for the docs content link rewrites project. In order for the E2E tests to be accurate in each main migration PR, the `main` branch PR's URL for a repo needs to be built from the latest of `dev-portal/main`. With bug fixes happening every few days that fix issues identified in failing E2E tests, it takes a lot of time and context switching to make sure the `main` branch preview URLs get updated.
- A side benefit of this is that content repos's `main` branch preview URLs will always have the latest `dev-portal/main` features & fixes without having to update their `main` branches or perform manual deploys in the Vercel UI.
For each content repo:
- Created a [Deploy …
=> Adding "Redeploy Content Repo Previews" workflow

src/components/try-hcp-callout/components/index.tsx, src/components/try-hcp-callout/components/try-hcp-callout-sidecar-placement/index.tsx, src/layouts/product-integration-layout/index.tsx, src/pages/[productSlug]/integrations/index.tsx, src/views/product-integrations-landing/index.tsx
For products with an HCP offering, adds a `Try HCP` callout to the sidecar of integration pages.
- Implements a new `TryHcpCalloutSidecarPlacement` component
- This component accepts a `productSlug`, and handles the logic of whether to render the HCP callout, and what content to show
- Adds `TryHcpCalloutSidecarPlacement` to integrations views
- Adds to `ProductIntegrationLayout`, which covers the majority of integration pages
- ~Adds to~ Does not add to `ProductIntegrationsLanding`, as this is not in designs
| View | Before | After |
| - | - | - | 
| [ReadmeView][/waypoint/integrations/aws-ami] | ![readme-before](https://user-images.githubusercontent.com/4624598/212408370-42c7cd1a-3c8f-48a2-814b-fc5afeeef2a3.png) | …
=> feat: add HCP callout to sidecar

src/lib/remark-plugins/remark-plugin-adjust-link-urls/__tests__/remark-plugin-adjust-link-urls.test.ts, src/lib/remark-plugins/remark-plugin-adjust-link-urls/helpers.ts
- Fixes how dot-slash links (start with `./`) are adjusted by `remarkPluginAdjustLinkUrls`
- We ignored folder-relative URLs until https://github.com/hashicorp/dev-portal/pull/1518, where this bug was introduced because of some incorrect test cases
- compare to [staging](https://dev-portal-git-staging-hashicorp.vercel.app/waypoint/plugins/aws-ecs#builders)
- compare to [staging](https://dev-portal-git-staging-hashicorp.vercel.app/waypoint/plugins/aws-ecs#builders)
- compare to [staging](https://dev-portal-git-staging-hashicorp.vercel.app/terraform/plugin/sdkv2/logging#log-http-transactions)
=> [preAdjustUrl] Fix how dot-slash URLs in content are adjusted

src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
Updates the `PaginatedIntegrationsList` to scroll to the top of the page when pages are changed.
- Adds a `useEffect` hook that calls `window.scrollTo(0, 0)` when `currentPage` changes after the initial render
- On initial render, scroll position should not change. For example, if you scroll partway down the page, and then reload the page, the browser behaviour of remembering your scroll position should still work.
- When interacting with the pagination bar, if the current page is changed, the window should scroll back up to the top
This PR implements scrolling to the very top of the page. If we'd prefer to scroll to a different position, such as the top of the paginated results, we could add a `ref` that we tack onto a target element, …
=> fix: scroll to page top on pagination change

playwright.config.ts, src/__tests__/e2e/docs-content-link-rewrites.spec.ts
- Updates the `gatherHrefsFromLocator` to filter out `href` properties that are empty, to prevent errors with `new URL(href)`
- Adds a `retries` configuration to the `docs-content-link-rewrites` playwright project, to save time in workflow runs
```
REPO=consul npm run test:e2e:linkRewrites:loadData
```
```
MAIN_BRANCH_PREVIEW_URL=https://consul-git-main-hashicorp.vercel.app/ PR_BRANCH_PREVIEW_URL=https://consul-git-docs-ambmigrate-link-formats-hashicorp.vercel.app/ npm run test:e2e:linkRewrites
```
=> [docs-content-link-rewrites] Filter out empty hrefs, set retries to 0

src/views/certifications/views/[slug]/components/heading-permalink/heading-permalink.module.css, src/views/certifications/views/[slug]/components/heading-permalink/index.tsx, src/views/certifications/views/[slug]/components/index.tsx, src/views/certifications/views/[slug]/index.tsx, src/views/certifications/views/[slug]/program-view.module.css
- [Preview link](https://dev-portal-git-ksadd-anchors-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
- [Asana task](https://app.asana.com/0/1202801212949828/1203714554456192) 🎟️
Adds anchor links to the accordion headings so the education team can directly link to a specific program details. 
- Visit a [certifications program page](https://dev-portal-git-ksadd-anchors-hashicorp.vercel.app/certifications/infrastructure-automation)
- Click on an accordion heading, validate that an anchor link renders in your browser tab
- Visit the [anchor link directly](https://dev-portal-git-ksadd-anchors-hashicorp.vercel.app/certifications/infrastructure-automation#terraform-associate-(003)-details) to make sure it works. 
We should decide whether we want to render the link icon, …
=> chore: adds heading anchors to certifications accordions

src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-external-docs-link.test.ts, src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-tutorial-links.test.ts, src/lib/remark-plugins/rewrite-tutorial-links/utils/rewrite-external-docs-link.ts, src/views/docs-view/__tests__/multiple-remark-plugins.test.ts, src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts, src/views/docs-view/utils/product-url-adjusters.ts
- [Asana task](https://app.asana.com/0/1202114367927919/1203750517664204/f) 🎟️
- Adds test cases for both `rewriteTutorialLinksPlugin`- and `remarkPluginAdjustLinkUrls`- related logic to:
- not rewrite .io home page links
- also not rewrite `/` links (which were previously rewritten to .io home page links by `rewriteDocsUrl`)
- Updates the logic to no longer rewrite .io home page links to developer product landing pages
To retain the marketing abilities that come with linking to .io home pages
=> [link rewrite plugins] Update to no longer rewrite .io home page links in content

package-lock.json, package.json, src/components/pagination/index.tsx, src/components/pagination/pagination.test.tsx, src/pages/_app.tsx, src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx, src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx, src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css, src/views/product-integrations-landing/contexts/integrations-search-context.tsx
This updates `/[productSlug]/integrations` to sync its filtering state with url query params
- https://dev-portal-git-kw-integrations-url-state-hashicorp.vercel.app/vault/integrations
- https://dev-portal-git-kw-integrations-url-state-hashicorp.vercel.app/waypoint/integrations?size=4&page=6&tiers=official&components=builder%2Cconfig-sourcer%2Cplatform%2Ctask&flags=builtin
This also updates the reset-filters button to `tertiary` button
- https://app.asana.com/0/1202626741675858/1203768518799617/f
---
- https://app.asana.com/0/0/1203716187854657
=> feat: integrations via URL state - update Reset filters to match Tutorials

.github/workflows/docs-content-check-legacy-links-format.yml, src/lib/remark-plugins/rewrite-tutorial-links/utils/get-tutorial-map.ts
- Adds `"Get target_url hostname"` step to pull `hostname` from `github.event.deployment_status.target_url`
- Updates `.github/workflows/docs-content-check-legacy-links-format.yml` workflow to set `VERCEL_URL` inline when it runs `npm run rewrite-docs-content-links`
Since refactoring the link rewrite script in https://github.com/hashicorp/dev-portal/pull/1525, the script calls `getTutorialMap` which relies on a VERCEL_URL, or defaults the baseUrl for the api endpoint to `http://localhost:3000`. The latest runs for this workflow aren't setting VERCEL_URL, so the default is being used. Since no local server is running, an error happens when trying to fetch the tutorial map.
- It's OK if the workflow fails because old link formats were detected
Once this PR is merged, I will update the …
=> [link format checker] Adding check for VERCEL_URL

.github/workflows/docs-content-check-legacy-links-format.yml, .github/workflows/docs-content-link-rewrites-e2e.yml
- Replaces the `get-target-url-hostname` step with a hardcoded value for `VERCEL_URL` in the `run-rewrite-docs-content-links-script` step
- Changes the return value of `get-pr-number` when no PR is found to `false`
- Updates all subsequent steps to `get-pr-number` to only run if the return value was not false, so the workflow doesn't fail if a commit has been pushed up but does not have an associated PR yet
Testing with [hashicorp/cloud.hashicorp.com#593](https://github.com/hashicorp/cloud.hashicorp.com/pull/593):
=> [docs-content-check-legacy-links-format] Skip steps if no PR number found; set VERCEL_URL to prod

src/views/product-integrations-landing/contexts/integrations-search-context.tsx
Tiers were being sorted arbitrarily depending on what the state of the data was.  Sort this deterministically; Official > Partner > Community.
[🎟️ Asana Ticket](https://app.asana.com/0/1203792610600085/1203793680296866)
[🔍 Preview](https://dev-portal-git-brtier-ordering-hashicorp.vercel.app/vault/integrations)
=> Deterministically sort the Tier filters

src/pages/[productSlug]/integrations/index.tsx
- 🎟️ [Duplicated "Vault" in page Title](https://app.asana.com/0/1203792610600085/1203812301614400)
=> Fix duplicate product name in title

src/components/callout-card/index.tsx, src/components/card/components/index.ts, src/components/icon-card-link-grid-list/index.tsx, src/components/icon-card-link-grid-list/types.ts, src/components/landing-page-blocks/components/autosized-heading-block/autosized-heading-block.module.css, src/components/landing-page-blocks/components/autosized-heading-block/index.tsx, src/components/landing-page-blocks/components/autosized-heading-block/types.ts, src/components/landing-page-blocks/components/callout-card-block/index.tsx, src/components/landing-page-blocks/components/callout-card-block/types.ts, src/components/landing-page-blocks/components/card-grid-block/card-grid-block.module.css, src/components/landing-page-blocks/components/card-grid-block/index.tsx, src/components/landing-page-blocks/components/card-grid-block/types.ts, src/components/landing-page-blocks/components/icon-card-grid-block/index.tsx, src/components/landing-page-blocks/components/icon-card-grid-block/types.ts, src/components/landing-page-blocks/components/index.ts, src/components/landing-page-blocks/components/paragraph-block/index.tsx, src/components/landing-page-blocks/components/paragraph-block/types.ts, src/components/landing-page-blocks/components/section-heading-block/index.tsx, src/components/landing-page-blocks/components/section-heading-block/section-heading-block.module.css, src/components/landing-page-blocks/components/section-heading-block/types.ts, src/components/landing-page-blocks/index.tsx, src/views/product-root-docs-path-landing/components/marketing-content/index.tsx, src/views/product-root-docs-path-landing/components/marketing-content/marketing-content.module.css
- [Preview link](https://dev-portal-git-ambadd-lpb-component-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203820004767055/f) 🎟️ 
- Abstracts the marketing content block components used in `src/views/product-root-docs-path-landing/components/marketing-content/index.tsx` into a new, reusable `LandingPageBlocks` module/component that lives in `src/components`:
- `AutosizedHeadingBlock`
- `CalloutCardBlock`
- `CardGridBlock`
- `IconCardGridBlock`
- `ParagraphBlock`
- `SectionHeadingBlock`
- This is the first step in consolidating the authoring interfaces (JSON files in `src/content`) & components used on our three main landing pages for consistency and lower engineering maintenance
The following pages should be unchanged compared to prod:
| Page slug | …
=> Adding LandingPageBlocks component, abstracting components from /${productSlug}/docs views

src/components/pagination/pagination.module.css
- [Asana task](https://app.asana.com/0/1203792701577283/1203752857375375/f) 🎟️
- Fixes the differing font sizes cross browser with `appearance: none` and an explicit font size setting
=> [Pagination] Fix cross-browser font sizing

.vscode/extensions.json, .vscode/settings.json
This adds local `.vscode` config for the `vunguyentuan.vscode-css-variables` extension
- https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables
This enables intellisense/cmd-click'ing to see definitions of variables definite in various `@hashicorp` node_modules
https://user-images.githubusercontent.com/26389321/214897986-7145a391-ae87-4e74-b754-72b10a83bf3e.mp4
Improved DX for anyone using the `vunguyentuan.vscode-css-variables` extension!
=> feat: add vscode config for cssVariables extension

src/views/product-landing/helpers/get-icon-cards.tsx
This PR updates the Integration icon. Previously we used the `api` icon, this PR updates to use the `pipeline` icon.
---
- https://app.asana.com/0/0/1203838760523779
=> chore: update Integrations icon to Pipeline

src/views/product-integration/component-view/components/searchable-variable-group-list/index.tsx, src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
- [Preview link](https://dev-portal-git-ambresults-aria-live-hashicorp.vercel.app/vault/integrations) 🔎
- [Asana task](https://app.asana.com/0/1203792610600085/1203776130786803/f) 🎟️
- Adds `role="status"` to:
- the `<span>` that contains the "XX results found" text on `/${productSlug}/integrations`
- the `<p>` that contains the "XX Results" text in `SearchableVariableGroupList`
- This satisfies [SC 4.1.3: Status Messages (Level AA)](https://www.w3.org/WAI/WCAG22/Understanding/status-messages), to provide an update to AT users when the page state changes without moving browser focus from where it currently sits 
- [Technique ARIA22: Using role=status to present status messages](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA22)
=> Adding role=status on results count text

scripts/docs-content-link-rewrites/helpers/get-mdx-links-to-rewrite.ts
- Replaces 2 `return`s in a `for` loop with `continue`s
- I've written so many loops like this with `.forEach` that I forgot `continue` is what you want when trying to skip an iteration 😅 🤣
=> [rewrite-links] Replace accidental returns with continues

.github/workflows/docs-content-check-legacy-links-format.yml, scripts/docs-content-link-rewrites/helpers/get-rewrite-links-script-arguments.ts
- Fixes the `mdxFilesPrefix` and `navDataFilesPrefix` values returned by `getScriptArgumentsForCi`
- The script expects `mdxFilesPrefix` and `navDataFilesPrefix` to be full paths from the root of the machine that's running the script, and the values included periods in them to denote relative paths.
- I ran the following locally (the `` and `` values are where the content lives local to my copy of `dev-portal`)
```
CI=1 REPO="packer" MDX_FILE_PATH_PREFIX="../content-repos/packer/website/content" NAV_DATA_FILE_PATH_PREFIX="../content-repos/packer/website/data" RELEVANT_CHANGED_FILES='{"changedMdxFiles":["/community-tools.mdx"],"changedNavDataJsonFiles":[]}' npx hc-tools ./scripts/docs-content-link-rewrites/rewrite-links.ts
```
I tested this locally, and "live" by:
- Temporarily passing a …
=> [rewrite-links] Fix script argument parsing for CI

src/views/well-architected-framework/tutorial-view/index.tsx
Fixes an issue where the revised grid layout from #1412 was not applied to tutorial pages with [/well-architected-framework][/well-architected-framework] (WAF).
- The main area content width should be slightly narrower, matching other tutorials pages, such as [/waypoint/tutorials/get-started-docker/get-started-intro][/waypoint/tutorials/get-started-docker/get-started-intro]
[task]: https://app.asana.com/0/1202801212949828/1203848628599302/f
[preview]: https://dev-portal-git-zswaf-layout-tweak-hashicorp.vercel.app/
[/well-architected-framework]: https://dev-portal-git-zswaf-layout-tweak-hashicorp.vercel.app/well-architected-framework
[/well-architected-framework/com/cloud-operating-model]: …
=> fix: use narrow width for WAF

src/components/filter-input/filter-input.module.css, src/layouts/product-integration-layout/index.tsx, src/views/product-integration/component-view/components/mdx-heading-outside-mdx/index.tsx, src/views/product-integration/component-view/components/searchable-variable-group-list/index.tsx, src/views/product-integration/component-view/components/searchable-variable-group-list/style.module.css, src/views/product-integration/component-view/index.tsx, src/views/product-integration/readme-view/index.tsx, src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx, src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css, src/views/tutorial-library/tutorial-library.module.css
- [Asana][task-destructure] 🎟️
> **Note**: "variable groups" generally refers to Parameters and Outputs
On integration component views:
- Moves "variable groups" out of `Tabs` and into dedicated sections
- Updates the sidecar to show a table of contents linking to "variable groups"
- Render "variable groups" as sections rather than `Tabs`
- Tangent fix: Update variables groups to use `FilterInput` for consistency
- Tangent chore: clean up some unused styles
- Tangent chore: remove margin from shared FilterInput component
- Refactor: slight refactor so `ProductIntegrationsLayout` can render more varied sidecar content, instead of always rendering a `TryHCPCallout` and nothing else
- Implement a table of contents for "variable groups" on component views
🎨 [Figma …
=> feat: revise param and outputs to sections

src/components/dev-dot-content/mdx-components/mdx-heading-permalink/mdx-heading-permalink.module.css, src/views/product-integration/component-view/components/searchable-variable-group-list/index.tsx, src/views/product-integration/component-view/components/variable-group-list/index.tsx, src/views/product-integration/component-view/components/variable-group-list/style.module.css, src/views/product-integration/component-view/helpers/index.ts, src/views/product-integration/component-view/helpers/variable-group-slug-from-name.ts, src/views/product-integration/component-view/index.tsx
This PR implements permalinks for individual variables within variable groups. These variable groups appear on integrations component pages.
- Generates an ID for each variable with the format `<groupSlug>.<variable.key>`
- Uses the shared `MdxHeadingPermalink` component to implement the link
- Tangent fix: uses focus-visible for mdx-heading-permalink, to prevent focus styles lingering after click
🎨 [Figma][figma]
- By default, everything should look as it did before
- When hovering the name of any variable, or nested property, a "permalink" icon should appear directly after the variable key
- When clicking the "permalink" icon, the page URL should change to include the permalink. As well, the page should jump to the correct anchor link …
=> feat: anchor links for variables

scripts/docs-content-link-rewrites/rewrite-links.ts
- Removes a `.slice` that was used to reduce the output of the `rewrite-links` script, for testing purposes while working on #1579
=> [rewrite-links.ts] Remove .slice that was used for testing

src/components/command-bar/commands/search/components/tutorials-tab-contents/tutorial-hit.tsx
- [Preview link](https://dev-portal-git-ksfix-waf-search-link-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203869159927664) 🎟️
Fixes an issue where waf search hits had '/tutorials' in the path. I refactored to use the `getTutorialSlug` function that should handle all edge case logic with waf. 
- [Visit the preview](https://dev-portal-git-ksfix-waf-search-link-hashicorp.vercel.app), search for a waf tutorial, make sure the path resolves
- Test for other tutorial paths, make sure they resolve properly as well
=> patch: fix waf search links

src/layouts/product-integration-layout/components/header/index.tsx, src/layouts/product-integration-layout/components/header/style.module.css, src/views/product-integrations-landing/components/integrations-list/index.tsx, src/views/product-integrations-landing/components/tag-list/index.tsx, src/views/product-integrations-landing/components/tag-list/style.module.css
- [Preview link](https://dev-portal-git-ksrefactor-tag-list-hashicorp.vercel.app/waypoint/integrations) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1203841143367699) 🎟️
This PR refactors the `TagList` component used in integrations landing pages to use the [`Badge` component](https://developer.hashicorp.com/swingset/components/badge) and updates the integration header to use the same component ([follow-up](https://github.com/hashicorp/dev-portal/pull/1574/files#diff-fd02c7c956695e4750e0e5fe224383932153a78535df653f9a947e09d8cd0b57R31)). 
- [Visit this page](https://dev-portal-git-ksrefactor-tag-list-hashicorp.vercel.app/waypoint/integrations), ensure the tag list renders as expected
- [Visit this page](https://dev-portal-git-ksrefactor-tag-list-hashicorp.vercel.app/waypoint/in …
=> refactor: use badges in tag list

src/components/tutorial-card/helpers/with-auth-elements.tsx, src/components/tutorial-card/index.test.tsx, src/flags/config.ts, src/views/product-landing/helpers/__tests__/make-heading-slug-scope.test.ts
- [Preview link](https://dev-portal-git-ksremove-enable-auth-flag-hashicorp.vercel.app/consul/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203869159979404) 🎟️
Cleanup an old flag! 
Visit a page with[ tutorial cards,](https://dev-portal-git-ksremove-enable-auth-flag-hashicorp.vercel.app/consul/tutorials) there should be no changes, the bookmark icon should always render.
---
- https://app.asana.com/0/0/1203869159979404
=> chore: removes enableAuth flag

src/components/navigation-header/components/product-page-content/utils/__tests__/get-nav-items.test.ts, src/components/navigation-header/components/product-page-content/utils/get-nav-items.ts
🎟️ [Add 'Integrations' to top level product nav](https://app.asana.com/0/1203792701577283/1203869159927655)
https://dev-portal-git-brintegrations-in-nav-hashicorp.vercel.app/vault
https://dev-portal-git-brintegrations-in-nav-hashicorp.vercel.app/waypoint (here on Preview)
https://dev-portal-git-brintegrations-in-nav-hashicorp.vercel.app/nomad (and all other products)
=> Enable integrations in top nav if page active

src/views/product-integration/component-view/server.ts, src/views/product-integration/readme-view/server.ts, src/views/product-integrations-landing/server.ts
This PR updates `getStaticProps` & `getStaticPaths` settings to allow [incremental static regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) of integrations-related pages.
For all of the below changes, we've used our config value `__config.dev_dot.revalidate` for regeneration timing. This setting is in seconds, and is currently set to `360`, so pages will be regenerated at most every 6 minutes.
- For `/<product>/integrations` landing views, we add `revalidate: __config.dev_dot.revalidate` return value to `getStaticProps`.
- This means new integrations can be added between deploys, and will show up in search results on the product integrations landing pages.
- Note: we leave `fallback: …
=> fix: ISR settings for integrations

src/views/product-integration/component-view/components/variable-group-list/index.tsx, src/views/product-integration/component-view/helpers/get-processed-variables-markdown.ts
- [Preview link](https://dev-portal-git-zsvar-description-link-size-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1203792701577283/1203894339506160/f) 🎟️
Fixes an issue where inline links were not sized correctly in integrations variable descriptions.
---
- https://app.asana.com/0/0/1203894339506160
=> fix: inline link size in var descrips

src/views/product-integrations-landing/components/tag-list/index.tsx
- [Asana task](https://app.asana.com/0/1203792616809419/1203879534908332/f) 🎟️
- Adds the `icon` property for the Community `Badge`s that show on integrations `CardLink`s
=> [integrations] Adding users-16 icon for Community tier

src/pages/nomad/downloads/index.tsx, src/pages/nomad/downloads/style.module.css
- Passes an `InlineAlert`-type of element into the `merchandisingSlot` of Nomad's downloads page
- This is an extension of #1628
- I've created a ticket for considering a new feature on downloads views: [[ProductDownloadsView] Add support for custom PageAlerts](https://app.asana.com/0/1202801212949828/1203933033786126/f)
=> Adding merchandisingSlot on /nomad/downloads

src/content/vault/product-landing.json
- Fixes a duplicate link on a docs card on /vault
=> Fixing duplicate docs link on /vault

src/components/_proxied-dot-io/waypoint/homepage/hero/style.module.css
- [Asana task](https://app.asana.com/0/1202791227659279/1203962669700281/f) 🎟️
Fixes a background pixel row leak issue in Safari.
| - | - | 
| <img width="1552" alt="before" src="https://user-images.githubusercontent.com/4624598/218243290-3d50bccf-40fa-4de4-8802-3a7c2ed32d39.png"> | <img width="1552" alt="after" src="https://user-images.githubusercontent.com/4624598/218243286-667f1861-bdd2-4e64-8d48-f307a1593331.png"> |
- Visit the home page in Safari
- The pixel artifact seen in the `Before` picture above should no longer be there
- The page should look as expected when browser zoom is applied, and should continue to look as expected across all viewport sizes.
[preview]: …
=> fix: gradient pixel leak on waypoint.io landing

src/pages/[productSlug]/tutorials/[...tutorialSlug]/index.tsx
For `HASHI_ENV: 'tutorials-preview'`, bypass the call to our `/static_paths` endpoint, and statically build all **tutorials** pages..
=> tutorials-preview: Bypass /static_paths endpoint

src/components/outline-nav/utils/highlight-active-items.ts, src/views/product-integration/component-view/index.tsx
This PR implements nested outline links for variable groups on Integrations component pages. Common variable groups include Parameters and Outputs.
To match designs, providing a more detailed outline of component pages.
- Updates business logic to generate nested `outlineNavItems` rather than flat `variableGroupHeadings`
- Swaps out `OutlineNavFromHeadings`, swaps in `OutlineNavWithActive`
🎨 [Figma file][figma]
- The sidecar should show an `OutlineNav` listing all parameters and outputs
- Jump links to `Parameters`, `Outputs`, and all nested items should function as expected
> **Note**: on integration component pages, we are not yet extracting headings and adding them to the `OutlineNav`. Due to sanitization requirements, this may be a …
=> feat: integrations nested outline for variable groups

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
Fixes a layout bug, which mainly affects Open API docs pages.
| - | - |
| ![before](https://user-images.githubusercontent.com/4624598/222510272-d414ef15-7eec-4532-a496-86111ffcfb8b.png) | ![after](https://user-images.githubusercontent.com/4624598/222510275-cbed2975-7923-4ac0-af38-905a19c8ebe3.png) |
- The layout should now be fixed - the main content should be aligned with the breadcrumb bar, and the API docs should occupy a similar width as a main container on other docs pages (note: is in intentionally a little wider).
[task]: https://app.asana.com/0/1202097197789424/1204090899347066/f
[preview]: https://dev-portal-git-zsfix-layout-bug-hashicorp.vercel.app/
[/boundary/api-docs/worker-service]: …
=> fix: width bug in sidebar-sidecar layout

src/components/landing-hero/landing-hero.module.css
Fixes a bug where there was no spacing between the "landing hero" on docs landing pages, and the content of those pages.
| - | - |
| ![before](https://user-images.githubusercontent.com/4624598/223557598-5f88b1db-c986-40fb-8676-fd6bf6c622cd.png) | ![after](https://user-images.githubusercontent.com/4624598/223557588-25220b34-70e3-4871-bcf9-600456585ec8.png) |
- There should be spacing between the landing hero (`h1` with icon next to it) and the main content of the page
[task]: https://app.asana.com/0/1202097197789424/1204130762580102/f
[preview]: https://dev-portal-git-zsfix-docs-hero-spacing-hashicorp.vercel.app/
[/terraform/language]: https://dev-portal-git-zsfix-docs-hero-spacing-hashicorp.vercel.app/terraform/language …
=> fix: add missing margin to docs landing-hero

src/content/consul/docs-landing.json
- [Preview link](https://dev-portal-98rz5umo6-hashicorp.vercel.app/consul/docs) 🔎
We noticed some broken links on the docs landing page as a result of some content refactoring. This PR fixes the broken links and updates some of the existing content for consistency with the style guide. 
I also swapped out one of the Kubernetes cards for a link to Consul Dataplane. I figured it was new and something we would want to promote on the docs landing page.
=> fixes broken links and style guide inconsistencies

src/components/navigation-header/navigation-header.module.css
- Fixes the colors used in the `.mobileMenuButton` class
- In some dark mode work, these colors were updated in such a way that made the mobile menu button look invisible:
=> Fixing mobileMenuButton class colors

src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
- [Preview link](https://dev-portal-git-ambintegrations-pagination-hashicorp.vercel.app/vault/integrations) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1204131002305968/f) 🎟️
- Removes manual focus management from `PaginatedIntegrationsList` that happened when `page` changed
- We have an Asana task for getting guidance from the Design Systems team on focus management in filter views, so removing this functionality for now rather than make it more complex feels like the right move
- This behavior was causing browser focus to move from the filter input to the first result while a user was typing, if the current page number was not 1
=> Removing manual focus management from integrations pagination

src/components/open-api-page/server/index.ts, src/components/open-api-page/utils/index.js, src/components/open-api-page/utils/remove-circular-references.js, src/pages/waypoint/api-docs/[[...page]].tsx
Fixes an issue where some information does not render in Boundary API docs.
As method for dealing with circular references was introduced in #1654, as it was necessary for `/waypoint/api-docs` to render. This method unknowingly removed some information from Boundary API docs (information that was falsely identified by the method as being a circular reference).
Updates to only apply the method of dealing with circular references in operation objects to `/waypoint/api-docs`.
- The docs should look & function as they do upstread, except...
- Some operations which previously displayed incomplete information should now be fixed. For example, the `Create Host` operation under [/boundary/api-docs/host-service] should display `Request` parameter …
=> fix: fix api-docs issues from handling circular json

src/components/tabs/components/tab-button-controls/tab-button-controls.module.css
- [Preview link](https://dev-portal-git-ksupdate-tabs-background-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204108582255288) 🎟️
Updates the background of the tab action button to be transparent to blend in with the background on dark mode where its not always white. 
- Test light mode fully in the [swingset page](https://dev-portal-git-ksupdate-tabs-background-hashicorp.vercel.app/swingset/components/tabs). Ensure that it matches upstream.
- Test dark mode on the preview [install view](https://dev-portal-git-ksupdate-tabs-background-hashicorp.vercel.app/packer/downloads), ensure that the tab buttons now blend in with the accordion disclosure background, as opposed to [current staging upstream.](https://dev-portal-git-staging-hashicorp.vercel.app/packe …
=> style: update tab tokens

src/components/dev-dot-content/dev-dot-content.module.css, src/components/dev-dot-content/mdx-components/mdx-inline-code/mdx-inline-code.module.css
- [Preview link](https://dev-portal-git-ksupdate-inline-code-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204108582255289) 🎟️
- [Figma File](https://www.figma.com/file/v0Hyqvjdf6QJAvRkdIBV24/Dark-Mode?node-id=302-30801&t=zKEXDsfXxqaz5rY9-0) 🎨 
Updates the inline code background color to be a semantic token instead of the base neutral token. Also adjusts the border to use a token. 
- [Visit a page](https://dev-portal-git-ksupdate-inline-code-hashicorp.vercel.app/terraform/cli/commands/init) with inline code
- [And another](https://dev-portal-git-ksupdate-inline-code-hashicorp.vercel.app/terraform/enterprise/run/cli#excluding-files-from-upload)
- Validate that light mode looks the same as production
- Check dark mode, ensure the background and border …
=> style: update inline code border and bg color

src/views/sign-up-view/index.tsx
- [Preview link](https://dev-portal-git-ksforce-light-sign-up-hashicorp.vercel.app/sign-up) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204138604242158) 🎟️
This PR adds the theme provider to the sign up page and forces this view to always be 'light' theme. There was an issue where the dark color palette tokens would carry over into this view, even though there isn't theming (see video in ticket). 
This view should remain consistent despite dark and light theming due to the hybrid design. 
[✨ **View diff without whitespace** ✨ ](https://github.com/hashicorp/dev-portal/pull/1751/files?diff=split&w=1)
- [Visit the preview](https://dev-portal-git-ksforce-light-sign-up-hashicorp.vercel.app/), select 'dark' for the theme
- Visit the [sign up …
=> fix: add theme provider forced light - sign up page

src/components/product-icon/index.tsx
Hcp was set to use `hashicorp-brand` but this should inherit from the parent context instead. 
Bug: 
Should be:
- [Visit the preview](https://dev-portal-git-ksfix-hcp-logo-hashicorp.vercel.app/hcp/docs)
- Ensure the logo tile looks okay in both dark and light mode for the hcp icon
=> fix: hcp color inherit

src/components/try-hcp-callout/components/try-hcp-callout-compact/img/try-hcp-callout-compact-background.svg, src/components/try-hcp-callout/components/try-hcp-callout/img/try-hcp-callout-background.svg
- [Preview link](https://dev-portal-git-ksfix-hcp-svg-safari-hashicorp.vercel.app/) 🔎
Safari didn't like the svg edits we made in https://github.com/hashicorp/dev-portal/pull/1753. This fixes those for light mode.
- [Visit the preview](https://dev-portal-git-ksfix-hcp-svg-safari-hashicorp.vercel.app/packer) in light mode **in safari**, ensure the hcp callouts don't have an odd dark background. 
- [look at install page](https://dev-portal-git-ksfix-hcp-svg-safari-hashicorp.vercel.app/)
I'll need to follow up and adjust the approach for dark mode on the compact one and there's still a slight white glare on the main one, since its still off with this change. Will do that in a follow up PR / may need to rethink the svg approach to make it happy with safari.
=> patch: hcp callout svg safari

src/components/try-hcp-callout/components/hcp-logo-heading/hcp-logo-heading.module.css
- [Preview link](https://dev-portal-git-ksfix-hcp-wordmark-hashicorp.vercel.app/hcp) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204240152820189) 🎟️
This fixes an issue where the HCP wordmark wasn't 'flipping' for dark mode since its using `mktg-logos` that don't inherit the `currentColor`
- Visit the hcp landing page. Checkout the HCP callout. Verify that in both light and dark mode the logo renders as expected.
=> fix: hcp wordmark color

src/views/product-downloads-view/boundary/components/operating-system-icons.tsx
- [Preview link](https://dev-portal-git-ksupdate-apple-icon-hashicorp.vercel.app/boundary/downloads) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204240152820178) 🎟️
Adjusts the import for the apple logo to not be color, so that the color is inherited from the parent context and can shift with themes. 
- Visit the [boundary downloads page](https://dev-portal-git-ksupdate-apple-icon-hashicorp.vercel.app/boundary/downloads), validate that the apple logo switches properly between light and dark.
=> style: fixup apple logo import

src/components/product-icon/index.tsx
- [Preview link](https://dev-portal-git-ksfix-vagrant-logo-hashicorp.vercel.app/vagrant) 🔎
For theming, we updated the product icons to dynamically set their fill color associated with the brand since brand colors can shift between themes. Since vagrant doesn't shift and also is '3d' with shadows, we still need to import the color version. 
- [visit vagrant in preview](https://dev-portal-git-ksfix-vagrant-logo-hashicorp.vercel.app/vagrant), validate that the logo shoes highlights / shadows.
=> chore: fix vagrant icon import

config/base.json, config/development.json, config/preview.json, src/components/command-bar/index.tsx, src/components/navigation-header/index.tsx, src/views/docs-view/index.tsx, src/views/product-root-docs-path-landing/index.tsx
- [Asana task](https://app.asana.com/0/0/1204295268139181/f) 🎟️
- Removes the `enable_global_search` feature flag & cleans up references
- Turns off the `enable_product_docs_search` flag
- Feature flag is no longer needed! 🎉
- The `enable_product_docs_search` was coupled to this one, so I've only flipped that off here for ease of reviewing
- [Clean up `enable_product_docs_search` feature flag](https://app.asana.com/0/0/1204295268139188/f) is coming in https://github.com/hashicorp/dev-portal/pull/1798!
---
- https://app.asana.com/0/0/1204295268139181
=> Removing enable_global_search flag and references ✂️

src/views/homepage/components/featured-content-grid/featured-content-grid.module.css, src/views/homepage/components/featured-content-grid/index.tsx, src/views/homepage/index.tsx
- [Preview link](https://dev-portal-git-ambcb-settings-on-open-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1204131825828256/f) 🎟️
- Adds basic `<button>`s to the featured search card
- The featured search terms are defined in the attached task
- These buttons leverage the `setCurrentInputValue` and `toggleIsOpen` helpers exposed by `CommandBar`
- Sets the `contentType` of the `HomePageView` to `'tutorials'`
- This makes `CommandBar` show the `"Tutorials"` tab by default
- Added a comment with explicit context, since we previously had this page use the `"global"` `contentType`
- Adds a magenta border around WIP cards, since this page is starting to shape up and may look official/done/broken otherwise
- This PR does not style these new buttons. That will come in a …
=> [CommandBar] Enable input & tab pre-population on open

src/components/command-bar/components/activator/command-bar-activator.module.css
- [Preview link](https://dev-portal-git-ksfixup-focus-ring-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204304009719187) 🎟️
This fixes up the focus ring styles that were being overridden by the dark override styles for the `box-shadow`. 
- [Visit the preview ](https://dev-portal-git-ksfixup-focus-ring-hashicorp.vercel.app/waypoint), enable dark theme and tab through the nav. The command bar activator input should have focus styles that match light mode.
=> chore: fix focus style

src/components/dropdown-disclosure/index.tsx, src/components/dropdown-disclosure/types.ts, src/components/navigation-header/index.tsx, src/components/navigation-header/navigation-header.module.css, src/components/user-dropdown-disclosure/index.tsx, src/components/user-dropdown-disclosure/types.ts
- [Preview link](https://dev-portal-git-ambfix-user-dropdown-focus-ring-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1204304009719193/f) 🎟️
- Adds `activatorClassName` prop to `DropdownDisclosure`
- Adds `activatorClassName` prop to `UserDropdownDisclosure`, inherited directly from `DropdownDisclosure`
- Renames the `userDropdownDisclosure` class to `userDropdownDisclosureActivator`
- Updates the same class to compose `g-focus-ring-from-box-shadow-dark`
- This element was the only one in the nav header that did not compose `g-focus-ring-from-box-shadow-dark` for the focus ring styles
- Not directly related to this PR, but a Dark Mode question for @kendallstrautman & @braydenlove: Does the `--custom-token-focus-ring-action-box-shadow-dark` variable that …
=> Aligning UserDropdownDisclosure focus ring for consistency

src/views/product-downloads-view/helpers.ts
Second attempt at https://github.com/hashicorp/dev-portal/pull/797
This time using `gpg -o` as suggested by @phinze 
Attaching a screenshot of what happens when users follow the instructiosn as-is. Your terminal turns into an unusable mess. It's an awful UX.
=> ubuntu: use gpg -o instead of tee for getting gpg key

src/views/product-integration/readme-view/index.tsx
Adjusting the Integration page H1 to be driven by the `{integration.name}`.
Previously, the title of this page was `README`, and our guidance to integration authors was that they incorporate the {integration.name} as the first H2 of the top level integration README.  We've adjusted this guidance in our documentation for authors [here](https://github.com/hashicorp/integration-template/blob/main/INTEGRATION_README.md).
Right now, Waypoint integrations are the only remote integrations, and I've adjusted those in this PR: https://github.com/hashicorp/waypoint/pull/4610.  We'll be sure to sync that content before merging this PR to ensure there is no duplication of Titles.
- [Preview link...](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana …
=> Switch the Integration page <h1> to be {integration.name} rather than `README`

src/components/content-header-card/content-header-card.module.css, src/components/content-header-card/index.tsx
We do not want this integration header to be the H1 of the page, as it remains consistent beween subpages (with different page titles). In a [slack discussion](https://hashicorp.slack.com/archives/C03RZAF1XS8/p1680542560922859) it was brought up that there are two `h1`'s on the integration pages, due to the Header component having a H1, and also due to the template having a H1.
The header component always refers to the integration, and is not the source of the page title, so I'm updating this component to be driven via a `span`.
I was considering adjusting this to be another header (like a h2), but realized that it does not fall within the header hierarchy at all.
Let's wait on merging this one until we have https://github.com/hashicorp/dev-portal/pull/1805 deployed & in.
=> Update the integration header’s title to be to be a span instead of a h1

src/components/dropdown-disclosure/components/list-item/index.tsx, src/components/dropdown-disclosure/components/list-item/list-item.module.css, src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx, src/components/mobile-menu-container/components/mobile-user-disclosure/mobile-user-disclosure.module.css, src/lib/auth/user.tsx
- [Preview link](https://dev-portal-git-ksrefactor-mobile-menu-icon-placement-hashicorp.vercel.app/boundary) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204303889362367) 🎟️
- [Figma](https://www.figma.com/file/v0Hyqvjdf6QJAvRkdIBV24/Dark-Mode?node-id=815-40857&t=BLzfEIgRtHWvgFn3-0) 🎨 
This PR refactors the placement of the dropdown disclosure item icon to the right hand side. 
- [Visit the preview](https://dev-portal-git-ksrefactor-mobile-menu-icon-placement-hashicorp.vercel.app/boundary)
- Sign in
- Test the desktop dropdown disclosure placement
- Test the tablet / mobile view
We've removed all the icons from the menus except the external link icon. [This is a follow up task.](https://github.com/hashicorp/dev-portal/pull/1793#issuecomment-1491047999)
=> refactor: disclosure list item icon placement to right

src/content/certifications/exam-faqs/terraform-associate-003.mdx, src/content/certifications/programs/infrastructure-automation.json
- [Preview link](https://dev-portal-git-certta003-live-on-cert-pages-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
- [Asana task](https://app.asana.com/0/1202910531801828/1204283654992281/f) 🎟️
Made updates to https://developer.hashicorp.com/certifications/infrastructure-automation page to call out that TA003 exam is now live.
Because TA 003 exam is now live
=> Update TA cert page to reflect that TA003 exam is live

src/components/standalone-link/docs.mdx, src/components/standalone-link/index.tsx, src/components/standalone-link/standalone-link.module.css, src/components/standalone-link/types.ts
- [Preview link](https://dev-portal-git-ambadd-standalone-link-contents-hashicorp.vercel.app/swingset/components/standalonelink) 🔎
- Abstracts new `StandaloneLinkContents` out of `StandaloneLink`
- We've had to do this as one-offs in a few places, and I'm seeing a need for it in the Home Page Redesign work as well
This PR does not attempt to make use of `StandaloneLinkContents` in other areas of the app to keep this PR small, for faster review purposes since this work will be used in Home Page Redesign PRs.
=> Abstracting StandaloneLinkContents

src/components/footer/index.tsx, src/components/theme-switcher/index.tsx
- Branching off of #1811, updates `ThemeSelect` to auto generate the rendered `<select>`'s `aria-label`
- Also lifts up a `THEME_CONFIGS` constant that stores each theme's `icon`, `label`, and `text`
- The `aria-label` originally proposed in #1811 poses an issue for speech recognition users: the text is not visible, so not intuitive for these users to know how to interact with the element
- We can't totally omit `aria-label` in this case because `<select>` elements do not set their Accessible Name based on their content. This contrasts how `DropdownDisclosure` works, which uses a `<button>` under the hood.
- These changes emulate how `DropdownDisclosure` would behave if we used it here, which is that the Accessible Name becomes the text of the currently selected theme.
- Worth noting this …
=> [ThemeSelect] Auto generating aria-label when no id

src/components/content-header-card/content-header-card.module.css
[🔍 Preview](https://dev-portal-git-brintegration-header-hotfix-hashicorp.vercel.app/waypoint/integrations/hashicorp/aws-ami)
Noticed a visual bug that cropped up on the Integrations component header. This link is supposed to be a different color.
The comment that's in the code there is _exactly_ what has happened here.
This is a hotfix, and not addressing the root issue, but should at least patch it up for now.  I'll open up a thread of discussion here so we can avoid this class of bug in the future.
=> Adds a hotfix to fix the integration header link color

src/content/terraform/product-landing.json
Terraform Associate 003 exam launched today. We want to make sure potential candidates are pointed at the right study materials.
- [Preview link](https://dev-portal-git-ta003-get-certified-updates-hashicorp.vercel.app/terraform) 🔎
- [Asana task](https://app.asana.com/0/1202910531801828/1204283654992281/f) 🎟️
Changed the links in the "Get Certified" section to point to Terraform 003 materials, instead of 002, because 003 launched today.
Because 003 exam launched today.
=> Point Get Certified section to new 003 exam

src/components/standalone-link/index.tsx, src/components/standalone-link/standalone-link.module.css, src/components/standalone-link/types.ts
- [Preview link](https://dev-portal-git-ambfix-standalone-link-contents-hashicorp.vercel.app/) 🔎
- Updates `StandaloneLinkContents`'s `.contents` class to inherit it's `color` when nested inside of `StandaloneLink`
- Adds `DEFAULT_COLOR_VARIANT` since it's needed in 2 places in the file now
- Simplifies the classname associated with `StandaloneLink`'s `color` prop (easier to maintain 2 references to)
- Fixes the color classes to only apply a color change on active/hover if the element it's applied to has an `href` property
=> [StandaloneLinkContents] Fixing how color prop is handled

config/base.json, src/components/footer/index.tsx, src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx, src/components/user-dropdown-disclosure/index.tsx, src/layouts/core-dev-dot-layout/index.tsx, src/lib/isThemedPath.ts
- [Preview link](https://dev-portal-git-ksthemed-product-icon-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204323512217789) 🎟️
So we can control the non-themed paths from one spot. 
I added a utility for checking whether the current path is _themed_ and used that where we render theming UI. 
- [Visit the preview](https://dev-portal-git-ksthemed-product-icon-hashicorp.vercel.app/)
- Validate that the themed ui (user nav dropdown, mobile nav, & footer) shows up on all routes except the homepage and the sign up path
=> refactor: non-themed routes to config

src/components/version-alert-banner/index.tsx, src/layouts/docs-view-layout/components/docs-version-alert/index.tsx, src/layouts/docs-view-layout/index.tsx, src/layouts/sidebar-sidecar/types.ts, src/views/docs-view/index.tsx
- [Preview link](https://dev-portal-git-napre-release-version-alert-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1203347061500809/1203374761617819) 🎟️
This PR changes the message on the `VersionAlertBanner` when a pre-released or non-stable version is selected. 
**Pre-release Version Message:**  You are viewing pre-released documentation for version __
**Stable Version Message (unchanged):**  You are viewing documentation for version __
This will get allow the user to know that the docs version they are currently looking at is not a stable version
To achieve this I passed `versions` from `DocsViewProps` (`views > docs-view > server.ts > getStaticProps()`) through `DocsView`, into `DocsViewLayout`, ultimately into `DocsVersionAlertBanner`. 
From there, I find the …
=> Add pre-release info on version alert banner

.prettierignore
- Removes the `*.css` line from `.prettierignore`
- `.css` files haven't been getting auto formatted on save
- This is likely a remnant from the `SPACE` > `TAB` migration many, many months ago
=> Removing css extension from prettierignore

src/layouts/base-new/base-new-layout.module.css
- [Preview link](https://dev-portal-git-ambmobile-menu-hotfix-hashicorp.vercel.app/) 🔎
- Fixes the `z-index` value for the mobile menu container on the home page
- Some of the absolutely positioned elements of the home page were on top of the mobile menu container
=> hotfix: Fixes z-index of mobile menu on home page

src/views/homepage/components/featured-content-grid/search-featured-card.module.css, src/views/homepage/components/featured-content-grid/search-featured-card.tsx
- [Preview link](https://dev-portal-git-ambhp-safari-autoscroll-hashicorp.vercel.app/) 🔎
- Replaces the `scrollBy` autoscroll implementation with programmatically setting the `transform: translateX()` property in JS
- Autoscroll was not working consistently in macOs or iOS Safari
- My first attempt at this tried to animate against the `left` CSS property. When testing it in Safari, it was jittery/laggy. Shout out to @BRKalow for a resource about this and the suggestion to use `translate: transformX()` instead! The resource is: [Stick to Compositor-Only Properties and Manage Layer Count](https://web.dev/stick-to-compositor-only-properties-and-manage-layer-count/).
---
- …
=> [Home Page Redesign] Implement search card auto scroll with transition on `transform: translateX()` property

src/components/content-header-card/content-header-card.module.css, src/components/content-header-card/index.tsx
An issue cropped up which was hot-fixed via https://github.com/hashicorp/dev-portal/pull/1825, which addressed an issue where the styles were no longer targeting the right element (leading to the links in this header component to be incorrect).
This PR removes the Override from the integrations header. After some discussion with Design, we landed on the fact that we are OK not including the permanent underline, in favor of using the StandaloneLink as designed.
[🔍 Preview](https://dev-portal-git-brintegration-header-remove-override-hashicorp.vercel.app/waypoint/integrations/hashicorp/aws-ami). 
> There is an outstanding bug right now, unrelated to this PR, where underlines are displaying the incorrect color, which is being worked on currently.
=> Remove Override from Integration Header

src/hooks/use-on-swipe.ts, src/views/homepage/components/featured-content-grid/search-featured-card.tsx
- [Preview link](https://dev-portal-git-ambhp-search-card-swipe-hashicorp.vercel.app/) 🔎
- Adds new `useOnSwipe` hook
- Leverages the new hook in `SearchFeaturedCard`
- Abstracts 2 new `incrementIndex` and `decrementIndex` callbacks in `SearchFeaturedCard`
- The [React Aria `useMove`](useMove) was raised as a potential solution for this functionality, but I decided not to leverage it here since we only need to listen for touch events in this case. However, I did leave a note in the code comments about the hook in case we find it's additional functionality necessary in the future.
=> [Home Page Redesign] Implementing swipe interaction on featured search card

src/pages/hcp/api-docs/packer/[[...page]].tsx, src/views/api-docs-view/components/api-docs-version-alert/api-docs-version-alert.module.css, src/views/api-docs-view/components/api-docs-version-alert/index.tsx, src/views/api-docs-view/components/api-docs-version-alert/types.ts, src/views/api-docs-view/components/index.tsx, src/views/api-docs-view/index.tsx, src/views/api-docs-view/server/get-api-docs-static-props/index.ts, src/views/api-docs-view/types.ts
Adds a version alert on non-latest-URL API docs pages.
To more consistently signal to visitors when they're viewing a non-latest version of documentation.
| Page | Before | After |
| - | - | - |
| [Preview version][/hcp/api-docs/packer/2023-01-01] | <img width="400" alt="before-preview" src="https://user-images.githubusercontent.com/4624598/235529675-5807e21a-25ca-42e1-98b2-ad34ebabfb5b.png" /> | <img width="400" alt="after-preview" src="https://user-images.githubusercontent.com/4624598/235529669-ecf95589-9d84-4e4f-a70c-e6b34091e853.png" /> |
| [Older stable version][/hcp/api-docs/packer/2021-04-30] | <img width="400" alt="before-older-stable" src="https://user-images.githubusercontent.com/4624598/235529673-fb79eb65-8a92-45bd-92de-46a268f …
=> feat: add version alert for api docs

src/components/head-metadata/index.tsx
- [Preview link](https://dev-portal-git-zsmulti-zendesk-meta-attrs-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202801212949828/1204197006767451/f) 🎟️
Adds two additional zendesk crawler verification tags. [Visit a page](https://dev-portal-git-ksadds-additional-crawler-tags-hashicorp.vercel.app/) on the preview and verify that the additional meta tags render in the head.
> **Note**: this PR follows up #1901 , which made the same change, but had an unexpected issue due to `name`-based `<meta />` tag de-duplicating in `next/head`.
=> fix: zd-verify meta tag de-dupe issue

src/views/api-docs-view/index.tsx
This PR fixes up the display logic for the `/hcp/api-docs/packer` version selector.
- [Upstream][upstream/hcp/api-docs/packer], the version select dropdown is shown even though there is only one version of the docs to display, resulting in an empty dropdown
- In this PR, at [/hcp/api-docs/packer], the version select dropdown should not be shown
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/87587e2d-819f-4969-b8a3-1f3b3bd12092) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/d420d77f-c930-47fe-8bf5-08e6d101adc6) | 
[preview]: https://dev-portal-git-zspatch-api-docs-version-select-hashicorp.vercel.app/
[upstream/hcp/api-docs/packer]: https://developer.hashicorp.com/hcp/api-docs/packer
[/hcp/api-docs/packer]: …
=> fix: display logic for api-docs version select

src/pages/hcp/api-docs/packer/[[...page]].tsx
This PR avoids trying to statically render `/hcp/api-docs/packer` in all "content preview" repositories, as determined by our `isDeployPreview()` utility.
=> fix: avoid static api-docs render in preview repos

src/components/navigation-header/navigation-header.module.css
- [Preview link](https://dev-portal-git-ksfix-background-user-button-hashicorp.vercel.app/) 🔎
Fixes an issue where the user dropdown disclosure active background color was off on light-themed pages. I connected with @braydenlove to figure out what this color should be. We chose to do an override this this only affects light themed user dropdown disclosure in the navigation.
- [Visit the homepage](https://dev-portal-git-ksfix-background-user-button-hashicorp.vercel.app/), click the user dropdown disclosure, ensure that on `active` the component background color isn't too light. Compare with production. 
- Visit a [page with theming](https://dev-portal-git-ksfix-background-user-button-hashicorp.vercel.app/waypoint), switch between light and dark theme and ensure the contrast on the active …
=> fix: user dropdown disclosure active bg-color

config/production.json
This reduces `__config.dev_dot.max_static_paths` from `50` to `15`.
This offloads some amount of static generation to post-build ondemand generation
This aims to reduce production build times
---
- https://app.asana.com/0/0/1204565843516262
=> feat: reduce dev-dot paths from 50 to 15

src/components/tutorial-meta/components/badges/index.tsx
- [Preview link](https://dev-portal-git-ksfix-vertical-line-metadata-hashicorp.vercel.app/) 🔎
Only render the vertical separator in tutorial meta when badges beyond readtime exist.
🔧 Fix
🐛 Bug
- [visit this tutorial](https://dev-portal-git-ksfix-vertical-line-metadata-hashicorp.vercel.app/well-architected-framework/security/security-introduction) that has no products or other metadata associated, verify [against upstream ](https://dev-portal-4a1q81voa-hashicorp.vercel.app/well-architected-framework/security/security-introduction)that the vertical line doesn't render.
=> fix: render vertical line when badges exist

src/components/tabs/components/tab-button-controls/tab-button-controls.module.css
Increases the spacing between tab buttons and the border below them for `"compact"` variants of the `<Tabs />` component.
To improve the Search results experience. Giving the tabs slightly more breathing room in the search results context should make them more visible and easier to use.
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/378b6717-06de-4c6a-bd61-9f2c8c8c5992) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/a02d649b-363c-45db-ae29-056cf8645615) |
- The search experience should continue to function as expected
- Tabs should have a little more breathing room in the spacing to the "tab line" below tab `<button />` controls
- Note: I couldn't actually find a use of …
=> chore: tweak tab padding for compact variant

src/components/tutorial-meta/components/index.ts, src/components/tutorial-meta/components/variant-list/index.tsx, src/components/tutorial-meta/components/variant-list/variant-list.module.css, src/components/tutorial-meta/index.tsx, src/views/tutorial-view/index.tsx, src/views/tutorial-view/utils/variants/_tmp-variants-data.json
- [Preview link](https://dev-portal-git-ksvariants-button-list-hashicorp.vercel.app/vault/tutorials/getting-started-ui/getting-started-policies-ui?variants=deployment:hcp) 🔎
- [Asana task](https://app.asana.com/0/1204333057896641/1204615849802274) 🎟️
- [Figma File 🎨 ](https://www.figma.com/file/NAFjIPkbwjyY8jPl6T9nlP/Tutorial-Variants?type=design&node-id=165-30497&t=XEhCsJPFalEhRqQK-0)
🚧 Merging into an Assembly 🚧 
This PR adds the variants button link list below the tutorial metadata.
Adds a new `VariantList` component within the tutorial metadata.
- [Visit the preview](https://dev-portal-git-ksvariants-button-list-hashicorp.vercel.app/vault/tutorials/getting-started-ui/getting-started-policies-ui?variants=deployment:hcp), validate that the list matches the design spec
- Validate that it …
=> feat: variants button list

config/plugin.js, src/pages/well-architected-framework/[...tutorialSlug]/index.tsx, src/pages/well-architected-framework/[collectionSlug].tsx
Same work as https://github.com/hashicorp/dev-portal/pull/1943
---
This adds a static path limit (`__config.learn.max_static_paths`) to our `well-architected-framework/*` pages
- `src/pages/well-architected-framework/[collectionSlug].tsx`
- `src/pages/well-architected-framework/[...tutorialSlug]/index.tsx`
Decrease build times and offload page building to ondemand generation.
---
- https://app.asana.com/0/0/1204605831831148
=> feat: limit /well-architected-framework/* static path count

src/components/head-metadata/index.tsx
This PR is a follow up to https://github.com/hashicorp/dev-portal/pull/1915 and removes `--[product]` from each Zendesk meta tag. Documentation showed nothing saying the `name` had to be `zd-site verification` but after deploying, the tags weren't working. I moved the product name to it's own data attribute instead. Hoping this approach works while also signaling which product the meta crawler is for for future us and for the requestor [here](https://app.asana.com/0/1202801212949828/1204197006767451/f).
These Zendesk crawler tags are for the sandbox instance. There is a ticket already created to handle the change to production crawlers once this implementation is verified.
=> chore: remove product modifier from zendesk crawlers 

src/components/dialog/dialog.module.css
Fixes an issue where on certain viewports, a scrollbar is shown on modal contents when it's not strictly needed.
| - | - |
| <img width="654" alt="before" src="https://github.com/hashicorp/dev-portal/assets/4624598/258930f6-8b99-4505-881c-9cf3b3b6e2a3"> | <img width="659" alt="after" src="https://github.com/hashicorp/dev-portal/assets/4624598/0d254a8f-b9d9-4ed7-94ab-c07e3c2579b6"> |
https://github.com/hashicorp/dev-portal/assets/4624598/16e3eef8-5368-456b-b96d-e30fd1a2a8f9 
https://github.com/hashicorp/dev-portal/assets/4624598/9aaf89a9-ca26-4a8f-a73c-4abfa4bb4151
[preview]: https://dev-portal-git-zsfix-dialog-bottom-overflow-hashicorp.vercel.app/
=> fix: overflow-y auto on modal content

src/pages/boundary/api-docs/[[...page]].tsx, src/views/api-docs-view/api-docs-view.module.css
This PR transitions [/boundary/api-docs] from previously implemented `api-docs-view` utilities, which originated from the `io` implementation, to a newer version implemented specifically for Dev Dot.
This is largely a maintenance task, to ensure all API docs use the same underlying logic. The broader intent is to ensure further iteration on API docs is smooth.
As well, one major difference is that the new implementation supports versioned API docs. The [/boundary/api-docs] page does not currently use versioned functionality, but could in the future.
| - | - | 
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/89c0c9bc-bfc4-4d17-bf0c-b8864bbaa84a) | …
=> chore: upgrade boundary api docs to new utils

src/components/filter-input/filter-input.module.css
- [Preview link](https://dev-portal-git-ksfix-filter-input-type-hashicorp.vercel.app/boundary/docs) 🔎
- [Asana task](https://app.asana.com/0/1204333057896641/1204623770940349) 🎟️
Fixes an issue where the type-200 styles were overriding the filter input styles. Since all the type 200 styles were being overridden anyways, this removes that composition. 
- [Visit this URL](https://dev-portal-git-ksfix-filter-input-type-hashicorp.vercel.app/boundary/docs), verify the styles render as expected. [Compare against prod.](https://developer.hashicorp.com/boundary/docs) and [upstream 🐛 ](https://dev-portal-git-ksvariants-assembly-hashicorp.vercel.app/boundary/docs)
- Test on mobile
=> style: remove type-200 on filter input

src/views/tutorials-landing/components/content-types-section/content-types-section.module.css, src/views/tutorials-landing/components/content-types-section/index.tsx, src/views/tutorials-landing/components/index.ts, src/views/tutorials-landing/index.tsx, src/views/tutorials-landing/tutorials-landing.module.css
- [Preview link](https://dev-portal-git-tfd-ambcontent-types-section-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/0/1204660968035224/f) 🎟️
- Adds `ContentTypesSection` component under `src/views/tutorials-landing/components/`
[Figma link](https://www.figma.com/file/mmbCubXM9sOQqvGG0b8o0D/Tutorial_LP?type=design&node-id=303-23730&t=zidhDWZL6umha1KR-11)
- The kitten placeholder images will be replaced next week in a follow-up PR; one of them is still being discussed.
- The way this component sits in the view will be worked on when all components are arranged.
=> [Tutorials Front Door] Adding ContentTypesSection subcomponent

src/components/content-header-card/index.tsx
Adjust the badge style to be more consistent with the cards on the Integrations library page (per design)!
[🎟️ Asana ticket](https://app.asana.com/0/1203792704477769/1204425861866904/f)
=> Adjust integration header card badge style

src/lib/get-integration-badges.tsx
Incorporates a `type` badge to the integration cards if a type is set.
[🎟️ Asana Ticket](https://app.asana.com/0/1203792704477769/1204425861866904/f)
=> Adds a 'Type' Badge to Integration Cards

src/layouts/sidebar-sidecar/index.tsx, src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css, src/layouts/sidebar-sidecar/types.ts, src/views/tutorial-view/index.tsx
- [Preview link](https://dev-portal-git-ksrefactor-variant-dropdown-disclosure-layout-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204333057896641/1204621999504614) 🎟️
This PR introduces a workaround so that the variant dropdown disclosure in the sidecar is not contained in the scrollable sidecar area. However, the hard-coded height for the `max-sidecar-height` calculation [isn't a long term solution](https://app.asana.com/0/1204333057896641/1204669563792095), needs to be refactored after this launch so that this slot can accept any component, not just the dropdown disclosure. Since no other views use it currently, this isn't an issue. 
- [Visit this Tutorial](https://dev-portal-git-ksrefactor-variant-dropdown-dis-97e464-hashicorp.vercel.app/vault/tutorials/getting-star …
=> refactor: variant dropdown disclosure layout

src/views/tutorials-landing/constants.tsx, src/views/tutorials-landing/index.tsx
- [Preview link](https://dev-portal-git-tfd-ambproduct-section-order-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/0/1204662262934320/f) 🎟️
- Adds `PRODUCT_SECTIONS_ORDER_BY_SLUG` constant scoped to `TutorialsLandingView` 
- Using a named constant makes the intended use clear. Other options for determining order are higher effort or not immediately clear:
- Adding an `order` property to the `src/content/` file for each product requires more manual effort to reorder sections and runs the risk of accidentally setting the same number for multiple products
- Inferring order from the product slug properties in the `src/content/` file would require moving a lot of lines of code around, and it's not explicit from the file that changing the order would change how the …
=> [Tutorial Front Door] Add constant that specifies production section order

src/views/tutorial-view/utils/variants/mdx-variant.tsx
It looks like the MdxVariant uses `useVariant`, which does not always yield a variant. We run into a null reference on lines right after this check / ejection I add without it, which prevents a build.
https://github.com/hashicorp/tutorials/actions/runs/5137008172/jobs/9244505941
=> Fixes a bug with Variants

src/views/tutorial-view/utils/index.ts
This fixes our cache-warming workflow.
The cause:
A `.tsx` module added to a barrel-export causes our `npx hc-tools ./scripts/warm-cache.ts` script to error.
- see export: https://github.com/hashicorp/dev-portal/commit/5556b222346e70927eb9f3abf6a7e4f18fdb999a#diff-5fea0ff96b61e4194461e3cccee1ffa9e376ed1b5c9084e3dcc96aa788dfefebR9
- see error: https://github.com/hashicorp/dev-portal/actions/runs/5125219860/jobs/9218275252#step:6:8
=> fix(warm-cache): avoid `.tsx` export side-effect

src/views/tutorials-landing/components/product-section/index.tsx
- [Preview link](https://dev-portal-git-tfd-ambfix-explore-more-cta-hashicorp.vercel.app/tutorials) 🔎
- Fixes the "Explore more" `StandaloneLink` CTA text in `ProductSection`
- It wasn't correct with what was designed & proposed in the RFC
=> [Tutorials Front Door] Fix "Explore more" general CTA text

src/lib/learn-client/api/collection/formatting.ts, src/lib/learn-client/api/tutorial/formatting.ts, src/lib/learn-client/types.ts, src/views/tutorial-view/server.ts
Updates the `getTutorialPagePaths` function to also return all variant paths.  This is needed for our tutorials preview to statically build all variant paths.
=> Statically build all variant pages for Tutorials Preview

analytics/spec/events/tutorials_front_door_link_clicked.yaml, src/components/card-link/index.tsx, src/components/card-link/types.ts, src/components/tutorials-landing-view/certification-content-card-link/index.tsx, src/components/tutorials-landing-view/collection-content-card-link/index.tsx, src/components/tutorials-landing-view/content-card-link/index.tsx, src/components/tutorials-landing-view/types.ts, src/views/tutorials-landing/analytics.ts, src/views/tutorials-landing/components/product-section/index.tsx
- [Preview link](https://dev-portal-git-tfd-ambevent-tracking-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1204535818156240/1204687872642324) 🎟️
- Adds analytics spec: `analytics/spec/events/tutorials_front_door_link_clicked.yaml`
- Adds analytics tracking helpers in: `src/views/tutorials-landing/analytics.ts`
- Main helper, not exported: `trackTutorialsFrontDoorLinkClicked`
- `trackCertificationCardLinkClicked`
- `trackCollectionCardLinkClicked`
- `trackFeaturedUseCaseLinkClicked`
- `trackProductTutorialsLandingLinkClicked`
- `trackTutorialLibraryLinkClicked`
- Adds `CardLink.onClick` prop
- Adds `ContentCardLink.onClick` prop
- Adds `CertificationContentCardLinkProps.product` prop
- Adds click event tracking to:
- `CertificationContentCardLink`
- …
=> [Tutorials Front Door] Add link click event tracking

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
Fixes a bug where the Variants dropdown in the sidecar did not overflow correctly. Overflow for the `.sidecarTopSlot` should be visible, rather than being cut off or scrolling.
| Before | After | 
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/250bc76b-ef50-42d1-a523-c15aef156bd0) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/67867fd7-451c-43f4-a4f4-9352f6e7ad72) |
- The `.sidecarTopSlot` should no longer have scrolling overflow
- Then the variants dropdown is open, the dropdown pane should be visible
[preview]: https://dev-portal-git-zsfix-sidecar-overflow-hashicorp.vercel.app/
=> fix: sidecar overflow for variant dropdown

config/base.json, config/development.json, src/components/command-bar/commands/search/index.tsx, src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx, src/components/command-bar/commands/search/unified-search/components/index.tsx
Stubs in unified search placeholder behind a feature flag, disabled in all environments for now.
To set up a foundation off which to build a unified search "All" tab.
| Flag off | Flag on |
| - | - |
| ![flag-off](https://github.com/hashicorp/dev-portal/assets/4624598/66936a6d-4c75-43f5-a2d1-10a661c9f85f) | ![flag-on](https://github.com/hashicorp/dev-portal/assets/4624598/32afbd68-6cfb-40aa-85cd-2d3b445c3685) | 
- When you open the search modal, search should function exactly as it does [upstream]
- When you open the search modal, there should be a useless search placeholder
[task]: https://app.asana.com/0/1204333060736722/1204604641329009/f
[preview]: https://dev-portal-git-zsstart-unified-search-hashicorp.vercel.app …
=> chore: add flag & placeholder for unified search

src/views/well-architected-framework/tutorial-view/index.tsx, src/views/well-architected-framework/tutorial-view/server.ts, src/views/well-architected-framework/types.ts
- [Preview link](https://dev-portal-git-ksadds-waf-variants-support-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204650842219622) 🎟️
Adds variants support to waf tutorials.
There isn't any waf tutorials in the staging api with variants data. I tested this locally with manually seeded api data and validated that it works as expected.
=> feat: adds waf variant support

src/pages/_error.jsx
Removing a console log from our error page. I've only ever seen it log `undefined`, so it feels unnecessary 👀
=> chore: remove unused error message

src/content/certifications/exam-faqs/vault-operations-professional.mdx
Added information on the 15-min break that comes with the appointment
- [Preview link](https://dev-portal-git-eganhashicorp-patch-1-hashicorp.vercel.app/certifications/security-automation) 🔎
- [Asana task](https://app.asana.com/0/1155877155450049/1204728308498735/f) 🎟️
Added a few words explaining that a 15-min break can be taken during the exam
Support tickets asking about breaks made us realize we did not advertise the break externally
=> Updated vault-operations-professional.mdx

src/components/head-metadata/index.tsx, src/components/head-metadata/types.ts, src/lib/get-deployed-url.ts, src/pages/_app.tsx, src/types/_app.ts
This removes our usage of the legacy `getInitialProps` API
- The Next.js docs mark this as a legacy API. https://nextjs.org/docs/pages/api-reference/functions/get-initial-props
See PR diff comments for a more detailed explanation.
---
- https://app.asana.com/0/0/1204865849100226
=> chore: remove `App.getInitialProps`

src/layouts/base-new/index.tsx, src/layouts/base-new/types.ts, src/layouts/core-dev-dot-layout/index.tsx, src/pages/_app.tsx, src/views/homepage/index.tsx
This continues off https://github.com/hashicorp/dev-portal/pull/2027 and cleans up no longer used `.theme` code after #2007 
> **Note**: See https://github.com/hashicorp/dev-portal/pull/2007/files#r1242886411 for the last identified case of `<PageComponent>.theme`
=> _app/layouts: remove `.theme` usage

src/layouts/docs-view-layout/components/docs-version-alert/index.tsx
There are some errors showing up in Datadog that look like this:
```
ERROR	TypeError: Cannot read properties of null (reading 'find')
at DocsVersionAlertBanner (/var/task/.next/server/chunks/3864.js:1088:48)
...
```
I've updated the component to gracefully handle the scenario where `versions` is `null`. This should hopefully mitigate the number of errors we see that look like this.
=> fix: update DocsVersionAlertBanner to gracefully handle null versions

config/development.json, config/preview.json, src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx, src/components/command-bar/commands/search/unified-search/components/suggested-pages/index.tsx, src/components/command-bar/commands/search/unified-search/components/suggested-pages/suggested-page.module.css, src/components/command-bar/commands/search/unified-search/components/suggested-pages/types.ts, src/components/command-bar/commands/search/unified-search/components/unified-hits-container/index.tsx, src/components/link-region/link-region.module.css
> **Note**: 🚧 should disable `development` and `preview` flags for unified search before merging.
---
Revises the "suggested page" list items in the unified search modal, to match designs.
- Ejects from the existing `SuggestedPages` component, builds a new one for unified search
Empty query
| - | - |
| ![empty-before](https://github.com/hashicorp/dev-portal/assets/4624598/55a96672-f23d-4d10-92b5-6e3615283a41) | ![empty-after](https://github.com/hashicorp/dev-portal/assets/4624598/28fc88d1-3923-4041-95c2-88f4a42be35a) |
Query with zero results
| - | - |
| ![noresults-before](https://github.com/hashicorp/dev-portal/assets/4624598/5847b2aa-08bb-49bf-8272-a7dbbfdfd1a8) | …
=> feat(unified-search): revise suggested pages design

src/components/inline-alert/docs.mdx, src/components/inline-alert/index.tsx, src/components/inline-alert/inline-alert.module.css, src/components/inline-alert/types.ts, src/pages/nomad/downloads/index.tsx, src/pages/nomad/downloads/style.module.css
- [Preview link](https://dev-portal-git-ksupdate-nomad-downloads-inline-alert-hashicorp.vercel.app/nomad/downloads) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204909025833155) 🎟️
This PR adds a `ctaSlot` to the inline alert component and updates the nomad downloads alert to use inline alert. [Slack context. ](https://hashicorp.slack.com/archives/C01KCU4HDPY/p1687972000198179?thread_ts=1687969517.288049&cid=C01KCU4HDPY)
- [Visit nomad downloads](https://dev-portal-git-ksupdate-nomad-downloads-inline-alert-hashicorp.vercel.app/nomad/downloads), validate that the alert renders as expected.
=> adds ctaSlot to inline alert, updates nomad downloads

src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts, src/views/docs-view/utils/product-url-adjusters.ts
- [Preview link](https://dev-portal-git-ksfix-waf-link-docs-rewrite-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1204937553758581) 🎟️
Fixes a bug where waf / onboarding links were getting rewritten to .io urls. 
There are no active waf urls in use in docs content. However, this [aws waf link](https://dev-portal-git-ksfix-waf-link-docs-rewrite-hashicorp.vercel.app/terraform/enterprise/reference-architecture/aws#high-availability-failure-scenarios) shouldn't be rewritten. Other tutorial urls should still work as expected in docs content.
---
- https://app.asana.com/0/0/1204937553758581
=> fix: don't rewrite waf / onboarding links

src/lib/remark-plugins/rewrite-static-tutorials-assets/index.ts
- [Preview link](https://dev-portal-git-ksfix-rewrite-assets-local-dev-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1204908882543128/f) 🎟️
Adjusts the `rewriteStaticAssets` plugin so that images load for local dev. The 'special' condition for the local tutorials workflow is set by a new env `TUTORIALS_LOCAL`, [see related PR](https://github.com/hashicorp/tutorials/pull/1482)
- Pull this down locally, run dev, visit a tutorial (example path: /consul/tutorials/resiliency/introduction-chaos-engineering) and validate that tutorials images load as expected.
- Validate that images work the same on preview as well.
=> fix: tutorials image paths local dev

package-lock.json, package.json, src/components/dev-dot-content/mdx-components/mdx-headings/utils/is-injected-permalink.ts
Bumps `next` from `13.0.5` to `13.4.8`
**Preview**: https://dev-portal-git-kwupdate-next-hashicorp.vercel.app/
Related: https://github.com/hashicorp/dev-portal/pull/2036
Related: https://vercel.com/teams/hashicorp/support/cases/00143787
(ensure these URLs are rendering the correct content)
=> chore: bump next version

src/components/accordion-disclosure/index.tsx, src/components/accordion-disclosure/types.ts, src/components/dev-dot-content/mdx-components/index.tsx, src/components/dev-dot-content/mdx-components/mdx-accordion/index.tsx, src/components/dev-dot-content/mdx-components/mdx-accordion/mdx-accordion.module.css, src/views/tutorial-view/utils/mdx-components.tsx
- [Preview link](https://dev-portal-git-ks-fix-accordion-space-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1204131002305975/f) 🎟️
Fixes an issue where multiple accordions stacked next to each other don't have margin. 
- [Visit a path](https://dev-portal-git-ks-fix-accordion-space-hashicorp.vercel.app/terraform/tutorials/aws/blue-green-canary-tests-deployments) with multiple accordions
- Ensure that they have space between 
- Also ensure that they remain collapsed as expected
=> fix: adds accordion margin

src/components/author-primitives/packer/checklist/style.module.css
- [Preview link](https://dev-portal-git-ksfix-check-item-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203368245666617/f) 🎟️
Fixes a bug where packer checklist `::before` content wasn't rendering in the correct position. 
- [Visit path](https://dev-portal-git-ksfix-check-item-hashicorp.vercel.app/packer/docs/partnerships#checklist) with checklist 
- Validate that it is positioned as expected.
- Lists outside of this packer checklist primitive should remain unaffected
=> fix: packer checklist position

src/views/collection-view/helpers/index.ts, src/views/tutorial-view/index.tsx
This removes `.tsx` import side effects in shared files between Node scripts & runtime app code.
A command this fixes is 
```jsonc
//package.json
"rewrite-docs-content-links": "hc-tools ./scripts/docs-content-link-rewrites/rewrite-links.ts"
```
Example observed error: https://github.com/hashicorp/ptfe-releases/actions/runs/5513172741/jobs/10051028728?pr=570#step:7:18
```
Error: Cannot find module './generate-collection-sidebar-nav-data'
```
=> fix: avoid TSX imports in hc-tools scripts

src/views/onboarding/tutorial-view/server.ts, src/views/tutorial-view/utils/get-collection-context.ts, src/views/well-architected-framework/tutorial-view/server.ts
- [Preview link](https://dev-portal-git-ksfix-onboarding-path-match-hashicorp.vercel.app/) 🔎
Fixes a loose match on tutorial slugs for determining the correct tutorial data. 
- Visit some tutorial paths, validate that the correct data shows
- Visit a path that is [broken in prod](https://developer.hashicorp.com/onboarding/hcp-vault-week-3/database-secrets), validate that the [correct data](https://dev-portal-git-ksfix-onboarding-path-match-hashicorp.vercel.app/onboarding/hcp-vault-week-3/database-secrets) now shows.
=> fix: current tutorial data path match

src/pages/hcp/api-docs/vault-secrets/[[...page]].tsx, src/views/api-docs-view/api-docs-view.module.css, src/views/api-docs-view/components/path-truncation-aside/index.tsx, src/views/api-docs-view/index.tsx
This PR adds API documentation for HCP Vault Secrets at [/hcp/api-docs/vault-secrets].
To better expose documentation for this API to users.
Applies existing work with HCP Packer API docs to the analogous Swagger file for HCP Vault Secrets.
> **Note**: this is a net new page
- The page should look and function as expected
- For now, we've stuck to the existing API docs template, without further modifications
- Intent is to favour rebuilding the API docs template from scratch over tweaking the current template
[task]: https://app.asana.com/0/1204810348326275/1204973521875671/f
[preview]: https://dev-portal-git-zshcp-vault-secrets-api-docs-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: …
=> feat: add HCP Vault Secrets API docs

src/components/sidebar/components/sidebar-nav-menu-item/index.tsx, src/components/sidebar/components/sidebar-nav-menu-item/sidebar-nav-menu-item.module.css, src/components/sidebar/components/sidebar-nav-menu-item/types.ts
- [Preview link](https://dev-portal-git-ksadjust-chevron-direction-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204807665183200/1205002759200577/f) 🎟️
- [Figma file](https://www.figma.com/file/G6RNneOMHyRgcFx98VZUpp/IA-Improvements?type=design&node-id=406-54557&mode=design&t=rG3DKEUgroeRBpsY-0) 🎨 
Updates the nested sidebar chevron icon to point down / up to align with the dropdown disclosure styles. 
- [Visit a docs page ](https://dev-portal-git-ksadjust-chevron-direction-hashicorp.vercel.app/consul/docs)with nested sidebar items
- Validate that the chevron points down when closed and up when opened.
=> style: adjust docs sidebar chevron icon

src/content/hcp/docs-landing.json, src/content/vagrant/docs-landing.json, src/views/product-landing/helpers/get-icon-cards.tsx
- [Preview link](https://dev-portal-git-ksadjust-top-nav-order-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204807665183200/1205002759200572/f) 🎟️
- [Figma file](https://www.figma.com/file/G6RNneOMHyRgcFx98VZUpp/IA-Improvements?type=design&node-id=338-41767&mode=design&t=rG3DKEUgroeRBpsY-0) 🎨 
Adjusts the card link item order to align with the global nav. 
- Visit all the [product landing pages](https://dev-portal-git-ksadjust-top-nav-order-hashicorp.vercel.app/vault), validate that the card link item order matches the top nav where the items match
- Validate that vagrantfile is after vagrant cloud on the [vagrant docs landing](https://dev-portal-git-ksadjust-top-nav-order-hashicorp.vercel.app/vagrant/docs)
There's follow up work to align the sidebar on these views …
=> chore: adjust product landing card link order

src/views/product-integration/component-view/components/searchable-variable-group-list/index.tsx
- [Preview link](https://dev-portal-git-ksshow-required-conditionally-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204845103172089/1204091239221872/f) 🎟️
Updates the logic to render the 'Required Only' filter to only show when there is at least one required variable. 
- [Visit a page](https://dev-portal-git-ksshow-required-conditionally-hashicorp.vercel.app/waypoint/integrations/hashicorp/aws-ssm/latest/components/config-sourcer/aws-ssm-config-sourcer) where the required only filter should no longer show, compare [against upstream](https://developer.hashicorp.com/waypoint/integrations/hashicorp/aws-ssm/latest/components/config-sourcer/aws-ssm-config-sourcer)
- [Visit a page](https://dev-portal-git-ksshow-required-conditionally-hashicorp.vercel.app/waypoint/integrations/ …
=> [integrations] chore: only show required filter only when required var(s) exist

src/views/product-integration/component-view/components/searchable-variable-group-list/index.tsx, src/views/product-integrations-landing/components/integrations-list/index.tsx
- [Preview link](https://dev-portal-git-ksadds-empty-state-integrations-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204845103172089/1204068171740400/f) 🎟️
Adds an empty state to variable group list integrations filtering. 
I used the same component from the integrations library empty results. 
- [Visit this page](https://dev-portal-git-ksadds-empty-state-integrations-hashicorp.vercel.app/waypoint/integrations/hashicorp/aws-ssm/latest/components/config-sourcer/aws-ssm-config-sourcer), enter in a weird filter term like 'pickles'
- View the no results component
- Click 'clear' 
- validate that the query is reset
- Test again with the required checkbox filter. 
We may want to adjust the messaging in the 'no results' component body for this context? @braydenlove
=> [integrations] feat: adds variable group list empty state 

config/base.json, config/development.json, config/preview.json, config/production.json, src/pages/hcp/api-docs/vault-secrets/[[...page]].tsx, src/views/open-api-docs-view/index.tsx, src/views/open-api-docs-view/server.ts, src/views/open-api-docs-view/types.ts
Adds a `enable_hcp_vault_secrets_api_docs_revision` feature flag, and a related placeholder `open-api-docs-view`.
To allow development of the revised API docs template to happen behind a feature flag.
- The preview should be identical to the [upstream /hcp/api-docs/vault-secrets][upstream/hcp/api-docs/vault-secrets]
- Pull this branch down locally, and set the `enable_hcp_vault_secrets_api_docs_revision` flag to `false` in `src/config/development.json`
- Running the site locally, you should see a placeholder view at `/hcp/api-docs/vault-secrets`
[task]: https://app.asana.com/0/1204678746647847/1205011719572370/f
[preview]: https://dev-portal-git-zsadd-revised-api-docs-flag-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: …
=> chore: add flag for revised Vault Secrets API docs

config/development.json, config/preview.json
Reverts flags accidentally not set back to `false` in #2105.
=> chore: revert open-api-docs dev & preview flags

src/views/product-downloads-view/components/downloads-section/index.tsx
Updates the downloads view template `Changelog` link to point to specific release URLs, at which we expect to see changelog notes for that release. Previously the `Changelog` link pointed to a markdown file in the commit associated with the release tag.
- For any given version, there should be a `Changelog` link
- The `Changelog` link should link out to the GitHub release page, for example 
- Note: testing other products as well would be much appreciated!
> **Note**: We've validated that all products most often have some kind of changelog-equivalent content on every release. Part of the rational for this change is that release notes are relatively trivial to make changes to, at least compared to updating the contents of a markdown file …
=> chore: link to release changelog from downloads

src/views/open-api-docs-view/components/open-api-overview/open-api-overview.module.css
Refines responsive styling for the overview section of `OpenApiDocsView`
🎨 [Figma][figma]
https://github.com/hashicorp/dev-portal/assets/4624598/77b7c98f-bdb0-45c6-9292-dfb84c357ce9
https://github.com/hashicorp/dev-portal/assets/4624598/9a2b5cc5-1122-41c8-98dc-8c8ee5aec70e
- The mobile appearance should match [designs][figma], hiding the icon on small viewports, and stacking the "release stage" badge (eg `Preview`) above the page heading
[task]: https://app.asana.com/0/1204678746647847/1205278197175200/f
[preview]: https://dev-portal-git-zsopenapi-overview-responsive-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: https://dev-portal-git-zsopenapi-overview-responsive-hashicorp.vercel.app/hcp/api-docs/vault-secrets …
=> feat: responsive styling for OpenAPI docs view header

src/components/badge/index.tsx, src/views/open-api-docs-view/components/operation-details/index.tsx, src/views/open-api-docs-view/utils/get-response-data.ts
Updates response data headings on `OpenApiDocsView` to use coloured badges, themed based on success and error response codes.
| - | - |
| ![before-light](https://github.com/hashicorp/dev-portal/assets/4624598/6ed00274-f677-481d-9d12-05429c6a3942) | ![after-light](https://github.com/hashicorp/dev-portal/assets/4624598/64824cf2-32e4-443c-ab0d-a04e2feb418e) |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/d55dfbe0-8450-4166-a031-c74c2d88cdd2) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/b8e26731-1057-4810-98b3-b4906f810d65) |
- Badges should have a theme, with successful response headings in `success`-coloured badges, and error response headings in `critical`-coloured badges.
Not …
=> feat: themed badges for openapi response headings

src/views/open-api-docs-view/components/operation-sections/operation-sections.module.css
Hides operation path code blocks in `OpenApiDocsView` when the layout of each operation changes to one column.
| - | - |
| ![768-before](https://github.com/hashicorp/dev-portal/assets/4624598/8fefaed7-b670-4f07-a8fc-af64f6e32aa6) | ![768-after](https://github.com/hashicorp/dev-portal/assets/4624598/e52075ec-b4e0-4c2c-95cc-40ea3c058123) |
| ![1024-before](https://github.com/hashicorp/dev-portal/assets/4624598/661342f7-ee6a-44d9-a31f-b442d3aa6ac4) | ![1024-after](https://github.com/hashicorp/dev-portal/assets/4624598/c9b23cbe-c6e1-45cf-a467-e6ceed8b7caf) |
- When the layout of each operation changes to one-column, the code block should be hidden
[task]: …
=> fix(open-api): hide code path on small viewports

src/views/open-api-docs-view/utils/get-operation-props.ts, src/views/open-api-docs-view/utils/get-property-detail-props.ts
In OpenAPI view, modifies all `#anchor-link` slug values so that they're truer to source, namely by retaining original casing.
- All operation anchor links should now more closely match their operation IDs, like `#mySpecialOperation` rather than `#my-special-operation`
- Similarly, all nested parameter slugs should more closely match their keys
- With the above changes, all slugs should remain unique (not necessarily something easy to test in browser, probably better to assert this through code review, but clicking around a bunch would probably add some confidence)
[task]: https://app.asana.com/0/1204678746647847/1205367854380355/f
[preview]: https://dev-portal-git-zsopenapi-anchors-match-source-hashicorp.vercel.app/ …
=> chore(openapi): mod slugs to match source

jest.config.ts, package-lock.json, package.json
This introduces https://next-auth.js.org/getting-started/client#updating-the-session
`next-auth` diff https://github.com/nextauthjs/next-auth/compare/next-auth%404.19.2...next-auth%404.23.1
This is in support of #2128 
https://dev-portal-git-kwupgrade-next-auth-hashicorp.vercel.app/
If observing `https` being used in local dev, ensure `process.env.VERCEL` is not set.
- https://github.com/nextauthjs/next-auth/issues/7510
---
- https://app.asana.com/0/0/1205367031875887
=> chore: `next-auth` 4.23.1

src/views/open-api-docs-view/utils/get-operation-props.ts, src/views/open-api-docs-view/utils/get-url-path-code-html.ts
This PR fixes an issue in OpenApiDocsView where copied URL paths would contain additional space characters.
- When copied, URL paths should not contain any additional characters. Upstream, copied URL paths contained zero-width-space characters.
- URL paths should now all start with the `host` value [defined in the HCP Vault Secrets spec](https://github.com/hashicorp/hcp-specs/blob/274566639360a420515acf61961479461ae51790/specs/cloud-vault-secrets/preview/2023-06-13/hcp.swagger.json#L13), which is `api.cloud.hashicorp.com`. Note that we assume HTTPS as the protocol for connecting to the host.
[preview]: https://dev-portal-git-zsopenapi-url-path-tweaks-hashicorp.vercel.app/
[task]: …
=> fix(openapi): avoid extra line-break chars in copied code

src/views/open-api-docs-view/components/open-api-overview/index.tsx, src/views/open-api-docs-view/components/open-api-overview/open-api-overview.module.css, src/views/open-api-docs-view/index.tsx, src/views/open-api-docs-view/server.ts, src/views/open-api-docs-view/types.ts, src/views/open-api-docs-view/utils/get-nav-items.ts
Adds an `#overview` anchor link to the OpenAPI docs view sidebar, to make it easier for visitors to jump to the top of the page.
- The first link in the sidebar should now lead to and `#overview` anchor link
- The `#overview` anchor link should jump to the top of the page
- The "active state" on this link should now change when `activeSection` changes, such that only one sidebar link is ever highlighted at one time.
[task]: https://app.asana.com/0/1204678746647847/1205211659139665/f
[preview]: https://dev-portal-git-zsopenapi-overview-link-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: https://dev-portal-git-zsopenapi-overview-link-hashicorp.vercel.app/hcp/api-docs/vault-secrets
=> chore(openapi): update sidebar overview link to be anchor

src/views/open-api-docs-view/server.ts
> Asana task 🎟️ - Not Applicable
Fixes an issue where product repo deploy previews of the site would break.
- **Root cause**: a `GITHUB_TOKEN` is required to build `/hcp/api-docs/vault-secrets` (and also views like `/hcp/api-docs/packer` that source from closed repositories). This environment variable is not set in product repo contexts.
- **Context**: other pages, like `/hcp/api-docs/packer`, skip static rendering completely, which is why this issue has not surfaced for those pages.
- **Proposed solution**: avoid building `/hcp/api-docs/vault-secrets` in product repo deploy previews, this avoids the issue. The one caveat is that page will error and not function in product repo deploy previews, but this is currently not something we're worried about, I think …
=> fix(open-api-docs): patch product repo deploy issues

build-libs/redirects.js
Tweak redirects loading to allow redirects to be loaded from closed repositories, and adds configuration to load redirects from the `hashicorp/ptfe-releases` repo.
Redirects should load from `ptfe-releases`, but _only_ once the `redirects.js` file exists in a `ref` known to our content API. To fake this in order to test that redirects will work once released, clone this PR's branch down, and in `getRedirectsFromContentRepo`, force the ref `main` for `ptfe-releases` rather than the latest ref known by our content API:
```js
// const latestContentRef = await getLatestContentRefForProduct(repoName)
const latestContentRef =
repoName === 'ptfe-releases'
? 'refs/heads/main'
: await getLatestContentRefForProduct(repoName)
```
Redirects should …
=> feat: load redirects from ptfe-releases

src/components/feedback-form/components/question/index.tsx, src/components/feedback-form/types.ts
Allow `placeholder` to be customizable on feedback form
This is in service of #2128
=> chore(feedback-form): customize placeholder

src/views/api-docs-view/server/get-api-docs-static-props/index.ts, src/views/api-docs-view/types.ts, src/views/open-api-docs-view/server.ts, src/views/open-api-docs-view/types.ts
Fixes an issue where `OpenApiDocsView` pages did not have a custom `metadata.title`, resulting in the generic product name being used for the page title.
This PR also fixes an identical issue in the previous `ApiDocsView` template.
- fix(openapi): add page title for OpenApiDocsView
- fix(api-docs-view): add page title for ApiDocsView
| Note | Screenshot |
| - | - |
| vault-secrets-before | <img width="1734" alt="vault-secrets-before" src="https://github.com/hashicorp/dev-portal/assets/4624598/b36c24c4-a61a-4a96-a301-26152311f930"> |
| vault-secrets-after | <img width="1735" alt="vault-secrets-after" src="https://github.com/hashicorp/dev-portal/assets/4624598/0b805c53-e08d-439d-bda6-4914b3fa7c1b"> |
| boundary-before | <img width="1730" …
=> fix(openapi): fix missing page title

src/pages/hcp/api-docs/vault-secrets/[[...page]].tsx, src/views/open-api-docs-view/components/open-api-overview/index.tsx, src/views/open-api-docs-view/index.tsx, src/views/open-api-docs-view/server.ts, src/views/open-api-docs-view/types.ts
In `OpenApiDocsView`, this PR makes the icon shown next to the OpenAPI spec title name configurable, rather than being fixed to the `VaultIcon`.
As we onboard new products to the revised `OpenApiDocsView`, we need to be able to show icons other than the Vault icon.
- Adds an optional `serviceProductSlug` option to `OpenApiDocsView` `PageConfig`
- Falls back to the existing required `productSlug` configuration option
- Uses `ProductIcon` rather than `IconVaultColor16` in `OpenApiOverview`, passing the provided `serviceProductSlug` to drive which icon is shown.
No design changes, appearance should be identical to upstream.
- The icon next to the page title should appear as it does upstream, showing the `Vault` icon
- When previewing any …
=> feat(openapi): support dynamic API service icon

src/lib/api-docs/fetch-cloud-api-version-data/index.ts, src/lib/api-docs/types.ts, src/pages/boundary/api-docs/[[...page]].tsx, src/pages/hcp/api-docs/vault-secrets/[[...page]].tsx, src/pages/waypoint/api-docs/[[...page]].tsx, src/views/api-docs-view/components/api-docs-version-alert/types.ts, src/views/api-docs-view/server/get-api-docs-static-paths/fetch-api-docs-paths.ts, src/views/api-docs-view/server/get-api-docs-static-paths/index.ts, src/views/api-docs-view/server/get-api-docs-static-props/index.ts, src/views/api-docs-view/server/get-api-docs-static-props/utils/build-schema-props.ts, src/views/api-docs-view/server/get-api-docs-static-props/utils/build-version-switcher-data.ts, src/views/api-docs-view/types.ts, src/views/open-api-docs-view/server.ts, src/views/open-api-docs-view/types.ts, src/views/open-api-docs-view/utils/find-default-version.ts, src/views/open-api-docs-view/utils/sort-date-version-data.ts
This PR cleans up duplicate `ApiDocsVersionData` type interfaces.
It also finishes a partially started rename from a previous term `targetFile` to a new term `sourceFile`, for clarity and consistency in the consolidated `ApiDocsVersionData` interface.
> [!NOTE]
> Changes are under-the-hood developer experience and maintenance improvements. The pages highlighted below are those most likely to have unexpected issues, but if the work in this PR was done right, they should be _identical_ to their upstream counterparts.
[task]: https://app.asana.com/0/1204678746647847/1205587914766423/f
[preview]: https://dev-portal-git-zsfix-duplicate-api-version-types-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: …
=> chore(openapi): fix up duplicate VersionData types

src/components/command-bar/commands/chat/index.tsx, src/views/profile/account-view/index.tsx
- [Preview link](https://dev-portal-git-kssmall-a11y-fixes-hashicorp.vercel.app/profile/account) 🔎
Use `InlineLink` instead of plain `a` so that the link indication doesn't rely on color only. Also the aria label for the command bar header is aligned with the visible label. 
See issues outlined[ in this document.](https://docs.google.com/document/d/17VH69KP2TFNDkC7MEdP8-wUnec4UtcXfMUlCPX7eE6Y/edit#heading=h.38vj98htf15t)
- Sign in to the preview (with your HCP id added to accept list on edge config)
- Go to https://dev-portal-git-kssmall-a11y-fixes-hashicorp.vercel.app/profile/account
- You should see 'HCP Account Settings' link with an underline
- Use voice over or look in DOM to confirm that the aria-label for back icon in the command bar header says 'Return to …
=> a11y: use inline link instead of plain anchor element

src/data/alert-banner.json
- [Preview link](https://dev-portal-git-nq-update-alert-banner-2023-close-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1205709435086907/f) 🎟️
This PR updates the alert banner to signal the availability of virtual session recordings on the HashiConf event platform.
> [!Important]
> This PR should not merge until Oct 12 at 6pm PT (9pm ET) at the earliest.
Events team request
=> chore: Highlight HashiConf virtual session recordings in banner

src/pages/hcp/api-docs/consul/[[...page]].tsx
- [Preview link](https://dev-portal-git-ksmanually-filter-consul-api-version-hashicorp.vercel.app/) 🔎
- [Asana ticket](https://app.asana.com/0/1202097197789424/1205798063280001) 🎟️ 
Manually filters out this version until we support configuration in the spec to filter out a spec file from publishing as per request in slack.
- [Visit the preview ](https://dev-portal-git-ksmanually-filter-consul-api-version-hashicorp.vercel.app/hcp/api-docs/consul)
- Validate that 2-15-2022 isn't an available version. There should be no version selector visible as we only have the single version [spec from 10-10-23](https://github.com/hashicorp/hcp-specs/tree/main/specs/cloud-global-network-manager-service/preview/2023-10-10)
We should support config based option for authors to not publish a spec version.
=> chore: don't publish consul api docs from 2-15

Dockerfile
The docker build image workflow [has been failing ](https://github.com/hashicorp/dev-portal/actions/runs/6658627905/job/18095903036)at `npm install`. I was able to repro the same `errno ECONNRESET` error locally during `npm install` without changing anything in the file.
I think the docker image build was failing because it was installing the latest version of npm (10) yet still using node 18. When I ran this locally after pinning, `docker build -t dev-portal:local .` the build succeeded. 
It's a weird error so definitely open to input if there's other things I should try! 😅
=> fix: pin node & npm version in dockerfile

src/lib/learn-client/api/api-types.ts, src/lib/learn-client/api/collection/formatting.ts, src/lib/learn-client/types.ts, src/views/tutorial-view/index.tsx, src/views/tutorial-view/server.ts
- [Asana task](https://app.asana.com/0/1204810520737800/1205154011279146/f) 🎟️
- [`learn-api-content-sync`](https://github.com/hashicorp/learn-api-content-sync/pull/88)
- [`learn-api`](https://github.com/hashicorp/learn-api/pull/187)
If `next_collection` is defined on a `collection`, the frontend will use this to override the default behaviour for the Next / Previous button. If a next_collection is not passed provided, the next logical collection in the sidebar will be used (current behavior).
Add support for authors to supply a custom href for the 'Next collection' button. This will be optional and will be defined in the [collection files](https://github.com/hashicorp/tutorials/blob/main/content/collections/boundary/credential-management.yml) in the tutorials repo as a plain string.
=> enable custom next collection slugs in dev portal

src/components/breadcrumb-bar/breadcrumb-bar.module.css, src/components/breadcrumb-bar/index.tsx, src/views/product-downloads-view/helpers.ts, src/views/product-downloads-view/index.tsx
- Project brief [here](https://docs.google.com/document/d/12YmA6vo3eO6RpK0xfY8ARk-WR1jGxzq1aDDS5Viq2-c/edit#heading=h.p2a9c84bi0uv)
- [Asana project](https://app.asana.com/0/1204817897905865/1205117623326498)
- [Asana task](https://app.asana.com/0/1204817897905865/1205712837415356/f) 
- Removed `selectedVersion` from `initializeBreadcrumbLinks()` as it is no longer needed
- Added `useRouter()` in `product-downloads-view` to access the `pathname` to handle the VMware Utility breadcrumb edge case detailed below.
- A couple edge cases discovered during this task:
- Breadcrumb links on Enterprise install:
- current: `Developer / [product] / Install [product] Enterprise`
- new: `Developer / [product] / Install Enterprise`
- Vagrant VMware Utility:
- current: `Developer / Vagrant / Install …
=> Remove version from breadcrumb on product install page

src/components/version-context-switcher/index.tsx
- [Preview link](https://dev-portal-git-ksfix-tf-order-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202801212949828/1205921409065634/f) 🎟️
This logic was removed in #2217 ([see comment](https://github.com/hashicorp/dev-portal/pull/2217#discussion_r1382281828)) but caused the [terraform version on the install page](https://developer.hashicorp.com/terraform/install) to not be sorted properly. This is just a patch to fix the issue and we can readjust. 
**Preview**
**Upstream**
Validate that the version order on the [tf install page](https://dev-portal-git-ksfix-tf-order-hashicorp.vercel.app/terraform/install) is correct (latest first), [compared to production](https://developer.hashicorp.com/terraform/install).
=> patch: fix up terraform version selector sort

src/pages/consul/install/consul-downloads.module.css, src/pages/consul/install/index.tsx, src/views/product-downloads-view/components/release-information/index.tsx, src/views/product-downloads-view/components/release-information/release-information.module.css
- Link to [Slack thread](https://hashicorp.slack.com/archives/C011HP57U0Y/p1700247868763509) discussing changes to copy in ARM note
- [Consul install preview link](https://dev-portal-git-heat-featrelease-info-consul-hashicorp.vercel.app/consul/install) 🔎
- [Asana task](https://app.asana.com/0/1204817897905865/1205911880806870/f) 🎟️
- [Figma](https://figmashort.link/Sr42JA)
- Moved note for ARM users to Release information section
- Changed `<code>` blocks to `<CodeBlock>` so it can be copied
- Necessary install page enhancement for Consul
- Navigate to [/consul/install](https://dev-portal-git-heat-featrelease-info-consul-hashicorp.vercel.app/consul/install) and see the note for ARM users has moved
- Navigate to [/consul/install/enterprise](https://dev-portal-git-heat-featrelease-info-consu …
=> Install page enhancement: Release Information - command + code block (Consul only)

src/pages/consul/install/enterprise.tsx, src/views/product-downloads-view/boundary/components/desktop-client-callout/desktop-client-callout.module.css, src/views/product-downloads-view/boundary/components/desktop-client-callout/index.tsx, src/views/product-downloads-view/boundary/index.tsx, src/views/product-downloads-view/components/card-with-link/card-with-link.module.css, src/views/product-downloads-view/components/card-with-link/index.tsx, src/views/product-downloads-view/components/downloads-section/downloads-section.module.css, src/views/product-downloads-view/components/downloads-section/index.tsx, src/views/product-downloads-view/components/downloads-section/types.ts, src/views/product-downloads-view/components/release-information/index.tsx, src/views/product-downloads-view/components/release-information/release-information.module.css, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/types.ts
- [Preview link](https://dev-portal-git-heat-featinstallos-cards-hashicorp.vercel.app/vault/install) 🔎
- [Asana task](https://app.asana.com/0/1204817897905865/1205911880806862/f) 🎟️
- [Figma](https://www.figma.com/file/308QXXjFalJSFaCvmFU50L/Install%2FDownload-Template?type=design&node-id=926-11525&mode=design&t=dxobrdCfnqNtkqsw-0)
- Move OS download content from tabs to individual cards per Figma mocks
- Added a `'middle'` option for the merchandising slot.
- This allows for Boundary Desktop Client to be passed as the `merchandisingSlot` in `/pages/boundary/install`
- Navigate to current [Vault install page](https://developer.hashicorp.com/vault/install) and see the changes
- Navigate to the [Vault install preview page](https://dev-portal-git-heat-featinstallos-cards-hashicorp.vercel.app/ …
=> Install page enhancement: Move OS downloads from tabs to individual cards

src/views/product-downloads-view/components/featured-learn-cards-section/featured-learn-cards-section.module.css, src/views/product-downloads-view/components/featured-learn-cards-section/index.tsx, src/views/product-downloads-view/index.tsx, src/views/product-downloads-view/product-downloads-view.module.css
- [Figma](https://www.figma.com/file/308QXXjFalJSFaCvmFU50L/Install%2FDownload-Template?type=design&node-id=705-20983)
- [Preview link](https://dev-portal-git-heat-bug-fixnext-steps-hashicorp.vercel.app/consul/install) 🔎
- Moved "Next steps" heading to parent component for featured tutorial and collections.
- Added logic to show the "Next steps" heading if the install page has a featured tutorial or featured collections (this is to hide the section hiding on the Vagrant install page because it has neither featured content blocks)
- Missed this case while completing the work in previous [PR](https://github.com/hashicorp/dev-portal/pull/2243)
- Navigate to [Consul install page](https://dev-portal-git-heat-bug-fixnext-steps-hashicorp.vercel.app/consul/install). There should only be one "Next …
=> bug fix: Consul install has two next steps headings

next.config.js, src/components/navigation-header/components/product-page-content/utils/get-nav-items.ts, src/components/sidebar/helpers/generate-product-landing-nav-items.ts, src/components/sidebar/helpers/generate-resources-nav-items.ts, src/content/sentinel/product-landing.json, src/views/product-landing/helpers/get-icon-cards.tsx
> **Note**: this PR affects the `/sentinel` page, which is not yet published to production, as for now, we're continuing to serve the Sentinel docs content from https://docs.hashicorp.com. We remove the page with the `remove-inactive-product-pages` script, and this PR does not touch that script.
Removes `Tutorials` links from the spiked `/sentinel` landing page.
Sentinel does not currently have tutorials content. `Tutorials` links and pages need to be omitted from the Sentinel product landing pages during migration.
- Avoids automatic addition of "Tutorials" links in various "generate items" type code
- Note this doesn't necessarily feel ideal, we might prefer to author content rather than "generate" it to avoid such conditionals. …
=> chore: remove tutorials from sentinel spike

config/base.json, src/views/tutorial-library/constants.ts
Removes redundant configuration for search indices.
Since we've shipped [dev-portal#2037 - chore: update tutorials library to use unified index](https://github.com/hashicorp/dev-portal/pull/2037), we're now using the unified `<env>_DEVDOT_omni` indices across Algolia search use cases on Dev Dot, including the Tutorials library.
Using a single configuration value for our search index feels like it can reduce the chance of misconfiguration and reduce complexity as we iterate on search-related features.
[task]: https://app.asana.com/0/1202097197789424/1204964938948006/f
[preview]: https://dev-portal-git-zsrm-duplicate-index-config-hashicorp.vercel.app/
[/tutorials/library]: https://dev-portal-git-zsrm-duplicate-index-config-hashicorp.vercel. …
=> chore: remove duplicate search index config

src/pages/validated-designs/[...slug]/index.tsx, src/views/validated-designs/server.ts
Bug Fix for the issue of [breaking content preview/vercel builds for other teams.](https://hashicorp.slack.com/archives/C058H0MULTE/p1701812997016709)
Due to HVD docs being built during Static Site Generation, i.e. build time, we expected the HVD docs directory to exist. If the provided env variable GITHUB_TOKEN does not have access to the repo then the directory cannot be built. This code makes it so that any HVD pages will return 404 if the HVD docs directory cannot be found.
Locally edit [HVD_CONTENT_DIR](https://github.com/hashicorp/dev-portal/blob/b59f2dbe6b0da9dc1fb98b1bf126cb9182ac2155/src/views/validated-designs/server.ts#L41) to be something nonsensical, like '/test' and then build. HVD pages shouldn't cause a build to fail, but rather return a 404. e.g.
* /validated-designs
* …
=> Harden SSG for when HVD docs do not exist

src/data/alert-banner.json
Re-enables the previously live alert banner promoting signups for the private beta. I set the expiry date of Dec 22 since most of us will be out for the holiday break.
=> Enable AI alert banner

config/preview.json
Updates the `preview.json` configuration so that all preview deployments use the `staging_DEVDOT_omni` Algolia index.
To better test changes to our search index, specifically for migrating Sentinel content to `developer.hashicorp.com`.
For context, we want to use our staging preview deployment at https://developer.hashicorp.services to stage the Sentinel migration. Using the `staging_DEVDOT_omni` search index for preview deployments will enable more realistic staging.
| - | - |
| ![staging-search-before](https://github.com/hashicorp/dev-portal/assets/4624598/e05a6efc-5deb-445e-bdc3-0abe052d5e90) | ![staging-search-after](https://github.com/hashicorp/dev-portal/assets/4624598/138ba42b-68df-4fca-ae37-93b76436dbee) |
- …
=> feat: use staging Algolia index for previews

src/components/open-api-sidebar-contents/utils/filter-by-title.ts, src/components/sidebar/components/sidebar-nav-highlight-item/index.tsx, src/components/sidebar/components/sidebar-nav-menu-item/index.tsx, src/components/sidebar/helpers/generate-install-view-nav-items.ts
- [Preview link](https://dev-portal-git-heat-fast-followtoc-install-page-link-hashicorp.vercel.app/terraform/install) 🔎
- [Asana task](https://app.asana.com/0/1204817897905865/1206108514969228/f) 🎟️
- Removed link from SidebarHeading in sidebar for install page
- It links to the install page, which the user is currently on.
- Changed the props being passed to include `heading, theme, isActive` rather than `title, fullPath, theme`
- Go to [preview Terraform install page](https://dev-portal-git-heat-fast-followtoc-install-page-link-hashicorp.vercel.app/terraform/install) and click on this element in the TOC sidebar. It should not be a link.
- Go to prod Terraform install [page](https://developer.hashicorp.com/terraform/install) where the preview sidebar should match prod.
=> Install page TOC: Remove link from SidebarHeading

src/views/product-downloads-view/index.tsx
Fixes an issue where install pages that did not define the optional `sidebarMenuItems` would break.
In particular, the install page for Sentinel has undefined `sidebarMenuItems`, so is currently not working as expected in our staging environment - see https://developer.hashicorp.services/sentinel/install.
| - | - |
| ![sentinel-install-before](https://github.com/hashicorp/dev-portal/assets/4624598/f892bd66-abb4-4936-828d-69e36239e71c) | ![sentinel-install-after](https://github.com/hashicorp/dev-portal/assets/4624598/ba54bfa6-cb6c-4731-ba8f-83da9e5f6307) |
- The page should load as expected, without errors
- Compare to [upstream][upstream/sentinel/install], where the page errors immediately after load …
=> fix: allow empty sidebarItems on install pages

src/content/sentinel/product-landing.json, src/views/product-landing/components/hero-heading-visual/index.tsx
Updates the gradient and asset used in the hero heading for the [Sentinel landing page][/sentinel].
| [Before][upstream/sentinel] | [After][/sentinel] |
| - | - |
| ![sentinel-header-before](https://github.com/hashicorp/dev-portal/assets/4624598/e56d4f14-8bb9-497d-9ac9-513c530d06ff) | ![sentinel-header-after](https://github.com/hashicorp/dev-portal/assets/4624598/1cd2d6cf-9377-475f-a891-2ac8b0693c21)  |
- The asset shown in the header area should be updated as expected
- The header bar should show a blue-ish gradient, rather than default neutral gradient shown [upstream][upstream/sentinel]
[task]: https://app.asana.com/0/1204759533834554/1206143599875578/f
[preview]: …
=> chore: update sentinel header

src/content/sentinel/product-landing.json, src/views/product-landing/components/overview-cta/index.tsx, src/views/product-landing/components/overview-cta/overview-cta.module.css, src/views/product-landing/components/overview-cta/types.ts, src/views/product-landing/schema.ts
Removes a placeholder diagram image from the [Sentinel landing page][/sentinel].
We intend to add this diagram separately from the Sentinel migration. See 🎟 `🚧 TODO` for details.
- Adds support for omitting `overview.image` in `product-landing.json` content
- Updates the associated `OverviewCta` component to not require an `image`
- Removes the `overview.image` from Sentinel's `product-landing.json`
| [Before][upstream/sentinel] | [After][/sentinel] |
| - | - | 
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/807665ff-9057-46ed-8314-814e9efbf9bd) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/c8dd5e9b-61c6-441a-9c7e-9b4f74a50e2b) |
- The landing page image next to the `What is Sentinel?` section …
=> chore: rm Sentinel landing placeholder img

src/components/sidebar/index.tsx
- [Preview link](https://dev-portal-git-heatbugfix-tutorials-hashicorp.vercel.app/consul/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1202801212949828/1206206356889965/f) 🎟️
- Resources section of sidebar in product tutorials landing page wasn't present
- Missed this case when code was changed in sidebar refactor
- Added resources nav items to the case where the sidebar component is passed children
- Visit product tutorials preview [page](https://dev-portal-git-heatbugfix-tutorials-hashicorp.vercel.app/consul/tutorials). See that the resources section is now there
- Visit preview tutorial [page](https://dev-portal-git-heatbugfix-tutorials-hashicorp.vercel.app/consul/tutorials/get-started-hcp). See that the resources section is now there
- Visit preview install page and prod install …
=> Bug fix: resources section of nav in tutorials wasn't added

src/views/well-architected-framework/tutorial-view/index.tsx
- [Preview link](https://dev-portal-git-mwseo-fix-dupe-description-hashicorp.vercel.app/well-architected-framework/security/security-zero-trust-video) 🔎
- [Asana task](https://app.asana.com/0/0/1206199745721339/f) 🎟️
Prevent duplicate meta description tags.
One WAF page ([this one](https://developer.hashicorp.com/well-architected-framework/security/security-zero-trust-video)) was flagging in ahrefs.com as having duplicate `description` meta tags.
So digging in, I saw that all the existing WAF pages have duplicated `description` meta tags.
Replaced `HashiHead` with `next/head`
Weak answer, but I actually don't know. I do know that our `<HashiHead>` component needs some love and improvement at some point. 
I think there are some more systemic problems with `<HashiHead>`, but that's outside …
=> Tiny Wins: SEO: fix duplicated description tag

src/content/boundary/install-landing.json, src/content/boundary/product-landing.json
This PR is related to the refactoring of the boundary/oidc-auth tutorial into three separate tutorials, documented in this [Jira task](https://hashicorp.atlassian.net/browse/SPE-207?atlOrigin=eyJpIjoiYjM1ZTg5MThjZDMzNGE3M2EzNmFjNDRkMTllMGEwZGMiLCJwIjoiaiJ9).
- [Boundary install page Preview](https://dev-portal-git-rabboundary-oidc-refs-hashicorp.vercel.app/boundary/install) 
- [Boundary product landing Preview](https://dev-portal-git-rabboundary-oidc-refs-hashicorp.vercel.app/boundary) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-207?atlOrigin=eyJpIjoiYjM1ZTg5MThjZDMzNGE3M2EzNmFjNDRkMTllMGEwZGMiLCJwIjoiaiJ9) 🎟️
This PR removes references to the boundary/oidc-auth tutorial from the dev portal Boundary install and landing pages, which should allow the deploy preview for …
=> Remove boundary/oidc-auth product and install landing

build-libs/__tests__/redirects.test.ts, build-libs/docs-dot-hashicorp-redirects.js, build-libs/proxy-settings.js, build-libs/redirects.js, next.config.js
Adds redirects that divert traffic from `docs.hashicorp.com` to `developer.hashicorp.com`, but only once `proxySettings.sentinel` have been removed.
As soon as we launch Sentinel content on `developer.hashicorp.com`, we'll want to redirect traffic from the former `docs.hashicorp.com` domain. Since both domains are currently managed in the same Vercel project, it seems logical to put these redirects behind some sort of flag. We can then toggle the flag in order to complete the launch.
Our usual `config` flags don't seem suited to this use case, and we already have a kind of "flag" that captures proxied domain configuration in our `proxySettings`. So, this PR uses `proxySettings.sentinel` as the launch flag. To "toggle" it to launch, we'll …
=> chore: set up sentinel launch redirects

build-libs/docs-dot-hashicorp-redirects.js
Fixes an issue where not all `docs.hashicorp.com` redirects behaved as expected.
> **Note**: Using the staging domain `sentinel-launch-redirects-test.hashicorp.vercel.app`, as [configured in Vercel](https://vercel.com/hashicorp/dev-portal/settings/domains) to point to this PR's branch deployment.
- Note the "upstream" https://docs.hashicorp.com/sentinel does _not_ redirect at all. It renders a page, but this is not the correct behaviour, as we need the URL to be correct.
- Note the "upstream" https://docs.hashicorp.com/sentinel/docs redirects to https://developer.hashicorp.com/sentinel/docs/docs, which 404s
[task]: https://app.asana.com/0/1204759533834554/1206313101427625/f
[preview]: …
=> chore: add missing Sentinel redirects

src/content/hcp/docs-landing.json, src/content/hcp/product-landing.json, src/content/supported-icons.tsx
- [Preview link](https://dev-portal-git-rn-featupdate-vault-secrets-icon-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1205837019136532/1205837019136544/f) 🎟️
Update the Vault Secrets icon to our latest icon, given our icon refresh.
New Icon:
=> update vault secrets icon

src/views/validated-designs/guide/index.tsx, src/views/validated-designs/types.ts
- [Figma](https://www.figma.com/file/jS4ztJs2X6jspnHn7RjC7J/Developer-Components?type=design&node-id=24-7912&mode=design&t=Npo0KA1xG4ScQTmP-0)
- [Preview link](https://dev-portal-git-heat-chorehvd-sidebar-hashicorp.vercel.app/validated-designs/terraform-solution-design-guides-terraform-enterprise-fdo/introduction) 🔎
- [Asana task](https://app.asana.com/0/1202801212949828/1206186326415820/f) 🎟️
- Changed HVD Guide sidebar to use `<SidebarNavMenuItem>` instead of `<SidebarNavHighlightItem>`
- Added type `HvdPageMenuItem` to add the `isActive` property required for the current page/active styling to work.
Styling for HVD sidebar did not match the [current designs](https://www.figma.com/file/jS4ztJs2X6jspnHn7RjC7J/Developer-Components?type=design&node-id=24-7912&mode=design&t=Npo0KA1xG4ScQTmP- …
=> [chore]: Fix HVD guide sidebar styling

src/views/product-downloads-view/index.tsx
- [Preview link](https://dev-portal-git-heat-bug-fixinstall-top-nav-hashicorp.vercel.app/terraform/install) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1206351772603030/f) 🎟️
- Moved `setTableOfContents()` and `setState` outside of the `useEffect` hook.
- Wrapped `setTableOfContents()` in `useCallback`
- Broken site navigation from `/install` pages due to maximum callstack error
- Moved `setState` hook outside of the `useEffect()` hook.
- Visit [preview link](https://dev-portal-git-heat-bug-fixinstall-top-nav-hashicorp.vercel.app/terraform/install). Click on any link from the top nav, such as **Documentation > About the docs**
- Visit the Packer i[nstall page](https://dev-portal-git-heat-bug-fixinstall-top-nav-hashicorp.vercel.app/packer/install). The items under **Operating …
=> Fix maximum callstack exceeded error on install page

src/views/validated-designs/guide/index.tsx, src/views/validated-designs/server.ts
- [Preview link](https://dev-portal-git-rn-featfix-hvd-guide-styling-pass-1-hashicorp.vercel.app/validated-designs) 🔎
- [Asana task - HVD guide page QA & fixes](https://app.asana.com/0/1204908934882872/1205942535705313/f) 🎟️
First style pass as part of design review for HVD.
The product logo is now shown for the guide of the product, instead of the hashicorp logo
**Before:**
**After:**
- [Preview link](https://dev-portal-git-rn-featfix-hvd-guide-styling-pass-1-hashicorp.vercel.app/validated-designs) 🔎
=> HVD: Add product logo, and make TOC h2+ only

src/components/directional-link-box/index.tsx, src/components/directional-link-box/types.ts, src/views/validated-designs/guide/index.tsx, src/views/validated-designs/index.tsx
- [Preview link](https://dev-portal-git-rn-feathvd-focus-fix-and-typo-hashicorp.vercel.app/validated-designs) 🔎
- [Asana task - odd behavior "pre/next" active state holding](https://app.asana.com/0/home/1205890531436275/1206376499174139) 🎟️
* Fix type of Validated Designs not being plural
* Fix next and previous buttons refocusing after page transition
Next.js's Link will attempt to refocus itself after a page transition, in order to keep the user focused on what it believes to be the same content. (https://github.com/vercel/next.js/issues/49386) This makes sense for a menu buttons/links, but not for content buttons/links. Setting unique ids & keys convince's Next that this is now a new element.
=> Fix refocus on HVD next/prev buttons and title typo

src/components/outline-nav/components/outline-nav-with-active/index.tsx
- [Preview link](https://developer.hashicorp.services/validated-designs/vault-operating-guides-adoption/disaster-recovery-setup) 🔎
- [Asana task - sidecar not highlighting sections on scroll](https://app.asana.com/0/1205890531436279/1206376499174145/f) 🎟️
When visiting a page without any sections in the sidecar, and then moving back to a page with sections in the sidecar the sidecar sections fail to update. 
I believe this is due to Next caching elements, one of which has a ref on it.
Keep the ref around on by rendering the empty container div.
1. visit [Disaster Recovery Setup](https://developer.hashicorp.services/validated-designs/vault-operating-guides-adoption/disaster-recovery-setup) and scroll around and see the sidebar active item change
2. (in the same tab) click on **Vault …
=> Fix OutlineNavWithActive when items is 1 or less

src/views/validated-designs/guide/detail-view.module.css, src/views/validated-designs/guide/index.tsx
- [Preview link](https://dev-portal-git-heat-bugfixhvd-next-prev-bttn-mobile-hashicorp.vercel.app/validated-designs/terraform-operating-guides-adoption/introduction) 🔎
- [Asana task](https://app.asana.com/0/1204908934882872/1206467043753971/f) 🎟️
- Added media query for 50% width to apply only for tablet & up
- Added className to hide empty divs on mobile, which was adding space above single buttons (e.g. when there is only a Next button)
- UI bug that needs to be fixed
- Fixed width with media query by comparing with next/prev button in prod tutorials
1. Visit page with only a Next button [here](https://dev-portal-git-heat-bugfixhvd-next-prev-bttn-mobile-hashicorp.vercel.app/validated-designs/terraform-operating-guides-adoption/introduction)
1. The button **width** should match this …
=> [HVD] Fix mobile UI bug where next/prev buttons do not have a width of 100%

next-sitemap.config.js
- [Preview link](https://dev-portal-git-disallow-gptbot-on-hvd-hashicorp.vercel.app/) 🔎
- [Asana task - Ensure that HVD content is not being ingested by Developer AI](https://app.asana.com/0/1204908934882872/1206365592254052/f) 🎟️
We don't want HVD content to be crawled. Even though we have `noindex` on those pages [OpenAI is unclear if it even respects `noindex`](https://community.openai.com/t/does-openai-honor-noindex-and-robots-txt-when-scraping-for-training-data-how-does-it-deal-with-scraped-personal-data/133803), and [instead recommends disallowing it through robots.txt policies](https://platform.openai.com/docs/gptbot).
> User-agent: GPTBot
> Disallow: /validated-designs
=> Disallow gptbot on HVD pages

src/data/vault.json
Changing the way repository gpg sign keys are imported in Ubuntu.
The currently used apt-key command is deprecated and it's not considered best practices to import all keys in the trusted.db gpg keystore.
I used the same approach as here: https://github.com/hashicorp/dev-portal/blob/main/src/views/product-downloads-view/helpers.ts#L120
=> Removing apt-key as this method of importing the key is deprecated.

src/data/alert-banner.json
- [Preview link](https://dev-portal-git-heat-choreupdate-dev-ai-banner-expiry-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1206498827864755/f) 🎟️
- Changed expiry date to March 1st, 2024
- It expired on Feb 1st 2024
- Visit Dev Portal [homepage](https://dev-portal-git-heat-choreupdate-dev-ai-banner-expiry-hashicorp.vercel.app/). The sign-up banner should be visible as in the screenshot below
=> Update Dev AI sign-up banner expiry to March 1st 2024

jest.config.ts, scripts/docs-content-link-rewrites/helpers/fetch-nav-data-for-repo-and-base-path.ts, src/__tests__/e2e/docs-content-link-rewrites.spec.ts, src/__tests__/e2e/docs-landing-icon-card-links.spec.ts, src/__tests__/e2e/seo.spec.ts, src/lib/remark-plugins/rewrite-static-hvd-assets/index.ts, src/views/tutorial-view/components/next-previous/index.tsx, src/views/validated-designs/__tests__/server.ts, src/views/validated-designs/server.ts, tsconfig.json
Implement TS path aliases, which cleans up a few verbose and difficult to understand paths. Mainly helps with importing from files outside of our base directory, `/src`. (`scripts`, `build-libs`, `.test`, etc.)
Error message if multiple path aliasing are provided:
```
Error: Jest: Failed to parse the TypeScript config file /Users/ruben.nic/projects/dev-portal/jest.config.ts
Error: 
⚠️  Current typescript to jest path aliasing is limited to one path per alias.  ⚠️
Offending ts path aliases:
- [@test/*]: [../.test/*,../.test2/*]
```
1. Should build without errors and Tests should pass
=> Chore: Implement ts path alias

src/content/sentinel/product-landing.json
Fixes an incorrect link on the [/sentinel] landing page.
- The very last card, with the title `Sentinel Playground`, should link to https://play.sentinelproject.io/
[task]: https://app.asana.com/0/1204759533834554/1206321903608736/f
[preview]: https://dev-portal-git-zsfix-sentinel-playground-link-hashicorp.vercel.app/
[/sentinel]: https://dev-portal-git-zsfix-sentinel-playground-link-hashicorp.vercel.app/sentinel
=> chore: update link to Sentinel playground

src/components/docs-version-switcher/docs-version-switcher.test.tsx, src/components/docs-version-switcher/index.tsx
- [Preview link](https://dev-portal-git-heat-a11yterraform-cli-hashicorp.vercel.app/terraform/cli) 🔎
- [Asana task](https://app.asana.com/0/1205890709355230/1205890709355297/f) 🎟️
- Aria-label contains "Terraform" twice, which is an inconsistent experience for AT users.
`Choose a Terraform Terraform CLI version. Currently viewing v1.7.x (latest).`
- Added tests to ensure this doesn't happen again
1. Visit [preview link](https://dev-portal-git-heat-a11yterraform-cli-hashicorp.vercel.app/terraform/cli)
2. Inspect version dropdown
3. Aria-label should read `Choose a Terraform CLI version. Currently viewing v1.7.x (latest).`
nay
=> [TF VPAT A11Y] - /terraform/cli Inconsistent identification

src/components/mobile-menu-container/mobile-menu-container.module.css, src/layouts/base-layout/index.tsx
- [Preview link](https://dev-portal-git-heat-chorefix-mobile-banner-overlap-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203548570679724/f) 🎟️
- Removed `top` css property from mobile menu to allow the default of `top: auto` to be applied
- Fix UI bug where alert banner causes the header to overlap with the mobile menu, block sign in and sign up buttons
- Tried `position: relative` as suggested in the Asana task screenshot comment. This didn't work because it messed up the opening/closing animation
1. Visit preview link [here](https://dev-portal-git-heat-chorefix-mobile-banner-overlap-hashicorp.vercel.app/) (alert banner should be visible)
1. Shrink viewport to mobile
1. Open mobile menu
1. It should match this screenshot:
1. Visit …
=> chore: Fixed mobile menu overlap with site alertbanner

build-libs/redirects.js, src/views/docs-view/utils/product-url-adjusters.ts
Adds a redirect from [/sentinel/downloads] to [/sentinel/install]. This is necessary as Sentinel's content has not yet been updated with `developer.hashicorp.com` URLs.
This PR also fixes URLs using our existing product URL adjuster setup. This makes content-level corrections at build time, swapping any `/sentinel/downloads` links authored in our Sentinel content to become `/sentinel/install`.
- Compare to the upstream [/sentinel/downloads][prod/sentinel/downloads], which `404`s 
- For example, compare the URLs on [/sentinel/intro/getting-started/install] to [upstream][prod/sentinel/intro/getting-started/install]
[task]: https://app.asana.com/0/1204759533834554/1206321540168548/f
[preview]: …
=> chore: add redirect for /sentinel/downloads

src/components/mobile-menu-container/mobile-menu-container.module.css, src/layouts/base-layout/index.tsx
This reverts commit 7c35e7ae006123dde16f5ad5a95abb6c1d213539.
- navigation styling is broken, this PR reverts the commit that broke it while a better solution is figured out
1. Visit [this preview link](https://dev-portal-git-heat-fixnav-hashicorp.vercel.app/nomad)
1. Scroll down the page
1. The sidebar navigation on the left-hand side should stay fixed 
nay
=> Revert "chore: Fixed mobile menu overlap with site alert banner (#2318)"

src/views/docs-view/utils/product-url-adjusters.ts
- [Preview link](https://dev-portal-git-rn-bugfix-sentinel-install-link-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1205890531436279/1206567499591204/f) 🎟️
We had a special case of not rewriting /sentinel/docs/* links that were /sentinel/downloads links, and now we are extending that to /sentinel/install links as well.
=> Fix mdx /sentinel/install links

src/pages/_error.jsx
This is a quick fix to resolve the errors seen below:
A following PR will remove the other proxy-related items such as `layouts/_proxied-dot-io`
This [preview](https://dev-portal-4ukhhd7i5-hashicorp.vercel.app/waypoint/commands/v0.3.x/task-inspect?__vercel_draft=1) should not result in a 500 status compared to the [production](https://developer.hashicorp.com/waypoint/commands/v0.3.x/task-inspect) counterpart
=> hotfix: remove getProxiedProductSlug

build-libs/docs-dot-hashicorp-redirects.js
- [Asana task](https://app.asana.com/0/1204759533834554/1206602376424254/f) 🎟️
According to the network request log the stages of redirecting were:
1. `docs.hashicorp.com/sentinel/downloads`
2. `docs.hashicorp.com/sentinel/install`
3. `developer.hashicorp.com/sentinel/docs/install`
Since the source of the redirect was technically `sentinel/install`, it did not meet the negative lookahead condition we had set. This PR updates the redirect so that `sentinel/install` is not included when redirecting a path to `sentinel/docs/:path`. We are not sure why docs.hashicorp.com is not redirecting to developer.hashicorp.com immediately but this PR targets the process as it behaves today.
=> check sentinel docs downloads redirect

package-lock.json, package.json, src/content/hcp/docs-landing.json, src/content/supported-icons.tsx
- [Figma](https://www.figma.com/file/wK7R3TaPjnjQPkunh31GMn/Brand-identity-updates?type=design&node-id=1-503&mode=design&t=LRBtvjqPFn5MSoFq-0)
- [Preview link](https://dev-portal-git-heat-choreupdate-vault-radar-card-hashicorp.vercel.app/hcp/docs) 🔎
- [Asana task](https://app.asana.com/0/1205855506449349/1206365912448323/f) 🎟️
- Add the new Vault Radar logo
- Need to change the logo on the Vault Radar card on the HCP docs landing page from the Vault logo to the Vault Radar logo
- Updated `@hashicorp/flight-icons` packages to access the new Vault Radar logo
- Added Vault Radar icon to supported icons
- Visit the HCP docs [preview page](https://dev-portal-git-heat-choreupdate-vault-radar-card-hashicorp.vercel.app/hcp/docs)
- The logo for HCP Vault Radar should match the screenshot below: …
=> [chore] Add new Vault Radar icon to HCP docs

src/pages/waypoint/docs/[...page].tsx, src/views/docs-view/server.ts
- [Preview link](https://dev-portal-git-heat-choreremove-version-dropdown-hashicorp.vercel.app/waypoint/docs) 🔎
- [Asana task](https://app.asana.com/0/1206225787851796/1206697393359305/f) 🎟️
- Remove docs version switcher from Waypoint
- Part of Waypoint IA restructuring
1. Visit Waypoint docs landing [page](https://dev-portal-git-heat-choreremove-version-dropdown-hashicorp.vercel.app/waypoint/docs).
2. There should be no version switcher in heading like in [prod](https://developer.hashicorp.com/waypoint/docs)
##
1. Visit a specific docs [page](https://dev-portal-git-heat-choreremove-version-dropdown-hashicorp.vercel.app/waypoint/docs/upgrading/compatibility)
2. There should be no version switcher like there is in [prod](https://developer.hashicorp.com/waypoint/docs/upgrading/compatibility …
=> Remove docs versions switcher from Waypoint

src/components/sidebar/helpers/generate-resources-nav-items.ts
- [Preview link](https://dev-portal-git-heat-choreremove-github-link-wa-76488f-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/0/1206697393359304/f) 🎟️
- Remove GitHub link from resources section of sidebar nav
Part of Waypoint IA restructuring
1. Visit Waypoint landing [page](https://dev-portal-git-heat-choreremove-github-link-wa-76488f-hashicorp.vercel.app/waypoint). The GitHub link should not be in the "resources" section of the sidebar nav.
2. Visit Waypoint docs [page](https://dev-portal-git-heat-choreremove-github-link-wa-76488f-hashicorp.vercel.app/waypoint/docs). The GitHub link should not be in the "resources" section of the sidebar nav.
3. Visit specific docs [page](https://dev-portal-git-heat-choreremove-github-link-wa-76488f-hashicorp.vercel.app/waypoint …
=> Remove GH link from resources nav section for Waypoint

src/lib/integrations/generate-product-integration-library-sidebar-nav-data.ts
- [Preview link](https://dev-portal-git-heat-chorewaypoint-integrations-config-hashicorp.vercel.app/waypoint) 🔎
- [Failed deployment](https://vercel.com/hashicorp/dev-portal/7xMRp4LZYAVjdc1r17cZQoBehixg)
- [Failed prod deployments](https://vercel.com/hashicorp/dev-portal/deployments?environment=production)
- Add check for `product.integrationsConfig` so build doesn't error out
```
Error occurred prerendering page "/waypoint/integrations". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'sidebarLinks')
```
- To fix the failing builds. For some reason, this didn't cause a fail on the deployment, but only when deploying to production 🤷 (see screenshot section below)
=> [chore] Waypoint build error fix - add check for product.integrationsConfig

src/data/waypoint.json
Add integrations config back in to fix build error
- [Preview link](https://dev-portal-git-heat-chorefix-integration-confi-582ef6-hashicorp.vercel.app/waypoint)
- [Failed deployment](https://vercel.com/hashicorp/dev-portal/CdyFUDfo23AC9Ud9pHhJZQCufuDh)
- Just add it back in because I don't want to add logic that may cause a regression for a valid integration page
```
TypeError: Cannot read properties of undefined (reading 'description')
at p (/vercel/path0/.next/server/pages/[productSlug]/integrations.js:1:36313)
```
To fix the build error that won't quit
=> Add integrationsConfig back in to Waypoint data to fix build error

next.config.js
Bugsnag isn't used, so this PR removes the keys. The env vars aren't referenced in code anywhere else, so this should be all that is needed.
=> chore: remove bugsnag keys

config/production.json
- [Preview link](https://dev-portal-git-heat-bug-fixwaypoint-integrations-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/1206225787851796/1206707955223703/f) 🎟️
- Remove `waypoint` from `product_slugs_with_integrations` in production.json
- This was causing integrations to still show in nav, sidebar and landing page
- Visit [Waypoint landing page](https://dev-portal-git-heat-bug-fixwaypoint-integrations-hashicorp.vercel.app/waypoint). See that integrations is gone
nay
=> Remove Waypoint from integrations list in production.json

build-libs/integration-packer-redirects.js
Related issue: https://github.com/hashicorp/packer/issues/12873
The IPSW plugin was recently moved to integrations, and since we removed the old plugin system in Packer their docs were inaccessible.
This redirect should enable old-style plugin documentation links, and redirect them to the newly annointed documentation for IPSW.
=> build-libs: add redirect for ipsw packer plugin

config/base.json, config/preview.json, scripts/extract-hvd-content.ts
- [Preview link](https://dev-portal-git-rn-featnew-hvd-preview-on-services-hashicorp.vercel.app) 🔎
- [Asana task]() 🎟️ - None this is a fast PR/Change
We are adding a new config `enable_hvd_on_hvd_preview_branch` which downloads HVD content from the hvd repo `hvd-preview` branch and deploys it to `local preview` and `.staging`.
The HVD team wants a non-local website that they can use to test and share out internally upcoming versions of HVD content.
=> enable hvd-docs hvd-preview branch on .services

build-libs/redirects.js, src/views/product-root-docs-path-landing/server.ts
- [Preview link](https://dev-portal-git-heat-choreremove-waypoint-docs-sidebar-hashicorp.vercel.app/waypoint/docs) 
- [Asana task](https://app.asana.com/0/0/1206697393359303/f)
- Added a little bit of custom logic to remove `menuItems` from docs sidebar. The docs sidebar nav comes from the product repo; however, Waypoint has been archived so [this file](https://github.com/hashicorp/waypoint/blob/main/website/data/docs-nav-data.json) cannot be edited 
I also considered adding a request to check if the repo was archived or not, but decided against it as it would another request for a temporary change. The final decision for how to structure Waypoint & HCP Waypoint docs is TBD, and until it is, this is a intermediary change.
Part of the Waypoint restructuring IA
- Visit the [Waypoint docs …
=> Remove Waypoint docs side nav

src/views/docs-view/index.tsx
This PR replaces an instance of `next/router` with the equivalent version of `next/navigation`.
`next/router` does not expose the same values between App Router and Pages Router. As a way of slowly preparing the codebase to migrate to App Router, PRs like this will replace instances of `useRouter` with their new versions from `next/navigation`. This includes `usePathname` and `useSearchParams`. These PRs are intended to be small and easily testable; given the complexity of Dev Portal, we shouldn't try to replace all instances in one go.
This PR modifies a check in our Docs View that controls whether a no-index tag is rendered.
Replaced `const { pathname } = useRouter()` with …
=> feat: replace next/router with next/navigation in Docs View

src/lib/fetch-release-data.ts, src/views/docs-view/utils/get-latest-vagrant-vmware-version.ts, src/views/product-downloads-view/helpers.ts
This PR updates our code that processes releases from the ofificial HashiCorp Releases API to account for versions that have no builds.
Currently the "latest" (according to semver) release of Vault enterprise has a `builds` value set to `null`, which breaks code that expects `builds` to always be an array.
By checking both the `version` string and `builds` property to calculate the latest version as the latest version with builds according to semver.
=> fix: account for releases without builds

Dockerfile
- Preview link - **None no website changes** 🔎
- Asana task - **None dev chore** 🎟️
This PR updates our content-preview docker image in order to:
1. Fix a current build failure with our base image, `docker.mirror.hashicorp.services/node:18-alpine`, not existing
2. Moves us from using alpine to using debian as our base image distro
**Note: You will have to checkout this PR in order to build the correct docker image**
(The` -t -i` params allow the container to be exited through `Ctrl-C`)
=> Clean up docker file to modern standards

src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts, src/lib/learn-client/index.ts, src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-tutorial-links.test.ts, src/lib/remark-plugins/rewrite-tutorial-links/index.ts, src/lib/remark-plugins/rewrite-tutorial-links/utils/get-tutorial-map.ts, src/pages/api/tutorials-map.ts, src/views/docs-view/server.ts, src/views/docs-view/utils/get-root-docs-path-generation-functions.ts
This PR refactors the `getStaticProps` implementation for `docs-view` to only generate/fetch the tutorials map once. In a future PR, I'm going to explore if we even need to fetch the tutorials map to rewrite URLs anymore.
Prior to this PR, `getStaticProps` would generate/fetch the tutorials map multiple times, each taking ~2 seconds. This was because different steps of the implementation would fetch their own copy of the tutorials map independent of one another.
In this PR, we fetch the tutorials map once at the beginning of `getStaticProps`, and pass it into the remote content loader (for link rewrites) and again into the `prepareNavData` utility.
=> fix: only fetch tutorials map once

src/content/certifications/exam-faqs/terraform-associate-003.mdx
Added the delta between exams info back to the page; fixed some small typos
- [Preview link](https://dev-portal-git-certs_TFassoc_updates-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
User input from the Edu offsite prompted the change to make it easier  for 002 credential holders to study for recertification
=> TF Assoc 003: Added content differences table

src/pages/_app.tsx
Dials down our Vercel speed insights sample rate
Control overage spend a bit
Changed [sample rate prop](https://vercel.com/docs/speed-insights/package#samplerate)
=> Reduce speed insights sample rate

src/views/validated-designs/server.ts
- [Preview link](https://dev-portal-git-rn-chorehvd-code-highlighting-hashicorp.vercel.app/validated-designs/) 🔎
- Asana task - None Chore 🎟️
Add the same rehype code syntax highlighting we add to tutorials and api docs to HVD docs. Not all codeblocks for HVD have their language set, so this won't have a big effect at first.
| before | after |
|-|-|
| ![Screenshot 2024-04-15 at 11 45 33 AM](https://github.com/hashicorp/dev-portal/assets/1957315/e131e905-fe3d-417e-bf68-3b9dea7ef1f4) | ![Screenshot 2024-04-15 at 11 45 08 AM](https://github.com/hashicorp/dev-portal/assets/1957315/1b0be0a0-3840-48dc-a7d7-677e737068e1) |
=> Add rehype code highlighting to HVD docs

package-lock.json, package.json, src/pages/_app.tsx
This PR updates `next` to the latest version, `14.2.1`.
[Next.js 14.2](https://nextjs.org/blog/next-14-2#turbopack-for-development-release-candidate) comes with support for `next dev --turbo`, which offers improved performance for the development server. While we're not compatible with `--turbo` yet, updating to 14.2 before will make tracking down incompatibilities easier since 14.1 had a bunch of Turbopack issues.
Since this is a Next.js update, the best way to test is simply to click around on the site and make sure nothing looks broken.
=> chore(deps): update to next 14.2.1

src/views/validated-designs/__tests__/server.ts, src/views/validated-designs/index.tsx, src/views/validated-designs/server.ts, src/views/validated-designs/types.ts
- [Asana task - None small change](https://hashicorp.slack.com/archives/C05CCCMNUGN/p1712330353730979) 🎟️
Currently HVD guides must be a Hashicorp product name, this PR removes that requirement.
1. Checkout this branch
2. Start the project (so HVD downloads)
3. Run this script in this repos root directory to create a newly, non-product named HVD guide:
`cp -r src/.extracted/hashicorp-validated-designs/content/vault src/.extracted/hashicorp-validated-designs/content/integration-patterns`
=> Remove hvd guide name filter

src/components/link/index.tsx
- [Preview link](https://dev-portal-git-rn-fixproduct-nav-open-in-a11y-hashicorp.vercel.app/terraform) 🔎
- [Asana task](https://app.asana.com/0/1205890709355230/1205890709355241/f) 🎟️
Because of a bug, namely using += instead of = on a undefined variable, when setting `ariaDescribedBy` some information was not showing up in the accessibility tree. (In this case "opens in new window")
You can view an element accessible tree properties by following this screenshot:
=> Fix a bug when setting aria-describedby

src/views/validated-designs/guide/index.tsx
- [🔎 Preview link](https://dev-portal-git-rn-featadd-hvd-download-pdf-link-hashicorp.vercel.app/validated-designs)
- 🎟️ Asana task - None, small QOL fix
Adds a "Download as PDF" button to HVD pages. This button links to the PDF generated on the main branch of the HVD repo.
- [🔎 Preview link](https://dev-portal-git-rn-featadd-hvd-download-pdf-link-hashicorp.vercel.app/validated-designs)
=> Add hvd download PDF link

src/components/navigation-header/navigation-header.module.css
- [Preview link](https://dev-portal-git-rn-feata11y-login-menu-active-border-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1205890709355230/1205890709355281/f) 🎟️
Always show user menu border when open.
=> Always show border when active for user login menu

src/components/sidebar/components/sidebar-nav-menu-item/index.tsx
- [Preview link](https://dev-portal-git-rn-featfix-aria-controls-in-sidebar-hashicorp.vercel.app/hcp/docs/vault/what-is-hcp-vault/client) 🔎
- [Asana task](https://app.asana.com/0/1205890709355230/1206539228551239/f) 🎟️
Only show `aria-controls` when specific sidebar menu is open. (Because we hide the element that has that ID when the menu item is not opened.)
=> Only show aria-controls when specific sidebar menu is open

src/components/link/index.tsx
- [Preview link](https://dev-portal-git-rn-fixonly-set-aria-describedby-794e5c-hashicorp.vercel.app/hcp/docs/vault/what-is-hcp-vault/client) 🔎
- 🎟️ Asana task - None bug
When changing aria-describedby to fix an undefined error last week, we introduce a new bug where we are adding an empty aria-describedby to a bunch of elements. This PR fixes that.
On the
=> Default aria-describedby to null and only set when needed

src/content/tutorials-landing.json
- [Tutorials landing preview link](https://dev-portal-4mk385c2k-hashicorp.vercel.app/tutorials)🔎
- [SPE Jira task](https://hashicorp.atlassian.net/browse/SPE-780?atlOrigin=eyJpIjoiNTMyMDg1ZWQ3Mzc0NDgzN2JhMTNlZDJjMDk3N2RkNDQiLCJwIjoiaiJ9) 🎟️
This PR removes a missed boundary/oss-* tutorial link from the tutorials landing page.
Boundary is removing all references to `oss` in tutorial slugs and renaming them to `community`. This PR should be merged prior to [tutorials PR 2045](https://github.com/hashicorp/tutorials/pull/2045) to allow the vercel preview to build with the new dev-portal image.
These tutorials will be added back to the product, install, and tutorials landing pages after the tutorial renaming is complete.
I updated the following files to remove the boundary tutorial links:
- …
=> Tutorials: removes missed boundary/oss link from tutorials landing page

src/content/boundary/install-landing.json, src/content/boundary/product-landing.json, src/content/tutorials-landing.json
- [tutorials landing preview link](https://dev-portal-git-rab-boundary-add-community-links-hashicorp.vercel.app/tutorials)
- [Boundary landing preview link](https://dev-portal-git-rab-boundary-add-community-links-hashicorp.vercel.app/boundary)
- [Boundary install preview link](https://dev-portal-git-rab-boundary-add-community-links-hashicorp.vercel.app/boundary/install) 🔎
- [SPE Jira task](https://hashicorp.atlassian.net/browse/SPE-780?atlOrigin=eyJpIjoiNTMyMDg1ZWQ3Mzc0NDgzN2JhMTNlZDJjMDk3N2RkNDQiLCJwIjoiaiJ9) 🎟️
This PR adds the boundary/community-* tutorial links back to the Boundary product landing and install pages.
This PR follows up on [2432](https://github.com/hashicorp/dev-portal/pull/2432) and [2433](https://github.com/hashicorp/dev-portal/pull/2433) by adding back the boundary …
=> Rab boundary add community links

.github/workflows/auto-merge-staging.yml, .github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/close-stale-prs.yml, .github/workflows/docker_publish.yml, .github/workflows/docs-content-check-legacy-links-format.yml, .github/workflows/nextjs_bundle_analysis.yml, .github/workflows/playwright.yml, .github/workflows/register-preview-url.yml, .github/workflows/repo-sync.yml, package.json
Updates all GitHub Actions avoid Node 16, using versions approved based on security recommendations.
To start, I swiped all the work from #2335 - Thanks Heat! 🙌 
Then, referenced the `security-tsccr` repo to update all actions to their latest approved versions:
```sh
actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
bahmutov/npm-install@237ded403e6012a48281f4572eab0c8eafe55b3f # …
```
=> chore: update GitHub Actions workflows to node 20

.github/workflows/repo-sync.yml
Fixes up the `repo-sync` workflow so that our `dev-portal-internal` repo can resume syncing.
- Updates the workflow to align with more recent work in the workflow we originally copied
- Updates the PAT being used, as I think the previous one had expired
- Check out the results of a test of this modified action, at https://github.com/hashicorp/dev-portal-internal/pull/342/
- Note that since `repo-sync` hadn't been run in a while, that PR did require some manual merge conflict resolution. All the changes seemed like trivial content changes, so my approach was to default to whatever's on `dev-portal` `main`, and discard whatever conflicting changes were present in `dev-portal-internal` `main`.
[preview]: …
=> fix: update repo-sync script for dev-portal-internal

src/content/hcp/tutorials-sidebar.json, src/content/tutorials-landing.json
- [tutorials landing preview link](https://dev-portal-git-rab-boundary-remove-hcp-getting-started-hashicorp.vercel.app/tutorials) 🔎
- [HCP tutorials landing preview link](https://dev-portal-git-rab-boundary-remove-hcp-getting-started-hashicorp.vercel.app/hcp) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-754?atlOrigin=eyJpIjoiZTRkNDdjOWQ3MGFlNDRhZGJkZjBkODg4YmQ4OGU1NDIiLCJwIjoiaiJ9) 🎟️
This PR removes the boundary/hcp-getting-started collection links from the dev-portal tutorials/ landing page.
Boundary is renaming the `hcp-getting-started` collection to `get-started-hcp` to help improve SEO. This PR should be merged prior to [tutorials PR 2060](https://github.com/hashicorp/tutorials/pull/2060) to allow the vercel preview to build with the new dev-portal image.
The collection …
=> removes boundary/hcp-getting-started

build-libs/redirects.js
- [Asana task](https://app.asana.com/0/1206176289707208/1207325959967185/f)
- Add redirect for `redirect for waypoint/commands/:slug`
- those pages are no longer relevant to Waypoint documentation as the non-HCP version has been deprecated
- missed in original Waypoint deprecation work
1. Visit waypoint/commands/login in [production](https://developer.hashicorp.com/waypoint/commands/login)
1. See that it returns a 404 page
1. Visit waypoint/commands/login with [this preview link](https://dev-portal-git-heat-choreadd-waypoint-redirect-hashicorp.vercel.app/waypoint/commands/login)
1. You should be redirected to the [Waypoint GH repo commands directory](https://github.com/hashicorp/waypoint/tree/main/website/content/commands)
=> [chore] Add redirect for waypoint/commands/:slug

src/lib/syntax-highlighting/theme.ts
- [Preview link](https://dev-portal-git-dscode-block-shell-prefix-hashicorp.vercel.app/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress#explore-ingress-into-the-demo-application) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1207317287440394/f) 🎟️
This PR adds a specific selector to the `$` prefix in `shell-session` CodeBlocks to differentiate it from the surrounding text.
Our Shiki theme does not currently differentiate the prefix `$` in `shell-session` CodeBlocks, whereas previously Prism did.
Added a specific grammar selector that colors `punctuation.separator.prompt.shell-session` with `var(--hds-code-block-color-cyan)`.
- Go to [preview](https://dev-portal-git-dscode-block-shell-prefix-hashicorp.vercel.app/consul/tutorials/get-started-kubernetes/kubernetes-gs- …
=> feat: differentiate the $ prefix in shell-session

src/components/dev-dot-content/mdx-components/mdx-code-blocks/index.tsx, src/lib/rehype-code-plugins.ts
This PR updates our MDX CodeTabs component to correctly render language names and static names (when provided).
1. Add the expected `language-<language>` class to the `pre` element.
2. Override the generated heading when `tabs` is provided.
- Go to [preview](https://dev-portal-git-dscodeblock-tabs-static-hashicorp.vercel.app/consul/tutorials/implement-multi-tenancy/kubernetes-admin-partitions)
- Ensure that the first CodeTabs instance has tabs for "HTTPS" and "SSH".
- Ensure that the second CodeTabs instance (under the heading "Consul Enterprise values files") has tabs for "Server" and "Client".
- Go to [preview](https://dev-portal-git-dscodeblock-tabs-static-hashicorp.vercel.app …
=> fix: render correct codetabs names

src/views/open-api-docs-view/components/property-details/index.tsx, src/views/open-api-docs-view/components/property-details/property-details.module.css
Fixes an issue where some long descriptions in OpenAPI docs views would sometimes overlap into adjacent layout space.
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/d89c14e4-eeba-45d1-ae9b-1477e4d912a6) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/7b4aa63f-b028-4002-afb0-a0f9153132bb) |
- Confirm the issue exists, at smaller viewport widths, the descriptions for `Default error response` properties overflow into the sticky column
- Even at smaller viewport widths, the descriptions should be contained in their layout area
[task]: https://app.asana.com/0/799513369421962/1207309674701468/f
[preview]: …
=> fix(open-api-docs): fix overflowing descriptions

scripts/generate-tutorial-variant-map.ts, src/lib/integrations-api-client/standard-client.ts
This PR removes unnecessary usage of `@vercel/fetch`.
Something has happened on Vercel, resulting in HTTP requests made via `@vercel/fetch` to fail, with a `queryA ETIMEOUT`. `@vercel/fetch` was useful back in the Node v16 days, but now we have native global `fetch`, so we don't need to use it.
Currently two instances of `@vercel/fetch` were breaking builds. Those have been removed, and the respective logic now relies on the global `fetch` object instead of `@vercel/fetch`.
=> feat: use native fetch

src/views/tutorials-landing/img/play-custom.svg
Fixes an issue on [/tutorials] where an SVG icon is not displayed as expected.
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/dd401633-f8e3-4c8d-812d-165c5a161505) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/2296f74c-b9b4-456e-81c6-47b1d97b8572) |
[task]: https://app.asana.com/0/1206176289707208/1207349252120013/f
[preview]: https://dev-portal-git-zsfix-tutorial-landing-svg-hashicorp.vercel.app/
[/tutorials]: https://dev-portal-git-zsfix-tutorial-landing-svg-hashicorp.vercel.app/tutorials
=> fix: broken icon on tutorials landing

src/lib/rehype-code-plugins.ts, src/pages/style.css
This PR switches blank lines in our CodeBlocks to use a CSS pseudo element, which won't be copied when the user manually selects content to copy.
Due to the way we split lines, empty lines aren't properly retained. We need to manually insert those blank lines, which requires that we give them some content so they take up space. Previously, we used the `nbsp;` character, but this creates issues when code is copied and pasted, since some languages don't allow this specific character.
This PR switches the approach somewhat, by targeting empty lines via a specific CSS class. This class uses the `:after` pseudo element to render a space character, which isn't copied to the clipboard …
=> fix: prevent nbsp characters from being manually copied

src/components/dev-dot-content/mdx-components/mdx-code-blocks/index.tsx, src/lib/rehype-code-plugins.ts, src/lib/syntax-highlighting/index.ts, src/lib/syntax-highlighting/theme.ts
- [Preview link](https://dev-portal-git-rn-fixadd-diff-syntax-highlighting-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1205890531436279/1207516355156788/f) 🎟️
Adding syntax highlighting to diff code blocks.
=> Add diff syntax highlighting

src/components/tutorials-landing-view/certification-content-card-link/index.tsx, src/components/tutorials-landing-view/docs.mdx, src/components/tutorials-landing-view/types.ts, src/content/tutorials-landing.json, src/views/certifications/components/gradient-card/gradient-card.module.css, src/views/certifications/content/schemas/landing-page.ts, src/views/certifications/content/utils/program-slug-map.ts, src/views/certifications/views/[slug]/components/program-hero/index.tsx, src/views/certifications/views/[slug]/components/program-hero/program-hero.module.css
- [Preview link](https://vercel.live/link/dev-portal-git-preschoreupdate-hrefs-hashicorp.vercel.app?page=%2Ftutorials%3FvercelThreadId%3DJtNOO&via=in-app-copy-link) 🔎
- [Asana task](https://app.asana.com/0/1207484854701350/1207436782605801/f) 🎟️
This is PR is a follow up to https://github.com/hashicorp/dev-portal/pull/2472 
It gets rid of the references to `/networking-automation` in favor of the updated [`/security-automation`](https://dev-portal-git-preschoreupdate-hrefs-hashicorp.vercel.app/certifications/security-automation) page
See comments for more detailed notes on code changes
1. Open Preview Link
2. Navigate to `/tutorials`
3. Click on the Consul Certification Card
4. Verify that it correctly opens the page on the appropriate consul certification details header
These are just …
=> chore: Remove References to `networking-automation`

src/components/footer/index.tsx
- [Preview link](https://dev-portal-git-preschoreupdate-footer-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1207484854701350/1205890709355283/f) 🎟️
This Pull request: 
- Adds a link to our [Accessibility guidelines](https://www.hashicorp.com/trust/accessibility)
- Updates the security link to go directly to `https://www.hashicorp.com/trust/accessibility` instead of having to use the redirect
Per US and EU regulations, there should be specific documentation available on accessibility. 
Guidance: This is typically present in the form of an accessibility statement. See https://helios.hashicorp.design/about/accessibility-statement/ for an example. The W3C provides a template through WAI-ARIA: https://www.w3.org/WAI/planning/statements/generator/#create
(out of scope but it …
=> Chore: Update `Footer`

package-lock.json, package.json
[🔍 Preview](https://dev-portal-git-rn-fixconsent-modal-a11y-hashicorp.vercel.app/)
🎟️ Asana Tasks
- [[TF VPAT A11Y] Cookie manager modal does not respond to the ESC key](https://app.asana.com/0/1205890709355230/1205890709355251/f)
- [[TF VPAT A11Y] Cookie manager modal has multiple banner landmarks](https://app.asana.com/0/1205890709355230/1205890709355253/f)
- [[TF VPAT A11Y] Consent manager - Indistinguishable “see more” buttons](https://app.asana.com/0/1205890709355230/1205890709355259/f)
- [[TF VPAT A11Y] Switch toggles missing accessible name](https://app.asana.com/0/1205890709355230/1205890709355261/f)
- [[TF VPAT A11Y] Switches missing keyboard interactions](https://app.asana.com/0/1205890709355230/1205890709355249/f)
Pull in the new version of consent manager, which fixes a …
=> Update consent manager to include a11y fixes

src/pages/api/revalidate.ts
- Preview link - **None test locally** 🔎
- Asana task - **None chore task** 🎟️
Changes the revalidate api so that a list of paths that either successfully or failed to revalidated are returned, e.g.
```json
[
{
"status": "fulfilled",
"value": "/packer/docs/templates/hcl_templates/functions/string/trim"
},
{
"status": "fulfilled",
"value": "/packer/docs/templates/hcl_templates/functions/string/trimprefix"
},
]
```
1. checkout this branch locally and start up the project
2. hit the revalidate api 
(Make sure you have jq installed)
```
curl -X POST "http://localhost:3000/api/revalidate" \
-H "Content-Type: application/json" \
-d '{"product": "packer"}' | jq .
```
3. json of either successfully or failed to revalidated paths should be returned
=> Add logging to revalidate api

src/pages/api/revalidate.test.ts, src/pages/api/revalidate.ts
- [Asana](https://app.asana.com/0/1206176289707208/1207661736742262/f)
- Extracted logic to resolve product repo name to product slug into a function
- added check for `hcp-docs`
- Added tests for `resolveProduct` function
- This error comes up continuously and needs to be corrected. It only happens for `/api/revalidate` per Datadog logs (in ticket)
- Helps to remove unneeded noise from error alerts channel
- in your terminal, run this curl request:
```
curl -X POST "https://content.hashicorp.com/api/revalidate" \
-H "Authorization: Bearer <REVALIDATE_TOKEN>" \
-H "Content-Type: application/json" \
-d '{"product": "hcp-docs"}'
```
You should see the following:
```
The page could not be found
NOT_FOUND
```
- check out branch locally
- run `npm start`
- in another terminal window, run this …
=> chore: Refactor logic to resolve product name in revalidate endpoint

.gitignore, src/pages/api/open-api-docs-preview-v2.ts, src/pages/open-api-docs-preview-v2/[[...page]].tsx, src/views/open-api-docs-preview-v2/components/file-string-input/file-string-input.module.css, src/views/open-api-docs-preview-v2/components/file-string-input/index.tsx, src/views/open-api-docs-preview-v2/components/open-api-preview-inputs/index.tsx, src/views/open-api-docs-preview-v2/components/open-api-preview-inputs/open-api-preview-inputs.module.css, src/views/open-api-docs-preview-v2/components/open-api-preview-inputs/utils/fetch-open-api-static-props.ts, src/views/open-api-docs-preview-v2/components/textarea-input/index.tsx, src/views/open-api-docs-preview-v2/components/textarea-input/textarea-input.module.css, src/views/open-api-docs-preview-v2/constants.ts, src/views/open-api-docs-preview-v2/index.tsx, src/views/open-api-docs-preview-v2/server.ts, src/views/open-api-docs-preview-v2/utils/get-props-from-preview-data.ts, src/views/open-api-docs-view-v2/index.tsx, src/views/open-api-docs-view-v2/types.ts
Implements a new OpenAPI preview tool, at  [/open-api-docs-preview-v2]. 
The perceived value of this tool is:
- Provide a way for authors to quickly preview changes to OpenAPI specs. With authored content being a very key part of the value of these pages, and the interaction between the authored content and our rendering of that content being just as important, we want to create a tight feedback loop so that we can work closely with teams working on OpenAPI specs.
- Provide a way for `developer.hashicorp.com` web engineers to iterate on the new OpenAPI docs view, testing changes across many products, without having to set up new page routes and content source `.json` file fetching for every new product or new change.
Backing up a bit, …
=> Set up preview tool for split page OpenAPI docs

src/lib/api-docs/parse-and-validate-open-api-schema.ts, src/views/open-api-docs-preview-v2/index.tsx, src/views/open-api-docs-preview-v2/server.ts, src/views/open-api-docs-preview-v2/utils/get-props-from-preview-data.ts, src/views/open-api-docs-view-v2/components/landing-content/index.tsx, src/views/open-api-docs-view-v2/components/landing-content/server.ts, src/views/open-api-docs-view-v2/components/operation-content/index.tsx, src/views/open-api-docs-view-v2/components/operation-content/server.ts, src/views/open-api-docs-view-v2/index.tsx, src/views/open-api-docs-view-v2/server.ts, src/views/open-api-docs-view-v2/types.ts, src/views/open-api-docs-view-v2/utils/get-nav-items.ts, src/views/open-api-docs-view-v2/utils/word-break-camel-case.ts
Scaffolds in placeholder views for OpenAPI docs Landing and Operation content.
To push forward on some work to improve our OpenAPI docs pages.
| - | - |
| ![landing-before](https://github.com/hashicorp/dev-portal/assets/4624598/244e2e1f-1767-443b-b670-0cf95d0b77e8) | ![landing-after](https://github.com/hashicorp/dev-portal/assets/4624598/bdbcb6de-d807-4d27-8312-74272041400f) |
| - | - |
| ![operation-before](https://github.com/hashicorp/dev-portal/assets/4624598/c48895b7-aa16-49ef-b596-cbd675a3d46e) | ![operation-after](https://github.com/hashicorp/dev-portal/assets/4624598/ca746a5e-df93-4f90-b72e-6498bb8b2cf5) |
- Upload a valid OpenAPI spec, such as [the one for HCP Vault …
=> scaffold new open-api landing and operation views

.github/workflows/upload-sourcemaps-to-datadog.yml, next.config.js
- [Asana task](https://app.asana.com/0/1207660807251534/1207660807251544/f)
Per the [Datadog docs](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs), it instructs to create and upload source maps to unminify RUM errors in a CI step.
This PR adds a GHA to build & upload sourcemaps to Datadog when there is a push event to `main`
- More information to understand where errors are coming from. For any given error, you can access the file path, line number, and code snippet for each frame of the related stack trace.
- In several documentation sites generating sourcemaps is advised against. To prevent leaking unminified code the best course of action determined was to add custom logic to control the webpack config and only run it in a specific …
=> Chore: add sourcemaps to unminify RUM errors in Datadog

src/components/breadcrumb-bar/index.tsx
- [Preview link](https://dev-portal-git-leah-featbreadcrumbs-hashicorp.vercel.app/terraform/enterprise/v202404-1/releases/2024/v202402-1) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1207746622331000/f) 🎟️
This PR fixes the breadcrumbs bar so it does not show items without urls. The reason it is showing them is because a `forEach` was chained after the `filter` and that does not work as intended in javascript. I changed it so the `forEach` is on the new array that is formed from the `filter` method.
1. Go to [prod](https://developer.hashicorp.com/terraform/enterprise/v202404-1/releases/2024/v202402-1)
2. Notice that the 2018 and 2024 breadcrumbs are not clickable
3. Go to [preview](https://dev-portal-git-leah-featbreadcrumbs-hashicorp.vercel.app/terraform/enterprise/v202404-1/ …
=> fix: remove breadcrumbs without links

src/components/docs-version-switcher/index.tsx, src/views/docs-view/server.ts, src/views/docs-view/utils/get-valid-versions.ts
This PR modifies our versioned documentation dropdown to avoid rendering any links that will 404. To accomplish this, we use the new docs content API `content-versions` endpoint introduced in https://github.com/hashicorp/mktg-content-workflows/pull/460.
Rendering links that 404 makes for a confusing user experience, and adds a lot of noise to our 404 logging, and also seems to have a significant negative SEO impact. It also looks bad in tools like [ahrefs](https://ahrefs.com/).
| - | - |
| ![before](https://github.com/hashicorp/dev-portal/assets/4624598/5b27af37-1c58-4c5a-8572-30551bae3506) | ![after](https://github.com/hashicorp/dev-portal/assets/4624598/96e27275-f20b-42ce-9c9f-6dd0e170da73) |
- For example, …
=> avoid bad links in version dropdowns

next.config.js, src/views/homepage/index.tsx
- change devtool value to `hidden-source-map` to fix 404 error
(no sourcemap found instead of 404)
- You can see in [this previous deployment](https://dev-portal-fs7cudo0n-hashicorp.vercel.app/) that the message of "no sourcemap found" is expected
- visit [this page](https://dev-portal-git-heat-chorefix-sourcemap-404-hashicorp.vercel.app/)
- open console and wait for error `Uncaught Error: This is a new test error thrown after 5 seconds` to appear
- visit rum error logs [here](https://app.datadoghq.com/rum/sessions?query=%40type%3Aerror%20%40application.id%3A40a2019f-88ad-4076-ab52-ffd074064eed%20-%40error.source%3Anetwork%20%40session.type%3Auser%20%225%20seconds%22&agg_m=count&agg_m_source=base&agg_t=count&cols=&fromUser=false&refresh_mode=sliding&track=rum&viz=stream&from_ts=17216919074 …
=> chore: change sourcemap to hidden

src/lib/hash-links/use-active-section.ts
- [Asana task](https://app.asana.com/0/1207660807251534/1207935781668949/f) 🎟️
- [Datadog error logs](https://app.datadoghq.com/rum/sessions?query=%40type%3Aerror%20%40session.id%3A11fb182a-98bd-4ca0-a375-7ff2f18d688a&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZEBE67iRtyO_gAAAAAAAAAYAAAAAEFaRUJFOWNYQUFBbV9OVWZpTk1JZXdBQQAAACQAAAAAMDE5MTAxY2ItODE2MS00MDE0LWFmMjYtMTlkM2EwMGM5YmEx&fromUser=false&refresh_mode=paused&track=rum&viz=stream&from_ts=1722296352842&to_ts=1722306363403&live=false) 🎟️
When we are calculating the distance of the top heading in a doc, to mark it as the "active heading", we are assuming that each headingID will exist. This PR adds guards to that code to skip over …
=> Check active heading IDs before calculating distance

next.config.js, scripts/upload-source-maps.ts
- [Asana task](https://app.asana.com/0/1207660807251534/1207956118285656/f)
- prevent the upload sourcemap script from running in product repo builds
- Build will error because `DATADOG_API_KEY` is undefined. See example [here](https://vercel.com/hashicorp/boundary/21xAyGzcbf5K1ruTZt65PM3LtVQf#L395)
=> chore: Prevent upload sourcemap script from running in product repo builds

src/content/vault/docs-landing.json
- [Preview link](https://dev-portal-git-vault-update-doc-home-hashicorp.vercel.app/vault/docs) 🔎
- [Jira ticket](https://hashicorp.atlassian.net/browse/SPE-938) 🎟️ 
This PR updates the Vault docs landing page to link to HCP Vault docs pages.
The concern was raised that users land on the **Vault** pages instead of **HCP** to look the docs for:
- HCP Vault Dedicated
- HCP Vault Secrets
- HCP Vault Radar
Today, we don't do a good job linking to HCP docs. Users have to read the "What is Vault?" page to find any links to HCP Vault Dedicated. 
As for HVS and Vault Radar, we don't have any mentioning of them. 
Adding a card for each HCP product docs, navigate the users to the correct page on DevDot.
=> Update the Vault docs home to add HVS and Vault Radar

next.config.js, scripts/upload-source-maps.ts
- Fix check for `DATADOG_API_KEY` by replacing it with `DD_API_KEY`
- this check stopped sourcemaps from being uploaded. The `@datadog-ci` command requires `DATADOG_API_KEY`, but in our code base it is `DD_API_KEY`.
=> chore: Replace datadog_api_key with dd_api_key

src/content/vault/docs-landing.json
This PR removed the `HCP Vault Radar` card that was added to the Vault docs home.
R&D management team decided to "_Move HCP Vault Radar to be a standalone product_".
For HashiConf, Vault Radar will be **public beta** instead of GA.
=> Remove Vault Radar card

build-libs/redirects.js, next.config.js, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
- Preview link
- [Asana task](https://app.asana.com/0/1207947026228781/1207968736025985/f)
- Refactor logic to remove `/index` from nav nodes because when a user clicks on the link, it sends them to a 404 page
- Add redirect to `next.config.js` for paths that end with `/index`
- fix 404s in ahrefs found [here](https://app.ahrefs.com/site-audit/4163982/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&current=12-08-2024T231641M0400&filterId=28daa554b6921b6c6742b8b3f34bbf51&issueId=c64dae3f-d0f4-11e7-8ed1-001e67ed4656&sorting=-incomingAllLinks&st=index)
All of these paths should resolve:
- https://dev-portal-git-heat-chorefix-index-nav-item-hashicorp.vercel.app/vagrant/docs/v2.2.19/index
- …
=> bug fix: fix index.mdx nav items not resolving for api-docs & docs 

docs/decisions/adr-000-document-architecture-decisions.md
Proposes the adoption of [Architecture Decision Records](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions). The proposal is formatted as an architecture decision record that matches the proposed form of documentation.
This proposal is nearly identical to [web-presence-experimental-docs#7 - initialize architecture decision records](https://github.com/hashicorp/web-presence-experimental-docs/pull/7). The only difference is this document has an explicit list of `Status` options (`proposed | accepted | deprecated | superseded`) for clarity.
=> propose adr-000 on adopting adrs

src/content/certifications/exam-faqs/terraform-associate-003.mdx
- [Preview link](https://dev-portal-git-TFPro_GoLiveUpdates-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
- [Asana task](https://app.asana.com/0/1204533745817604/1206583690938205/f) 🎟️
Included the new TF Pro exam in the recertification logic section of the TF Assoc 003 page
When TF Pro launches, it becomes part of the recert path for Assoc
=> TF recert logic wording added to developer page

src/pages/vagrant/install/vmware/index.tsx, src/views/product-downloads-view/server.ts
- [Asana task](https://app.asana.com/0/1207947026228781/1207624641466040/f)
- Add a check that the file path exists to prevent the error `ENOENT: no such file or directory, open '/var/task/src/content/vagrant/install-vmware-landing.json'`
- Reduce noise in error logs
Client side navigation triggers this error, as you can see in the recording below. Tested in staging, the client-side navigation triggers the error. In the second part of the recording, you can see that the same client-side navigation in the preview does not trigger the same error.
https://github.com/user-attachments/assets/ce09706a-4b6c-4529-b22b-8996b12e9b41
- Visit [this page](https://dev-portal-git-heat-chorefix-vmware-prefetch-error-hashicorp.vercel.app/vagrant/install)
- scroll down to the VMWare Utility CTA …
=> bug fix: Add check that path exists for options.jsonFilePath

.env, docs/decisions/adr-001-env-changes-for-unified-docs.md, next.config.js, src/components/image/index.tsx, src/lib/__tests__/get-static-paths-from-analytics.test.ts, src/lib/fetch-content-api-file-string.js, src/lib/get-static-paths-from-analytics.ts, src/lib/remark-plugins/remark-image-dimensions/index.ts, src/lib/remark-plugins/remark-rewrite-assets.ts, src/lib/remark-plugins/rewrite-static-tutorials-assets/index.ts, src/lib/sitemap/docs-content-fields.ts, src/views/docs-view/loaders/__tests__/remote-content.test.ts, src/views/docs-view/loaders/content-api/content-api.test.ts, src/views/docs-view/loaders/content-api/index.ts, src/views/docs-view/utils/get-valid-versions.ts
This PR implements #2548.
In more detail, this PR introduces three new environment variables:
- `DOCS_STATIC_PATHS_API` - will be set to <https://content.hashicorp.com> initially. Intent is to scope work around this functionality separately from the unified docs API migration.
- `MKTG_CONTENT_DOCS_API` - will be set to <https://content.hashicorp.com> initially. Docs functions that are not yet migrated will use this env variable.
- `UNIFIED_DOCS_API` - will be set to point to our new unified docs API, currently <https://web-presence-experimental-docs.vercel.app/>. The migration process will be to switch individual docs sections to use this new variable.
This PR also removes the existing `MKTG_CONTENT_API` env variable, as with the introduction of the above environment variables, it is now …
=> implement adr-001 env changes for unified docs

src/components/dialog/dialog.module.css, src/components/dialog/index.tsx
- [Preview link](https://dev-portal-git-leah-fixsafari-keyboard-height-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1203910935802336/f) 🎟️
In mobile safari, the keyboard is covering up the content in the search dialog. You can't scroll to see the bottom of the list. This PR fixes this issue using the `visiualViewport` information and events on the `window` object. When the visualViewport gets resized (like when the keyboard pops up), the bottom padding amount will get adjusted to the difference between the actual screen size and the screen size that is visible when the keyboard is open.
Before
https://github.com/user-attachments/assets/abc21437-6c37-4153-9876-dbde02368576
After
https://github.com/user-attachments/assets/dd094bc1-2f3c-47e1-8d62-c9b8579e05 …
=> fix: keyboard covers content on mobile safari

.github/dependabot.yml
This PR updates reviewers for all dependabot PRs from @hashicorp/web-platform to @hashicorp/web-presence
I've created the same PR for the monorepo https://github.com/hashicorp/web/pull/1897
=> (chore) update dependabot auto reviewer assignment

src/views/docs-view/server.ts
- [Preview link]() 🔎
This PR removes the "Edit this page on GitHub" link at the bottom of the terraform docs as those pages are _not_ editable on GitHub. 
It was drawn to our attention by Rose Wittkower in [this thread](https://hashicorp.slack.com/archives/C5FSPUGDS/p1723236157918749) who had been alerted to it by a customer who had clicked the link and been sent to a GitHub 404 page.
It was pointed out in [a thread in #web-presence](https://hashicorp.slack.com/archives/C058H0MULTE/p1723236567773119) by @nandereck (shoutout to Nels for quickly finding that block!) that the conditional rendering could simply be changed here to hide that link for terraform (as well as sentinel and HCP).
---
- …
=> Remove "Edit on GitHub" link from terraform docs

src/views/docs-view/server.ts
This PR reverts hashicorp/dev-portal#2540, which was overly broad in it's scope when hiding the "Edit on GitHub" link at the bottom of dev docs. This caused the link to disappear for all Terraform products rather than just Terraform Enterprise(the intended target). 
[A ticket to re-do this logic with narrower scope has been opened](https://app.asana.com/0/1207947026228781/1208226840548303/f)
=> Revert "Remove "Edit on GitHub" link from terraform docs"

src/views/open-api-docs-view/utils/get-operation-props.ts
- [Preview link](https://dev-portal-900sskf54-hashicorp.vercel.app/) 🔎
- [WAYP-2783](https://hashicorp.atlassian.net/browse/WAYP-2783) 🎟️
This allows us to tag RPCs as `hidden` to prevent them appearing in API docs.
Looks like this in practice:
```proto
rpc UI_LoadProductBanner(UI.LoadProductBannerRequest) returns (UI.LoadProductBannerResponse) {
option (google.api.http) = {
get: "/waypoint/2023-08-18/namespace/{namespace.id}/ui/product-banner"
};
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
tags: ["WaypointService", "hidden"]
};
}
```
We have a set of specialized RPCs in cloud-waypoint-service that are designed only to be used by the UI. We were hoping we could mark these as [internal](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal …
=> [WAYP-2783] Add support for a "hidden" tag for api-docs

src/views/docs-view/server.ts
- `versions` should be `validVersions` to prevent docs versions dropdown from containing links that return a 404
- regression & bad UX
=> bug fix: Change versions to validVersions to prevent 404s

src/data/alert-banner.json, src/layouts/base-layout/index.tsx
- [Preview](https://dev-portal-git-heat-hashiconfalert-banner-day-one-hashicorp.vercel.app/)
- [Asana task](https://app.asana.com/0/1207947026228781/1208503549555255/f) 🎟️
- alert banner to watch live stream of HashiConf on October 15th, 2024 8:30 am - 12:30 pm EDT
- Visit the [preview link ](https://dev-portal-git-heat-hashiconfalert-banner-day-one-hashicorp.vercel.app/)and see the alert banner is not there
- Change the date & time on your machine to October 15th 8:30 AM and refresh the page
- The alert banner should be visible
- Change the date & time on your machine to October 15th 12:31 PM and refresh the page
- The alert banner should **not** be visible
=> chore: alert banner for HashiConf

src/data/alert-banner.json
- [Preview](https://dev-portal-git-heat-hashiconfadd-day-two-banner-hashicorp.vercel.app/)
- [Asana task](https://app.asana.com/0/1207947026228781/1208503549555255/f) 🎟️
- alert banner to watch live stream of HashiConf on October 16th, 2024 8:30 am - 12:30 pm EDT
=> Change HashiConf alert banner expiration date to Oct 16th

config/unified-docs-sandbox.json
Introduces a new `config/unified-docs-sandbox.json` environment, with the `"unified_docs_migrated_repos"` flag set to load Terraform content from the new unified docs API.
To allow development and deploy previews from within the `hashicorp/web-unified-docs` repo to load Terraform content from the API at the URL specified by the env variable `UNIFIED_DOCS_API`, while loading content for all other products from the API at the URL specified by `MKTG_CONTENT_API` (ie `content.hashicorp.com`).
To use this new environment via `make` in `hashicorp/web-unified-docs`, we'll need to add `HASHI_ENV=unified-docs-sandbox` to the [environment configuration for `dev-portal` image](https://github.com/hashicorp/web-unified-docs/blob/2829bb8914d090467e5da6 …
=> introduce unified-docs-sandbox config env

src/lib/consent-manager/component.tsx, src/lib/consent-manager/utils.ts
- [Preview link](https://dev-portal-git-presdg-bannerstyling-hashicorp.vercel.app/?vercelToolbarCode=cW4QxZO562Iedlv) 🔎
- [Asana task](https://app.asana.com/0/1207484854701350/1208634233952599/f) 🎟️
Adjusts the styling of the Datagrail scrollbar
1. Removes the forced scroll so that we only get a scrollbar if we need one
2. Uses the default light scroll bar instead of the dark to better match the styling of the pop up
Simulated long list for when more translations get added
> [!NOTE] 
> Cookies won't persist since we are in preview
=> style: cookies dg-banner

build-libs/redirects.js, src/app/api/refresh/route.ts, src/layouts/base-layout/index.tsx, tsconfig.json
No preview link as this will purposely **only** work in local dev.
Creates a new **App Router API** route /api/refresh that keeps a connection open on clients so that when they are send the reload message they can reload their webpage.
This makes editing documents in Unified Docs a much better experience.
1. Checkout this repo
2. Set the following envs
1. `HASHI_ENV="unified-docs-sandbox"`
2. `UNIFIED_DOCS_API="http://localhost:8080"`
3. [Checkout this PR from unified docs](https://github.com/hashicorp/web-unified-docs/pull/58)
4. Start both dev-portal and unified docs
1. dev-portal: `npm run start`
2. unified-docs: `npm run dev`
5. Visit a page
1. e.g. `http://localhost:3000/terraform/cli`)
6. Open the DevTools and make sure the Reload Client has connected
1. e.g. `Reload Client …
=> Create custom dev reload api route

src/app/api/refresh/route.ts, src/layouts/base-layout/index.tsx
No preview link as this will purposely **only** work in local dev.
Updates the **App Router API** route /api/refresh to use NODE_ENV as VERCEL_ENV isn't available client side.
1. Checkout this repo
2. Set the following envs
1. `HASHI_ENV="unified-docs-sandbox"`
2. `UNIFIED_DOCS_API="http://localhost:8080"`
3. `NODE_ENV="development"`
4. [Checkout this PR from unified docs](https://github.com/hashicorp/web-unified-docs/pull/58)
5. Start both dev-portal and unified docs
1. dev-portal: `npm run start`
2. unified-docs: `npm run dev`
6. Visit a page
1. e.g. `http://localhost:3000/terraform/cli`
7. Open the DevTools and make sure the Reload Client has connected
1. e.g. `Reload Client ad581121-b944-495f-aed2-d65fc515b074 Connected`
8. Edit that page in Unified Docs
1. example page is contained …
=> Use NODE_ENV

src/components/sidebar/components/sidebar-horizontal-rule/sidebar-horizontal-rule.module.css, src/views/open-api-docs-view-v2/index.tsx, src/views/open-api-docs-view-v2/server.ts, src/views/open-api-docs-view-v2/types.ts
> [!NOTE]
> This PR is based off of #2594. We likely want to finalize and merge #2594 before handling this PR, at which point we can rebase this PR onto `main`.
Builds out the mobile menu for our new version of OpenAPI docs view.
We have a practice of reflecting sidebar navigation in the collapsed navigation we display on narrow viewports, known as our "mobile menu". This PR ensures the OpenAPI V2 view follows this practice.
- Slots components built in #2594 into the mobile menu slot setup previously constructed for OpenAPI docs pages
Group by `tag` example, with [HCP Consul Central][hcp-consul-central-spec] (note the `Before` menu is `null`):
| - | - |
| ![hcp-consul-mobile-menu-before](https://github.com/user-attachme …
=> OpenAPI V2 - implement mobile menu

src/views/open-api-docs-preview-v2/utils/get-props-from-preview-data.ts, src/views/open-api-docs-view-v2/components/content-with-permalink/content-with-permalink.module.css, src/views/open-api-docs-view-v2/components/content-with-permalink/index.tsx, src/views/open-api-docs-view-v2/components/operation-content/index.tsx, src/views/open-api-docs-view-v2/components/operation-content/server.ts, src/views/open-api-docs-view-v2/components/operation-content/style.module.css, src/views/open-api-docs-view-v2/components/operation-details/index.tsx, src/views/open-api-docs-view-v2/components/operation-details/operation-details.module.css, src/views/open-api-docs-view-v2/components/operation-examples/index.tsx, src/views/open-api-docs-view-v2/components/operation-sections/index.tsx, src/views/open-api-docs-view-v2/components/operation-sections/operation-sections.module.css, src/views/open-api-docs-view-v2/components/property-details/index.tsx, src/views/open-api-docs-view-v2/components/property-details/property-details.module.css, src/views/open-api-docs-view-v2/schema-transforms/schema-transform-component.ts, src/views/open-api-docs-view-v2/schema-transforms/shorten-protobuf-any-description.ts, src/views/open-api-docs-view-v2/server.ts, src/views/open-api-docs-view-v2/utils/get-property-detail-props.ts, src/views/open-api-docs-view-v2/utils/get-request-data.ts, src/views/open-api-docs-view-v2/utils/get-response-data.ts, src/views/open-api-docs-view-v2/utils/get-url-path-code-html.ts
Implements operation page content for the split-operations Open API template.
Our current OpenAPI docs view renders all operations on a single page. For some spec files, the page data can get heavy enough that it becomes very slow and even error-causing to try to handle it.
This PR implements the operation page content for a new version of the Open API docs template, which splits operations to separate pages.
- Pulls in components from the existing OpenAPI view
- Implements `<OperationContent />` component to match upstream setup
- Only significant difference is operation name is now used as `<h1 />` rather than `<h2 />`
| - | - |
| ![hcp-vault-secrets-before](https://github.com/user-attachments/assets/dab93c6c-44e7-454 …
=> add operation content to OpenAPI v2 template

.github/workflows/playwright.yml, .github/workflows/register-preview-url.yml
- [Asana task](https://app.asana.com/0/1208691590278290/1208699942108403/f) 🎟️
This PR adjusts the github actions that are failing in dev-portal-internal to only run in the dev-portal repo. This way dev-portal-internal can be in sync with dev-portal but not have the failing actions anymore
1. In the current build, view the Register Preview URL with CloudIDP / on-deploy and E2E Tests / test actions
2. Verify that both of these actions ran as expected
3. In commit 7c72ac1, view the Register Preview URL with CloudIDP / on-deploy and E2E Tests / test actions
4. Verify that both of these actions were skipped when the repo name does not match where the action is run
=> fix: update actions for dev-portal-internal

.github/workflows/repo-sync.yml
- [Asana task](https://app.asana.com/0/1208691590278290/1208699942108403/f) 🎟️
This PR updates the version for `actions/github-script` to the latest trusted version. 
The [TSCCR verify check](https://github.com/hashicorp/dev-portal-internal/actions/runs/11745455774/job/32722917783) on dev-portal-internal is failing because the version of `actions/github-script` in `repo-sync` is untrusted. They recommend upgrading to `actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea` instead of `actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0`
=> fix: update github script version for failing TSCCR check on dev-portal-internal

src/content/tutorials-landing.json
- [Preview link](https://dev-portal-git-nels-remove-collection-hashicorp.vercel.app/tutorials) 🔎
The `cloud/networking` tutorial collection is being removed in [this PR](https://github.com/hashicorp/tutorials/pull/2372) but the collection is referenced on the /tutorials landing page. This results in broken builds in the tutorials PR. This PR removes the reference.
=> Fix: Remove collection

src/pages/hcp/api-docs/vault-secrets/[[...page]].tsx
This PR migrates `/hcp/api-docs/vault-secrets` to the new split-operations OpenAPI view.
Our current OpenAPI docs view renders all operations on a single page. For some spec files, the page data can get heavy enough that it becomes very slow and even error-causing to try to handle it.
Uses very similar configuration to upstream, but passes it to the new OpenAPI view.
Overview content
| - | - |
| ![overview-before](https://github.com/user-attachments/assets/7cc02444-e401-4141-853f-b5075544d96a) | ![overview-after](https://github.com/user-attachments/assets/f4c57d2b-b0da-441e-a7ea-f2d223cc520f) |
Operation content
| - | - |
| ![operation-before](https://github.com/user-attachments/assets/d662b3f1-6187-4 …
=> Migrate HCP Vault Secrets to split OpenAPI view

build-libs/__tests__/redirects.test.ts, build-libs/redirects.js
- [Preview link](https://dev-portal-git-leah-featudr-redirects-api-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1207899860738460/1208961563646273/f) 🎟️
This PR adds support for fetching UDR redirects. It uses the app config to determine if a specific repo is migrated to UDR and if so, pulls the redirects from UDR instead of the product repo. 
To add support for UDR redirects in dev-portal
Existing functionality:
1. Go to [preview /terraform/cloud-docs/workspaces/creating](https://dev-portal-git-leah-featudr-redirects-api-hashicorp.vercel.app/terraform/cloud-docs/workspaces/creating)
2. Verify the link shown in the search bar is redirected to `/terraform/cloud-docs/workspaces/create`
New functionality: 
1. Run the command below and go to [local …
=> feat: fetch redirects from udr for migrated repos

src/data/vault.json, src/views/product-downloads-view/helpers.ts
Fixes an issue with the Fedora installation [as the adding repository command changed slightly in Fedora 41.](https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/#_for_fedora_41_or_later_dnf_5)
resolves #2651
=> update: fedora repository installation script

src/lib/__tests__/docs-content-fields.test.ts, src/lib/sitemap/docs-content-fields.ts
- [Preview link](https://dev-portal-git-leah-featudr-all-docs-paths-hashicorp.vercel.app/server-sitemap.xml) 🔎
- [Asana task](https://app.asana.com/0/1206815131022336/1208939388171199/f) 🎟️
This PR fetches the paths from the UDR `api/all-docs-paths` for generating the sitemap. It only does fetches these if there are migrated content repos in the config. After fetching the paths, it filters the paths from the content API that are duplicates and then merges both results together.
1. Go to [Preview link](https://dev-portal-git-leah-featudr-all-docs-paths-hashicorp.vercel.app/server-sitemap.xml)
2. Verify that there is not an entry for `https://developer.hashicorp.com/terraform` in the sitemap (Run command f with `https://developer.hashicorp.com/terraform<`)
3. Pull down this branch and run …
=> feat: fetch paths from UDR all-docs-paths

src/components/collection-progress-group/components/collection-progress-status-section/collection-progress-status-section.module.css, src/components/collection-progress-group/docs.mdx, src/components/collection-progress-group/index.tsx
- [Asana task](https://app.asana.com/0/1208777238149723/1208951572065294/f) 🎟️
The start button puts the user in the first tutorial listed in the collection, which is relevant to ordered collections, so we want to keep it in all ordered collections. Unordered collections are arranged in rows of tutorials, to be completed in any order, so the start button is irrelevant since the user does not need to start with the first tutorial. We will remove it in all unordered collections.
Removed "Start" button from unordered collection, updated style so `CollectionProgressStatusSection` doesn't look funky (it looks slightly more condensed).
Before:
After (no style change):
After:
=> Remove 'start' button from unordered collection

build-libs/__tests__/get-latest-content-sha-for-product.test.ts, build-libs/redirects.js, next-env.d.ts, tsconfig.json
- [Preview link](https://dev-portal-git-leah-feathvd-redirects-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1206815131022336/1208690625725474/f) 🎟️
This PR adds redirects functionality for hvd-docs. It works the same way as other product redirects in dev-portal.
There is not currently redirect support for hvd-docs. That team has requested the functionality (see [Slack thread](https://hashicorp.slack.com/archives/C5FSPUGDS/p1730463708879159))
1. Go to [/validated-designs/boundary-operating-guides-adoption](https://dev-portal-git-leah-feathvd-redirects-hashicorp.vercel.app/validated-designs/boundary-operating-guides-adoption)
2. Verify that it is not going to that page and instead redirects to the `/validated-designs` homepage
The PR has a sha value for the hvd-docs repo …
=> feat: add hvd-docs redirects functionality

src/views/product-downloads-view/boundary/components/install-callout/index.tsx, src/views/product-downloads-view/boundary/components/install-callout/install-callout.module.css, src/views/product-downloads-view/boundary/download.module.css, src/views/product-downloads-view/boundary/index.tsx
- [Preview link](https://dev-portal-git-leah-boundary-desktop-note-hashicorp.vercel.app/boundary/install#desktop-client) 🔎
- [Asana task](https://app.asana.com/0/1208691590278290/1208739328917039/f) 🎟️
This PR adds a note to the bottom of the 'Desktop Client' section for the boundary install page. The note links to the previous versions of the desktop client.
Previous versions of boundary are not always compatible with the latest version of the desktop client. Linking to that page will allow users to download the version compatible with their boundary version. 
1. Go to [preview link](https://dev-portal-git-leah-boundary-desktop-note-hashicorp.vercel.app/boundary/install#desktop-client)
2. See the note at the bottom of that section and verify that it matches design in [Asana task](url)
3. …
=> feat: add note for boundary desktop client

src/content/tutorials-landing.json, src/content/vagrant/install-vmware-landing.json, src/content/vagrant/product-landing.json, src/pages/tutorials/library.tsx
Currently, the Vagrant landing and install pages reference the old `getting-started` collection and content. This temporarily removes all those references so DevDot can successfully build. We will add those changes in after we merge the new content.
Merge order:
1. https://github.com/hashicorp/dev-portal/pull/2677 (this PR)
2. https://github.com/hashicorp/dev-portal/pull/2676
3. https://github.com/hashicorp/tutorials/pull/2437
=> Temp remove GS content from Vagrant to update Vagrant GS

src/views/product-downloads-view/boundary/components/install-callout/index.tsx, src/views/product-downloads-view/index.tsx
- [Preview link](https://dev-portal-git-leah-boundary-remove-install-hashicorp.vercel.app/boundary/install) 🔎
- [Asana task](https://app.asana.com/0/1206815131022336/1208659321863812/f) 🎟️
This PR removes the 'Boundary Installer' section on the boundary install page for versions less that 0.18.0
Boundary versions before 0.18.0 don't work with the installer so the boundary team requested that we remove this section for those versions.
I used the `useCurrentVersion` hook to get the current version and used `semver` to compare that with version 0.18.0 to see if it was a lesser version. Using that value I conditionally rendered the 'Boundary Installer' section on the page and removed the 'Boundary Installer' section from the sidebar.
In order to use the `useCurrentVersion` hook, I had to use …
=> feat: remove boundary installer for versions less than 0.18.0

.env, src/lib/remark-plugins/remark-rewrite-assets.ts, src/views/docs-view/loaders/__tests__/file-system.test.ts, src/views/docs-view/loaders/__tests__/remote-content.test.ts, src/views/docs-view/loaders/file-system.ts, src/views/docs-view/loaders/remote-content.ts, src/views/docs-view/render-page-mdx.ts, src/views/docs-view/utils/get-deploy-preview-loader.ts
- [Preview link](https://dev-portal-git-load-mdx-imgs-from-udr-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1207899860738460/1207910088307871) 🎟️
This PR modifies MDX image loading to load from the UDR asset API. It does this by updating and injecting the `remark-rewrite-assets.ts` remark plugin to rewrite the MDX img URLs when an product is in `config.flags.unified_docs_migrated_repos`. Which currently only the `HASHI_ENV=unified-docs-sandbox` has those flags set.
Before this [only use case of remark-rewrite-assets remark plugin](https://github.com/hashicorp/dev-portal/pull/2684/files#diff-fba91fc20d9e03dac5cd7a8a0b953d1a58f0c1c245e55b5ef004bf67f5f961ccR78) was in rewriting the MDX imgs of URLS for any `terraform` and `ptfe-releases` products. (e.g. …
=> Load mdx images from UDR

src/views/docs-view/loaders/remote-content.ts
This PR adds `githubFileUrl` to UDR, giving it feature parity with existing `learn-api`. We need to merge the companion api change in UDR that adds `githubFile` to the specific docs api. 
- [Asana task](https://app.asana.com/0/1209152747858598/1209408966538822) 🎟️
1. Checkout this PR and create a local image `dev-portal:github-link`.
2. Checkout web-unified-docs [PR](https://github.com/hashicorp/web-unified-docs/pull/138), update `docker-compose` to use local dev-portal image instead of `hashicorp/dev-portal`.
3. Start UDR with `make`.
4. Go to http://localhost:3000/terraform/plugin/framework/resources and confirm "Edit this page on GitHub" at the bottom of the page.
5. Click on link to confirm it …
=> Add "Edit this page on GitHub" functionality for UDR

src/views/docs-view/loaders/__tests__/remote-content.test.ts, src/views/docs-view/loaders/remote-content.ts
- [Preview link](https://dev-portal-ojnqbe9i0-hashicorp.vercel.app/terraform/plugin/framework) 🔎
- [Asana task](https://app.asana.com/0/1209152747858598/1209393273791795) 🎟️
UI
Previous version (extra "Framework" and "Overview")
Alternatively, run the test suite.
=> Remove extraneous headers and nav item from versioned docs

.github/workflows/nextjs_bundle_analysis.yml
This PR updates the actions/cache version to fix errors on [bundle analysis builds](https://github.com/hashicorp/dev-portal/actions/runs/13634967691). I used the version web uses for their bundle analysis action to keep them in sync. More details about this [here](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)
Bundle analysis actions are failing.
Verify the bundle analysis action works on this PR.
=> fix: update actions/cache version to fix errors

src/views/docs-view/loaders/__tests__/remote-content.test.ts
- [Asana task](https://app.asana.com/1/90955849329269/project/1209152747858598/task/1209570563537655) 🎟️
Currently our typecheck is failing, which is causing a pre-commit hook to fail as well. THis PR fixes that.
1. Checkout `main`
1. Run `npm run typecheck`
1. Notice the error
1. Checkout this branch: `rn/fix-precomit-typecheck`
1. Run `npm run typecheck`
1. The error in 3 should be gone
=> Fix pre-commit typecheck

src/views/docs-view/loaders/__tests__/remote-content.test.ts, vitest.config.mts
1. We were running vitest on compiled code in the .next directory, which was causing tests to fail. We can safety skip the compiled test code.
1. Checkout `main`
1. Run `npm run test:ci`
1. Notice the error
1. Checkout this branch: `rn/skip-dotnext-in-vitest`
1. Run `npm run test:ci`
1. The error in 3 should be gone
=> Skip .next dir when running vitest

src/app/api/refresh/route.ts, src/components/breadcrumb-bar/__tests__/breadcrumb-bar.test.tsx, src/components/open-api-page/partials/collapsible/index.tsx, src/hooks/use-authentication/index.ts, src/layouts/sidebar-sidecar/types.ts, src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts, src/lib/api-docs/fetch-cloud-api-version-data/build-query-string-suffix.ts, src/lib/integrations-api-client/standard-client.ts, src/lib/next-mdx-remote/__tests__/next-mdx-remote.test.tsx, src/lib/next-mdx-remote/index.tsx, src/lib/rehype-code-plugins.ts, src/lib/remark-plugins/rehype-sanitize/__tests__/rehype-sanitize.test.ts, src/lib/remark-plugins/remark-image-dimensions/__tests__/index.test.tsx, src/lib/syntax-highlighting/index.ts, src/pages/_app.tsx, src/pages/api/open-api-docs-preview-v2.ts, src/pages/api/opt-out-feedback.ts, src/pages/api/revalidate.ts, src/views/collection-view/index.tsx, src/views/docs-view/loaders/__tests__/file-system.test.ts, src/views/docs-view/loaders/__tests__/remote-content.test.ts, src/views/docs-view/loaders/content-api/index.ts, src/views/docs-view/loaders/file-system.ts, src/views/docs-view/loaders/index.ts, src/views/docs-view/types.ts, src/views/docs-view/utils/__tests__/get-valid-versions.test.ts, src/views/product-tutorials-view/index.tsx, src/views/tutorial-view/index.tsx
This PR resolves the `@typescript-eslint/no-explicit-any` eslint error only relative to the base assembly branch (`rm/fix-linting`)
Apologies to @LeahMarieBush for introducing a ton more `$TSFixMe` instances, but it seemed like the best way to resolve this eslint error within the scope of the ticket without doing _a ton_ of refactoring. If there's a better way to resolve some/all of this I'm happy to hear it though.
=> @typescript-eslint/no-explicit-any

eslint.config.js
This PR updates the eslint config file to allow the usage of inline `require` (thus resolving 13 linting issues). Under closer inspection of this (and of www) it seems as though (in the case of the latter) inline `require()` is used in various places. 
The significant commit can be found here: https://github.com/hashicorp/dev-portal/commit/7a9724b30a815f8b251065b48fcfeefd268aea27.
=> @typescript-eslint/no-require-imports

src/components/author-primitives/packer/badges-header/index.tsx, src/components/outline-nav/components/outline-list-items/index.tsx, src/views/product-root-docs-path-landing/components/marketing-content/index.tsx
This PR resolves linting issues related to the `no-array-index-key` linting rule.
1. I would like to call out [this change](https://github.com/hashicorp/dev-portal/compare/rm/fix-linting...rm/no-array-index-key?expand=1#diff-0ee33eb12315f956f8e988aa744ca328320dc8e0b87700ef92db4185b3030006R9) where component typing was updated to use `PropsWithChildren` instead of manually typing `{ children: React.ReactChild[] }` - it wasn't  _directly_ in scope but it was showing as a react warning in my IDE and it seemed like a quick and easy fix at the time...
2. I'd also like to draw attention to [this …
=> no-array-index-key

src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx
- [Asana task](https://app.asana.com/1/90955849329269/project/1202801212949828/task/1209672612329409?focus=true)
- Comment out udr docs index as it is overriding docs records from  the `*_DEVOT_omni` index
- The records w/ `type: 'docs'` from `*_DEVOT_omni`  are being overridden by the udr index. The implementation of federated search is incorrect. The hits from prod_UDR need to be merged with hits `*_DEVOT_omni`
- As an interim solution, the JSON file generated from `npm run prebuild` has been added to the `prod_DEVDOV_omni` index.
=> Patch fix: documentation tab in search modal broken

.github/workflows/playwright.yml, playwright.config.ts
- [Asana task](https://app.asana.com/0/home/1207213190767773/1209537883815012) 🎟️
Enable vercel authentication bypass for e2e tests.
Vercel deployment protection is currently disabled for previews because enabling it causes e2e tests to fail. The fix for this is to enable automation bypass which allows an additional token (obtained via env var) to be passed in the header allowing programmatic access to preview deployments
Some additional work to be done when this is merged:
In order to avoid breakages to new deployments (while this is in review) the Vercel/GitHub side of things hasn't been turned on yet. When this PR is merged, there is some additional work to be done to set this up:
1. Go into Vercel …
=> Enable Vercel automation bypass for e2e tests

config/base.json, config/unified-docs-sandbox.json, src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx
- [Asana task](https://app.asana.com/0/1205788188868789/1209705281993242/f)
- [related UDR PR](https://github.com/hashicorp/web-unified-docs/pull/192)
Clean up task:
- Removing udr index component as udr docs are now pushed to the appropriate devdot omni index
- Removing udr index from Algolia property in config files
- this implementation was overriding the docs from the omni index; it's now no longer needed as udr records are not under a udr index, they are pushed to the omni index
n/a, removing commented out code
=> chore: Remove udr index component

config/base.json, config/preview.json, src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx, src/components/command-bar/commands/search/unified-search/components/unified-hits-container/helpers/gather-search-tabs-content.tsx
This PR update the zendesk algolia configuration to use the omni algolia index instead of the zendesk one. This will make the zendesk results returned in the 'All' tab without special configuration. The reason the separate index was used at first was so data in the dev and prod index could be tested without impacting the production site global results.
Since the algolia staging_DEVDOT_omni index settings were adjusted as part of this PR (and the prod ones will be adjusted after this merges as well), the search results across all tabs will be ordered differently from what they are on prod. They now are ordered based off the following criteria in order: page_title, description, …
=> feat: use omni algolia index for zendesk articles

src/data/vault.json
- [Preview link](https://dev-portal-git-rn-remove-extra-vault-tutorials-link-hashicorp.vercel.app/vault) 🔎
Removes the extra tutorials link for vault docs that was accidentally added in the PR: https://github.com/hashicorp/dev-portal/pull/2745.
=> Remove extra vault tutorials link

src/components/docs-version-switcher/index.tsx
If no previous version exists then we should hide the version picker. Otherwise it is a poor user experience and gives the user the idea that this document existed in previous versions, when it did not.
The document **might** of existed in a previous path, and got renamed/moved in a new version but our current API/data structure has no concept of that.
1. [Vault document that **has NO** previous versions](https://dev-portal-git-rn-hide-version-picker-on-singl-c7df6d-hashicorp.vercel.app/vault/docs/about-vault/what-is-vault)
1. It might of gotten renamed, but see above.
1. [Vault document that **has** previous version](https://dev-portal-git-rn-hide-version-picker-on-singl-c7df6d-hashicorp.vercel.app/vault/docs/get-started/developer-qs)
=> Hide version picker if page has no previous versions

src/components/video-embed/index.tsx, src/lib/posthog-events.ts
The current implementation only tracks video starts rather than video plays (starts and when users restart the video after clicking pause). The historic way we've tracked video plays before the video embed was whenever users clicked the CSS selector that mapped to the wisita/youtube embed. This update makes it closer to the original implementation.
We still want to keep `video_start` as a metric. This newer `video_play` metric will let us reconcile with our historical data.
1. Go to any page with a video in the deploy preview ([example](https://dev-portal-git-video-embed-ph-track-plays-hashicorp.vercel.app/terraform/tutorials/aws-get-started/infrastructure-as-code)). For event …
=> Update video embed to also track video plays

src/components/posthog/posthog-provider.tsx
This PR initializes posthog using the correct api key for whatever environment it is in. Previously it was always using the prod key for initialization.
We should be using the correct keys for the correct environments. This env variable has a check in the [next config file](https://github.com/hashicorp/dev-portal/blob/0156798af89c4a7b9ba2529eced0362b39562bbf/next.config.js#L86) that sets it for the environment
1. Go to [preview](https://dev-portal-git-leah-fixposthog-init-env-hashicorp.vercel.app/terraform/tutorials/aws-get-started/infrastructure-as-code)
2. Click play and pause on the video a few times
3. Verify the events are showing up in the [dev posthog project](https://eu.posthog.com/project/29988/activity/explore)
=> fix: initialize posthog in correct env

package-lock.json, package.json, src/components/command-bar/commands/search/unified-search/components/no-results-message/index.tsx, src/components/command-bar/commands/search/unified-search/components/unified-hits-container/index.tsx
- [Asana task](https://app.asana.com/1/90955849329269/project/1210146125607813/task/1210201394680100?focus=true) 🎟️
This PR adds an experiment for the support tab text. Currently, the text is 'Support' for the last tab in the search modal. In this experiment, we are testing if the text 'Knowledge Base' leads to higher clicks for this tab.
I also had to update the `posthog-js` package in this PR because the package we were using previously had a bug where if you tried flipping the flags on the posthog toolbar, it would not work and an error would pop up.
Control
Variant 
1. Go to [posthog](https://eu.posthog.com/project/29988/toolbar)
2. Click launch on the link that is …
=> feat: support tab text experiment

build-libs/redirects.js
- [Asana task](https://app.asana.com/1/90955849329269/project/1206815131022336/task/1210451336821731?focus=true) 🎟️
This PR updates the redirects in dev-portal so that the UDR docker image does not request redirects for hvd-docs.
UDR currently has a bug where the `make` command is failing for the dev-portal image. This is because UDR does not have access to the token necessary to pull the redirects for the hvd-docs repo since it is a private repo. 
1. Pull down this branch
2. Create a docker image: `docker build -t test-dev-portal-build . `    
3. Add that image to UDR in docker-compose.yaml on line 6
4. Run UDR using `make`
5. Verify that dev-portal builds successfully
=> fix: redirects for hvd-docs causing make to fail in UDR

package-lock.json, package.json, src/components/mobile-menu-levels-generic/index.tsx, src/components/navigation-header/components/dropdown-menu/index.tsx, src/components/sidebar/index.tsx, src/pages/tutorials/library.tsx, src/views/profile/sidebar/index.tsx
- [Preview link](https://dev-portal-git-leah-featproduct-dropdown-experiment-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1206815131022336/task/1210201394680102?focus=true) 🎟️
This PR adds an experiment to move the promo placement in the product dropdown. Currently, the promo is underneath under the products in the dropdown (control) but this experiment will be moving it to the top of the dropdown for half of users (variant). I am using the autocapture event where the element text is 'All HCP Products' to track the primary metric in this experiment
We want to see if changing the position of this element will lead to higher clicks.
| Desktop | Mobile |
| --- | --- |
| <img width="1109" alt="Screenshot 2025-06-19 at 2 35 33 PM" …
=> feat: product dropdown promo placement experiment

src/lib/remark-plugins/remark-rewrite-assets.ts
- [Preview link](https://dev-portal-git-rn-update-img-wrapped-in-links-in-udr-hashicorp.vercel.app/) 🔎
[We currently have a case where an image wrapped in a link to that image](https://hashicorp.slack.com/archives/C09K1N960/p1750692279277449), so folks can easily see a bigger version of that image is not updating to the newest image URL. This is because we are now serving images through an API.
This PR adds a special case to our rewrite image remark plugin to handle that case.
=> Update link url in UDR it if wraps an img and both share a url

src/content/certifications/exam-faqs/terraform-associate-003.mdx, src/content/certifications/exam-faqs/vault-associate-003.mdx, src/content/certifications/programs/security-automation.json
I fixed the exam version, as somehow this was incorrect
- [Preview link](https://dev-portal-git-BE_nites-hashicorp.vercel.app/certifications/security-automation) 🔎
=> Nits: Vault version & URLs

src/hooks/use-authentication/helpers/make-sign-in.ts, src/hooks/use-authentication/index.ts
- Memoize last captured user Id using useRef
- Added guards to prevent duplicate firing on auth state changes
- Avoided structural changes to keep the patch low-risk and self-contained
- [Preview link](https://dev-portal-git-ericat-choreposthog-auth-event-dedupe-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1210546436661486/task/1209865393442034?focus=true) 🎟️
This PR fixes an issue where the user_authenticated PostHog event was firing mutliple times per session due to layout-level hook usage and rerenders triggered by auth transitions.
The original uer_authenticated PostHog event was firing multiple times per session. This was caused by how the useAuthentication hook is invoked at layout level. It ran anytime the app layout mounts, rehydrates or …
=> Fix duplicate PostHog user_authenticated event due to layout re-renders

build-libs/__tests__/get-latest-content-sha-for-product.test.ts, build-libs/redirects.js
- [Preview link](https://dev-portal-git-rm-fix-terraform-enterprise-redirects-hashicorp.vercel.app/) 🔎
Adds products (mostly `terraform-*` but others too like WAF to the `PRODUCT_REDIRECT_ENTRIES` array to fix redirects in devdot.
Redirects are currently not working due to devdot not requesting the array of redirects from UDR
If I `curl` the redirects endpoint for terraform enterprise(filtering for the source path we're interested in), like so:
```bash
curl 'https://web-unified-docs-hashicorp.vercel.app/api/content/terraform-enterprise/redirects' | jq '.[] | select(.source | contains("terraform/enterprise/system-overview/capacity"))'
```
I get this:
```json
{
"source": "/terraform/enterprise/system-overview/capacity",
"destination": …
```
=> Add terraform-enterprise to redirect array

src/views/docs-view/utils/__tests__/get-valid-versions.test.ts, src/views/docs-view/utils/get-valid-versions.ts
Remove the version filtering logic for the time being and just return ALL versions. This will cause a TON of 404s and is only a temporary measure to get things going
1. Go to path on developer.hashicorp.com with versioned docs (i.e: `/vault/docs/deploy/aws/run`)
2. Observe that no documents below 1.19.x are available in the version picker dropdown
3. Go to the same path in the preview link
4. Observe that all versions are available, however any version below v1.19.x goes to a 404
=> Return all versions without filtering

src/data/terraform.json
- [Preview link](https://dev-portal-git-atru-add-beta-badge-mcp-server-hashicorp.vercel.app/terraform) 🔎
This PR adds a beta badge in the main Terraform sidebar navigation for the MCP server docs.
Because MCP server is still in beta.
=> Add beta to mcp server nav item
