hashicorp/dev-portal

README.md

> Note: preview links are not applicable, this is a README change only.
> - [ ] The Vercel preview link has been added to this PR's description
> - [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
---
> - Preview link 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201468185072167/f) 🎟️
This PR adds a short note on local preview for `.io` sites to the project's README.
To clarify the steps to preview co-located `.io` site content, and to provide helpful contextual links to relevant documents.
Not applicable, just a README change.
Not applicable, just a README change.
Nope.
---
- https://app.asana.com/0/0/1201468185072167

docs: add README note on local preview of dot-io sites

---

config/proxy-config.js
src/lib/env-checks.js

---
Testing supporting multiple proxy hosts, for Waypoint specifically, using regex.
---
- https://app.asana.com/0/0/1201641390947372

feat: test multiple hosts for waypoint

---

config/proxy-config.js

---
Update the proxy config for the waypoint cutover so that www.waypointproject.io correctly proxies to the waypoint site.

feat: update proxy config for waypoint cutover

---

package-lock.json
package.json
src/data/waypoint.json
src/layouts/_proxied-dot-io/waypoint/index.tsx

---
Adding the `usePageviewAnalytics` hook to the waypoint layout component.
Ensures we're sending analytics to fathom for waypointproject.io

fix(waypoint): adds analytics hook to layout

---

src/data/waypoint.json
src/layouts/_proxied-dot-io/waypoint/index.tsx

---
Adds `segmentWriteKey` to our product data object and pass it to the consent manager
Ensures that the segment snippet is correctly loaded

fix: pass segment write key consent manager

---

config/products.ts
config/redirects.js
config/rewrites.js
next.config.js
package-lock.json
package.json
src/components/_proxied-dot-io/common/preview-product-select/index.tsx
src/components/_proxied-dot-io/common/preview-product-select/style.module.css
src/pages/_app.tsx
src/types/products.ts

---
- [Preview link](https://dev-portal-git-brkfeat-io-preview-cookie-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201722975655660/f) 🎟️
Implements an adjusted version of @ashleemboyer's product switcher to drive switching between io sites for deploy previews.
This will allow us to preview io site changes easily!
Implement rewrites using a cookie check. We look at the `io_preview` cookie's value and if it matches a product slug, we rewrite to its io site.
Note: this code will be thrown away at some point, and is largely a copy-paste of Ashlee's initial work, so I'm considering it to have a lower quality bar. 😅

feat: io preview via cookie

---

src/data/waypoint.json
src/lib/fetch-release-data.ts
src/lib/fetch-with-retry.ts
src/pages/_proxied-dot-io/waypoint/downloads/index.jsx

---
- [Preview link](https://dev-portal-git-brkfeat-downloads-derive-latest-84be77-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201722975655666/f) 🎟️
Derive `latestVersion` from the data fetched from releases.hashicorp.com
In order to reduce the reliance on manually bumping a version for a product release, we want to derive it automatically.
I copy-pasted the downloads page server code and made some adjustments

feat(downloads): derive the latest version from the fetched releases data

---

package-lock.json
package.json
src/components/card-link/card-link.module.css
src/components/card-link/docs.mdx
src/components/card/card.module.css
src/components/disclosure/disclosure.module.css
src/components/disclosure/docs.mdx
src/components/disclosure/index.tsx
src/components/disclosure/types.ts
src/components/navigation-header/style.module.css

---
- [Preview link](https://dev-portal-git-ambadd-disclosure-component-hashicorp.vercel.app/swingset/components/disclosure) 🔎
- [Asana task](https://app.asana.com/0/0/1201654639085728/f) 🎟️
- new `Disclosure` component and swingset page
- upgrades `@hashicorp/design-system-tokens` to `^0.4.7`
- using new `--token-surface-high-box-shadow` and `--token-focus-ring-box-shadow` tokens
- updated a few CSS comments to be shorter
- See [the internal Digital Team RFC for this component](https://www.notion.so/hashicorp/DevDot-New-Disclosure-Component-96108613ea114bbab8f6f840b357f167) for discussion on this component's implementation and future placement in DevDot
- The `@hashicorp/design-system-tokens` upgrade enables us to use new tokens for hover and focus states!
- I mainly modeled this off of …

Add Disclosure component

---

src/data/waypoint.json
src/views/_proxied-dot-io/versioned-error/index.tsx

---
- [Preview link](https://dev-portal-git-brkfix-error-view-href-hashicorp.vercel.app/docs/v0.5.x/kubernetes/external-build) 🔎
- Fixes incorrect `href` properties in the DOM on the error view. They were containing segments of the proxied path (e.g. `/_proxied-dot-io/`, even though none of the props or state values had those segments on the client.
- Force the error view to remount during rendering so it renders the correct values.
- Previous discussion from the initial PR: https://github.com/hashicorp/dev-portal/pull/92#discussion_r803202803

fix(_error): incorrect href for links

---

package-lock.json
package.json
src/components/tabs/components/tab/index.tsx
src/components/tabs/components/tab/types.ts
src/components/tabs/index.tsx
src/components/tabs/types.ts
src/layouts/sidebar-sidecar/utils/_local_platform-docs-mdx/index.jsx
src/pages/_app.tsx

Mainly making this as a draft PR for the preview link + discussion, and preventing the main tabs branch from getting too tangly if this approach ends up not working. Won't require review since it's going into a branch that _will_ be reviewed before it gets merged into the assembly branch.

[EXPERIMENT] Generate Tabs ids with react-aria

---

README.md

---
Adds a note to README on setting `GITHUB_TOKEN`
To prevent running into API rate limit for unauthenticated requests, which prevents running `npm run build`

Add note on GITHUB_TOKEN usage

---

src/components/footer/index.tsx
src/components/footer/style.module.css
src/components/footer/types.ts

---
- [Preview link](https://dev-portal-git-ambfix-cookie-manager-text-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201794573284204/f) 🎟️
The "Cookie Manager" text in the footer was smaller than the other text, this PR makes all the text consistent in size and weight with the `Text` component. I also refactored `Footer` to iterate over an array of objects to render content instead of having each item manually typed out, to reduce repeated code and also to make sure each item always gets the same shared class names and other properties passed to them.
Nope!

Fix cookie manager text

---

scripts/migrate-io/migrate-nomad.js
src/pages/_proxied-dot-io/nomad/api-docs/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/docs/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/intro/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/plugins/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/tools/[[...page]].tsx

---
- [Preview link](https://dev-portal-git-dsnomad-placement-hashicorp.vercel.app/) 🔎
Adds the `<Placement>` component which was missed in the initial migration.

Add Placement component for Nomad

---

README.md
config/development.json
config/preview.json
config/production.json
global.d.ts
next.config.js
package-lock.json
package.json
src/lib/_proxied-dot-io/get-static-generation-functions.ts
src/pages/_proxied-dot-io/boundary/docs/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/api-docs/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/docs/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/intro/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/plugins/[[...page]].tsx
src/pages/_proxied-dot-io/nomad/tools/[[...page]].tsx
src/pages/_proxied-dot-io/sentinel/sentinel/[[...page]].tsx
src/pages/_proxied-dot-io/sentinel/sentinel/intro/[[...page]].tsx
src/pages/_proxied-dot-io/vault/api-docs/[[...page]].tsx
src/pages/_proxied-dot-io/vault/docs/[[...page]].tsx
src/pages/_proxied-dot-io/vault/intro/[[...page]].tsx
src/pages/_proxied-dot-io/waypoint/commands/[[...page]].tsx
src/pages/_proxied-dot-io/waypoint/docs/[[...page]].tsx
src/pages/_proxied-dot-io/waypoint/plugins/[[...page]].tsx

---
- [Preview link](https://vercel.com/hashicorp/dev-portal/8LKTABJFSW342T7oKXNJBbNx3nH4) 🔎
- [Asana task](https://app.asana.com/0/1100423001970639/1201745229608930/f) 🎟️
Introducing a lightweight config pattern, which makes config values available via a global `__config` object. Building off of that, I added an `__config.io_sites.max_static_paths` value, which I used in a wrapper around `getStaticGenerationFunctions` to ensure that we only render 10 static paths per dynamic docs route.
Mini-RFC for the config approach: https://www.notion.so/hashicorp/dev-portal-application-config-d39ba8dff9924edf84e8d67d7229c3c2
Our deploy preview build times were a bit slow (5m), with this change they are less than 2m. This will speed up iterations and reduce unnecessary load on our content API.
Speed …

feat: add basic config, limit static paths

---

README.md
config/development.json
config/preview.json
config/production.json
next.config.js
package-lock.json
package.json

---
Introduces the new app configuration implementation to the UI branch. Access values defined in the environment configs in `config/` via the global `__config`.
This will allow us to define global config values which we can use throughout the app! They will get replaced at build time with the associated value, so it will also unlock some new patterns leveraging dead code elimination to exclude certain code paths from the production build.
Using webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/), we can statically replace each reference to a config value with its literal value. The `HASHI_ENV` environment variable controls which environment file is loaded at build time.
See [the original …

feat: introduce app config for the UI branch

---

config/production.json

---
- [Preview link](https://dev-portal-git-ambenable-new-install-view-flag-hashicorp.vercel.app/waypoint/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201885695157815/f) 🎟️
This enabled the new install view for the Waypoint downloads page.
Time to get this page out for testing! 🎉
Flipped the `enable_new_downloads_view` in `config/production.json` to `true`. 😊
- The version switcher is not yet inside of the Operating System card but will be soon.
- The version switcher is currently a plain HTML <select> element, the designed component has not yet been implemented but is coming soon.
- The `CodeTabs` component is not being used under OSes with many package managers because we found a bug in the component that has to be fixed and released from another repo. For now we are using the …

Enable new install view for Waypoint

---

.github/workflows/docker_publish.yml
Dockerfile

feat: multi-arch docker images

---

config/redirects.js

---
- [Preview link](https://dev-portal-git-dspacker-redirects-hashicorp.vercel.app/) 🔎
Adds Packer's redirects (which were missing from the initial migration).

Add Packer redirects

---

src/pages/_app.tsx

---
- [Preview link](https://dev-portal-git-ambadd-code-tabs-provider-hashicorp.vercel.app/vault/docs/get-started/developer-qs#step-3-authenticate-to-vault) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201819583594273/f) 🎟️
- Wraps the whole site in `CodeTabsProvider` in `src/pages/_app.tsx`
- This enables CodeTabs components within the same page to be synced if they've been specified to be in the same group.
- I decided to place it in `_app.tsx` because we plan to have wider usage of `CodeTabs` beyond pages that render `DocsView`, such as in install views. We can easily move it later if needed!
Imported code, and then wrapped content with the `CodeTabsProvider`. EZPZ. 😎 
Nope!

Add CodeTabsProvider

---

src/data/vault.json
src/pages/_proxied-dot-io/vault/use-cases/[slug].tsx

---
This PR updates Vault to source its favicon from Dato, and updates the `/use-cases` pages to set their `revalidate` from `__config`.

fix: update Vault favicon and use __config for revalidate setting

---

src/data/nomad-install.json
src/pages/nomad/downloads/index.tsx

---
- [Preview link](https://dev-portal-git-ambadd-nomad-install-view-hashicorp.vercel.app/nomad/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201893669632602/f) 🎟️
- Adds `src/data/nomad-install.json`, which contains the data needed for Nomad's `ProductDownloadsView`
- Adds `src/pages/nomad/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
Using the same process as #140 and #143 😊
Nope!

Add new install view for Nomad

---

src/lib/cms.ts

---
Removes some console.log statements that accidentally made their way into `main`

fix: remove leftover console.logs

---

src/data/packer.json
src/pages/_proxied-dot-io/packer/index.jsx

---
- [Preview link](https://dev-portal-git-pbpacker-alert-banner-update-hashicorp.vercel.app/_proxied-dot-io/packer) 🔎
- [Asana task](https://app.asana.com/0/0/1201782466382221/f) 🎟️
Update packer's alert banner data and hero for proxied packer site. Should match https://packer-git-pbalert-banner-hashicorp.vercel.app/
To announce the HCP Packer updates
Just changed some text 😇
Do not merge until Monday 3/7

Packer Updates

---

src/data/boundary-install.json
src/pages/boundary/downloads/index.tsx

---
- [Preview link](https://dev-portal-git-ambadd-boundary-install-view-hashicorp.vercel.app/boundary/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201893669632603/f) 🎟️
- Adds `src/data/boundary-install.json`, which contains the data needed for Boundary's `ProductDownloadsView`
- Adds `src/pages/boundary/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
Using the same process as:
- #140
- #143
- #148
- #150
- #151
Nope!

Add new install view for Boundary

---

src/data/terraform-install.json
src/pages/terraform/downloads/index.tsx

---
- [Preview link](https://dev-portal-git-ambadd-terraform-install-view-hashicorp.vercel.app/terraform/downloads) 🔎
- [Asana task](https://app.asana.com/0/0/1201893669632607/f) 🎟️
- Adds `src/data/terraform-install.json`, which contains the data needed for Terraform's `ProductDownloadsView`
- Adds `src/pages/terraform/downloads/index.tsx`, which conditionally renders the new downloads view based on the `enable_new_downloads_view` flag
Using the same process as:
- #140
- #143
- #148
- #150
- #151
- #170
Nope!

Add new install view for Terraform

---

package-lock.json
package.json
src/lib/learn-client/api/api-types.ts
src/lib/learn-client/api/collection/fetch-product-collections.ts
src/lib/learn-client/api/collection/formatting.ts
src/lib/learn-client/api/collection/index.ts
src/lib/learn-client/api/tutorial/augment-tutorial.ts
src/lib/learn-client/api/tutorial/formatting.ts
src/lib/learn-client/api/tutorial/index.ts
src/lib/learn-client/api/utils/fetch-all.ts
src/lib/learn-client/api/utils/index.ts
src/lib/learn-client/index.ts
src/lib/learn-client/types.ts
src/lib/strip-undefined-props.ts
src/pages/waypoint/tutorials/[...tutorialSlug]/index.tsx
src/pages/waypoint/tutorials/[collectionSlug].tsx
src/pages/waypoint/tutorials/index.tsx
src/views/tutorial-view/helpers.ts
src/views/tutorial-view/index.tsx
src/views/tutorial-view/server.ts

---
- [Preview link](https://dev-portal-git-kslearn-scaffold-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro) 🔎
- [Asana task](https://app.asana.com/0/home/1199634971443477/1201936772955808) 🎟️
This PR adds routing for the waypoint tutorial product hub, collection, and individual tutorial pages. It also adds basic data fetching for the tutorial page and copies over collection and tutorial methods from the [learn client](https://github.com/hashicorp/learn/tree/master/client). 
This PR is a skateboard 🛹 , setting up some initial plumbing for the learn views. Additional PRs will add skeleton components for the tutorial view and data fetching for the collection and product hub pages. 
I created a new directory in `lib` to house the learn API client - …

feat: learn tutorial scaffold

---

config/development.json
config/preview.json
config/production.json
src/layouts/sidebar-sidecar/server.ts
src/pages/waypoint/tutorials/[...tutorialSlug]/index.tsx

---
- [Preview link](https://vercel.com/hashicorp/dev-portal/3EmtHSDBv7tKmyHE3kZy1TV4JTiS) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201971457671029/f) 🎟️
Limit static paths for dev dot and learn routes. Added new config values to accomplish this in the same way we have already done for the .io sites.
Statically generating every page significantly slows down builds (30m with no limits). With this configuration in place, we can tweak the io site limit, dev dot limit, and learn limits individually.
Adding new config values for `dev_dot.max_static_paths` and `learn.max_static_paths`. Static paths generated goes from ~5000 to ~790
---
- https://app.asana.com/0/0/1201971457671029

feat: limit static paths for dev dot and learn routes

---

config/project-preview.json

---
Adds a new `project-preview.json` config file.
This enables us to target deploy previews for separate projects, such as in hashicorp/waypoint. We'll want to do full static generation for these deployments, so using config to enable that. Those projects will set `HASHI_ENV=project-preview` and they'll be able to leverage this config file.

feat: add project-preview config file

---

src/views/product-downloads-view/components/sidecar-marketing-card/index.tsx
src/views/product-downloads-view/components/sidecar-marketing-card/sidecar-marketing-card.module.css

---
- [Preview link](https://dev-portal-git-ambfix-sidebar-marketing-card-font-hashicorp.vercel.app/waypoint/install) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201959792840221/f) 🎟️
- Fixes the size of `SidecarMarketingCard` title
- Fixes the hover state of `SidecarMarketingCard` featured docs links
Because they were incorrect based on designs. 😊
- `SidecarMarketingCard` title size was easy to change with the `size` prop
- `SidecarMarketingCard` featured docs links were also easy to change via an existing CSS class
Nope!

Fix some SidecarMarketingCard text styles

---

src/components/tabs/tabs.module.css

---
- [Preview link](https://dev-portal-git-ambfix-tabs-hover-state-hashicorp.vercel.app/swingset/components/tabs) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201893669632623/f) 🎟️
- Adds missing hover state styling for Tab buttons
- This was supposed to be here all along, but was missed when the `Tabs` component was originally built.
- Looked at [the Figma designs for `Tabs`](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Dev-Portal?node-id=2812%3A55880) and used the associated HDS tokens for the text color and `Tab` button background.
Nope!

Adding hover state for Tab buttons

---

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css

---
- [Preview link](https://dev-portal-git-ambset-img-background-white-hashicorp.vercel.app/waypoint/docs/kubernetes/resource-status#viewing-resource-status) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201959792992319/f) 🎟️
Sets `background-color` of `img` elements rendered in `SidebarSidecarLayout` content to `white`.
This is an early step for supporting dark mode in the future. We have some transparent images that would lose readability on dark backgrounds.
CSS 🪄
Nope!

Setting img backgrounds in content to white

---

src/data/README.md
src/data/types.d.ts

---
This PR adds JSDoc comments for all the properties used in `src/data/<product>.json` files, and updates the README within that folder to reference the types.

Add docs for ProductData properties

---

config/products.ts
package.json
src/data/README.md
src/types/products.ts

---
- [Preview link](https://github.com/hashicorp/dev-portal/blob/amb.add-dev-dot-json-data-docs/src/data/README.md) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201959792840210/f) 🎟️
- Adds DevDot details for `{product-slug}.json` files in `src/data/README.md`
- Adds some `<details>/<summary>` elements to existing section of docs
- Adds `ProductName` type
- Adds `productSlugsToNames` map in `config/products.ts`
- Adds `typecheck` npm script in `package.json`
See the annotations via PR comment below.
Nothing special to test, just make sure [the README file](https://github.com/hashicorp/dev-portal/blob/amb.add-dev-dot-json-data-docs/src/data/README.md) reads well and the PR checks pass. 😊
Nope!

Adding <product>.slug DevDot docs in src/data/README

---

.github/workflows/nextjs_bundle_analysis.yml

---
N/A
Removes reference to `assembly-ui-v1` in `.github/workflows/nextjs_bundle_analysis.yml`
The `assembly-ui-v1` branch has been merged! 🎉
Cut out the code 🔪

Removing assembly branch from bundle analysis

---

README.md

---
Fixes a typo in the README

docs: drop the "the", it's cleaner

---

src/data/vagrant.json

---
Updates vagrant's search key, as it is not currently working (try searching here https://test-vg.hashi-mktg.com/docs)

fix: update search key for vagrant

---

package-lock.json
package.json
src/layouts/_proxied-dot-io/vault/index.tsx

---
- [Preview link](https://dev-portal-8kve4fap0-hashicorp.vercel.app/) 🔎
Adding `onAcceptAll` and `onManagePreferences` callbacks to vault consent manager config.
Track Fathom events on accepting and managing consent preferences.
Update consent manager package, and adding callbacks to config.
Fathom events only fire in production envs, so there isn't a solid way to detect events are firing until this code is live.

chore(vault): add fathom events to consent manager

---

src/layouts/base-new/index.tsx
src/pages/_app.tsx

---
We we're loading to consent managers on the page.
Ensure only one consent manager is present on the page.
Remove consent manager from top level `_app.tsx`

chore: remove duplicate consent manager from _app

---

next.config.js

---
I noticed that our preview builds were generating the number of static paths that I would expect from a production build. Did some sleuthing and found out that our usage of DefinePlugin was being cached across builds with different `HASHI_ENV` values. This means our static paths limit for production was applying to preview builds, no good! Thankfully, `DefinePlugin` has a built-in mechanism to address this. I've updated the implementation to take `HASHI_ENV` into account so that when the value changes, webpack will invalidate its cache.
More info: https://github.com/webpack/webpack/issues/10249

fix: ensure webpack does not cache incorrect config values across builds

---

src/pages/_app.tsx

- [Preview link](https://dev-portal-git-ambfix-hydration-check-hashicorp.vercel.app/) 🔎
- Removes product hydration check, fingers crossed that some in-progress TS refactors will get us the same affect as the error

Fixing hydration check in App

---

src/pages/_proxied-dot-io/boundary/api-docs/[[...page]].jsx

---
Support reading a local swagger file for API docs to allow deploy and local previews of any changes. Without this, if the swagger doc was changed in a PR, the deploy preview in hashicorp/boundary would not reflect those changes.

feat(boundaryproject.io): support reading local swagger file for api docs

---

.github/workflows/playwright.yml

---
Switch our e2e tests to only run against preview deployments.
These tests are written to validate against preview deployments at the moment. Our production deploys don't support the `io_preview` cookie and so they will fail every time.
Checking that `github.event.deployment.environment == 'preview'` before running the job.

chore(e2e): only run playwright tests on preview deployments

---

src/layouts/_proxied-dot-io/consul/index.tsx
src/layouts/_proxied-dot-io/dict.js
src/lib/_proxied-dot-io/fetch-layout-props.ts
src/lib/cms.ts
src/pages/_app.tsx
src/pages/_error.jsx

---
- Implement the missing .io layouts in our product layout map.
- Abstract out the layout prop fetching from `App.getInitialProps` into `fetchLayoutProps` so we can reuse it in our error component
Ensure we can correctly render an error page with the right layout for any given .io site with all of the necessary data.

feat: add missing error layouts, use next/dynamic

---

package-lock.json
package.json
src/layouts/core-dev-dot-layout/core-dev-dot-layout.module.css

---
- [Preview link](https://dev-portal-git-ambupdate-ds-font-tokens-hashicorp.vercel.app/) 🔎
- Updates `@hashicorp/design-system-tokens` to `0.8.0`
- Updates `--font-body`, `--font-display`, `--font-monospace` CSS variables in `CoreDevDotLayout` to reference DS tokens
- The tokens referenced in these changes were updated in `0.8.0`, so that's why the package version was updated.
- We're updating our CSS variables to reference DS tokens for consistency and lower maintenance. 😊
Nope!

Use updated DS font stack tokens

---

config/redirects.js

---
Update consul redirect path after it got moved recently.

fix(redirects): update consul redirect path

---

src/pages/_proxied-dot-io/boundary/community/index.jsx
src/pages/_proxied-dot-io/boundary/index.jsx
src/pages/_proxied-dot-io/boundary/security/index.tsx
src/pages/_proxied-dot-io/consul/community/index.jsx
src/pages/_proxied-dot-io/consul/consul-on-kubernetes/index.tsx
src/pages/_proxied-dot-io/consul/security/index.tsx
src/pages/_proxied-dot-io/nomad/community/index.jsx
src/pages/_proxied-dot-io/nomad/index.jsx
src/pages/_proxied-dot-io/nomad/security/index.tsx
src/pages/_proxied-dot-io/packer/community/index.jsx
src/pages/_proxied-dot-io/packer/index.jsx
src/pages/_proxied-dot-io/packer/security/index.tsx
src/pages/_proxied-dot-io/vagrant/community/index.jsx
src/pages/_proxied-dot-io/vagrant/security/index.tsx
src/pages/_proxied-dot-io/vault/community/index.jsx
src/pages/_proxied-dot-io/vault/security/index.tsx
src/pages/_proxied-dot-io/waypoint/community/index.jsx
src/pages/_proxied-dot-io/waypoint/copyright-policy/index.jsx
src/pages/_proxied-dot-io/waypoint/index.tsx
src/pages/_proxied-dot-io/waypoint/security/index.tsx
src/pages/_proxied-dot-io/waypoint/terms/index.jsx

---
Adds an empty `getStaticProps` function to all static pages.
Since we use `_app.getInitialProps`, pages have to be marked explicitly as being SSG capable by adding a `getStaticProps` function.
Adds a `getStaticProps` function that returns an empty object for all pages that can be SSG.
- Confirm that the build logs for this PR in Vercel denote the modified pages with a `●` symbol instead of a `λ`
---
- https://app.asana.com/0/0/1202043114644928

feat: use empty getStaticProps to allow for SSG

---

config/redirects.js

---
Updating redirect location based on its recent move: https://github.com/hashicorp/vault/pull/14910

chore: update vault redirect source

---

src/components/_proxied-dot-io/boundary/how-it-works/how-boundary-works-diagram/how-boundary-works-diagram.module.css
src/components/_proxied-dot-io/consul/downloads-props/index.jsx
src/components/_proxied-dot-io/consul/subnav/index.jsx
src/components/_proxied-dot-io/packer/subnav/index.jsx
src/components/_proxied-dot-io/vault/subnav/index.jsx
src/components/_proxied-dot-io/waypoint/footer-with-props/index.tsx
src/pages/_proxied-dot-io/boundary/downloads/index.jsx
src/pages/_proxied-dot-io/vagrant/downloads/index.jsx
src/pages/_proxied-dot-io/vault/downloads/index.jsx

---
Applies `prettier` formatting to `_proxied-dot-io` pages and components
It's annoying to have prettier automatically apply when you're working on a feature since it increases the noise in your PR.
`npx prettier --write` and only commit files that are in `_proxied-dot-io` folders.
N/A

chore: fix formatting

---

.eslintrc.js
config/proxy-settings.js
config/redirects.js
package-lock.json
package.json
postcss.config.js
scripts/capture-build-metrics.ts
src/components/_proxied-dot-io/consul/config-entry-reference/index.jsx
src/components/_proxied-dot-io/consul/downloads-props/index.jsx
src/components/_proxied-dot-io/consul/subnav/index.jsx
src/components/_proxied-dot-io/packer/subnav/index.jsx
src/components/_proxied-dot-io/vault/subnav/index.jsx
src/components/_proxied-dot-io/waypoint/footer-with-props/index.tsx
src/hooks/use-on-click-outside.js
src/hooks/use-on-focus-outside.js
src/layouts/sidebar-sidecar/components/table-of-contents/use-active-section.ts
src/layouts/sidebar-sidecar/components/table-of-contents/utils/get-truncated-title.ts
src/layouts/sidebar-sidecar/utils/product-url-adjusters.ts
src/pages/_proxied-dot-io/boundary/downloads/index.jsx
src/pages/_proxied-dot-io/vagrant/downloads/index.jsx
src/pages/_proxied-dot-io/vault/downloads/index.jsx
src/pages/_proxied-dot-io/waypoint/copyright-policy/index.jsx
src/pages/_proxied-dot-io/waypoint/terms/index.jsx
src/views/404/index.jsx
src/views/_proxied-dot-io/vault-docs-landing/components/featured-card/style.module.css
src/views/_proxied-dot-io/vault-docs-landing/style.module.css
src/views/product-downloads-view/components/downloads-section/index.tsx

---
Updating our eslint config to not apply TS-specific rules to js files, and in our shared config not specify a deprecated parser.
.js files did not appear to be getting linted!

chore(eslint): update ts rules to overrides, use parser from eslint-config-next

---

src/data/waypoint-install.json

This PR updates the Waypoint download links. 
---
- [Preview link](https://dev-portal-ea31h2dbd-hashicorp.vercel.app/waypoint/downloads) 🔎
- [Asana task](https://app.asana.com/0/1201979547919485/1201979547919574) 🎟️
These changes are the result of a Dev Portal review asked from the Education team.
I changed the tutorials cards to focus on two themes. Getting started, and cloud providers. 
The first row focuses on the generic getting started, and the Kubernetes, and Nomad collection. I removed the Install, as it is redundant with the existing information on the page. The second row targets the cloud providers, which are more common usecases and more relevant to the practittioner.

docs: waypoint download page changes

---

src/data/vault.json

---
This PR updates the alert banner for Vault's website.
- [Preview link](https://dev-portal-git-nq-update-vault-alert-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/346384260719996/1202006133761616/f) 🎟️

[DO NOT MERGE TIL 4/7] chore(vault): Update alert banner

---

src/data/vault.json

---
- [Preview link](https://dev-portal-git-nq-update-alert-banner-4-7-2022-hashicorp.vercel.app/) 🔎
This PR adjusts the alert banner text of vaultproject.io to match that of hashicorp.com/products/vault.

chore(vault): Update alert banner

---

package.json

---
- [Preview link](https://dev-portal-git-ambupdate-precommit-hook-hashicorp.vercel.app/) 🔎
- Updates our precommit hook to run `npm run typecheck` after it runs `npx next-hashicorp precommit`
- Adds a `prepare` npm script that runs `simple-git-hooks`
We can often run into the problem of pushing code to a branch that doesn't pass the typecheck. This will always cause builds to fail, which means build resources can be unnecessarily wasted. The resulting actions we have to take after this to fix TypeScript issues is also a tedious and manual process that has a lot of opportunities to get distracted in between steps.
Here's an example situation the updated `pre-commit` helps save time and lowers risk for distraction. I've broken down the process into atomic steps to demonstrate how many …

Add typecheck to pre-commit hook; Add prepare npm script

---

src/components/navigation-header/index.tsx
src/types/products.ts
src/views/collection-view/helpers.ts

Fixes references to old beta slugs config variable name, issue was caused by me merging #271! 🙏🏻

Fix beta slugs references

---

src/data/waypoint-landing.json

---
- [Preview link](https://dev-portal-f7a2ttml1-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/1201979547919485/1201979547919558) 🎟️
I reviewed the content of the Waypoint docs landing page. I made changes to the docs landing page. 
The tutorials highlighted are the same as on the download page. Waypoint does not have enough content to really highlight from a Learn perspective. We are better off calling attention to the big three cloud providers and the tutorials we have for each cloud provider.
I updated the `waypoint-landing.json` file.
N/A

docs: updated the tutorial list for the Waypoint docs landing page

---

config/index.js
jest.config.ts

---
I forgot to push this up to #285 before merging 😅  Ensures we throw an error when we failed to load config, instead of continuing on with an empty object. This should make us _fail faster_ if there are any config problems.

feat: throw on config load error

---

src/data/vault-install.json

This replaces lorem ipsum on the download page sidecar for Vault.
---
- [Preview link](https://dev-portal-git-ggvault-install-content-hashicorp.vercel.app/vault/downloads) 🔎
- [Asana task](https://app.asana.com/0/1201979547919485/1201979547919566) 🎟️
Update the sidecar description from the official tagline for Vault.
Lorem ipsum was the only placeholder text previously.

Update Vault description on install page

---

src/components/standalone-link/standalone-link.module.css

---
- [Preview link](https://dev-portal-me9e50ndk-hashicorp.vercel.app/) 🔎
- [Github comment](https://github.com/hashicorp/dev-portal/pull/295#pullrequestreview-939812419) 👀 
Fixing issue where icon would not preserve its sizing.
https://github.com/hashicorp/dev-portal/pull/295#pullrequestreview-939812419
Adds `flex-shrink: 0` to preserve sizing.

fix: `<StandaloneLink />` icon shrinking

---

src/data/vault-install.json
src/data/vault-landing.json

---
- [Preview link - Home](https://dev-portal-git-yhvault-pages-hashicorp.vercel.app/vault) 🔎
- [Asana task](https://app.asana.com/0/1201712347646323/1201979547919539/f) 🎟️
- [Preview link - Install](https://dev-portal-git-yhvault-pages-hashicorp.vercel.app/vault/downloads) 🔎
- [Asana task](https://app.asana.com/0/563192436488770/1201979547919566/f) 🎟️
This PR:
- Updates the [/src/data/vault-landing.json](https://github.com/hashicorp/dev-portal/blob/main/src/data/vault-landing.json) file to replace the place-holder contents.
- Updates the [/src/data/vault-install.json](https://github.com/hashicorp/dev-portal/blob/main/src/data/vault-install.json) with installation related **Featured Tutorials**.
To finalize the Vault home page with _what I think_ most useful starting points.

[Vault] Home & Install pages contents

---

build-libs/__tests__/redirects.test.ts
build-libs/redirects.js
src/__tests__/e2e/redirects.spec.ts
src/pages/_middleware.ts

---
Handling simple redirects which are not associated with a product. This isn't having any user-facing impact at the moment, but deploy previews in our product repos will benefit from this change. As we add redirects specific for dev-portal, this will also be necessary as well.

chore: handle simple redirects not associated with a product

---

package-lock.json
package.json
tsconfig.json

---
Adds the new `@hashicorp/platform-configs` package, and uses the shared Next.js `tsconfig`.
Using a shared configuration allows us to roll out configuration changes across all properties with package updates. It also helps enforce standards by requiring us to explicitly deviate from the shared config.
Adds the following to our `tsconfig.json` file:
```json
"extends": "@hashicorp/platform-configs/tsconfig/next.json",
```
- `npm run typecheck`

Use shared Next `tsconfig`

---

config/base.json
config/preview.json
config/production.json
src/pages/index.tsx

---
Adds new feature flag for homepage work.
Need to be able to build out the new homepage without disrupting current homepage.
Add new feature flag to config.

feat(homepage): add new homepage feature flag

---

package-lock.json
package.json

---
Upgrade hc-tools so that the `build:deploy-preview` script works with our abstracted tsconfig.

chore: upgrades hc-tools

---

src/pages/index.tsx
src/views/homepage/components/pre-footer/index.tsx
src/views/homepage/components/pre-footer/pre-footer.module.css
src/views/homepage/index.tsx

---
- [Preview link](https://dev-portal-git-achomepagehelp-section-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1200641486648086/1202112386641585) 🎟️
Implements homepage `<PreFooter />` component.
For new homepage implementation.
Final content is being handled in follow up task https://app.asana.com/0/1200641486648086/1202112386641621

feat(homepage): `<PreFooter />`

---

src/pages/index.tsx
src/views/homepage/index.tsx

feat(homepage): Assembly

---

src/components/navigation-header/components/dropdown-menu/dropdown-menu.module.css
src/components/navigation-header/components/product-page-content/product-page-content.module.css

---
- [Preview link](https://dev-portal-git-ambaddress-nav-feedback-hashicorp.vercel.app/waypoint) 🔎
- Asana tasks 🎟️
- [Nav has too much spacing to the left of Home dropdown](https://app.asana.com/0/1202097197789424/1202111590267537/f)
- [Home dropdown has bottom-left corner radius](https://app.asana.com/0/1202097197789424/1202111590267560/f)
- [Home dropdown positioning incorrect when opening](https://app.asana.com/0/1202097197789424/1202118922745531/f)
This PR makes 3 adjustments to the H menu that shows in the product primary nav menu.
- Removes the left and right padding of the button
- Moves the dropdown to be left-aligned with the window
- Removes the bottom-left border radius of the dropdown
These were quick-to-address feedback items that came from the VQA of the new primary nav. …

Address primary nav feedback

---

src/views/homepage/components/product-nav/index.tsx
src/views/homepage/components/product-nav/product-nav.module.css
src/views/homepage/index.tsx

---
- [Preview link](https://dev-portal-git-achomepageproduct-nav-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1200641486648086/1202112386641526) 🎟️
Implement `<ProductNav />` component on the homepage.
New homepage design.

feat(Hompeage): `<ProductNav />`

---

src/views/homepage/components/tutorial-card/index.tsx
src/views/homepage/components/tutorial-card/tutorial-card.module.css
src/views/homepage/index.tsx

---
- [Preview link](https://dev-portal-git-achomepagetutorial-card-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/inbox/1200641486636491/1202118917268192/1202122065211612) 🎟️
Adding rough implementation of `<TutorialCard />`
```tsx
<TutorialCard
link="/"
duration="10min"
heading="Title Max 70 Characters Try and Keep it to a Max of Three Lines Loremi"
description="Body maximum 130 characters. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vitae pharetra accumsan risu, eu v..."
badges={["vault", "boundary", "interactive", "video"]}
/>;
```
Implementation a rough version for the homepage, knowing there is more needed of this component once the product version gets implemented.

feat(homepage): `<TutorialCard />`

---

src/views/homepage/components/product-nav/index.tsx
src/views/homepage/components/product-nav/product-nav.module.css

---
- [Preview link](https://dev-portal-git-achomepagefix-product-nav-hashicorp.vercel.app/) 🔎
Should have reviewed https://github.com/hashicorp/dev-portal/pull/289/commits/0ec6b226b014df5f20bc74876c4f80aa6acde4b9 before merging, missed the first and last hover radiuses, and lost the HCP border color override needed
Before:
https://user-images.githubusercontent.com/825855/163402586-434cdb41-20e3-43a9-9558-6cc1eca78096.mp4
After:
https://user-images.githubusercontent.com/825855/163402629-629880e7-8b45-4d59-ba79-56cddfd1a54b.mp4

fix(homepage): HCP border color and first and last product hover radius

---

src/pages/_document.tsx

---
Adding lang attribute to document.
To better lighthouse score.

chore(a11y): add lang attribute

---

src/views/homepage/components/hero/hero.module.css
src/views/homepage/components/hero/index.tsx
src/views/homepage/components/learn-section/index.tsx
src/views/homepage/components/learn-section/learn-section.module.css
src/views/homepage/components/merchandising-slots/merchandising-slots.module.css
src/views/homepage/components/pre-footer/index.tsx
src/views/homepage/components/pre-footer/pre-footer.module.css
src/views/homepage/components/product-nav/index.tsx
src/views/homepage/components/product-nav/product-nav.module.css
src/views/homepage/homepage.module.css
src/views/homepage/index.tsx

---
- [Preview link](https://dev-portal-git-achomepagepolish-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202111817660946/1202127264881981) 🎟️

chore(homepage): polish 💅🏼 

---

src/pages/_middleware.ts

---
Remove handling of `DEV_IO` in our redirects middleware.
We don't split redirects for the product specified in `DEV_IO`, as we don't add any host conditions to the redirect definitions. This causes them to get bucketed into our wildcard bucket, `*`. Removing the handling in our redirects middleware for `DEV_IO` to ensure that the redirects get picked up in this case.
This is only for deploy previews and local previews of our .io sites in product repositories. I stumbled across this by noticing that the redirect from `/` -> `/sentinel` when running sentinel's site locally didn't seem to be working.

chore: remove DEV_IO handling in redirects middleware

---

build-libs/redirects.js

chore: update location of redirect files for products

---

src/components/_proxied-dot-io/packer/remote-plugin-docs/utils/resolve-nav-data.js

---
Ensure we resolve plugin data locally when running in the context of hashicorp/packer.
Allow testing of local adjustments and avoiding GH API rate limits.

fix(packer): resolve plugin data locally when running in hashicorp/packer

---

src/views/homepage/components/learn-section/learn-section.module.css

---
Fixing vault badge sizing on the homepage.

fix(homepage): vault svg badge sizing

---

build-libs/redirects.js

fix: source packer redirects from correct location

---

.github/PULL_REQUEST_TEMPLATE.md

---
N/A
- Adds emojis to each heading of the PR template
- Elaborates on a couple of comments in the PR template
- Adds a "Design Screenshots" section to the PR template
I think the emojis give PRs a little more color and lighter feel to them. ✨ I think the new Design Screenshots section will also be a time saver during review, since we're always working in different files and it's not always clear where to find the referenced design. 😊
Only took some editing in `.github/PULL_REQUEST_TEMPLATE.md`.
N/A
I pasted the updated PR template content here to visually test how it looks and feels. 👀 
I started a discussion in the Digital Team channel to discuss adopting [Netlify's Feedback Ladder](https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/) for …

Adding some ✨ flair ✨ to the PR template

---

package.json
scripts/remove-non-beta-product-pages.ts

---
- [Asana task](https://app.asana.com/0/1201903760348480/1202100739731087/f) 🎟️
Only render beta product pages in our production build.
This should cut down on build times and reduce confusion if folks are navigating around the site and come across an incomplete page.
Wrote a small script which is called on `prebuild` to actually remove page files from disk.
- See build completed here and logs indicating removal of page dirs: https://vercel.com/hashicorp/dev-portal/3UMNbCa5HKCuypMnhVaJwf52oc6d

feat(build): only render beta product pages for production build

---

scripts/remove-non-beta-product-pages.ts

fix: do not remove api dir

---

scripts/content-repo-preview/build.ts

fix: io build

---

scripts/remove-non-beta-product-pages.ts

fix: formatting

---

src/pages/_proxied-dot-io/nomad/downloads/index.jsx

---
- [Preview link](https://dev-portal-git-nomad-130-rc1-download-box-hashicorp.vercel.app) 🔎
Update the [Nomad download box](https://www.nomadproject.io/downloads) to point to the new Release Candidate instead of the Beta.
Update download link so users know where to find the latest version.
I'm not really sure what's the Vercel preview path for this, so I just set the branch slug.

update Nomad v1.3.0-rc.1 download box

---

src/pages/_proxied-dot-io/nomad/downloads/index.jsx

> No Asana task for this PR, so items below are not applicable
> - [ ] The Asana task has been added to this PR's description
> - [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
> - [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task 
---
- [Preview link](https://dev-portal-git-zsfix-lint-error-hashicorp.vercel.app) 🔎
> - Asana task 🎟️ (Not applicable)
Fixes a lint error that seems to be causing our CI check to fail.
A single failing check, even if it's for a relatively trivial reason, can distract from more meaningful failed checks.
Saves the file in question locally, which automatically applies the required formatting changes (in VSCode at least).
- All other checks should pass too.
Nope.

chore: fix lint error

---

scripts/remove-non-beta-product-pages.ts

---
Build swingset during the production build so we can share links to our components with others.

chore: build swingset for production

---

analytics/.gitignore
analytics/Makefile
analytics/README.md
analytics/package-lock.json
analytics/package.json
analytics/spec/_index.yaml
analytics/spec/events/_index.yaml
analytics/spec/events/page_scrolled.yaml
analytics/spec/events/page_viewed.yaml
analytics/spec/meta/context.yaml

---
- [Asana task](https://app.asana.com/0/1201903760348480/1202030548842193/f) 🎟️
Adds an Analytics spec setup so we can include all of the Analytics tracking in a JSON Schema.
For now, the only expectation of this directory is for documentation & transparency purposes. I've included a simple Makefile which will compile the json schema down to a singular JSON file.  Potentially in the future we can build Analytics tooling off of this.

Analytics Spec

---

analytics/spec/events/_index.yaml
analytics/spec/events/product_downloaded.yaml
analytics/spec/events/video_played.yaml
analytics/spec/global/types/hashicorp_product.yaml

Adds two more analytics events.
`Product Downloaded` to keep track of product download events in dev portal.
`Video Played` to keep track of video watching progress.

Misc analytics events

---

src/data/boundary.json
src/data/consul.json
src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/vagrant.json
src/data/waypoint.json

---
- [Preview link](https://dev-portal-git-nq-add-hashiconf-eu-2022-alert-banners-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1187888078520425/1202197372632732/f) 🎟️
This PR updates available alert banners to announce availability of HashiConf Europe 2022 schedule information.

chore: Add alert banners announcing HashiConf Europe 2022 schedule info

---

config/production.json

---
Flip flag in production for single product search. I'm keeping the flag around in case we want to use it to toggle between cross-product search when that work starts up.

chore: enable single product search

---

src/pages/_proxied-dot-io/nomad/downloads/index.jsx

---
Remove the release candidate box from the Nomad download page.
Nomad 1.3.0 is now GA.

update Nomad v1.3.0 download box

---

package-lock.json
package.json

fix: use latest version of platform packer plugins

---

src/pages/_proxied-dot-io/consul/consul-on-kubernetes/index.tsx

Updates consul on kubernetes video on consul.io
https://dev-portal-git-acconsul-on-kubernetes-video-hashicorp.vercel.app/consul-on-kubernetes

chore(consul): update consul on kubernetes video

---

src/components/icon-tile/icon-tile.module.css
src/views/collection-view/components/collection-meta/index.tsx

- [Preview link](https://dev-portal-git-kscollection-meta-qa-hashicorp.vercel.app/waypoint/tutorials/get-started-docker) 🔎
- [Asana task](https://app.asana.com/0/1202001387788447/1202287572319146) 🎟️
This PR addresses some minor QA tickets for the collection meta component. See asana tasks for specifics.

cleanup: collection meta styles

---

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css

---
- [Preview link](https://dev-portal-git-ambfix-sidecar-height-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202300536466689/f) 🎟️
- Fixes height of sidecar to `fit-content` so it's sticky again. The problem was that it was too tall!
Nope! 😊

Fixing height of sidecar so it's sticky again

---

src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css

---
- [Preview link](https://dev-portal-git-ambupdate-content-width-hashicorp.vercel.app/) 🔎
Updates `--main-element-max-width` from `780px` to `896px`
There was a request in #442 to test out a wider max-width for the `main` element in the app
Easy-peasy, just changed a variable value!
N/A
Nope!

Widening main element max width

---

LICENSE

- [Asana task](https://app.asana.com/0/1202139754245883/1202178451271282/f) 🎟️
Adds our standard MPL v2 license to the project.

Add license file (MPL v2)

---

src/components/sidebar/index.tsx
src/layouts/sidebar-sidecar/server.ts

- [Preview link](https://dev-portal-git-ksupdate-sidebar-links-hashicorp.vercel.app/vault/docs) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202293409873442) 🎟️
This PR adjusts the 'all tutorials' resources link in the docs sidebar to hit the learn 'advanced search' page instead of the home page.

chore: update 'all tutorials' link

---

package-lock.json
package.json

---
This bumps `@hashicorp/mktg-global-styles`
https://github.com/hashicorp/mktg-global-styles/releases/tag/v4.2.2 contains a style update to fix `<video>` elements that are overflowing out of their containing element
Visit https://dev-portal-git-kevin-mktg-global-styles-hashicorp.vercel.app/_proxied-dot-io/boundary/docs/getting-started/run-and-login
Click the **Admin Console** tab
Verify that the video is sized properly

chore: bump mktg-global-styles

---

README.md
src/lib/analytics.ts
src/pages/_app.tsx

---
Adds an analytics plugin to log out events in development.
Makes it easier to see what analytics events are being fired during development. Very nice for working on analytics stuff specifically!

feat: development analytics logger

---

src/pages/waypoint/docs/content.json
src/views/product-root-docs-path-landing/README.md
src/views/product-root-docs-path-landing/index.tsx
src/views/product-root-docs-path-landing/product-root-docs-path-landing.module.css
src/views/product-root-docs-path-landing/server.ts

---
- [Preview link](https://dev-portal-git-arwaypoint-docs-landing-hashicorp.vercel.app/waypoint/docs) 🔎
- [Asana task](https://app.asana.com/0/1201979547919485/1201979547919596/f) 🎟️
Updates to the Waypoint docs page on devdot highlighting specific references pages.
Docs page should have some commonly referenced pages and features highlighted.

Waypoint docs landing page updates

---

src/components/dev-dot-content/dev-dot-content.module.css

---
- [Preview link](https://dev-portal-git-brkchore-table-double-border-hashicorp.vercel.app/waypoint/docs/upgrading/protocol-table) 🔎
- [Asana task](https://app.asana.com/0/1202110981600689/1202325853922351/f) 🎟️
Fix double border below table headings. Quick and easy so why not https://app.asana.com/0/1202110981600689/1202325853922351/f

chore: fix double border below table headings

---

package-lock.json
package.json
src/pages/api/opt-out-feedback.ts

---
- [Asana task](https://app.asana.com/0/1202276096167515/1202114007623817/f) 🎟️
Adds in an API endpoint for us to be able to send opt-out feedback to a Google Sheet.
```sh
curl -X POST \
https://dev-portal-git-bropt-out-feedback-hashicorp.vercel.app/api/opt-out-feedback \
-H 'Content-Type: application/json' \
-d '{
"segment_anonymous_id": "random-uuid-here",
"primary_opt_out_reason": "I can'\''t find the content I need",
"details": "some-details-here",
"opt_out_page_url": "https://developer.hashicorp.com/vault/api-docs"
}'
```
[Link to Google Sheet](https://docs.google.com/spreadsheets/d/15KyBwiEui6YfatLkN0QXcee3TR-pew_sVhnb9nk0DWo/edit?usp=sharing) (only accessible w/ HashiCorp email)
https://user-images.githubusercontent.com/2105067/170577072-f68b6214-e35a-4c5d-bb15-1a5ad80b3dd2.mp4

Adds opt-out-feedback API endpoint

---

src/components/dev-dot-content/dev-dot-content.module.css

---
- [Asana task](https://app.asana.com/0/1202114367927919/1202295504396681/f) 🎟️
Fixes a visual bug observed in Firefox where our injected anchor element was not playing nice with the paragraph tag.
Bad:
Good:

fix: list anchor visual bug in firefox

---

src/components/algolia-search/index.tsx

---
- [Asana task](https://app.asana.com/0/1202110981600689/1202333198712456/f) 🎟️
Keep search input focused when pressing `Enter`. This was based on feedback and observations in user testing that the search autocomplete being closed when pressing enter was non-intuitive.

fix(search): do not blur the search input when pressing enter

---

package-lock.json
package.json
src/components/navigation-header/components/home-page-content/index.tsx

---
- [Preview link](https://dev-portal-git-ksupdate-home-dropdown-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202348106428660) 🎟️
This PR only updates the nav to render 'products', it doesn't add the rest of the product menu items that say 'coming soon'  — that's now a different ticket.

chore: update home dropdown to only render products

---

src/components/tabs/components/tab-button-controls/tab-button-controls.module.css

---
- [Preview link](https://dev-portal-git-zsrefine-tabs-styles-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-install) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202325853922378/f) 🎟️
Tweaks padding on tab button items to match spec.

chore: tweak tabs padding to match spec

---

src/components/opt-in-out/helpers/platform-options.ts

---
Ran into this while testing. In the case where someone would opt-out immediately after opting-in, our middleware would pick up the presence of the `optInFrom` param and immediately add the cookie and redirect, so I was seeing a redirect loop. Removing the `optInFrom` param on opt-out should avoid any potential issues.

fix: remove optInFrom param when opting out to avoid loop

---

src/layouts/sidebar-sidecar/index.tsx

Updates the version PageAlert "View latest version" link to be the current path minus the version being viewed.
To match how the .io sites currently handle this functionality.
Using the `removeVersionFromPath` helper.
Nope!

Updating version PageAlert link

---

.github/PULL_REQUEST_TEMPLATE.md

Removes the "Ready for Review" checklist from the PR template
Pares down the template a little bit. And the items included in the checklist section aren't as needed as they used to be.

[PR template] Remove "Ready for Review" checklist

---

build-libs/__tests__/build-beta-opt-in-redirect.test.ts
config/base.json

- [Preview link](https://dev-portal-git-ksupdate-canonical-url-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202348106428669) 🎟️
Updates canonical base url and accepted analytics domains.

chore: update canonical base url value

---

src/layouts/sidebar-sidecar/components/table-of-contents/index.tsx

`replaceAll` is not available in node v14, which is what we currently have specified in our `.nvmrc`. Using `replace` with a pattern for now to ensure the app can run on node v14.

fix: use replace instead of replaceAll for node v14 compat

---

src/components/algolia-search/algolia-search.module.css

fix: adjust padding for mobile search results

---

src/views/product-tutorials-view/helpers/heading-helpers.ts

- [Preview link](https://dev-portal-git-ksfix-casing-hashicorp.vercel.app/waypoint/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202391122486291) 🎟️
Aligns `All Tutorials` section heading with the proper casing

chore: fix casing

---

src/pages/vault/index.tsx
src/pages/waypoint/index.tsx

- [Asana task](https://app.asana.com/0/1202114367927919/1202391122486283/f) 🎟️
Fixes infrequent error occurring when the product landing pages attempt to revalidate. They read from the filesystem, which won't have the expected files during ISR, causing an error. It's not possible to change this page independent of a deployment, so there's no need for revalidate here.

fix: back link error triggered by ISR

---

src/pages/_proxied-dot-io/sentinel/sentinel/[[...page]].tsx
src/pages/_proxied-dot-io/sentinel/sentinel/intro/[[...page]].tsx

Hiding the `Edit this page` link for sentinel docs as the repo is private.

fix(sentinel): hide edit this page link for sentinel

---

package-lock.json
package.json
src/components/navigation-header/components/dropdown-menu/index.tsx
src/components/navigation-header/types.ts
src/data/waypoint.json
src/views/product-root-docs-path-landing/components/supported-icons.tsx

- [Preview link](https://dev-portal-git-ksupdate-plugins-icon-hashicorp.vercel.app//waypoint/docs) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202408007169440) 🎟️
Updates the plugins icon to match the new design system icon. Also upgrades the flight package to access the new icon.

chore: update plugins icon

---

src/components/footer/index.tsx

- [Preview link](https://dev-portal-git-ksupdate-footer-content-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202292602441760) 🎟️
Adds extra items required by legal to the footer. 
We still need to adjust the cookie manager item to render with the sidebar sidecar layout still. I added [that task here.](https://app.asana.com/0/1202276096167515/1202407108957088)

chore: adds footer items

---

src/components/collection-card/components/company-logo/index.tsx

Ensure the company logo images don't get included in our JS bundles. Saves ~20kb gzipped where `<CollectionCard />` is used. They still appear to work fine with `next/image` with this change, so there shouldn't be any functional issues here.

chore: adjust image require for company logos to exclude from bundle

---

src/constants/version-path.ts
src/lib/__tests__/get-target-path.test.ts
src/lib/__tests__/get-version-from-path.test.ts
src/lib/__tests__/remove-version-from-path.test.ts
src/lib/get-target-path.ts
src/lib/get-version-from-path.ts
src/lib/remove-version-from-path.ts

- [Asana task](https://app.asana.com/0/1202324589579160/1202414004406121/f) 🎟️
> **Note**: Related work
> - https://github.com/hashicorp/react-components/pull/608
This updates a few utility functions to be able to handle a TFE version, which is not in a Semver format.
- format: **vYYYYMM-X**

parse tfe version from URL

---

src/lib/get-deployed-url.ts

fix: config reference name

---

package-lock.json
package.json
src/components/navigation-header/components/dropdown-menu/index.tsx
src/components/navigation-header/types.ts
src/data/vault.json
src/views/product-root-docs-path-landing/components/supported-icons.tsx

- [Preview link](https://dev-portal-git-ksupdate-api-icon-hashicorp.vercel.app/vault/docs) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202400698953811) 🎟️
Updates the nav and docs landing icon cards to use the new api icon from HDS.

chore: update api icon

---

src/components/navigation-header/components/product-page-content/index.tsx

- [Preview link](https://dev-portal-git-ambupdate-h-menu-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202022787106817/1202405210286695/f) 🎟️
Updates the content of the H menu that shows in the product navigation header.
This is an update to align with new spec where we show non-beta products as "Coming Soon".
Only required changing the data sent to `NavigationHeaderDropdownMenu` in `src/components/navigation-header/components/product-page-content/index.tsx`.
Figma link: https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/DevDot?node-id=9592%3A141194

Updating H menu content

---

src/components/head-metadata/index.tsx

fix: short-circuit metadata for io sites

---

src/data/vault-install.json

- [Preview link](https://dev-portal-git-ggvault-install-side-hashicorp.vercel.app/vault/downloads) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202333198712467) 🎟️
Edit sidecar content to be more useful to practitioners when visiting the Vault Install page.
Previous content was mocked up by designers in early drafts and had not been touched since.

Add tutorials link to Vault sidecar

---

src/data/vault-landing.json

- [Preview link](https://dev-portal-git-ambadjust-vault-landing-content-hashicorp.vercel.app/vault) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1202436586522452/f) 🎟️
- Removes some redundant cards from the /vault page, which were getting awkwardly laid out in narrower views

[/vault] Removing redundant cards

---

src/components/collection-card/helpers.ts
src/components/collection-card/types.ts
src/views/tutorial-view/index.tsx
src/views/tutorial-view/utils/get-canonical-collection-slug.ts
src/views/tutorial-view/utils/get-collection-context.ts
src/views/tutorial-view/utils/index.ts

- [Preview link](https://dev-portal-git-ksfix-canonical-urls-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202439144025004) 🎟️
Fixes an issue where canonical urls were being set for nonexistent collection links. 
Below are a list of urls to test against that were broken before (copy the path and append to preview url):
https://dev-portal-git-ksfix-canonical-urls-hashicorp.vercel.app/vault/tutorials/cross-products/vault-consul-secrets
- 404 https://developer.hashicorp.com/consul/tutorials/vault-secure/vault-consul-secrets
https://developer.hashicorp.com/vault/tutorials/cross-products/vault-nomad-secrets
- 404 https://developer.hashicorp.com/nomad/tutorials/integrate-vault/vault-nomad-secrets
https://developer.hashicorp.com/vault/tutorials/secrets-managemen …

fix: check canonical url is in beta

---

src/components/dev-dot-content/dev-dot-content.module.css

- [Preview link](https://dev-portal-git-ambfix-table-overflow-hashicorp.vercel.app/vault/docs/internals/telemetry#token-identity-and-lease-metrics) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1202439831418490/f) 🎟️
- Temporarily fixes horizontal overflow of `<table>` elements with horizontal scrolling
- On narrower viewports, a `<table>` wider than the viewport messes with the width of other content
- CSS 🪄✨ (we mainly needed `display: block` and `overflow-x: auto`)

Bandaiding <table> overflow

---

src/components/opt-in-out/components/opt-out-form/index.tsx

- [Preview link](https://dev-portal-git-kslook-into-opt-out-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202276096167515/1202447334062460) 🎟️
Fixes an issue where hitting the 'x' button on the opt out form submitted the form.
Hit the preview and opt in - [/waypoint/docs?optInFrom=waypoint-io](https://dev-portal-git-kslook-into-opt-out-hashicorp.vercel.app/waypoint/docs?optInFrom=waypoint-io)
Click **Leave Beta** and hit cancel or 'x' on the form. It should cancel and not redirect you.

fix: update opt out form button types

---

src/components/sidebar/helpers/generate-resources-nav-items.ts
src/components/sidebar/helpers/index.ts
src/components/sidebar/index.tsx

- [Preview link](https://dev-portal-git-ambupdate-community-links-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1202440008235051/f) 🎟️
Adds a sidebar helper for generating the resources nav items: `generateResourcesNavItems`.
We want to customize the "Community Forum" links, and I expect we'll also want to customize other links in the section based on the current product being viewed. Moving this logic into a helper prevents making `src/components/sidebar/index.tsx` too bloated. I've also tried to make it easy to add more helpers and also to add more customized links as we onboard more products.

Updating Community Forum links

---

.github/workflows/ci.yml
package.json

Remove use of the jest runner action and run jest directly. This action was obscuring output and wasn't really providing benefit, so I'm removing it to align with how we run tests elsewhere. Also running tests with `--runInBand` to see if that addresses some flaky failures.

chore: npm test directly instead of jest GH action

---

README.md

Adjust naming in the README. Do we also want to remove the internal links? 🤔

chore: adjust readme title to align with project naming guidelines

---

analytics/spec/events/_index.yaml
analytics/spec/events/error_page_loaded.yaml
package-lock.json
package.json

Upgrades our error page event to https://github.com/hashicorp/react-components/pull/614.
Also including this in our Analytics spec for this project.

Upgrade our Error View Analytics & update spec

---

src/data/waypoint.json

fix: waypoint favicon

---

src/__tests__/e2e/beta-opt-in-out.spec.ts
src/pages/_middleware.ts

Fixes some logic in our beta opt out flow when checking for a matching product. `in` is not a valid operator to check for an element in an array. 🙃 
```js
> 'vault' in ['waypoint', 'vault']
false
```
I also went ahead and added a few e2e specs for this behavior

fix: beta opt out logic

---

src/components/navigation-header/components/home-page-content/index.tsx
src/components/navigation-header/components/product-page-content/index.tsx
src/lib/generate-top-level-sub-nav-items.ts

- [Preview link](https://dev-portal-brkalow-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202114367927919/1202465704289939/f) 🎟️
Removing `beta` badges rendered next to product names to avoid any potential user confusion. It kinda of looks like we are implying the products themselves are in beta.
After:
H menu:
Product mobile nav:
Homepage mobile nav:
Install:

feat: do not render beta badges next to product names

---

src/components/opt-in-out/helpers/platform-options.ts

---
- https://app.asana.com/0/0/1202475665194284

chore: update learn redirect base url

---

src/data/boundary.json
src/data/consul.json

Updates alert banners for HashiConf day 2. 
Should not merge until 2:55am ET on 6/22
---
- https://app.asana.com/0/0/1202458447592573
- https://app.asana.com/0/0/1202476207672880

Update alert banners for day 2

---

src/data/boundary-install.json
src/pages/_proxied-dot-io/boundary/index.jsx

Quick fix to patch broken Learn link from the homepage of boundaryproject.io
[Open issue](https://github.com/hashicorp/boundary/issues/2228)
[Slack context](https://hashicorp.slack.com/archives/CP48EV08Z/p1655890187689899)

hotfix: fix incorrect getting started link

---

.env
next.config.js
scripts/warm-dotio-cache.ts
src/lib/_proxied-dot-io/get-static-generation-functions.ts
src/lib/fetch-content-api-file-string.js
src/lib/remark-plugins/rewrite-static-assets.ts
src/pages/terraform/cli/[[...page]].tsx
src/pages/terraform/configuration/[[...page]].tsx
src/pages/terraform/guides/[[...page]].tsx
src/pages/terraform/internals/[[...page]].tsx
src/pages/terraform/intro/[[...page]].tsx
src/pages/terraform/language/[[...page]].tsx

- [Asana task](https://app.asana.com/0/1100423001970639/1202503897645209/f) 🎟️
Update references to the content API vercel domain to our new content.hashicorp.com subdomain.

chore: update our content API to use the new domain

---

src/data/README.md
src/types/products.ts

- [Preview link](https://github.com/hashicorp/dev-portal/blob/amb.update-src-data-readme/src/data/README.md) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202488740132124/f) 🎟️
- Adds Table of Contents to top of `src/data/README.md` file
- Adds deprecation notes to the `basePaths` and `sidebar` sections of the `<product slug>-landing.json` main section
- Adds details on `rootDocsPaths` property
- Adds new `NavigationHeaderItem` interface in `src/types/products.ts` file
- Adds jsdocs comments to `NavigationHeaderItem` and `RootDocsPaths` interfaces in `src/types/products.ts` file
- New Table of Contents section hopefully makes the file easier to break down
- To make `<product slug>-landing.json` section accurate again
- New jsdocs comments are for improved developer experience …

Updating "<product slug>-landing.json" section of src/data/README.md

---

src/pages/api/opt-out-feedback.ts

Only log the error message property in an effort to get more valuable error messages, and to stop logging the full request object.

chore(api/opt-out-feedback): only log google sheet error message

---

src/components/_proxied-dot-io/packer/remote-plugin-docs/server.ts

Fixes an issue where Packer plugins content did not have the expected `remark` and `rehype` plugins applied.
Without these plugins our docs are missing several features, such as syntax highlighting in code blocks.
Adds `remark` and `rehype` plugin settings after fetching Packer plugins MDX.
- For example, https://www.packer.io/plugins/post-processors/hashicups/receipt
- Heading permalinks are not shown; code block are not syntax highlighted; etc
- Paragraph custom alerts should render (`paragraphCustomAlerts` remark plugin)
- Typography classNames should be present on heading elements (`typography` remark plugin)
- Heading permalinks should appear on hover, and function as expected (`anchor-links` remark plugin)
- Code blocks should be …

fix: remark rehype for packer plugins

---

scripts/remove-non-beta-product-pages.ts

fix: don't remove product slug dir

---

src/components/mobile-menu-container/index.tsx
src/components/mobile-menu-container/mobile-menu-container.module.css
src/layouts/base-new/index.tsx
src/layouts/sidebar-sidecar/index.tsx

- [Asana task](https://app.asana.com/0/1202097197789424/1202665629707459/f) 🎟️
- Adds `MobileAuthenticationControls` component in `MobileMenuContainer`
- Uses `MobileAuthenticationControls` alongside uses of `MobileMenuContainer`
- I tried not exporting `MobileAuthenticationControls` and directly placing it within `MobileMenuContainer`, but that didn't work because the instances of `MobileMenuContainer` are all styled differently. This approach requires using `MobileAuthenticationControls` everywhere `MobileMenuContainer` is used, but allows us to keep the CSS as simple as possible.
- The `useAuthentication` hook was useful for determining auth state.
<details>
<summary>Expand for screenshot</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11619%3A1148 …

Add mobile Sign In and Sign Up elements

---

src/layouts/_proxied-dot-io/consul/index.tsx
src/pages/_proxied-dot-io/consul/docs/index.tsx

- [Asana task](https://app.asana.com/0/1202097197789424/1202632199481629/f) 🎟️
- Wraps `ConsulIoLayout` with `ProductMetaProvider`
- Passes `DevDotOptIn` to `DocsPageInner` in `ConsulDocsLandingPage`
- To prepare Consul to render the "Join the beta" banner on its .io docs pages

Wrapping Consul with ProductMetaProvider

---

.github/workflows/nextjs_bundle_analysis.yml
.github/workflows/pr_guidelines.yml

This PR disables our PR review guidelines comments on Dependabot PRs since they're not really necessary, and result in a failed CI job. (Alternatively, if we feel the guidelines are useful on Dependabot PRs, it looks like we can adjust the PR comment workflow to have the necessary permissions to add comments to Dependabot PRs.)
Additionally, it enables PR comments for the Bundle Analysis step (since it'd be good to see if a dependency update causes an increase in bundle size).
I assume that PRs created by bots like Dependabot need additional permissions added to the generated GitHub token.
The PR review comment workflow was updated to exclude Dependabot branches (which are …

Fix PR comments on Dependabot PRs

---

src/lib/tutorials/normalize-product-like-slug.ts

Visit a tutorial with a link to another tutorial, it should work.

patch: fix tutorial map endpoint

---

src/layouts/_proxied-dot-io/boundary/index.tsx

- [Preview link](https://dev-portal-git-ksstage-boundary-product-meta-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202677983526066) 🎟️
Adds the product meta provider to boundary layout to enable the opt in cta on the .io site.

chore: adds boundary product meta provider

---

src/components/_proxied-dot-io/boundary/subnav/index.jsx
src/components/_proxied-dot-io/consul/subnav/index.jsx
src/components/_proxied-dot-io/packer/subnav/index.jsx
src/components/_proxied-dot-io/vault/subnav/index.jsx
src/pages/_proxied-dot-io/packer/index.jsx

- [Preview link](https://dev-portal-git-nq-cta-consistency-test-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1187888078520425/1202633580843430/f) 🎟️
This PR reorders nav CTAs on our `_proxied-dot-io` subnavs, as part of a larger effort to make hero/nav CTAs more consistent across these pages.

feat: .io site nav CTA changes

---

package-lock.json
package.json

- [Asana task](https://app.asana.com/0/1100423001970639/1202661960768349/f) 🎟️
Bumps docs-page to the latest version: https://github.com/hashicorp/react-components/blob/main/packages/docs-page/CHANGELOG.md

chore: bumps docs-page

---

src/components/tutorial-meta/index.tsx
src/components/tutorial-meta/tutorial-meta.module.css

- [Preview link](https://dev-portal-git-ksadds-bookmark-button-tutorial-meta-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202791375540707) 🎟️
- [Figma](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=11678%3A115071) 🎨 
This PR adds the bookmark button to the tutorial meta component. It should not render in prod yet, it is behind the 'auth enabled' flag.
- [visit a tutorial](https://dev-portal-git-ksadds-bookmark-button-tutorial-meta-hashicorp.vercel.app/vault/tutorials/adp/transform), it should render the button in the meta
- visit the [install terraform tutorial](https://dev-portal-git-ksadds-bookmark-button-tutorial-meta-hashicorp.vercel.app//terraform/tutorials/aws-get-started/install-cli) to see with the 'interactive lab' button …

🛹 feat: adds bookmark button tutorial meta UI

---

src/components/bookmark-button/bookmark-button.module.css
src/components/bookmark-button/icons/icons.module.css
src/components/bookmark-button/icons/index.tsx
src/components/bookmark-button/index.tsx
src/components/card-link/index.tsx
src/components/collection-card/docs.mdx
src/components/collection-card/index.tsx
src/components/tutorial-card/docs.mdx
src/components/tutorial-card/index.tsx
src/components/tutorial-card/tutorial-card.module.css
src/components/tutorial-card/types.ts
src/components/tutorial-collection-cards/components/card-eyebrow/index.tsx

- [Preview link](https://dev-portal-git-ksadds-bookmark-card-icon-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1202791375540706) 🎟️
This PR adds a new `BookmarkButton` component to the tutorial card eyebrow. Production will not render these changes since auth is not enabled. The production tutorial cards should not be affected by these updates. 
- Visit the [tutorial card swingset page](https://dev-portal-git-ksadds-bookmark-card-icon-hashicorp.vercel.app/swingset/components/tutorialcard) and test out the bookmark states. 
- Also check it out on the [tutorial product landing](https://dev-portal-git-ksadds-bookmark-card-icon-hashicorp.vercel.app/vault/tutorials) pages. 
This isn't linked up with actual data yet, the click handlers are basically a stub. …

🛹 feat: adds bookmark card icon

---

src/pages/[productSlug]/tutorials/[...tutorialSlug]/index.tsx
src/pages/[productSlug]/tutorials/[collectionSlug].tsx

Prevent tutorials being rendered for all products in production, e.g. https://developer.hashicorp.com/terraform/tutorials/automation/github-actions

fix: don't render tutorials for non-beta products

---

src/components/navigation-header/components/product-page-content/index.tsx

The links in the documentation menu are broken, see: https://developer.hashicorp.com/vault
They are rendered as `/[object Object]/docs` instead of `/vault/docs`

fix(ProductPageContent): fix documentation menu path

---

src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/vagrant.json
src/data/vault.json
src/data/waypoint.json

- [Preview link](https://dev-portal-git-nq-add-hashiconf-global-registe-42b070-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1187888078520425/1202765650251024/f) 🎟️
This PR updates available alert banners across our product sites to show HashiConf Global registration information.

feat: Update alert banners with HashiConf Global info

---

src/lib/remark-plugins/rewrite-tutorial-links/index.ts

- [Preview link](https://dev-portal-git-ksupdate-tf-link-paths-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/inbox/1199634971443477/1202577211695198/1202817635735601) 🎟️
Updates the tutorial link rewriter with all the tf docs paths.

chore: update link plugin with tf paths

---

src/__tests__/e2e/product-docs-menu-links.spec.ts

As a follow up to https://github.com/hashicorp/dev-portal/pull/850, I've added an e2e test that validates that these menu links go to a valid page.

chore: adds e2e test for documentation menu links

---

src/data/consul.json

Add 1.13 Blog post banner https://www.hashicorp.com/blog/consul-1-13-introduces-cluster-peering

banner: Update banner for Consul 1.13

---

src/data/vault.json
src/pages/_proxied-dot-io/vault/downloads/index.jsx

This addresses https://github.com/hashicorp/vault/issues/16829
See https://dev-portal-git-kevin-vault-changelog-hashicorp.vercel.app/_proxied-dot-io/vault/downloads

fix(vault/downloads): changelog url

---

src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/vagrant.json
src/data/vault.json
src/data/waypoint.json

- [Preview link](https://dev-portal-git-nq-update-alert-banners-hc-gl-2-21fb2b-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202791227659279/1202863271843666/f) 🎟️
This PR updates alert banners for HashiConf Global.
**This PR SHOULD NOT MERGE until August 30.**

[DO NOT MERGE] feat: Update alert banners (HashiConf Global)

---

.github/workflows/auto-merge-staging.yml

Adds a workflow to sync the `staging` branch with `main`. We'll use this to have a stable preview URL.

feat: add workflow to merge main into staging

---

config/project-preview.json
src/views/docs-view/server.ts

Set `revalidate: false` if we are in a deploy preview and reading from the filesystem. This fixes an issue where ISR attempts to read from the filesystem and errors.

fix: do not revalidate SSG'd pages in deploy previews

---

src/layouts/_proxied-dot-io/consul/query.graphql

Fix consul use case paths within the nav.

fix: consul use case slug

---

src/components/sidebar/helpers/generate-install-view-nav-items.ts
src/pages/nomad/downloads/enterprise.tsx
src/views/product-downloads-view/components/downloads-section/downloads-section.module.css
src/views/product-downloads-view/components/downloads-section/index.tsx
src/views/product-downloads-view/components/downloads-section/types.ts
src/views/product-downloads-view/components/page-header/index.tsx
src/views/product-downloads-view/helpers.ts
src/views/product-downloads-view/index.tsx
src/views/product-downloads-view/server.ts
src/views/product-downloads-view/types.ts

- [Asana task](https://app.asana.com/0/1202097197789424/1202817202285219/f) 🎟️
- Updates `generateInstallViewNavItems` to generate the sidebar title based on `isEnterpriseMode`
- Adds `src/pages/nomad/downloads/enterprise.tsx` page file
- Updates `generateGetStaticProps` in `views/product-downloads-view/server` to accept a new `isEnterpriseMode` option
- Adds `EnterpriseLegalNotice` to show after "Notes" section in main card
- Updates `ProductDownloadsView` `PageHeader` to generate title & subtitle off of _isEnterpriseMode_
- Adds `generateEnterprisePackageManagers` helper (copied from what .io uses)
- Updates `initializeBreadcrumbLinks` to generate the last breadcrumb item based on `isEnterpriseMode`
- Adds `sortAndFilterReleaseVersions` helper to move more logic for the view server-side …

Add /nomad/downloads/enterprise page

---

src/content/well-architected-framework/index.json
src/lib/get-is-beta-product.ts
src/views/onboarding/collection-view/index.tsx
src/views/onboarding/tutorial-view/index.tsx
src/views/tutorial-view/utils/get-canonical-collection-slug.ts
src/views/well-architected-framework/tutorial-view/index.tsx

- [Preview link](https://dev-portal-git-kswaf-updates-hashicorp.vercel.app/well-architected-framework) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1202817201846592) 🎟️
This PR fixes a few random things for the waf rollout. 
- adding the instruqt provider so interactive labs work
- adding a canonical url
- uploading the right landing page asset.
[visit the landing](https://dev-portal-git-kswaf-updates-hashicorp.vercel.app/well-architected-framework) and other views for a final round of QA before release!

chore: waf adjustments

---

package-lock.json
package.json

https://github.com/hashicorp/web-platform-packages/pull/84

chore: bump @hashicorp/platform-analytics

---

src/components/_proxied-dot-io/boundary/subnav/index.jsx
src/components/_proxied-dot-io/consul/downloads-props/index.jsx
src/components/_proxied-dot-io/consul/subnav/index.jsx
src/components/_proxied-dot-io/packer/subnav/index.jsx
src/components/_proxied-dot-io/vault/subnav/index.jsx
src/pages/_proxied-dot-io/consul/consul-on-kubernetes/index.tsx
src/pages/_proxied-dot-io/packer/index.jsx
src/pages/_proxied-dot-io/vault/downloads/index.jsx

- [Preview link](https://dev-portal-git-acutm-removal-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1187888078520425/1202270882674257/f) 🎟️
Removes hard code utm params from portal.cloud.hashicorp.com links.

chore: remove hard code utm params from portal urls

---

src/components/tag/docs.mdx
src/components/tag/index.tsx
src/components/tag/tag.module.css
src/components/tag/types.ts

- [Preview link](https://dev-portal-git-ambadd-basic-tag-hashicorp.vercel.app/swingset/components/tag) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202816749416423/f) 🎟️
- Adds _very_ basic `Tag`
- The basic version is all that's needed for global search and tutorial library

Adding basic Tag

---

src/content/boundary/product-landing.json
src/content/consul/product-landing.json
src/content/hcp/product-landing.json
src/content/nomad/product-landing.json
src/content/packer/product-landing.json
src/content/terraform/product-landing.json
src/content/vagrant/product-landing.json
src/content/vault/product-landing.json

- [Preview link](https://dev-portal-git-pblanding-page-diagrams-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202817202285139/f) 🎟️
Update or add diagrams for each product's landing page overview.
1. Edit all assets to have 16px of padding around diagram
2. Run through ImageOptim
3. Upload to Dato and paste the url in the product's `content/[product]/product-landing.json` file
Make sure the diagram in each product's landing page that was updated looks good ✨ 
- /boundary
- /consul
- /hcp
- /nomad
- /packer
- /terraform
- /vagrant
- /vault

chore: update landing page overview diagrams

---

src/components/_proxied-dot-io/vault/subnav/index.jsx

- [Asana task](https://app.asana.com/0/0/1202910456596384/f) 🎟️
Fix vault subnav cta to point to `/sign-up`

chore: fix vault subnav cta

---

src/content/boundary/product-landing.json

This updates the boundary hero title & image

feat: update Boundary hero

---

src/content/vagrant/product-landing.json

- [Preview link](https://dev-portal-git-ar-vagrant-fixes-hashicorp.vercel.app/vagrant) 🔎
Fixed the `Learn more about Vagrant features` link that pointed to a placeholder Vault doc.

Fixed Vagrant link pointing to vault doc

---

src/data/consul.json

Adding Consul K8s UX Study banner to gather more participants. Currently only 1 participant has registered. 

Add Consul K8s UX Study link to Consul Banner

---

src/views/docs-view/components/no-index-tag-if-versioned.tsx

Adjust any versioned pages to also include the `nofollow` directive in the robots meta tag, per recommendation from our SEO consultant. This will ensure that Google will not crawl these pages at all.

feat: add nofollow to versioned pages

---

scripts/remove-non-beta-product-pages.ts
src/__tests__/remove-non-beta-product-pages.test.ts
src/content/terraform/install-landing.json
src/pages/onboarding/[...tutorialSlug]/index.tsx
src/views/onboarding/tutorial-view/server.ts
src/views/tutorial-view/components/next-previous/helpers.ts

- [Preview link](https://dev-portal-git-ksonboard-cs-hashicorp.vercel.app/onboarding/hcp-vault-week-1) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202557239529698) 🎟️
Bring onboarding pages into 'beta' on production

feat: ship onboarding pages

---

src/content/supported-icons.tsx

fix: add server to SUPPORTED_ICONS

---

src/views/tutorial-library/index.tsx
src/views/tutorial-library/utils/scroll.ts

Scroll to the top of the page when the results meaningfully change.

feat(tutorial library): scroll to top on results change

---

src/lib/learn-client/api/tutorial/index.ts
src/views/product-tutorials-view/helpers/get-inline-content.ts

Adds [function overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) to the `getTutorials` type definition to refine the return type based on the arguments.
Currently, the return type is always `Promise<Tutorial[] | Omit<Tutorial, 'content'>[]>`, even though we can statically determine this based on the second argument, `withContent`. Function overloads allow us to declare different types for the function based on varying arguments, so we can say `if withContent is false, omit the 'content' property` and make that available to consumers.
Before:
After:

chore: improve getTutorials return typing

---

src/pages/tutorials/library.tsx
src/views/tutorial-library/components/results/index.tsx
src/views/tutorial-library/index.tsx
src/views/tutorial-library/types.ts
src/views/tutorial-library/utils/scroll.ts

Adds a default results state to the tutorial library. Only displayed when no filters are applied.

feat(tutorial library): add default results

---

src/components/command-bar/commands/search/dialog-body.tsx
src/components/command-bar/commands/search/index.tsx
src/components/command-bar/commands/settings/dialog-body.tsx
src/components/command-bar/commands/settings/index.tsx
src/components/command-bar/components/dialog/body.tsx
src/components/command-bar/components/dialog/command-bar-dialog.module.css
src/components/command-bar/components/dialog/index.tsx
src/components/command-bar/components/dialog/types.ts
src/components/command-bar/components/divider/command-bar-divider.module.css
src/components/command-bar/components/divider/index.tsx
src/components/command-bar/components/index.ts
src/components/command-bar/components/list-item/command-bar-list-item.module.css
src/components/command-bar/components/list-item/index.tsx
src/components/command-bar/components/list-item/types.ts
src/components/command-bar/components/list/command-bar-list.module.css
src/components/command-bar/components/list/index.tsx
src/components/command-bar/components/list/types.ts

- [Preview link](https://dev-portal-git-ambcommand-bar-items-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202948006171575/f) 🎟️
- Adds a few new subcomponents to `CommandBar`, intended for use within a command's `DialogBody`:
- `CommandBarButtonListItem`
- `CommandBarDivider`
- `CommandBarLinkListItem`
- `CommandBarList`
- Moves the search and settings commands into their own folders under `src/components/command-bar/commands/`, so the commands aren't one gigantic file
- Updates command bar dialog's body to show a few examples of the new subcomponents for testing purposes
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12514%3A144676)

[CommandBar] Add divider, list, and list item subcomponents

---

src/components/icon-tile-logo/index.tsx
src/components/icon-tile/icon-tile.module.css
src/components/product-icon/index.tsx

- [Preview link](https://dev-portal-git-ksupdate-hcp-tile-hashicorp.vercel.app/hcp/docs) 🔎
- [Asana task](https://app.asana.com/0/1202702246158644/1202946807363621) 🎟️
- [Figma](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12456%3A146008) 🎨 
This PR updates the hcp icon tile logo styles to match the new spec. 
- visit the [hcp docs landing](https://dev-portal-git-ksupdate-hcp-tile-hashicorp.vercel.app/hcp/docs), verify the tile logo styles matches the spec

style: adjust hcp icon tile logo color

---

src/views/tutorial-library/components/results/index.tsx

- [Asana task](https://app.asana.com/0/0/1202841351070160/f) 🎟️
Adds an `aria-live` region which announces the number of search results. This should improve the experience for users who rely on screen readers.
- Aria live regions MDN: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
- Discussion on this particular UI pattern as it relates to a11y success criteria: https://ux.stackexchange.com/questions/118488/does-faceted-search-fail-accessibility

feat(tutorial library): add aria-live region to announce results

---

src/layouts/sidebar-sidecar/components/table-of-contents/index.tsx

chore(TableOfContents): hasOneOrLessHeadings

---

src/content/boundary/install-landing.json

- [Preview link](https://dev-portal-git-boundary-typo-fix-hashicorp.vercel.app/boundary/downloads) 🔎
- [Asana task](https://app.asana.com/0/563192436488770/1202965575347281/f) 🎟️
This PR address the user findings reported on the [Design QVA](https://docs.google.com/document/d/1oGOdwsy1wktMTA4UCb2rwtVjKDxLlQiA7Irkl98cMZE/edit#heading=h.8ywz52dunl6w):
- Fix the typo:  `Bounary` --> `Boundary`
- Fix the doc URL: `/boundary/docs/getting-started/deploy-and-login` should be `/boundary/docs/getting-started`
- Added `Clients` doc link for convenience
Those findings should be corrected before it goes public.

[Boundary] Address the VQA feedback

---

src/pages/hcp/api-docs/packer/[[...page]].tsx

Do not render the HCP Packer API docs if we're in a deploy preview that's not for HCP.
This fetches a file from a private repository, so we would need to add GH PATs to each repo to facilitate rendering this page. It shouldn't be relevant for deploy previews in unrelated repositories.

fix: only render HCP Packer API docs in HCP deploy previews

---

src/components/docs-version-switcher/docs-version-switcher.test.tsx
src/components/docs-version-switcher/index.tsx
src/components/dropdown-disclosure/components/list-item/index.tsx
src/components/dropdown-disclosure/components/list-item/types.ts

feat: add `nofollow` to versioned links

---

src/views/product-root-docs-path-landing/index.tsx
src/views/product-root-docs-path-landing/product-root-docs-path-landing.module.css

Add margin right to landing page heading when versions are defined

fix(version switcher): add margin on docs landing page heading

---

src/content/terraform/product-landing.json

Restores image update made in #972 , this time ensure there's top padding built into the image (which is why we replaced the previously update-text image in #978).
To use image approved by education ([Slack thread][slack]).
Updates Dato URL.
[task]: https://app.asana.com/0/0/1202975892434092/f
[preview]: https://www.hashicorp.com
[slack]: https://hashicorp.slack.com/archives/C01KCU4HDPY/p1662748999069179?thread_ts=1662746135.472499&cid=C01KCU4HDPY

fix: update tf landing hero img

---

src/content/consul/install-landing.json
src/content/consul/product-landing.json
src/content/hcp/product-landing.json

- [Preview link](https://dev-portal-git-1008-hashicorp.vercel.app/consul) 🔎
Address feedback from [VQA](https://docs.google.com/document/d/1kvvVlD53yS7_b6RZOMcaK65zCcxih8hY4vnd1tvFknQ/edit)

Update HCP and Consul content

---

src/views/docs-view/server.ts

Pull consul's content from its default latest source, not the `dev-portal` branch, as we've shifted approaches here.

chore: consul content from latest

---

package-lock.json
package.json

chore: use newer version of next to fix fast refresh

---

src/views/docs-view/server.ts

Read boundary content from its default `latest` ref.

chore: do not read boundary content from dev-portal

---

src/data/boundary.json
src/data/consul.json
src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/terraform.json
src/data/vagrant.json
src/data/vault.json
src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts
src/views/docs-view/utils/product-url-adjusters.ts

- [Preview link](https://dev-portal-git-ambdocs-downloads-links-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202981777114596/f) 🎟️
- Adds a test suite for `rewriteDocsUrl`, and tests for `/downloads` links
- Adds `"downloads"` to product JSON files that have a downloads page
- HCP does not have a downloads page
- Waypoint's file already had the path added
- This is a link we just haven't handled yet for all products
- We are not yet handling external links to .io sites (such as terraform.io/downloads), but I'm exploring that today

[rewriteDocsUrl] Handle /downloads links in docs content

---

src/components/image-config/index.tsx
src/components/image/index.tsx
src/layouts/sidebar-sidecar/utils/_local_platform-docs-mdx/index.tsx

chore: use ImageConfig on docs

---

src/data/boundary.json

- [Preview link](https://dev-portal-git-nq-update-boundary-alert-banner-25a9b6-hashicorp.vercel.app/) 🔎
This PR updates the alert banner at https://boundaryproject.io to showcase registration for HashiConf Global.

feat(boundary): Update alert banner

---

src/layouts/core-dev-dot-layout/index.tsx
src/pages/_app.tsx

- [Preview link](https://dev-portal-git-pbwelcome-toast-fix-hashicorp.vercel.app/) 🔎
Fix welcome notifications so they only appear in developer and not proxied .io sites

fix(welcome toast): don't show on proxied .io sites

---

src/layouts/core-dev-dot-layout/index.tsx

- [Preview link](https://dev-portal-git-pbhide-welcome-toast-swingset-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
Hide welcome toast in swingset

fix(welcome notifications): hide in swingset & error pages

---

src/views/docs-view/server.ts

No longer pull nomad's content from its `dev-portal` branch, instead read from `stable-website`.

chore: remove nomad from the dev-portal latest version ref list

---

src/content/packer/docs-landing.json
src/content/packer/install-landing.json

Creating an overview docs landing page for Packer; updating the Packer install page content.
These are required for the devdot launch.

Update Packer docs homepage and install page

---

src/content/vagrant/install-vmware-landing.json
src/content/vagrant/product-landing.json

- [Preview link](https://dev-portal-git-ar-vagrant-content-hashicorp.vercel.app/vagrant) 🔎
- Reordered the new callouts on the landing page
- Added some specific links for the VMWare install page

Vagrant content updates

---

build-libs/__tests__/build-beta-opt-in-redirect.test.ts
build-libs/build-beta-opt-in-redirect.js
build-libs/redirects.js

Updates our opt-in redirect generation to generate from our `beta_product_slugs` list and a product's `basePaths`. This means when we rollout a new product we don't need to update the redirects config at all, it should _just work_.

fix: opt-in redirects for .io sites

---

src/data/consul.json

- [Preview link](https://dev-portal-git-nq-update-alert-banner-hc-gl-22-hashicorp.vercel.app/) 🔎
This PR updates the alert banner at https://consul.io to showcase registration for HashiConf Global 2022. **This should not merge until Monday, September 19.**

feat(consul): Update alert banner

---

src/layouts/_proxied-dot-io/packer/index.tsx

- [Preview link upcoming](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app) 🔎
This PR replaces the Packer subnav's "API" link with a "Plugins" link.

fix(packer): API subnav link -> Plugins link

---

src/lib/__tests__/get-target-path.test.ts
src/lib/get-target-path.ts
src/lib/get-version-from-path.ts

fix: Revert #1049 to fix version switcher bug

---

src/content/packer/docs-landing.json
src/content/vagrant/docs-landing.json
src/content/vagrant/product-landing.json

chore: fix vagrant link

---

src/views/homepage/components/product-nav/product-nav.module.css

- [Preview link](https://dev-portal-git-fork-braydenlove-patch-1-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1203018211842978/f) 🎟️
I am refining the corner radius of the product-nav.
Currently we are using 14px corner radius which looks odd on the far right and left cards visually. It is also not a common radius in HDS, we are moving forward with 6px which is the common radius across HDS.
Initially we wanted it to be a bit more 'round' in appearance but we went too far. 6px feels better aligned to the rest of the system and site.
Still can't upload images for some reason...

style: refine corner radius on product-nav

---

src/layouts/_proxied-dot-io/packer/index.tsx

Adds `ProductMetaProvider` to packer's io layout, so that the opt-in banner will render properly.

fix: Adds ProductMetaProvider to packer

---

src/components/opt-in-out/helpers/platform-options.ts

chore: fix hcp domain

---

.github/workflows/register-preview-url.yml

chore: stub in workflow to register preview urls

---

src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts
src/views/docs-view/utils/product-url-adjusters.ts

Update the logic to handle anchor links, which should never be rewritten here.
(e.g. see the anchor links on this page: https://developer.hashicorp.com/nomad/docs/configuration/client)

fix: Adjust rewriteDocsUrl to handle anchor links

---

src/views/docs-view/server.ts

Stop using the `dev-portal` branch for vault and waypoint to ensure the latest content is coming from the correct source.

chore: stop using dev-portal branch for vault and waypoint

---

.github/workflows/register-preview-url.yml
scripts/add-preview-url-to-cloud-idp.ts

Add GitHub workflow to register Vercel preview URLs (hash and branches) with CloudIDP

feat: register-preview-url

---

src/content/hcp/docs-landing.json
src/content/hcp/product-landing.json

Update landing pages for HCP content.
- [Preview link](https://dev-portal-git-gghcp-description-hashicorp.vercel.app/hcp) 🔎
Update content for HCP landing pages. Fix links, descriptions, etc.

Fix HCP content landing pages for beta

---

src/components/command-bar/commands/search/components/custom-hits-container/custom-hits-container.module.css
src/components/command-bar/commands/search/components/custom-hits-container/index.tsx
src/components/command-bar/commands/search/components/dialog-body/index.tsx
src/components/command-bar/commands/search/components/dialog-body/search-command-bar-dialog-body.module.css
src/components/command-bar/components/dialog/command-bar-dialog.module.css
src/components/tabs/components/tab/types.ts
src/components/tabs/hooks/use-synced-tab-groups.ts
src/components/tabs/types.ts

- [Preview link](https://dev-portal-git-ambupdate-search-tabs-styles-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203048705617961/f) 🎟️
- Updates the `Tabs` in global search to use the new compact variant and icons
- Adjusts spacing within the dialog body to align with designs
<details>
<summary>No search query</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-9836%2C4055%2C1.8">Figma link</a>
</details>
<details>
<summary>Documentation results</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-9929%2C2651%2C1.82">Figma link</a>
</details>
<details>
<summary>Tutorials results</summary>
<a …

[Global Search] Use compact Tabs with icons

---

src/components/_proxied-dot-io/consul/downloads-props/index.jsx
src/content/consul/install-landing.json
src/content/consul/product-landing.json
src/content/hcp/tutorials-sidebar.json
src/pages/_proxied-dot-io/consul/consul-on-kubernetes/index.tsx
src/pages/_proxied-dot-io/consul/docs/content.json

Update Consul GS collections

---

src/components/command-bar/components/dialog/command-bar-dialog.module.css

- [Asana task](https://app.asana.com/0/1202520168081556/1203052996378511/f) 🎟️
- Updates `color` of command bar's icon to match the designs
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-6978%2C3238%2C1.35)

[CommandBar] Setting icon color

---

src/components/badge/badge.module.css
src/components/command-bar/commands/search/components/no-results-message/index.tsx
src/components/command-bar/commands/search/components/no-results-message/no-results-message.module.css
src/components/standalone-link/standalone-link.module.css

- Asana tasks 🎟️
- [[Global Search] Font families are not setting correctly](https://app.asana.com/0/1202520168081556/1203052996378510/f)
- [[Global Search] No results message has wrong font styles and color](https://app.asana.com/0/1202097197789424/1203053381984302/f)
- Sets `font-family` CSS property in `Badge` and `StandaloneLink`
- Sets `color` CSS property in `NoResultsMessage`
- Updates `NoResultsMessage` to leverage `Text` component for font styles
<details>
<summary>Search results with Badges</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-7232%2C2028%2C1.35">Figma link</a>
</details>
<details>
<summary>No results state</summary>
<a href="https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A14190 …

[Global Search] Fix font families and no results message styles

---

src/components/command-bar/commands/search/components/tutorials-tab-contents/index.tsx

- [Preview link](https://dev-portal-git-ambgs-tutorial-library-cta-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1203053381984288/f) 🎟️
- Updates the Tutorials tab to always show the Tutorial Library CTA, regardless of search results
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-6533%2C-1796%2C0.95)

[Global Search] Always showing Tutorial Library CTA in Tutorials tab

---

src/components/video-embed/index.tsx

Updates the homepage video embed placeholder positioning to avoid layout shift.
Before:
After:

fix: update video placeholder positioning to avoid layout shift

---

src/components/dev-dot-content/mdx-components/mdx-hcp-callout/docs.mdx
src/components/dev-dot-content/mdx-components/mdx-hcp-callout/index.tsx
src/components/dev-dot-content/mdx-components/mdx-hcp-callout/types.ts
src/views/docs-view/index.tsx

- [Preview link](https://dev-portal-git-pbhcp-callout-updates-hashicorp.vercel.app/swingset/components/hcpcallout) 🔎
Update component name and subtitle

chore(hcp callout): rename component and update subtitle copy

---

package-lock.json
package.json

Installs `@types/shortid`
To fix the following TS error:
```
src/components/feedback-form/index.tsx:2:21 - error TS2307: Cannot find module 'shortid' or its corresponding type declarations.
```

Installing @types/shortid

---

src/components/command-bar/components/dialog/command-bar-dialog.module.css
src/components/command-bar/components/dialog/footer.tsx
src/components/command-bar/components/list-item/command-bar-list-item.module.css
src/components/command-bar/components/list-item/index.tsx

- Asana tasks 🎟️ 
- [[Global Search] Update footer Badges to be less prominent](https://app.asana.com/0/1202097197789424/1203060963607151/f)
- [[Global Search] Update Product Badges in search hits to have background color](https://app.asana.com/0/1202097197789424/1203060963607152/f)
- Sets the background color of the dialog header, body, and footer to `--token-color-surface-primary`
- Updates the `type`s of the footer `Badge`s to `"filled"`
- Sets the background color of the product `Badge`s in search results to `--token-color-surface-primary`
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=14771%3A186283&viewport=-14064%2C3685%2C1.49)

[Global Search] Update dialog footer badges and search result product badges

---

src/components/command-bar/commands/search/components/documentation-tab-contents/documentation-hit.tsx
src/components/command-bar/commands/search/components/tutorials-tab-contents/tutorial-hit.tsx

- Adds checks in `DocumentationHit` and `TutorialHit` that prevent rendering the component if a `hit`'s `_highlightResult` is falsy, or the needed properties in the object are not defined
- There was an error happening under `/vault` that caused the site to blow up

[Global Search] Check for invalid hit results

---

src/components/command-bar/components/activator/command-bar-activator.module.css
src/components/command-bar/components/activator/index.tsx

- [Preview link](https://dev-portal-git-ambgs-nav-header-badges-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203053381984282/f) 🎟️
- Updates the background color of the `CommandBarActivator` `Badge`s
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-39221%2C10162%2C4.57)

[CommandBarActivator] Updating Badge background colors

---

src/components/dev-dot-content/mdx-components/mdx-heading-permalink/index.tsx
src/components/dev-dot-content/mdx-components/mdx-heading-permalink/mdx-heading-permalink.module.css

- [Preview link](https://dev-portal-git-pbfix-dev-errors-permalink-hashicorp.vercel.app/) 🔎
Fixes error:
`Warning: React does not recognize the `parentName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `parentname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
`
Select only the props that are valid and needed.

fix(heading permalink): Fix unrecognized props error

---

config/base.json

Ships Global Search to prod! 🎉 
Preview environments should be unaffected.

Ship Global Search

---

package.json

Make sure we are generating the needed files on server start.

fix: generate opt-in redirect checks on npm start

---

src/data/boundary.json
src/data/consul.json
src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/vagrant.json
src/data/vault.json
src/data/waypoint.json

- [Preview link](https://dev-portal-git-nq-alert-banners-hc-gl-2022-open-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202594346269837/1203095337711091/f) 🎟️
This PR updates alert banners on our product sites to showcase the opening of HashiConf Global, **intended to merge at Oct 5 at 8am PST/11am ET.**
---
- https://app.asana.com/0/0/1203102822887328

feat(AlertBanners): Update for HashiConf Global open

---

package-lock.json
package.json

- 🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1203093711604797/f)
This PR updates `mktg-logos` so as to enable updated unattributed Vault logos (related PR [here](https://github.com/hashicorp/mktg-logos/pull/12)).
- Updates to the latest version of `mktg-logos`
- Navigate to /vault in the preview
- Verify that the correct logo is rendered in the nav:
_Old Logo_
_New Logo_

Chore: Bump `mktg-logos`

---

src/pages/api/revalidate.ts

- Updates the revalidate endpoint to handle `hcp` by using `productSlugForLoader` if it exists
- Handle cases where root docs paths don't have nav data (e.g. Boundary's generated api docs)
- Enable revalidate of hcp's docs pages
- Fixes revalidate of boundary's docs pages

fix: update revalidate to handle HCP and boundary

---

Dockerfile

This updates the 2nd Docker stage image to also be Node 16

fix: missed image update

---

src/components/dev-dot-content/mdx-components/mdx-table/mdx-table.module.css

Fixes an issue where `table` elements were not spaced correctly in MDX content.
- Adds `margin` CSS to `MdxTable` outer element (`.tableWrapper`).
- Tables should have `24px` spacing between them
- Tables next to other blocks should have at least `24px` spacing between them
[task]: https://app.asana.com/0/1202097197789424/1203110277457958/f
[preview]: https://dev-portal-git-zsfix-mdx-table-spacing-hashicorp.vercel.app/
[/terraform/enterprise/api-docs/admin/module-sharing]: https://dev-portal-git-zsfix-mdx-table-spacing-hashicorp.vercel.app/terraform/enterprise/api-docs/admin/module-sharing

fix: MDX table spacing

---

.github/workflows/cache.yml
scripts/warm-cache.ts
scripts/warm-dotio-cache.ts

This change updates our cache warming script to also warm the cache for our developer docs routes, using the revalidate endpoint.
For each product slug, this will make a call to `developer.hashicorp.com/api/revalidate`, which in turn will ISR every docs route present in our nav data files.
This should ensure that users don't experience slow load times immediately after a deployment when visiting a page which was not statically generated at build time.

feat: update cache warmer to use the revalidate endpoint for developer docs paths

---

package-lock.json
package.json

This should fix breakages as reported in https://github.com/hashicorp/waypoint/pull/3998
- Sample vercel build failure: https://vercel.com/hashicorp/waypoint/AtoUZX9wCV6Upf6TqepuWyH6mHCk?utm_source=notifications

revert engines

---

src/views/product-downloads-view/server.ts

Updates logic around the path generation to read the install content file. This ensures that [output file tracing](https://nextjs.org/docs/advanced-features/output-file-tracing) will pick u p the path and include it in the build artifact. Currently, ISR fails because the file can't be found.

fix(downloads): ensure downloads pages can ISR

---

src/components/dev-dot-content/mdx-components/mdx-table/mdx-table.module.css

Vertically aligns MDX table cells.
Adds `vertical-align: top` to `td` elements in MDX tables.
[task]: https://app.asana.com/0/1202097197789424/1203007761064336/f
[preview]: https://dev-portal-git-zstop-align-table-cells-hashicorp.vercel.app/consul/docs/agent/telemetry

fix: vertical align top MDX table cells

---

next.config.js
package-lock.json
package.json
src/flags/client.ts
src/flags/config.ts
src/flags/edge.ts
src/flags/server.ts

Install Happykit package and sets up basic config files.
To enable AB testing features across io sites and developer in the future.
Following Happkit setup steps https://github.com/happykit/flags/tree/master/package#setup
Example usage shown here:
- [src/middleware.ts](https://github.com/hashicorp/dev-portal/blob/c11bce248ce7528a4f352864e4fdf8564a39eb63/src/middleware.ts)
- [src/pages/_proxied-dot-io/vault/home-test.tsx](https://github.com/hashicorp/dev-portal/blob/c11bce248ce7528a4f352864e4fdf8564a39eb63/src/pages/_proxied-dot-io/vault/home-test.tsx)

chore: add happykit and config files

---

scripts/warm-cache.ts

Updates our cache warming script so that it's more resilient to errors occurring, ensuring we fire off all intended requests before bailing.

fix(warm-cache): make cache warming more resilient to errors

---

.github/workflows/cache.yml

The workflow needs access to `REVALIDATE_TOKEN` in order for the calls to `/api/revalidate` to work.

fix(warm cache): pass revalidate token to action step

---

scripts/generate-opt-in-redirect-checks.ts
src/middleware.ts

Updates our opt-in redirects to always apply when a product is removed from the beta array and we're in a production environment. This is further pre-work to make the GA rollout only a config change.

feat: update opt-in redirect conditional for GA

---

src/content/consul/install-landing.json
src/content/hcp/product-landing.json

- [Preview link](https://dev-portal-git-ksfix-consul-links-hashicorp.vercel.app/hcp) 🔎
- check the consul hcp consul sidebar link on the [install page](https://dev-portal-git-ksfix-consul-links-hashicorp.vercel.app/consul/downloads) and  the get started HCP consul link on the [hcp landing page](https://dev-portal-git-ksfix-consul-links-hashicorp.vercel.app/hcp)

fix consul hcp links

---

src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts
src/views/docs-view/utils/product-url-adjusters.ts

Some links in docs content are folder relative, e.g. `./docker`. These should not be rewritten at all and will _just work_. See the links in this section https://developer.hashicorp.com/waypoint/plugins/aws-ecs#builders

fix: do not rewrite docs links which are folder relative

---

build-libs/__tests__/build-beta-opt-in-redirect.test.ts
config/base.json
config/production.json
proxied-redirects/www.waypointproject.io.redirects.js

Make waypoint GA.
* Removes the opt-out CTA
* Makes redirects from waypointproject.io to developer permanent

feat: make waypoint GA

---

proxied-redirects/www.consul.io.redirects.js

consul GA: import redirects

---

build-libs/redirects.js
build-libs/rewrites.js
playwright.config.ts
src/__tests__/e2e/beta-opt-in-out.spec.ts
src/__tests__/e2e/redirects.spec.ts
src/__tests__/e2e/rewrites.spec.ts
src/components/_proxied-dot-io/common/preview-product-select/index.tsx
src/constants/hostname-map.ts
src/middleware.ts
src/pages/_error.jsx

Refactors all usages of `io_preview` to use our `hc_dd_proxied_site` cookie, which is a more generic cookie that handles redirects/rewrites for the sites which are proxied through this app.
This fixes a failing e2e test and removes an additional abstraction in our complex proxy / redirect / rewrite logic.
> **Note**
> The `hc_dd_` prefix is intended to stand for `HashiCorp Dev Dot` 🤷‍♂️ 
- Open the preview: https://dev-portal-git-brkchore-io-preview-to-proxied-site-hashicorp.vercel.app/
- Select products from the product switcher in the bottom left
- Validate that the correct proxied site is rendered
- Select consul from the product switcher
- Navigate to /api
- Validate you get …

chore: refactor io_preview to use hc_dd_proxied_site cookie

---

src/middleware.ts

Make sure it only excludes /api/* routes
Updates the middleware matcher to only exclude api routes, not any paths starting with `/api`

fix: scope middleware matcher for api routes

---

next.config.js

This adds `MKTG_CONTENT_API` to our next config, so that product previews (ex. `terraform-docs-agents`) can detect it, and not need to add a Vercel env var.
> **Warning** - `.env` doesn't appear to be picked up in current set up for product repos.
See https://github.com/hashicorp/terraform-docs-agents/pull/25
This is in support of terraform sub-project deploy previews
Visit https://terraform-docs-agents-hhafmkv7p-hashicorp.vercel.app/terraform/cloud-docs — it should render

add `MKTG_CONTENT_API` to next config

---

src/middleware.ts

This ignores all `/_next/` paths from our middleware
To reduce unnecessary middleware invocations
Regex test:
- https://regexr.com/702r6

chore(middleware): ignore all `_next/`

---

proxied-redirects/www.nomadproject.io.redirects.js

This PR migrates Nomad redirects using the `import-product-redirects` script:
```sh
npx hc-tools ./scripts/redirects/import-product-redirects.ts hashicorp/nomad/website/redirects.js www.nomadproject.io
```
[task]: https://app.asana.com/0/0/1203168563666032/f
[preview]: https://dev-portal-git-zsimport-nomad-redirects-hashicorp.vercel.app

feat: migrate nomad redirects

---

proxied-redirects/www.vaultproject.io.redirects.js

Adds redirects for www.vaultproject.io, sourced from vault's repository.

feat: adds www.vaultproject.io redirects

---

build-libs/__tests__/build-beta-opt-in-redirect.test.ts
config/base.json
config/production.json
src/components/_proxied-dot-io/vault/subnav/index.jsx
src/layouts/_proxied-dot-io/vault/index.tsx

Removes `vault` from the beta slugs array to permanently redirect vault's doc's pages to developer

feat: make vault GA

---

proxied-redirects/www.boundaryproject.io.redirects.js

chore: import boundary redirects

---

build-libs/__tests__/build-beta-opt-in-redirect.test.ts
config/base.json
config/production.json
src/components/_proxied-dot-io/boundary/subnav/index.jsx
src/layouts/_proxied-dot-io/boundary/index.tsx

This removes `boundary` from `beta_product_slugs` and updates `.io` UI Nav Links to point at developer

chore: remove boundary from `beta_product_slugs` + update Subnav links

---

config/base.json
config/production.json
src/views/docs-view/server.ts

Removes HCP from the beta product slugs array, making it GA.

feat: make HCP GA

---

build-libs/redirects.js

Use `isDeployPreview()` for checking whether or not to load local redirects. `isContentDeployPreview()` relies on old env variables that we are no longer using going forward.

fix: use isDeployPreview for loading local redirects

---

src/views/docs-view/utils/get-deploy-preview-loader.ts

Removes a debugging log to reduce noise in content repo deploy previews.

chore: removes debug log to reduce noise

---

src/pages/hcp/api-docs/packer/[[...page]].tsx

It appears that the HCP Packer API specs have moved to a new repository. I've updated our code to pull from the new location.

fix(hcp api docs): update packer api spec location

---

src/views/docs-view/server.ts
src/views/docs-view/utils/get-deploy-preview-loader.ts

Tweak the order of our remark plugins to ensure that link rewrites always get applied. We got a report that some links didn't appear to be properly rewritten.

fix(docs-view): ensure link rewrites always get applied

---

src/content/well-architected-framework/index.json

Added "well-architected-framework/security"
Adding Security to framework pillar in dev portal menu. It's currently under the overview section.
This helps to keep the current continuity.

content: Adding Security Pillar to waf sidebar

---

src/components/command-bar/components/activator/command-bar-activator.module.css

- [Preview link](https://dev-portal-git-ambnav-header-responsiveness-hashicorp.vercel.app/terraform) 🔎
- Updates the breakpoint where `CommandBarActivator` changes to be icon-only
- Makes the full-size `CommandBarActivator` narrower
- There is not enough space in Terraform's navigation header for all the elements, including the auth elements
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=15550%3A198031&viewport=2818%2C3976%2C0.93)
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=15535%3A198317&viewport=2979%2C3413%2C0.93)

[CommandBarActivator] Changing to icon-only at 1238px

---

src/layouts/docs-view-layout/index.tsx
src/layouts/sidebar-sidecar/index.tsx
src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
src/layouts/sidebar-sidecar/types.ts
src/views/collection-view/index.tsx
src/views/product-tutorials-view/index.tsx
src/views/tutorial-view/index.tsx
src/views/well-architected-framework/collection-view/index.tsx
src/views/well-architected-framework/index.tsx
src/views/well-architected-framework/tutorial-view/index.tsx

remove opt out component from view

---

src/components/tutorial-meta/index.tsx
src/hooks/use-authentication/index.ts
src/hooks/use-authentication/types.ts
src/views/authenticated-view/index.tsx
src/views/collection-view/components/collection-meta/index.tsx
src/views/sign-up-view/index.tsx

- [Preview link](https://dev-portal-git-ambremove-auth-flag-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202941566536299/1203237572285277/f) 🎟️
- Removes the `enableAuth` feature flag and the corresponding `isAuthEnabled` boolean from the `useAuthentication` hook
- This feature flag was purely for iterative development of auth features. Now that auth is released, we can clean up this feature flag and fix the flash that's happening with the `useFlags` hook.

Removing auth flag

---

src/data/vault.json

This PR updates the `alertBanner` configuration for Vault to drive users to the Vault 1.12 webinar.

feat: add vault 1.12 webinar alert banner

---

package-lock.json
package.json
src/components/_proxied-dot-io/common/io-home-call-to-action/index.tsx
src/components/_proxied-dot-io/common/io-home-call-to-action/style.module.css
src/components/_proxied-dot-io/common/io-home-pre-footer/index.tsx
src/components/_proxied-dot-io/common/io-home-pre-footer/style.module.css

- [Preview link](https://dev-portal-git-pbconvert-iohomeprefooter-nextsteps-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1187888078520425/1203270570400150/f) 🎟️
Use the [WPL NextSteps ](https://react-components.vercel.app/components/nextsteps) component in all .io homepages.
Convert the current `<IoHomePreFooter />` component to use the `<NextSteps />` and add some container styles for spacing alignment.
Visually check out all .io homepages that include `<IoHomePreFooter />`. The pre footer section should look like the react-component and no content should be changed.

update(.io homepage): use wpl `<NextSteps />` component in pre footer section

---

src/components/footer/index.tsx

- [Preview link](https://dev-portal-git-zsfix-footer-sentence-case-hashicorp.vercel.app/) 🔎
Fixes up footer content so that sentence case is consistent.
See [task][task] for context, this is meant to be a tiny lil content fix.
[task]: https://app.asana.com/0/1202097197789424/1203231796733953/f

chore: consistent sentence-case in footer

---

src/lib/integrations-api-client/index.ts
src/views/product-integrations-landing/components/categorized-integrations-list/index.tsx
src/views/product-integrations-landing/components/faceted-integrations-list/index.tsx
src/views/product-integrations-landing/components/tier-badge/index.tsx

Related: https://github.com/hashicorp/integrations-api/pull/43
This updates the frontend from "Verified" to "Partner"
- https://dev-portal-g3i5ly2ph-hashicorp.vercel.app/packer/integrations
- [Asana task](https://app.asana.com/0/1202626741675858/1203008311551728/f) 🎟️
See:

feat(integrations): verified to partner

---

src/components/navigation-header/components/product-page-content/utils/__tests__/get-nav-items.test.ts
src/components/navigation-header/components/product-page-content/utils/get-nav-items.ts

- [Preview link](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1203333219291187/f) 🎟️
- Adds "Try Cloud" nav header link for Boundary, Consul, HCP, Packer, Terraform, Vault, and Waypoint
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=15473%3A197055&viewport=2885%2C2786%2C0.91&t=wUhUXlNWrGtQjWm7-11)

Adding Try Cloud item for products in hcp

---

src/pages/hcp/api-docs/packer/[[...page]].tsx

In this PR, I'm updating the API docs target file to pull from the desired API version. 
The Packer team has beta features in the API preview version `2022-04-11` which we wish to list in our API docs.

Update Packer API docs target file

---

global.d.ts
scripts/generate-opt-in-redirect-checks.ts
src/middleware.ts

It looks like the GA redirects from product docs routes to developer accidentally got removed in #1322. This adds them back so the redirects will work.

fix: add back GA redirects

---

src/hooks/use-authentication/index.ts

Short term adjustment to prevent the looping sign in behavior that Mike was seeing.

patch: sign out when encountering auth error

---

src/pages/consul/downloads/index.tsx

fix consul download link

---

.test/__mocks__/fileMock.js
.test/__mocks__/graphql-fragment-mock.js
.test/__mocks__/styleMock.js
jest.config.ts
package-lock.json
package.json
src/lib/learn-client/api/bookmark/__tests__/create-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/delete-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-all-bookmarks.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-bookmarks-by-tutorial-ids.test.ts

Adopt our shared jest config from `@hashicorp/platform-configs/jest/config`. Removes now-unnecessary jest config and related files/mocks.

feat: use shared jest config

---

src/views/product-downloads-view/helpers.ts

- ~~[Asana task](url)~~ 🎟️ NA. Requested via slack https://hashicorp.slack.com/archives/C011HP57U0Y/p1668620040985249
Instructions were broken, as reported [via slack](https://hashicorp.slack.com/archives/C011HP57U0Y/p1668620040985249)

update consul amazon-linux install instructions

---

package-lock.json
package.json
src/hooks/use-authentication/index.ts

- [Preview link](https://dev-portal-git-pbconsent-manager-sign-in-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203274026595792/f) 🎟️
Use updates from https://github.com/hashicorp/react-components/pull/824

update(consent-manager): Update package to solve banner issues

---

package.json

chore: adjust node engines

---

src/hooks/use-authentication/index.ts
src/layouts/base-new/index.tsx

The modal wasn't behaving as expected in production with the cascading errors. Rolling back for now!

chore: rollback modal

---

src/components/try-hcp-callout/components/hcp-logo-heading/index.tsx

I dropped a raw-include loader directive in #1376, this PR patches the issue.

hotfix: hcp logo in TryHcpCallout

---

next-auth.d.ts
package-lock.json
package.json
src/components/authentication-error-dialog/index.tsx
src/components/mobile-menu-container/components/mobile-user-disclosure/types.ts
src/components/mobile-menu-container/index.tsx
src/components/user-dropdown-disclosure/types.ts
src/hooks/use-authentication/index.ts
src/hooks/use-authentication/types.ts
src/lib/auth/cloud-idp-provider.ts
src/lib/auth/refresh-token-set.ts
src/lib/auth/user.tsx
src/lib/learn-client/api/bookmark/create-bookmark.ts
src/lib/learn-client/api/bookmark/delete-bookmark.ts
src/lib/learn-client/api/bookmark/get-all-bookmarks.ts
src/lib/learn-client/api/bookmark/get-bookmark.ts
src/lib/learn-client/api/bookmark/get-bookmarks-by-tutorial-ids.ts
src/lib/learn-client/api/progress/create-tutorial-progress.ts
src/lib/learn-client/api/progress/get-progress.ts
src/lib/learn-client/api/progress/get-tutorial-progress.ts
src/lib/learn-client/api/progress/update-tutorial-progress.ts
src/pages/api/auth/[...nextauth].ts
src/types/auth.ts

- [Preview link](https://dev-portal-git-ksupgrade-next-auth-hashicorp.vercel.app/) 🔎
Upgrading to the latest version of next auth. Looks like the biggest changes related to types. We should do smoketests to verify that auth is still working as expected.

chore: upgrade next-auth

---

public/boundary-sitemap.xml
src/content/boundary/install-landing.json
src/content/boundary/product-landing.json

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎 - I don't think the preview will work since this spans repos.
- [Asana task](https://app.asana.com/0/563192436488770/1201180027594366/f) 🎟️
This PR updates the link for the What is Boundary documentation topic.
In [PR #2626](https://github.com/hashicorp/boundary/pull/2626) in the Boundary repo, we added a new topic and updated the overall navigation. The **What is Boundary** and **Use Cases** topics were nested 1 level down. This PR updates the existing links to that topic with the new path.

Update links to What is Boundary topic

---

src/content/well-architected-framework/index.json

Adding a hyphen to well architected, making it well-architected
- [Preview link](https://dev-portal-git-bjcwaf-name-update-hashicorp.vercel.app/well-architected-framework) 🔎
- [Asana task](https://app.asana.com/0/1202314215619508/1202623686123605/f) 🎟️
Edited WAF to well-architected throughout. 
Edited to match the industry standard.

WAF Name updates

---

src/data/well-architected-framework.json

chore: fix waf name

---

.env
package.json
src/lib/integrations-api-client/index.ts
src/lib/integrations-api-client/standard-client.ts
src/lib/with-timing.ts
src/pages/[productSlug]/integrations/[integrationSlug]/index.tsx
src/pages/[productSlug]/integrations/index.tsx
src/views/product-integration/components/header/index.tsx
src/views/product-integration/index.tsx
src/views/product-integrations-landing/components/faceted-integrations-list/index.tsx
src/views/product-integrations-landing/components/integrations-list/index.tsx

This updates https://github.com/hashicorp/dev-portal/pull/1365 to handle breaking changes from the Integrations API [v0.4.0](https://github.com/hashicorp/integrations-api/blob/main/CHANGELOG.md#v040---2022-11-23)
- https://app.asana.com/0/0/1203366189861872/f
This also implements a [`withTiming` method](https://github.com/hashicorp/dev-portal/pull/1393/files#diff-fb22e7c24b828e45e9c2d94eacbe3507479f0b72712c281fadd1cb97ac12d893)
- https://app.asana.com/0/1100423001970639/1203442542938543/f

kw.integrations demo 2

---

.env
src/lib/__tests__/with-timing.test.ts
src/lib/learn-client/index.ts
src/lib/remark-plugins/rewrite-tutorial-links/utils/get-tutorial-map.ts
src/lib/with-timing.ts
src/pages/[productSlug]/docs/index.tsx
src/pages/[productSlug]/tutorials/[...tutorialSlug]/index.tsx
src/pages/consul/docs/[...page].tsx
src/views/docs-view/server.ts

- [Asana task](https://app.asana.com/0/1100423001970639/1203442542938543/f) 🎟️
This adds a `with-timing` method to wrap function calls, and apply a label for console debugging.
This also applies the method to a small handful of places across the codebase.
The logging is toggled via env var: `HC_DEBUG_TIMINGS="1"`
<details>
<summary><b>Console Output on:</b> <code>http://localhost:3000/consul/docs</code></summary>
```console
wait  - compiling /api/auth/[...nextauth] (client and server)...
event - compiled successfully in 75 ms (1093 modules)
[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
[middleware] /consul/docs: 0.074ms
[[productSlug]/docs/index::getStaticProps] …
```

feat: with-timing

---

src/pages/_error.jsx

Adds a log in our `getServerSideProps` method of our error page. This should hopefully give more insight into what errors we're seeing when we render the error page.

chore: add log to getServerSideProps for the error page

---

src/components/button-link/index.tsx
src/components/button-link/types.ts
src/components/card-link/docs.mdx
src/components/card-link/index.tsx
src/components/card-link/types.ts
src/components/command-bar/components/dialog/footer.tsx
src/components/footer/index.tsx
src/components/footer/types.ts
src/components/navigation-header/components/give-feedback-button/index.tsx
src/components/navigation-header/components/primary-nav-link/index.tsx
src/components/navigation-header/components/product-page-content/utils/__tests__/get-nav-items.test.ts
src/components/navigation-header/components/product-page-content/utils/get-nav-items.ts
src/components/standalone-link/index.tsx
src/components/standalone-link/types.ts
src/views/homepage/components/merchandising-slots/slots/hashiconf-global-slot/index.tsx
src/views/homepage/components/pre-footer/index.tsx
src/views/product-downloads-view/components/downloads-section/index.tsx
src/views/product-tutorials-view/components/product-view-content/components/branded-callout/index.tsx

- [Preview link](https://dev-portal-git-ambrename-openInNewTab-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203388835781795/f) 🎟️
- Renames the `openInNewTab` prop for various components to `opensInNewTab`
- Updates references to `openInNewTab` to use the new name
- Updates some components' props interfaces to inherit props from `components/link`
- For consistency with `components/link`'s `opensInNewTab` prop name

Rename openInNewTab props to opensInNewTab

---

build-libs/__tests__/redirects.test.ts
build-libs/redirects.js

It seems like product-specific redirects are getting dropped when we handle grouping our redirects for use in middleware. I've updated the logic and added a test case to ensure that redirects for the developer domain are retained.

fix: ensure product redirects do not get dropped

---

src/components/_proxied-dot-io/packer/remote-plugin-docs/utils/resolve-nav-data.js
src/lib/env-checks.js
src/pages/_proxied-dot-io/packer/community-plugins.jsx
src/pages/_proxied-dot-io/packer/community-tools.jsx

- Fixes loading packer plugin data for local and deploy previews in the packer repository.
- Removes a now-unused method `isContentDeployPreview()`

fix local packer plugin manifest loading

---

src/content/well-architected-framework/index.json

Remove HashiCorp's to replace it with HashiCorp.
- [Preview link](https://dev-portal-git-bjcwaf-intro-update-hashicorp.vercel.app/well-architected-framework) 🔎
Edited WAF introduction adjusting HashiCorp's well-architected framework to HashiCorp Well-Architected Framework 
This new adjustment makes the WAF a product of HashiCorp with a proper name.

WAF Intro update

---

src/data/consul.json

- [Preview link](https://dev-portal-git-acconsul-webinar-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202791227659279/1203375748343205/f) 🎟️
Update consul alert banner to promote webinar.

update consul alert banner

---

src/views/product-integrations-landing/components/integrations-list/index.tsx
src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
src/views/product-integrations-landing/components/paginated-integrations-list/style.module.css
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx

[🔍 Preview](https://dev-portal-git-brintegrations-pagination-2-hashicorp.vercel.app/vault/integrations)

Integrations Pagination

---

src/components/accordion-disclosure/accordion-disclosure.test.tsx

chore: adds test for isOpen

---

src/pages/api/tutorial-feedback.ts

chore: add full error to feedback log

---

src/views/product-integration/index.tsx
src/views/product-integration/style.module.css

[🔍 Preview](https://dev-portal-git-brintegration-sidebar-hashicorp.vercel.app/waypoint/integrations/docker)

Adds proper sidebar to integrations pages

---

src/pages/api/revalidate.ts

In preparation for rolling out the on-demand trigger to our content workflows. This change adjusts our revalidate endpoint to handle TF's sub-project repositories. This should be more efficient than busting the cache for all of terraform's pages.

feat: adjust the revalidate endpoint to handle TF sub-projects

---

src/content/certifications/landing-faq.mdx
src/content/certifications/landing.json
src/content/certifications/programs/infrastructure-automation.json
src/content/certifications/programs/networking-automation.json
src/content/certifications/programs/security-automation.json

This PR updates landing page content on the certifications assembly branch.
[/certifications]: https://dev-portal-git-zscertifications-content-2022-12-15-hashicorp.vercel.app/certifications

chore: update home page content

---

.github/workflows/docs-content-link-rewrites-e2e.yml

Forgot to remove these lines in #1465 😅

Removing TODOs from new workflow

---

src/data/alert-banner.json

- [Asana task](https://app.asana.com/0/1202114367927919/1203572855492468/f) 🎟️
Updates the expiration date for research banner from mid-day Jan 31, 2023 to Dec 29, 2022 EoD PT.
Org-wide decision has been made to sunset Maze. Consequently, since the research banner uses Maze, we need to expire  it this year.

Chore: updates research banner expiration

---

src/pages/[productSlug]/integrations/[...integrationSlug]/index.tsx
src/views/product-integration/components/component-tab-content/index.tsx
src/views/product-integration/components/component-tab-content/style.module.css
src/views/product-integration/index.tsx

https://dev-portal-git-kw-improve-markdown-rendering-hashicorp.vercel.app
Consistent look/feel of code blocks and markdown in general
This leverages `next-mdx-remote` and our typical suite of remark/rehype plugins and client-side react components
---
- https://app.asana.com/0/0/1203548351777713

[integrations] Improve markdown rendering

---

src/pages/[productSlug]/integrations/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css
src/views/product-integrations-landing/index.tsx

- https://dev-portal-git-kwupdated-filtering-hashicorp.vercel.app/waypoint/integrations
---
- https://app.asana.com/0/0/1203582243454853

chore: move filtering out of sidebar

---

src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css
src/views/product-integrations-landing/contexts/integrations-search-context.tsx

---
- https://app.asana.com/0/0/1203604781390831

feat: add "Flags" filtering + style updates

---

src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
src/views/product-integrations-landing/components/paginated-integrations-list/style.module.css

---
- https://app.asana.com/0/0/1203548351777721

feat: Use new Pagination

---

package-lock.json
src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css

- [Preview Link](https://dev-portal-ido6fy5oc-hashicorp.vercel.app/waypoint/integrations)
- [Figma](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=17267%3A219677&t=Q7TzcVkE2uWMOEj2-0)
This updates the Integrations Filtering UI with proper mobile styles
---
- https://app.asana.com/0/0/1203705051952457

integrations: Mobile styles for Filtering

---

src/content/certifications/exam-faqs/terraform-associate-003.mdx

- [Preview link](https://dev-portal-git-lszp-cert-tf003-dates-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
- ~~[Asana task](url) 🎟️~~
- Added a new faq item "Exam Availability Dates"
- Added text and table to "Which Exam to Take" faq item
This additional content is needed to prepare folks for the upcoming exam release
Reused content from https://preview.hashicorp.com/certification/terraform-associate-next
NA
Thanks for the good read-me page so I could figure out how to do this.

Add dates/changelog to terraform-associate-003.mdx

---

analytics/spec/events/integration_library_searched.yaml
src/lib/hooks/use-typing-debounce.ts
src/views/product-integrations-landing/components/searchable-integrations-list/helpers/analytics.ts
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx

Implements Integrations Library analytics events.
- Add helper functions integrations library events, to match `.yml` spec
- Use library event helpers in the `SearchableList` component
https://user-images.githubusercontent.com/4624598/213570164-39560275-3727-434b-8cc3-3fbe8cce7856.mp4
> **Note**: analytics events may be easier to see firing when running this work locally, as they're logged to the console in development.
- For `integration_library_searched`: When entering any search query more than 2 characters, you should see an analytics event firing for each new query string
- For `integration_library_filter_selected`: When toggling any of the filtering properties "on" (but not "off"), you should see an analytics event firing
Not at …

feat: implement integrations analytics

---

src/content/certifications/exam-faqs/terraform-associate-003.mdx

We are pushing dates back two weeks for go-live. This commit captures all date changes in page text on the Terraform Associate (003) page.
- [Preview link](https://dev-portal-git-eganhashicorp-patch-1-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
Changed the go live and scheduling dates for TF Associate 003
We are pushing our launch back two weeks and need to ensure dates match this
Just text changes

Updated dates for Terraform Associate (003)

---

src/content/vagrant/product-landing.json

Add callout for HCP account link to Vagrant Cloud

---

src/data/consul.json
src/data/nomad.json
src/data/vault.json

- [Asana task](https://app.asana.com/0/1202791227659279/1166227505681935/f) 🎟️
Adds HashiTalks alert banners to vault, consul, and nomad.

chore: add hashitalks alert banners

---

src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts
src/views/docs-view/utils/product-url-adjusters.ts

With the link rewrite effort, we noticed some image paths were being prepended with the .io domain since they were treated as unknown base paths. This adds a check to skip all node urls that end with common image suffixes.

fix: do not process image links

---

src/views/product-integrations-landing/components/integrations-list/style.module.css

Updates a few styles for the cards to address some issues that were caught in VQA.
[🔍 Preview](https://dev-portal-git-brcard-styling-hashicorp.vercel.app/vault/integrations)
- 🎟️ [Refine card typography styles](https://app.asana.com/0/1203792610600085/1203810707418767)
- 🎟️ [Refine card spacing at smaller breakpoints](https://app.asana.com/0/1203792610600085/1203810703916569)

Fix Card Styling

---

src/views/product-integrations-landing/components/integrations-list/index.tsx
src/views/product-integrations-landing/components/integrations-list/style.module.css
src/views/product-integrations-landing/components/paginated-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx

https://user-images.githubusercontent.com/2105067/214452062-ac6cce76-9f2d-4d3f-acad-af78b5d5cef6.mp4
- 🎟️ [Add empty state to Integrations Library](https://app.asana.com/0/1203792610600085/1203810703916565)

Adds Empty State

---

src/views/product-integrations-landing/components/integrations-list/index.tsx

[🎟️ ARIA Label for Integration Card item](https://app.asana.com/0/1203792610600085/1203824021594914)
[🔍 Preview](https://dev-portal-git-braria-label-hashicorp.vercel.app/vault/integrations)

Adds an Aria label to the integrations card

---

src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/components/searchable-integrations-list/style.module.css

- [Asana task](https://app.asana.com/0/1202097197789424/1203752857375371/f) 🎟️
- Fixes the differing font sizes cross browser with appearance: none and an explicit font size setting

[searchable integrations list] Fix cross-browser font sizing

---

scripts/docs-content-link-rewrites/helpers/get-mdx-links-to-rewrite.ts

- Prevents files that live in the root of content directories from being rewritten
- These files are used for top-level pages in a content repo's website

[rewrite-links script] Preventing rewrites of files in root of content directory

---

scripts/docs-content-link-rewrites/rewrite-links.ts

- Formats the output of `scripts/docs-content-link-rewrites/rewrite-links.ts` so it's clearer what needs to be fixed, where, and how
- Just the file names is helpful for _us_ locally when we have all the context, but folks seeing this output for the first time need more information than that

[rewrite-links.ts] Updating output for clearer feedback

---

src/layouts/product-integration-layout/components/header/index.tsx
src/layouts/product-integration-layout/components/header/style.module.css

- [Preview link](https://dev-portal-git-ksfix-card-align-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami) 🔎
Fixes an issue where the version selector doesn't show and the alignment was off with the title and description. 
[Bug reported here](https://github.com/hashicorp/dev-portal/pull/1574/files#r1091254634)
- See this example for [no version selector](https://dev-portal-git-ksfix-card-align-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ecs)
- [See this example with the selector](https://dev-portal-git-ksfix-card-align-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami)

style: fix integration card without version selector

---

src/middleware.ts

Fixes an edge case in our middleware redirect handling where we were not properly assigning the hash segment of a URL. This caused the hash to be url encoded as part of the path, breaking the intended destination.
- Visit the preview, select boundary in the product switcher
- visit: `/help/admin-ui/targets/worker-filters`
- Validate the redirect worked and the URL contains a non-encoded `#`

fix(middleware): handle simple redirects with hash segment

---

package-lock.json
package.json
src/views/certifications/components/signup-form-area/components/newsletter-signup-form/index.tsx
src/views/certifications/components/signup-form-area/components/newsletter-signup-form/marketo-form-data.ts

Upgrades `@hashicorp/react-marketo-form` to the latest version.
The latest version of `@hashicorp/react-marketo-form` implements a breaking API change to support form localization, so I wanted to make the upgrade while the changes were still fresh in my mind.
Updated the static API data in `marketo-form-data.ts` to the new API shape.

chore(deps): bump react-marketo-form

---

src/components/try-hcp-callout/content.ts

Updates Consul and HCP CTAs so they can participate properly[ in the AB test.](https://github.com/hashicorp/dev-portal/pull/1590)

chore: update cta copy

---

.github/workflows/close-stale-prs.yml

- [Asana task](https://app.asana.com/0/1202097197789424/1203911094667990) 🎟️
This workflow will close stale issues and PRs after 20 days.

feat: Adds stale bot workflow

---

src/pages/api/revalidate.ts

Updates handling of the nav data fetch in our revalidate endpoint to be resilient if the nav data file does not exist. Boundary, for example, does not have any nav data for its `/api-docs/` route.
A 404 response looks like this, causing `result` to be undefined when we destructure:
```
{ meta: { status_code: 404, status_text: 'Not Found' } }
```

fix(revalidate): handle case where nav data does not exist

---

src/pages/_proxied-dot-io/nomad/downloads/index.jsx
src/pages/nomad/downloads/index.tsx
src/pages/nomad/downloads/style.module.css

update Nomad v1.5.0-beta.1 download box

---

package-lock.json
package.json

Fixes `TypeError: _jsxDEV is not a function` error when swingset renders. Updates swingset to `latest`, and as a result `next-mdx-remote` to latest, to fix the error.
The error was originally fixed in `next-mdx-remote@4.2.1` ([release notes](https://github.com/hashicorp/next-mdx-remote/releases/tag/v4.2.1))

fix: update swingset to latest to fix render error

---

src/content/certifications/exam-faqs/terraform-associate-003.mdx

Updated the go love and scheduling dates based on project adjustments-->
Our vendor is not able to make the original go live date. So everything needs to be adjusted.

Updated dates for TF003

---

src/data/terraform.json

The nav data file was recently renamed, and now that a release has happened we need to update the `navDataPrefix` to match the renamed file.
The file was renamed here: https://github.com/hashicorp/terraform-plugin-sdk/pull/1119

fix: updates navDataPrefix for terraform-plugin-sdk

---

src/flags/config.ts

Removes unused defaultFlags from config.

remove unused defaultFlag

---

next-env.d.ts
src/pages/api/revalidate.ts

The path currently being generated uses the provided `product`, which has the potential to be a repository name, such as `ptfe-releases`. This was causing non-existent paths to be constructed. I've updated the path to use `resolvedProduct`, which resolves to the actual product based on the repository.
Fixes invalid paths that are trying to be revalidated, such as:
```
[revalidate] /ptfe-releases/enterprise/releases/2022/v202205-1
```

fix(revalidate): use the resolvedProduct when constructing the path to revalidate

---

.github/workflows/ci.yml

Adds the `merge_group` event to our CI workflow triggers in preparation for using [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

chore: add merge_group to our CI workflow triggers

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-ks.add-alert-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1203838377880049/1203838391079380/f) 🎟️
Adds an alert banner for the IA research study.
We should follow up and fix this bug on mobile https://app.asana.com/0/1202097197789424/1203548570679724

chore: adds alert banner

---

src/pages/_proxied-dot-io/nomad/downloads/index.jsx
src/pages/nomad/downloads/index.tsx

update Nomad v1.5.0-rc.1 download box

---

.github/workflows/auto-merge-staging.yml

This updates our `auto-merge-staging` workflow to update `staging` by force pushing from `main`. This should be fine to do as there is no expectation that `staging` can diverge from `main. Any differences in our staging environment should be driven by configuration.

chore: update auto-merge-staging to force push from main

---

src/data/alert-banner.json

chore: remove alert banner

---

.copywrite.hcl

- [Asana task](https://app.asana.com/0/1199634971449915/1204013844377015) 🎟️
Adds a copywrite config file so we can ignore generated files. I followed these steps https://github.com/hashicorp/copywrite#config-structure

chore: adds copywrite config

---

src/pages/nomad/downloads/index.tsx

Removing nomad's pre-release CTA on their downloads page now that the stable release has shipped/is shipping.

chore: remove nomad's RC CTA

---

config/base.json
config/production.json
package-lock.json
package.json
src/components/navigation-header/index.tsx
src/components/theme-switch/index.tsx
src/layouts/base-new/index.tsx
src/layouts/base-new/types.ts
src/layouts/core-dev-dot-layout/index.tsx
src/layouts/core-dev-dot-layout/types.ts
src/pages/_app.tsx
src/pages/style.css
src/styles/themes/dark.css
src/styles/themes/types.ts
src/types/_app.ts
src/views/homepage/index.tsx

- [Preview link](https://dev-portal-git-ksscaffold-dark-mode-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204102236300016) 🎟️
This PR stands up the basic theming structure with next-themes, configuring the theme provider and which pages render theming (i.e. disable on home page). 
Also copies over the new dark mode palette from the playground and adds the feature flag config. 
- [visit the homepage](https://dev-portal-git-ksscaffold-dark-mode-hashicorp.vercel.app/), validate that the theme is always light despite switching
- [visit other subroutes](https://dev-portal-git-ksscaffold-dark-mode-hashicorp.vercel.app/consul) and view the themed state, use the theme switcher in the nav to toggle between states. 
- to test the config, pull this down locally …

feat: scaffold dark mode

---

src/data/alert-banner.json
src/data/boundary.json
src/data/consul.json
src/data/nomad.json
src/data/packer.json
src/data/sentinel.json
src/data/vagrant.json
src/data/vault.json
src/data/waypoint.json

- [Preview link](https://dev-portal-git-nqhc23-set-up-alert-banners-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1204167510013714/f) 🎟️
This PR updates all alert banners on developer.hashicorp.com to prepare for HashiConf 2023.
Requested by events team
Currently awaiting content finalization from the events team before merge.

chore: Prepare alert banners for HashiConf 2023

---

package-lock.json
package.json

- [Preview link](https://dev-portal-git-ksupgrade-consent-mgr-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204167618837026) 🎟️
Pulling in changes from https://github.com/hashicorp/react-components/pull/903
To ensure the text color in the consent manager remains consistent despite theme changes. 
- open an incognito window,[ visit the preview,](https://dev-portal-git-ksupgrade-consent-mgr-hashicorp.vercel.app/) select 'dark' theme and ensure the consent manager text matches the 'light' theme.

chore: update consent manager

---

src/content/nomad/install-landing.json

- [Preview link](https://dev-portal-git-tunzor-patch-1-hashicorp.vercel.app/nomad/downloads) 🔎
Thread with background for this change: https://hashicorp.slack.com/archives/C01KCU4HDPY/p1678821334060809
Replacing one of the slugs of a tutorial that is being deprecated.
Removing the tutorial and leaving this slug in place causes the install/downloads page to not render.

Replacing deprecated Nomad tutorial slug

---

src/styles/themes/dark.css

- [Asana task](https://app.asana.com/0/1199634971449915/1204167618837036) 🎟️
Refactoring the semantic tokens to reference the core palette tokens. 
It's been difficult to track the propagation of token value updates when we were using hex values across the board. This refactor allows us to more easily see how the core palette is being used within semantic tokens. And it also helps us weed out and prevent unintentional random hex tokens that are outside the core palette. 
- There should be no visible changes, this is a pure refactor. To fully validate, [visit the file](https://github.com/hashicorp/dev-portal/blob/42e7dddf70508f55dd731ad7cda44802ae988a68/src/styles/themes/dark.css) and ensure that the …

chore: refactor semantic tokens

---

src/styles/themes/dark.css

- [Preview link](https://dev-portal-git-ksupdate-purples-again-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204178586611253) 🎟️
Updates purple-200 token value. 
Validate that the hex[ matches the ticket. ](https://app.asana.com/0/0/1204178586611253/1204178586611260/f)

chore: update purple 200

---

config/base.json
config/development.json
config/preview.json
src/views/homepage/index.tsx

- [Preview link](https://dev-portal-git-ambadd-home-page-flag-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1201147515801429/1204132608541457/f) 🎟️
- Adds a new `enable_home_page_redesign` flag
- Conditionally renders content in `HomePageView` using the new flag
- This feature flag will make it easy to iteratively work on the newly redesigned home page without having to use a long lived feature branch

Add enable_home_page_redesign flag

---

src/components/feedback-form/components/question/question.module.css
src/styles/themes/dark.css

- [Preview link](https://dev-portal-git-ksupdate-form-tokens-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204108584803973) 🎟️
This PR tweaks the form token values as defined[ in this ticket](https://app.asana.com/0/1199634971449915/1204108584803973). The hex values have been mapped to their core palette tokens. 
- [Visit a tutorial page](https://dev-portal-git-ksupdate-form-tokens-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro), scroll down to view the feedback form. Validate that it looks okay. Also validate that the values are mapped properlty @braydenlove

chore: update form tokens

---

src/components/dev-dot-content/mdx-components/mdx-hcp-callout/index.tsx
src/components/dev-dot-content/mdx-components/mdx-hcp-callout/mdx-callout.module.css

- [Preview link](https://dev-portal-git-ksupdate-docs-hcp-callout-hashicorp.vercel.app/hcp/docs/vault) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204108582255305) 🎟️
- [Original Figma](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12855-169533&t=Xih45z5fKPwijHBs-0) 🎨 
This PR updates the Docs HCP callout component for dark mode. I also refactored some of the styles for how text color was handled for light mode, although there should be no visual changes for light mode. 
For dark theme, we are just overriding the background color and text color. 
[See design's comments here.](https://app.asana.com/0/0/1204108582255305/1204230239282927/f)
- Visit a few hcp docs overview pages, toggle between light and dark. Verify [that the light …

style: dark mode docs hcp callout

---

global.d.ts
src/components/command-bar/commands/search/components/integrations-tab-contents/index.tsx
src/types/products.ts
src/views/product-integration/component-view/server.ts
src/views/product-integration/readme-view/server.ts

This PR improves the type-hinting for our global `__config` object
https://user-images.githubusercontent.com/26389321/228659027-14f134ff-1206-4a32-8f95-491dbb08ddf7.mp4

chore: `__config` improved type hinting

---

src/views/homepage/components/chiclets/chiclets.module.css
src/views/homepage/components/chiclets/constants.ts
src/views/homepage/components/chiclets/index.tsx
src/views/homepage/components/chiclets/types.ts

- [Preview link](https://dev-portal-git-ambhome-page-chiclets-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1204295268139197/f) 🎟️
- Adds hover styles to each product chiclet
Since there's no explicit way to create a border with a linear gradient, we have to simulate one:
- Wrapped each chiclet's `<a>` element content in a `<div>`
- Added `1px` padding to the `<a>` element
- Set the background of each `<a>` to use `linear-gradient`
- Decreased the `padding` of the content `<div>` by `1px`
[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=21103-285360&t=C4ozVSnYBcdy6DrE-11)
- The `--hover-background` variable references hex colors rather than HDS tokens; I plan to connect with Kelly on this at the start of VQA along with other general …

[Home Page Redesign] Taking second pass at Chiclets styles

---

src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
src/components/mobile-menu-container/index.tsx

- [Preview link](https://dev-portal-git-ksfollow-up-mobile-nav-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1203652232454021/1204341255877531) 🎟️
The theme switcher shouldn't render on the home page. This was missed in https://github.com/hashicorp/dev-portal/pull/1808
- [Visit the preview](https://dev-portal-git-ksfollow-up-mobile-nav-hashicorp.vercel.app/)
- Scale to mobile viewport
- Validate that the theme switcher doesn't render in the mobile menu when authenticated and unauthenticated 
- Validate that it still renders on other routes.

chore: follow up mobile nav

---

src/views/docs-view/utils/get-deploy-preview-loader.ts

This fixes a RegExp that is missing `ptfe-releases`, and fixes markdown image previews during local preview in `ptfe-releases`
Example of broken images can be seen in this preview: https://ptfe-releases-git-docs-v202304-1-hashicorp.vercel.app/terraform/enterprise/vcs/gitlab-com#step-3-on-terraform-cloud-set-up-your-provider

fix: ptfe-releases local & deploy previews images

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-ksadds-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1204365457427592/f) 🎟️
Updates alert banner for the IA research.

chore: update banner

---

src/components/author-primitives/consul/config-entry-reference/index.jsx

- [Preview link](https://dev-portal-git-im2nguyen-update-consul-config-953733-hashicorp.vercel.app/consul/docs/connect/config-entries/service-router) 🔎
The custom Consul component uses the older version of the Tabs component. As a result, it doesn't render well with dark mode. This PR updates the custom component to use the standard Tabs component which works on both light/dark modes.
Old version:
New version:

Update custom Consul component to use standard tabs component

---

package-lock.json
package.json

- [Preview link](https://dev-portal-git-dsbump-code-block-hashicorp.vercel.app/terraform/cdktf/concepts/tokens) 🔎
- https://github.com/hashicorp/react-components/pull/942
Updates `@hashicorp/react-code-block` to remove dependency on `@reach/listbox` and replacing it with a native select element.
- Go to [preview URL](https://dev-portal-git-dsbump-code-block-hashicorp.vercel.app/terraform/cdktf/concepts/tokens)
- Activate your browser's responsive design mode, and select a device profile with a narrow viewport (such as the iPhone SE or anything with a viewport width less than 400px)
- Confirm that the code block on the bottom of the page correctly switches between languages.

chore(deps): bump react-code-block

---

src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/contexts/integrations-search-context.tsx

refactor(integrations-search-context)
- tiers are now an array
- use single pass through all integrations to gather unique fields

refactor(integrations-search-context)

---

analytics/spec/events/integration_library_filter_selected.yaml
src/components/multi-select/index.tsx
src/lib/integrations-api-client/integration.ts
src/views/product-integrations-landing/components/searchable-integrations-list/helpers/analytics.ts
src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
src/views/product-integrations-landing/contexts/integrations-search-context.tsx

This adds support for Integration **types**, including filtering

support `integration_type`

---

src/middleware.ts
src/views/tutorial-view/index.tsx
src/views/tutorial-view/server.ts
src/views/tutorial-view/types.ts

- [Preview link](https://dev-portal-git-ksvariants-middleware-rewrite-hashicorp.vercel.app/consul/tutorials/kubernetes/kubernetes-api-gateway?variants=config:hcp) 🔎
- [Asana task](https://app.asana.com/0/home/1199634971443477/1204343104798012) 🎟️
This PR stubs in the variant route support and middleware rewrites for the query param, `variants`.
❗ _Merging into an assembly_ 
See the [routing section of the RFC ](https://docs.google.com/document/d/1bDQCGDgjJouBAOfc8K5zkjeSjOFvg8gC7wXPeBasf8E/edit#heading=h.mi4ha5ru0ren)for full context
- Visit a tutorial with[ variants defined](https://dev-portal-git-ksvariants-middleware-rewrite-hashicorp.vercel.app/consul/tutorials/kubernetes/kubernetes-api-gateway?variants=config:hcp)
- Validate that the variant shows up in the pink box
- Validate that …

feat: stubs variant route support with rewrite 

---

package-lock.json

Aims to fix a few build errors
- https://vercel.com/hashicorp/vault/6hsecRsoKDiSN77NyhZKTiF4p8gH
- https://vercel.com/hashicorp/boundary/FU3kroPoK325SnJSor6rQEk9bYnt
- https://vercel.com/hashicorp/nomad/7MqKEm1wc6FCP3Luyu1fuHGahpCc
```console
npm i 
npm run start
warn  - Found lockfile missing swc dependencies, patching...
warn  - Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
```

fix: patch package lock

---

config/plugin.js
src/pages/onboarding/[...tutorialSlug]/index.tsx
src/pages/onboarding/[collectionSlug].tsx

This adds a static path limit (`__config.learn.max_static_paths`) to our `onboarding/*` pages
- `src/pages/onboarding/[collectionSlug].tsx`
- `src/pages/onboarding/[...tutorialSlug]/index.tsx`
Decrease build times and offload page building to ondemand generation.
---
- https://app.asana.com/0/0/1204565843516265

feat: limit /onboarding/* static path count

---

src/views/tutorial-view/utils/mdx-components.tsx
src/views/tutorial-view/utils/variants/mdx-variant.tsx

This PR creates the MDX component for authors to use. Below is an example of the authoring interface. 
We can't test this yet until we have the backend setup. See my attached screenshots for local testing.

feat: adds mdx component

---

.env

- [Asana task](https://app.asana.com/0/1203347061500817/1204565842346427) 🎟️
This updates our integrations-api URL.
We've added CloudFront in front of it as a light caching layer. As a result, we should see some slight buildtime speed improvements

feat: update integrations-api URL

---

src/components/dropdown-disclosure/components/list-item/index.tsx
src/components/dropdown-disclosure/components/list-item/types.ts
src/components/tutorial-meta/components/variant-list/desktop/index.tsx
src/views/tutorial-view/components/variant-dropdown-disclosure/index.tsx
src/views/tutorial-view/utils/variants/index.ts

- [Preview link](https://dev-portal-git-ksenable-variant-cookies-hashicorp.vercel.app/waypoint/tutorials/get-started-nomad-cloud/get-started-nomad-cloud) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204638008370801) 🎟️
Enabled cookies on the tutorial UI interactions to the `onClick` handler.
- Visit this preview
- Click one of the variant ui buttons
- Validate that the cookie is set in your browser
- Test the sidebar dropdown disclosure and mobile dropdown disclosure as well
Using the cookies to handle state management will occur in a follow up PR via rewrites.

feat: enable variant cookies

---

src/components/tutorial-meta/components/variant-list/desktop/index.tsx
src/views/tutorial-view/components/variant-dropdown-disclosure/index.tsx
src/views/tutorial-view/utils/variants/index.ts

- [Preview link](https://dev-portal-git-ksensure-display-order-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204333057896641/1204662062953638) 🎟️
Adds a sort to ensure the options are rendered by display order. 
Nothing should visually change, but the [rendered variant option order](https://dev-portal-git-ksensure-display-order-hashicorp.vercel.app/waypoint/tutorials/get-started-nomad-cloud/get-started-nomad-cloud) should match what's listed[ in this data file. ](https://github.com/hashicorp/tutorials/commit/b5aa954049bd3fabfc39f4b6a0e515d3ac0ee6ec)

chore: ensure display order

---

src/views/tutorials-landing/components/index.ts
src/views/tutorials-landing/components/page-hero/index.tsx
src/views/tutorials-landing/components/page-hero/page-hero.module.css
src/views/tutorials-landing/index.tsx
src/views/tutorials-landing/tutorials-landing.module.css

- [Preview link](https://dev-portal-git-tfd-ambpage-hero-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/0/1204660968035221/f) 🎟️
- Adds `PageHero` component under `src/views/tutorials-landing/components/`
[Figma link](https://www.figma.com/file/mmbCubXM9sOQqvGG0b8o0D/Tutorial_LP?type=design&node-id=221-18790&t=zidhDWZL6umha1KR-11)
- The way this component sits in the view will be worked on when all components are arranged.

[Tutorials Front Door] Adding PageHero subcomponent

---

package.json

Update `start:remote-watch` to also run `prestart`. This ensures that some generated files exist before the app is started.

run prestart before start:remote-watch

---

.env

feat: use `learn-api` CDN

---

src/components/tutorials-landing-view/collection-content-card-link/index.tsx
src/components/tutorials-landing-view/types.ts
src/pages/tutorials/index.tsx
src/views/tutorials-landing/components/cross-product-section/cross-product-section.module.css
src/views/tutorials-landing/components/cross-product-section/img/background-dark.svg
src/views/tutorials-landing/components/cross-product-section/img/background-light.svg
src/views/tutorials-landing/components/cross-product-section/index.tsx
src/views/tutorials-landing/components/index.ts
src/views/tutorials-landing/constants.tsx
src/views/tutorials-landing/index.tsx
src/views/tutorials-landing/tutorials-landing.module.css

- [Preview link](https://dev-portal-git-tfd-ambcross-product-section-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1204535818156240/1204660968035225) 🎟️
- Adds new `CrossProductSection` subcomponent to `TutorialsLandingView`
| light theme ([Figma link](https://www.figma.com/file/mmbCubXM9sOQqvGG0b8o0D/Tutorial_LP?type=design&node-id=240-20534&t=P7ccBpGAtbDkI5JI-11)) | dark theme ([Figma link](https://www.figma.com/file/mmbCubXM9sOQqvGG0b8o0D/Tutorial_LP?type=design&node-id=221-18790&t=P7ccBpGAtbDkI5JI-11)) |
|--------|--------|
| <img src="https://github.com/hashicorp/dev-portal/assets/43934258/c84a8451-8835-4730-badd-33dd024967e2" /> | <img src="https://github.com/hashicorp/dev-portal/assets/43934258/d91dd9f1-7fb4-495c-8722-8972287eb88f" /> |
- CSS spacing & …

[Tutorials Front Door] Add CrossProductSection

---

src/views/tutorials-landing/components/content-types-section/index.tsx
src/views/tutorials-landing/components/cross-product-section/index.tsx
src/views/tutorials-landing/index.tsx
src/views/tutorials-landing/tutorials-landing.module.css

- [Preview link](https://dev-portal-git-tfd-ambpage-layout-hashicorp.vercel.app/tutorials) 🔎
- [Asana task](https://app.asana.com/0/1204535818156240/1204687872642336) 🎟️
- Updates `TutorialsLandingView` to handle rendering `<section>` elements, rather than making the subcomponents aware of how they're placed in the view
- Updates the view's CSS to handle max-widths, spacing, alignment, etc. across sections
[Figma link](https://www.figma.com/file/mmbCubXM9sOQqvGG0b8o0D/Tutorial_LP?type=design&node-id=221-18790&t=Ve96JZtzY0cGCsUU-11)
- Page responsiveness is being handled in a separate polish task
- The geometric SVGs for each product section still need a little modification, and applying the opacity gradients is tedious, so I've moved that work to be part of polish as well

[Tutorials Front Door] Arrange page sections

---

src/content/tutorials-landing.json
src/pages/tutorials/index.tsx
src/views/tutorials-landing/constants.tsx

- [Preview link](https://dev-portal-git-tfd-ambauthorable-cross-product-115b82-hashicorp.vercel.app/tutorials) 🔎
- Restructures the `src/content/tutorials-landing.json` to have two properties:
- `crossProductSection`
- `productSections`
- Nests the previous content of `src/content/tutorials-landing.json` under the new `productSections` property
- Updates the data fetching layer (`getStaticProps`) to match the updated data structure
- Removes the `BETTER_TOGETHER_SECTION_COLLECTION_SLUGS`
This change comes after clarifying with EDU (via Slack) that these collection card links should be authorable. The title of the section remains non-authorable.

[Tutorials Front Door] Making CrossProductSection collections authorable

---

.github/workflows/repo-sync.yml

Add `repo-sync.yml` to support an internal fork of `dev-portal`.

Add repo-sync action

---

src/content/certifications/exam-faqs/consul-associate-002.mdx
src/content/certifications/exam-faqs/terraform-associate-003.mdx
src/content/certifications/exam-faqs/vault-associate-002.mdx
src/content/certifications/exam-faqs/vault-operations-professional.mdx
src/content/certifications/landing-faq.mdx

- [Preview link](https://dev-portal-git-cert-add-recertification-copy-hashicorp.vercel.app/) 🔎
Added copy describing the recertification process to the certification home page and the FAQ pages for each certification.
The Certifications team has been receiving questions about recertification since it's launch in March. This will help candidates self-serve.
Included copy that matches what is present on .com and in candidate emails.

Add recertification copy to cert pages

---

src/components/video-embed/index.tsx

Updates our `VideoEmbedPlaceholder` component to only attempt to load the placeholder image (via CSS) if it is defined.
Fixes an increase in 404s reported after some tutorial content updates were merged this morning ([ref](https://app.datadoghq.com/logs?query=%40proxy.statusCode%3A404&agg_q=%40proxy.referer&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice&index=%2A&messageDisplay=inline&sort_m=&sort_t=&stream_sort=desc&top_n=10&top_o=top&viz=toplist&x_missing=true&from_ts=1687356879698&to_ts=1687361424000&live=false)).

fix: only load video placeholder image if it is defined

---

src/pages/_app.tsx

Remove unused `data` prop, reducing dependency on `.layout` pattern.

_app layout: remove unused data prop

---

src/pages/nomad/downloads/index.tsx

- [Preview link](https://dev-portal-anqtnt5cl-hashicorp.vercel.app/nomad/downloads) 🔎 (about halfway down the page)
- [GitHub release checklist](https://github.com/hashicorp/nomad-releases/issues/250) 🎟️
Updates the marketing box for the Nomad 1.6.0-beta.1 release. This should go live no sooner than 9am PT on June 28.

update Nomad v1.6.0-beta.1 download box

---

config/base.json
config/development.json
config/preview.json
config/production.json

This PR enables unified search in production
Search for `well architected`
| - | - | 
| ![waf-before](https://github.com/hashicorp/dev-portal/assets/4624598/0c70e5f0-e8c3-43ba-942d-7349a97797af) | ![waf-after](https://github.com/hashicorp/dev-portal/assets/4624598/bab328b0-87c5-420a-9234-45aac970a693) |
Search for `docker ref`
| - | - | 
| ![docker-ref-before](https://github.com/hashicorp/dev-portal/assets/4624598/546cc6d6-86c1-4695-bed7-b43549695c58) | ![docker-ref-after](https://github.com/hashicorp/dev-portal/assets/4624598/4b4786a6-e754-4f83-bd78-8eb676f0bd12) |
- Visit the [preview]
- From the home page, open the search modal 
- Search should look and function as expected, and match [designs] …

feat: ship unified search all tab

---

src/components/tutorial-meta/components/badges/helpers.tsx
src/lib/learn-client/types.ts

- [Asana task](https://app.asana.com/0/1202097197789424/1203704507579626/f) 🎟️
Cleanup work from TFC pricing project.

chore: remove legacy edition options

---

build-libs/redirects.js

This aims to clean up build logs as seen in https://vercel.com/hashicorp/dev-portal/uKeA5RQ1shNVGkSf83A6cSRaRyhA#L40

chore: terraform-docs-common redirects

---

src/middleware.ts

check UA in middleware

---

package-lock.json
package.json
src/components/dev-dot-content/mdx-components/mdx-headings/utils/is-injected-permalink.ts

Reverts hashicorp/dev-portal#2052

Revert "chore: bump next version"

---

src/components/head-metadata/index.tsx

- [Asana task](https://app.asana.com/0/1202801212949828/1204606269616351/f) 🎟️
Note - Waypoint & Vagrant are in reverse order on the ticket vs code.

chore: update zendesk crawlers to production values

---

src/views/product-integration/component-view/components/variable-group-list/style.module.css

- [Preview link](https://dev-portal-git-ksfix-icon-color-variable-groups-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204845103172089/1203988523494876/f) 🎟️
Updates arrow icon to correct color. 
- Navigate[ to this page](https://dev-portal-git-ksfix-icon-color-variable-groups-hashicorp.vercel.app/waypoint/integrations/hashicorp/azure-container-instance/latest/components/platform/azure-container-instance-platform)
- Validate that the child arrow icon is `foreground-faint`

style: fix arrow color

---

package-lock.json
package.json
src/lib/learn-client/api/utils/index.ts

chore: remove packages: `nuka-carousel`, `validator`

---

src/views/product-integration/component-view/components/variable-group-list/index.tsx
src/views/product-integration/component-view/components/variable-group-list/style.module.css

- [Preview link](https://dev-portal-git-ksadd-hr-variable-group-parent-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204845103172089/1203988523494872/f) 🎟️
- [Figma](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?type=design&node-id=17898-231390&mode=design&t=bvfm6gByfTR4MFZ8-0) 🎨 
This PR adds an hr before nested variable group items to promote visual hierarchy. 
- [Visit a page](https://dev-portal-git-ksadd-hr-variable-group-parent-hashicorp.vercel.app/waypoint/integrations/hashicorp/azure-container-instance/latest/components/platform/azure-container-instance-platform) with nested variable group list
- Validate that the hr only renders in nested variable group lists and that it matches the design spec

[integrations] adds nested divider variable group list

---

src/views/tutorial-library/constants.ts

Adjusts reference to 'open source' filter to 'community.'
This PR just updates the label. Further work will be done to adjust the route params and edition config in the content. That will need to be coordinated with API changes. 
**To test**: visit the [preview](https://dev-portal-git-ksupdate-tutorial-filter-hashicorp.vercel.app/tutorials/library), validate the the 'community' input exists and that the results function as expected.

Update tutorials library edition filter

---

src/components/dev-dot-content/mdx-components/mdx-hcp-callout/index.tsx
src/components/tutorials-landing-view/docs.mdx
src/content/boundary/product-landing.json
src/content/certifications/exam-faqs/terraform-associate-002.mdx
src/content/certifications/exam-faqs/vault-operations-professional.mdx
src/content/certifications/programs/infrastructure-automation.json
src/content/certifications/programs/networking-automation.json
src/content/certifications/programs/security-automation.json
src/content/packer/product-landing.json
src/data/boundary.json
src/data/packer.json
src/data/waypoint.json

- chore: update product metadata
- chore: update product nomenclature
Updates some nomenclature around products.
See https://www.hashicorp.com/license-faq for more detail.

chore: update product references

---

next-auth.d.ts
src/pages/api/auth/[...nextauth].ts

This is in support of https://github.com/hashicorp/dev-portal/pull/2128

chore(auth): return `user.id`

---

src/content/hcp/tutorials-sidebar.json

https://developer.hashicorp.com/hcp/tutorials
- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/hcp/tutorials) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-422?atlOrigin=eyJpIjoiZmM3ZDU2ZjZjOWU3NGQ5Njg2Y2Y2ZDRjNzc1OGZkMTkiLCJwIjoiaiJ9) 🎟️
- Remove beta tag from HCP Boundary tutorial navigation
- HCP Boundary is no longer in beta

Remove HCP Boundary beta tag from tutorial nav

---

.github/workflows/register-preview-url.yml
scripts/add-preview-url-to-cloud-idp.ts

https://app.asana.com/0/1202097197789424/1205523634432684/f
Debug https://github.com/hashicorp/dev-portal/actions/workflows/register-preview-url.yml

debug: auth workflow

---

.github/workflows/register-preview-url.yml
scripts/add-preview-url-to-cloud-idp.ts

Add friendly error message to `add-preview-url-to-cloud-idp.ts` workflow

chore(add-preview-url-to-cloud-idp.ts) friendly error

---

src/components/chatbox/Markdown.tsx
src/components/chatbox/message.tsx

This PR lazliy-loads a `Markdown` component that contains the imports for `ReactMarkdown`, `remarkGfm`, and `rehypePrism`.
Without lazy loading, the three imports mentioned above add >200KB of JavaScript to every page on Dev Portal.
The `Markdown` component renders `ReactMarkdown`, and is imported into the `AssistantMessage` component via `React.lazy`.

feat: lazy-load react-markdown

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-nq-update-homepage-alert-banner-hashicorp.vercel.app/) 🔎
This PR updates the alert banner on developer.hashicorp.com to bring attention to HashiConf registration.
Request from Events

feat(alert banner): Update for HashiConf promo

---

src/components/chatbox/chatbox.module.css
src/components/chatbox/chatbox.tsx
src/components/chatbox/message.tsx
src/components/command-bar/commands/chat/chat.module.css
src/components/command-bar/commands/chat/index.tsx
src/components/command-bar/components/dialog/header.tsx

- [Base PR](https://github.com/hashicorp/dev-portal/pull/2191)
This PR makes some slight adjustments to use our global utility class for visually hidden elements in addition to tweaking how we style SVG elements within the Command Bar header to support `currentColor` without needing to use inline styles.

cleanup: use global sr-only util class

---

src/content/tutorials-landing.json
src/views/tutorials-landing/constants.tsx

Removes Waypoint section from[ tutorials landing](https://dev-portal-git-ksupdate-waypoint-tutorials-hashicorp.vercel.app/tutorials) temporarily.

Remove waypoint from tutorials landing

---

src/content/tutorials-landing.json
src/views/tutorials-landing/constants.tsx

- [Preview link](https://dev-portal-git-judith-tutorials-home-waypoint-update-hashicorp.vercel.app/tutorials) 🔎
- [Asana Task](https://app.asana.com/0/1205381807623014/1205682611512138) 🎟️
We took Waypoint off the tutorials landing page to reduce errors when making content changes. This PR adds it back and updates the highlighted tutorials and collections.

Re-add waypoint to tutorials landing with updated content for HCP

---

src/components/chatbox/chatbox.tsx
src/components/chatbox/welcome-message.module.css
src/components/chatbox/welcome-message.tsx

- [Preview link](https://dev-portal-git-ksupdate-welcome-message-width-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204687249651885/1205761264547858/f) 🎟️
Updates the CSS for the welcome message to align with [the spec](https://www.figma.com/file/0Op0f8SEDLB8HuOHzfXAwP/Chat_GPT?type=design&node-id=1332-9315&mode=design&t=FT40Pj6cAr6MOT1X-0).

style: update welcome message width

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-heat-gpt-integrationalert-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204687249651885/1205654693141436) 🎟️
- Adding an alert banner for the beta Developer AI sign up
- We launched Developer AI private beta 🥳 
- Screenshot in [Asana task](https://app.asana.com/0/1204687249651885/1205654693141436)

Developer AI Private Beta Launch - alert banner

---

README.md

We now pull a `GITHUB_TOKEN` from vercel so the PAT is no longer needed.

remove PAT note from readme

---

jest.config.ts
src/views/open-api-docs-view/utils/__fixtures__/petstore3.openapi.ts
src/views/open-api-docs-view/utils/__tests__/__snapshots__/get-request-data.test.ts.snap
src/views/open-api-docs-view/utils/__tests__/__snapshots__/get-response-data.test.ts.snap
src/views/open-api-docs-view/utils/__tests__/get-request-data.test.ts
src/views/open-api-docs-view/utils/__tests__/get-response-data.test.ts
src/views/open-api-docs-view/utils/get-request-data.ts
src/views/open-api-docs-view/utils/get-response-data.ts
src/views/product-tutorials-view/server.ts

This PR adds Jest snapshot tests to the `get-request-data` and `get-response-data` utilities to ensure future compatibility with OpenAPI v3 spec files. It also adds a dereferenced version of the Pet Store sample spec. It also includes a tiny refactor to use `Object.entires` in lieu of iterating keys and accessing values with said keys (which just makes it a bit tidier).

tests: add tests and fixtures for openapi v3 compat

---

src/components/version-context-switcher/index.tsx
src/components/version-context-switcher/version-context-switcher.module.css
src/views/product-downloads-view/components/downloads-section/downloads-section.module.css
src/views/product-downloads-view/components/downloads-section/index.tsx
src/views/product-downloads-view/components/downloads-section/types.ts
src/views/product-downloads-view/components/page-header/index.tsx
src/views/product-downloads-view/components/page-header/page-header.module.css
src/views/product-downloads-view/helpers.ts
src/views/product-downloads-view/index.tsx

- [Asana task](https://app.asana.com/0/1204817897905865/1205712837415354/f) 🎟️
- [Figma](https://figmashort.link/GJTJF3)
- Removed some dead code related to latest version as this is handled [here](https://github.com/hashicorp/dev-portal/blob/main/src/views/product-downloads-view/helpers.ts#L189-L204)
- Removed header subtitle:
- Moved `<VersionContextSwitcher />` to `PageHeader`
For consistency, We'd like to update to the new component (version toggle/dropdown) used in our [documents](https://dev-portal-git-ksupdate-welcome-message-width-hashicorp.vercel.app/consul/docs) template and move it's placement to the page header.
- Navigate to [Vault install page](https://dev-portal-git-heat-featversion-select-update-hashicorp.vercel.app/vault/downloads)

Install page enhacement: version dropdown moved to PageHeader

---

config/hvd-preview.json

This PR adds a custom config file for the hvd preview so that the hvd repo config doesn't statically build a bunch of content paths that aren't relevant for authors there. And we can enable the hvd flag for that repo and not the tutorials / docs repos.

Adds hvd-preview config

---

src/views/product-downloads-view/components/page-header/index.tsx
src/views/product-downloads-view/components/page-header/page-header.module.css

- [Asana task](https://app.asana.com/0/1204817897905865/1205911880806855/f) 🎟️
- Changed font-size to match [mocks](https://figmashort.link/dK5BTk)
- Removed a bit of unused css I missed in the PR to move the version dropdown to PageHeader on the install page
- Part of the install page enhancement
- Navigate to [https://developer.hashicorp.com/vault/install](https://developer.hashicorp.com/vault/install) and inspect the "Install Vault" h1. See the font-size is 36px and the line-height is 44px.
- Navigate to preview page [vault install page](https://dev-portal-git-heat-choreinstall-heading-hashicorp.vercel.app/vault/install) and inspect the "Install Vault" h1. See the font-size is 30px and the line-height is 36px.

Install Page: Heading change - removed dead css and changed heading size

---

src/content/consul/product-landing.json

This PR replaces one of the tutorials on the Consul landing page to reference a tutorial that is not going to be renamed in a future Tutorials PR.

Tempoarily add placeholder for CTS tutorial while we rename it

---

src/components/version-context-switcher/index.tsx
src/content/consul/install-landing.json
src/content/consul/product-landing.json

This depends on https://github.com/hashicorp/tutorials/pull/1713 before we can merge it

Update landing page CTS link to new CTS tutorial

---

scripts/content-repo-preview/builders/developer.ts

Refactoring to use the repo env and not the config data.

fix: use env not config

---

src/pages/vagrant/install/index.tsx
src/pages/vagrant/install/vagrant-downloads.module.css

- [Figma](https://figmashort.link/EXZf2a) 🔎
- [Asana task](https://app.asana.com/0/1204817897905865/1206006432806321/f) 🎟️
- Update Vagrant Merchandising slot component.
- Install page enhancement
- Go to Vagrant install [page](https://developer.hashicorp.com/vagrant/install) and scroll down to the VMware Utility card. It should match the "Before" screenshot above.
- Go to the Vagrant install preview [page](https://dev-portal-git-heat-chorevmware-card-update-hashicorp.vercel.app/vagrant/install) and scroll down to the VMware Utility card. It should match the "After" screenshot above.

Vagrant VMware utility

---

src/pages/consul/install/consul-downloads.module.css
src/pages/consul/install/index.tsx

- [Preview link](https://dev-portal-git-heat-choreconsul-tools-hashicorp.vercel.app/consul/install) 🔎
- [Asana task](https://app.asana.com/0/1204817897905865/1205996862927676/f) 🎟️
- [Figma](https://figmashort.link/pC3k5r)
- Replace Consul tools `<CardLink />` component with card with a link component 
- Install page enhancement
- Go to [Consul install prod](https://developer.hashicorp.com/consul/install) and scroll down to the bottom of the `Release information` section to see the current implementation of the Consul tool card
- Go to [Consul install](https://dev-portal-git-heat-choreconsul-tools-hashicorp.vercel.app/consul/install) and scroll down to the bottom of the `Release information` section to see the updated Consul tools

Install page: Consul tools UI update

---

.github/CODEOWNERS

This PR removes the `dev-portal` codeowner blocks since we're deprecating the `dev-portal` team in favor of `@hashicorp/web-presence`. We're going to try out not automatically assigning an individual to each PR when it's opened. If that causes issues we'll restore what was removed in this PR and automatically assign `@hashicorp/web-presence`.

feat: remove dev-portal codeowners

---

src/pages/validated-designs/[...slug]/index.tsx
src/views/validated-designs/guide/index.tsx
src/views/validated-designs/index.tsx
src/views/validated-designs/server.ts
src/views/validated-designs/types.ts

- [Preview link](https://dev-portal-git-rnhvd-guide-fetching-hashicorp.vercel.app/validated-designs) 🔎
- [Figma Designs](https://www.figma.com/file/s5mltxHQiTZ45PuqQ6b6JO/HVD-Phase-1?type=design&node-id=13-1210&mode=design&t=44oVeXpR7LdLnRer-0) 🎨 
Asana tickets
- [Scaffold guide template data fetching](https://app.asana.com/0/1204908934882872/1205942535702199/f) 🎟️
- [[guide template] set up sidebar sidecar layout](https://app.asana.com/0/1204908934882872/1205942535705364/f) 🎟️
- [[guide template] set up mdx content & page heading](https://app.asana.com/0/1204908934882872/1205942535705366/f) 🎟️
Scaffold out the the Main and Detail view of HVD and have the Detail view load the actual content

HVD: Load preview of content in the Guide Detail View

---

src/content/hcp/tutorials-sidebar.json

- [Preview link](https://dev-portal-git-hcpv-remove-cloud-monitoring-hashicorp.vercel.app/hcp/tutorials) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-508?atlOrigin=eyJpIjoiYjc5ODJiMTI4ODNlNGJjMThmMjUyYmE2MTgxMzEwMzUiLCJwIjoiaiJ9) 🎟️
- Removes monitoring from HCP Vault tutorials nav
- Tutorials were migrated to usage docs in the hcp-docs repository

Remove monitoring from HCP Vault navigation

---

scripts/warm-cache.ts

This PR removes the .io cache warming portion of the `cache.yml` workflow.
The `cache.yml` workflow previously warmed URLs from the .io sites as reported by Fathom. Since those products are no longer served from Dev Portal, it makes sense to remove that from the workflow, especially in light of Fathom's recent API limit imposition.
Removed the relevant code.

cleanup: remove .io cache warming

---

package-lock.json
package.json

- [Preview link](https://dev-portal-git-rn-featfix-ai-copy-code-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1205761144977632/f) 🎟️
Because we were using an older copy to clipboard AI it was causing the "copy code" button for developer AI to not work. [That component was fixed in the following PR](https://github.com/hashicorp/react-components/pull/1006), this PR just pulls those changes in.
Requirements: Make sure you are logged in and have access to developer AI, if you do not ask Emily or Tony for access.

Fix developer ai copy code button

---

src/content/hcp/docs-landing.json

Do not merge until HCP Vault Radar docs assembly branch has been merged (or link from landing page will be broken) --> https://github.com/hashicorp/hcp-docs/pull/785
- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/hcp/docs) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-469?atlOrigin=eyJpIjoiZjlhNDk3OGE4NmRjNGJmMmJjODkyZTAzOTc3Zjk0NzEiLCJwIjoiaiJ9) 🎟️
Adds HCP Vault Radar card to HCP docs landing page
HCP Vault Radar beta

Add HCP Vault Radar card to HCP docs landing page

---

src/content/hcp/product-landing.json

- [Preview link](https://dev-portal-git-hcp-wp-link-fix-hashicorp.vercel.app/hcp) 🔎
This updates the get started link for HCP Waypoint on the main HCP product page as the current link points to a deprecated tutorial.

HCP Waypoint Get Started link fix

---

src/pages/hcp/api-docs/packer/[[...page]].tsx

Update HCP Packer API design

---

src/middleware.ts

This PR uses middleware to return a 429 response for requests to `/terraform/cdktf` from `curl`.
```
➜  dev-portal git:(ds.middleware-curl-429) curl 'https://dev-portal-git-dsmiddleware-curl-429-hashicorp.vercel.app/terraform/cdktf'
{"error":"Please reach out to support@hashicorp.com so we can learn more about your use case."}
```
This is because there is someone sending a request to this page every two seconds.
We check the User-Agent header and pathname, and return a 429 response if it's for `/terraform/cdktf` from a UA containing `curl`.

feat: block curl requests to cdktf

---

.vscode/settings.json
src/content/sentinel/product-landing.json

- [Preview link](https://dev-portal-git-pbsentinel-update-graphics-hashicorp.vercel.app/sentinel) 🔎
- [Asana task](https://app.asana.com/0/1204759533834554/1206097144137369/f) 🎟️
Add the finished graphics for the **What is Sentinel?** section in light & dark mode.
Post launch fast follows
Ran images through imageOptim and uploaded them to Dato. Used those links in `product-landing.json`.

update: add sentinel product diagram assets

---

.github/workflows/auto-merge-staging.yml
.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/close-stale-prs.yml
.github/workflows/docker_publish.yml
.github/workflows/docs-content-check-legacy-links-format.yml
.github/workflows/nextjs_bundle_analysis.yml
.github/workflows/playwright.yml
.github/workflows/register-preview-url.yml
.github/workflows/repo-sync.yml
package.json

This reverts commit 5e860e7191b65ba9aa5bbdfd7bfed46ffde729a8.
- causing build errors in product repo website dirs

Revert "[chore] Update GitHub Actions to use Node 20 (#2335)"

---

src/content/hcp/product-landing.json
src/content/hcp/tutorials-sidebar.json

- [Preview link](https://dev-portal-git-radar-add-radar-tutorials-hashicorp.vercel.app/hcp) 🔎
Add Radar tutorials (https://developer.hashicorp.com/vault/tutorials/radar-foundations) to HCP landing page and tutorial nav bar
So people can find Radar tutorials 😄 
Update product-landing and tutorials-sidebar json files

Add radar tutorials

---

build-libs/redirects.js

- [Preview link](https://dev-portal-git-heat-choreredirect-waypoint-docs-hashicorp.vercel.app/waypoint) 🔎
- [Asana task](https://app.asana.com/0/0/1206697393359298/f) 🎟️
Added a top-level redirect for `/waypoint/docs/<path>`
Part of the Waypoint IA restructing
The redirect is a top-level where any `/waypoint/docs/<path>` will redirect to https://github.com/hashicorp/waypoint/tree/main/website/content/docs. Another approach was redirecting each doc, but that was deemed too much effort for a deprecated product.
- Visit the [Waypoint docs page](https://dev-portal-git-heat-choreredirect-waypoint-docs-hashicorp.vercel.app/waypoint/docs). You should not be redirected to the [Waypoint docs directory](https://github.com/hashicorp/waypoint/tree/main/website/content/docs)
- Visit a [Waypoint docs …

Redirect for Waypoint docs

---

src/data/alert-banner.json
src/data/boundary.json
src/data/consul.json
src/data/nomad.json
src/data/packer.json
src/data/terraform.json
src/data/vagrant.json
src/data/vault.json
src/data/waypoint.json

- [Preview link](https://dev-portal-git-nels-update-alert-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202802428287999/1206847023107242/f) 🎟️
This PR updates the alertBanner across Dev Portal with HashiDays content.

Update AlertBanner with HashiDays content

---

src/layouts/sidebar-sidecar/utils/prepare-nav-data-for-client.ts
src/lib/learn-client/index.ts
src/lib/remark-plugins/rewrite-tutorial-links/__tests__/rewrite-tutorial-links.test.ts
src/lib/remark-plugins/rewrite-tutorial-links/index.ts
src/lib/remark-plugins/rewrite-tutorial-links/utils/get-tutorial-map.ts
src/pages/api/tutorials-map.ts
src/views/docs-view/server.ts

Reverts hashicorp/dev-portal#2399

Revert "fix: only fetch tutorials map once"

---

src/content/certifications/exam-faqs/consul-associate-003.mdx
src/content/certifications/programs/networking-automation.json

- [Preview link](https://dev-portal-git-cert-update-consul-cert-page-hashicorp.vercel.app/certifications/networking-automation) 🔎

Consul Associate 003 developer page

---

src/pages/style.css

- [Asana task](https://app.asana.com/0/0/1207005043286303/f) 🎟️
- Remove klavika font as it isn't used anywhere
- code clean up
- no testing as this is unused code

[chore] Remove unused klavika font

---

src/data/alert-banner.json

update alert banner

---

src/components/command-bar/commands/search/helpers/generate-suggested-pages.tsx
src/components/try-hcp-callout/content.ts
src/content/consul/install-landing.json
src/content/consul/product-landing.json
src/content/hcp/docs-landing.json
src/content/hcp/tutorials-sidebar.json

- [Preview link](https://dev-portal-git-heat-choreconsul-hashicorp.vercel.app/)
- [Asana task](https://app.asana.com/0/1206186907615643/1207140311357481/f)
Syncing changes from dev portal internal for rebrand. HCP Consul product name update was delayed to May 1st 2024
Update HCP Consul to HCP Consul Dedicated
03d6ea26219e454e5117a79e205caff3066f6fe3
Update HCP Consul to HCP Consul Dedicated in product landing page json
20f29c245fc257f7ad9502b2df2d88833e10735f
Update HCP Consul to HCP Consul dedicated - HCP callout card
995b09d2522087cf78c134e54a9ad98ac7a2314a
HCP Consul to HCP Consul Dedicated
3541d2e64e341f2f961489da3498918cf477f780
HCP Consul to HCP Consul Dedicated - HCP landing page
1d2793dd62acdcad8f14af377ac5d2be9c81b67e
Update HCP tutorials sidebar - Consul …

Update HCP Consul to HCP Consul Dedicated

---

.vscode/settings.json
src/components/navigation-header/components/product-page-content/utils/__tests__/get-nav-items.test.ts
src/data/terraform.json

Renaming "Terraform Cloud Agents" to "HCP Terraform"

HCP TF docs agents

---

src/content/certifications/exam-faqs/consul-associate-003.mdx
src/content/certifications/programs/networking-automation.json

- [Preview link](https://dev-portal-git-cert-consul002-remove-hashicorp.vercel.app/certifications) 🔎
Retiring Consul Associate 002 from the Certification pages on developer. This goes with https://github.com/hashicorp/tutorials/pull/2071 on the tutorials repo.
View the deploy preview and click all the links.

Remove consul 002 retired exam from cert pages

---

src/lib/rehype-code-plugins.ts

This PR fixes an issue where we incorrectly determined that `sentinel` was an unknown language, falling back to `text`. It also fixes an issue where `text` was reported to be an unknown language.

fix: sentinel is a known language

---

src/components/chatbox/Markdown.tsx

- Preview link - None Login doesn't work in preview branches 🔎
- Asana task - None bug 🎟️
Syntax highlighting was breaking developer AI, due to react-markdown not working with async transformers.

Disable syntax highlighting in DAI

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-heat-choreupdate-banner-hashicorp.vercel.app)
- [Asana task](https://app.asana.com/0/0/1207373785420586/f)
- Revert banner to HashiDays from IBM acquisition blog post
- Visit preview link
- The banner should now be for HashiDays

Update site banner to HashiDays

---

src/views/validated-designs/guide/index.tsx

- [Preview link](https://dev-portal-git-leah-fixremove-extra-slash-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1207472975295931/f) 🎟️
This PR removes an extra slash in the url to download the PDF guide for validated designs.
There was an error in the console because there were two slashes in the middle of the url instead of one
1. Go to [dev-portal](https://developer.hashicorp.com/validated-designs/consul-operating-guides-adoption)
2. Open console
3. See that there is an error for having a double slash in the url
4. Go to [preview link](https://dev-portal-git-leah-fixremove-extra-slash-hashicorp.vercel.app/validated-designs/consul-operating-guides-adoption)
5. Open console
6. The error is no longer there
7. Click download as pdf link in the side bar …

fix: remove extra slash in url

---

src/content/certifications/programs/security-automation.json

- [Preview link](https://dev-portal-git-Nit_certs-hashicorp.vercel.app/certifications/security-automation) 🔎
I noticed a typo in the Vault Ops Pro copy, so this PR fixes that plus two other small nits
Please review the copy to ensure there are no typos.

Vault Professional certification typo fixes

---

src/pages/api/revalidate.ts

- Preview link  - None chore dev task  🔎
- Asana task - None chore dev task 🎟️
This PR is a continuable of work in #2490. It now groups together results by their status and will return any thrown errors.
1. checkout this branch locally and start up the project
2. hit the revalidate api 
(Make sure you have jq installed)
```
curl -X POST "http://localhost:3000/api/revalidate" \
-H "Content-Type: application/json" \
-d '{"product": "packer"}' | jq .
```
3. json of either successfully or failed to revalidated paths should be returned

Group validate api results

---

src/content/certifications/exam-faqs/terraform-authoring-operations-professional.mdx
src/content/certifications/programs/infrastructure-automation.json

- [Preview link](https://dev-portal-git-Nit_certs-hashicorp.vercel.app/certifications/infrastructure-automation) 🔎
* Added clarifying language about scope of exam, ideal candidate, and AWS experience

TF Pro language updates on Developer

---

src/views/homepage/index.tsx

- remove error that was used to test sourcemaps RUM

bug fix: Remove error for testing sourcemaps

---

src/lib/products.ts
src/types/products.ts

- [Asana task](https://app.asana.com/0/1206815131022336/1207832908083300/f) 🎟️
This PR creates the new product nav data structure and fills in the correct information. When the new nav-panel package is ready to be imported, this data will be used to pass into the component.
Currently our product dropdown only supports name and icon. Since the new designs feature more information, the data structure had to be updated to support it.
Since this is not being used anywhere yet, it can not be tested. The nav data will be used once [this Asana task](https://app.asana.com/0/1206815131022336/1207832908083297/f) is ready to start.

feat: create new product nav data structure

---

src/components/image/index.test.tsx
src/components/image/index.tsx

- [Support request](https://hashicorp.slack.com/archives/C5FSPUGDS/p1723843460759869)
Some image srcs were encoded (`#` -> `%23`) and were not getting properly parsed. This PR decodes the src before the regex.
If the unit tests pass, I believe we should be confident that this will work.

fix(image theme): decode uri

---

package-lock.json
package.json

- [Preview link](https://dev-portal-git-leah-fixcode-block-covered-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1206176289707208/1208055032817317/f) 🎟️
This PR pulls in the latest changes to the code block from `@hashicorp/react-design-system-components`. The changes include adding some extra padding to the end of the code lines so the copy button does not cover the text at the end of the line. More information on those changes can be found in [this PR](https://github.com/hashicorp/web/pull/1853)
There was an issue with the overlap in the support channel, more info in [the slack thread](https://hashicorp.slack.com/archives/C5FSPUGDS/p1723746126645709)
Before
After
1. Go to [preview](https://dev-portal-git-leah-fixcode-block-covered-hashicorp.vercel.app/terraform/enterpri …

fix: code block copy button covers end of text string

---

src/content/certifications/exam-faqs/terraform-authoring-operations-professional.mdx
src/content/certifications/exam-faqs/vault-operations-professional.mdx
src/content/certifications/landing-faq.mdx
src/content/certifications/programs/infrastructure-automation.json

- [Preview link](https://dev-portal-git-TF_Pro_reg-hashicorp.vercel.app/certifications) 🔎
- [Asana task](https://app.asana.com/0/1204533745817604/1206173952679506/f) 🎟️
- Added link to register for new exam
- Reduced word count on both Pro pages
- Fixed some old URLs
- Removed refs to deprecated resources
- Made embedded link language more accessible
Exam is live on Sept 1!

Terraform Pro launch and registration

---

src/components/sidebar/helpers/get-filtered-nav-items.ts
src/components/sidebar/types.ts

- [Preview link](https://dev-portal-git-docs-sidebar-alias-hashicorp.vercel.app/?vercelToolbarCode=EBBgVNHMkCUIng-) 🔎
- [Asana task](https://app.asana.com/0/1202520168081556/1202841933621138/f) 🎟️
Right now we only filter on the word in the sidebar explicitly. This feature would be to add hidden aliases to these sidebar items. As an example, adding alias "bar" to sidebar item "foo", so that when a user filtered on the text "bar", "foo" would be shown in the results. 
The issue for the site and the reason this is being considered is because we have "use case" items in the side bar and we have products that focus on these use cases. So a user filtering on a product (or subproduct/feature) could be shown use cases as results. 
Add an optional `alias` attribute to the docs nav JSON file. …

Add alias for docs sidebar filtering

---

src/content/hcp/docs-landing.json
src/content/supported-icons.tsx

- [Preview link](https://dev-portal-git-add-vagrant-hcp-docs-landing-hashicorp.vercel.app/hcp/docs) 🔎

Add HCP Vagrant to the HCP docs landing page

---

src/content/hcp/tutorials-sidebar.json

Remove beta tag from hcp waypoint

---

.github/workflows/playwright.yml
package-lock.json
package.json

- [Original support request](https://hashicorp.slack.com/archives/C5FSPUGDS/p1728596838750039) 🛟 
- [Asana task](https://app.asana.com/0/home/1207213190767773/1208530332703320) 🎟️
The PR version bumps the version of playwright being used in order to get more up to date (third party dependencies) so that playwright is able to install correctly on the `ubuntu-latest` runner
The ["Install Playwright" step](https://github.com/hashicorp/dev-portal/actions/runs/11279297877/job/31381965845?pr=2574) of the "E2E Tests" workflow was failing (as-of approx 2 weeks ago). This is due to the version of playwright requiring dependencies that were present in Ubuntu `jammy`, but not Ubuntu `noble`.
```
Package libicu70 is not available, but is referred to by another package.
This may mean that the package …
```

Version bump playwright and NPM

---

src/pages/hcp/api-docs/identity/[[...page]].tsx

- [Preview link](https://dev-portal-git-leah-hcp-identity-docs-hashicorp.vercel.app/hcp/api-docs/identity) 🔎
- [Asana task](https://app.asana.com/0/1207947026228781/1208478194212317/f) 🎟️
Adds new api docs for `/hcp/api-docs/identity` based on the [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-iam/stable/2019-12-10/hcp.swagger.json)
1. Go to [preview link](https://dev-portal-git-leah-hcp-identity-docs-hashicorp.vercel.app/hcp/api-docs/identity)
2. Verify that docs match the [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-iam/stable/2019-12-10/hcp.swagger.json)

feat: add new api docs for hcp identity

---

src/content/tutorials-landing.json
src/content/vault/install-landing.json

- [Jira task](https://hashicorp.atlassian.net/browse/SPE-1000) 🎟️
- Update links on Vault install page to new get started intro, and new UI tutorial
- In support of deprecating old UI tutorial collection

Remove UI colleciton from install page

---

src/lib/unified-docs-migration-utils.ts

- Remove console.log 
- To remove it from the build logs (see screenshot)

chore: Remove console log

---

src/content/vault/install-landing.json

Remove HCP tutorial link from Vault install page
Renaming for SEO efforts, will add back in after site map update

Remove link to HCP tutorial

---

src/content/vault/product-landing.json

- [Preview link](https://dev-portal-git-update-vault-home-hashicorp.vercel.app/vault) 🔎
This PR replaces the 'ADP' card with 'Data encryption' card under **Use Cases**.
We have deprecated the 'ADP' tutorial collection.

[Vault] Replace 'ADP' with 'EaaS'

---

src/content/certifications/exam-faqs/vault-associate-002.mdx
src/content/certifications/exam-faqs/vault-associate-003.mdx
src/content/certifications/programs/security-automation.json

- [Preview link](https://dev-portal-git-Certs_VaultAssociate_003-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](https://app.asana.com/0/1207927636763096/1208751379256112/f) 🎟️
New version of Vault Associate exam. This PR updates the 002 info and the 003 info on Developer

Vault associate 003

---

src/content/hcp/product-landing.json

Remove network collection

---

src/data/alert-banner.json

- [Preview link](https://dev-portal-git-leah-feathashitalks-banner-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1208691590278290/1208969326653432/f) 🎟️
This PR updates the dev-portal alert banner so it shows the information for hashitalks. It should have the same information as the [alert banner on www](https://www.hashicorp.com/)
1. Go to [preview link](https://dev-portal-git-leah-feathashitalks-banner-hashicorp.vercel.app/)
2. Verify alert banner is showing with the correct information

feat: update alert banner for hashitalks

---

src/content/certifications/exam-faqs/vault-associate-002.mdx
src/content/certifications/exam-faqs/vault-associate-003.mdx
src/content/certifications/programs/security-automation.json

- [Preview link](https://dev-portal-git-VaultAssoc_003_nov-hashicorp.vercel.app/certifications/security-automation) 🔎
- [Asana task](https://app.asana.com/0/1207927636763096/1208297821941817/f) 🎟️
* Add CM Connect registration link
* Remove reference to November dates
We're ready!

Vault Associate 003 Registration

---

src/content/vault/product-landing.json

- [Jira task](https://hashicorp.atlassian.net/browse/SPE-841?atlOrigin=eyJpIjoiNWM2ZjUzMjE1MTZkNDcxZThiNDAxZmU0ODY5ODllNWUiLCJwIjoiaiJ9) 🎟️
- Replace link to CLI quick start tutorials with link to ops/CLI quick start doc
- Retiring CLI quick start tutorials and redirecting to foundations collection

Replace link to CLI tutorial quickstart

---

src/content/vault/install-landing.json
src/pages/tutorials/library.tsx
src/views/docs-view/loaders/__fixtures__/index.mdx

- Remove references to CLI quick start tutorials
- Retiring CLI quick start collection

Remove Vault CLI quick start tutorials

---

src/content/certifications/exam-faqs/vault-associate-003.mdx

- [Preview link](https://dev-portal-git-VaultAssociate_fix-hashicorp.vercel.app/certifications/security-automation) 🔎
Fixed an error
#

Certs: fixed error in objectives

---

src/content/certifications/exam-faqs/vault-associate-003.mdx
src/content/certifications/programs/security-automation.json

- [Preview link](https://dev-portal-git-VaultAssoc003_Launch-hashicorp.vercel.app/certifications/security-automation) 🔎
- [Asana task](https://app.asana.com/0/1201255015193340/1208344084881598/f) 🎟️
* Remove Vault Associate 002 from DevDot
* Remove temporary text about 003 that is unnecessary after its launch
002 is retired; long live 003

Updated Vault associate 003 + removed 002 from dev site

---

src/content/vault/product-landing.json

https://hashicorp.slack.com/archives/C5FSPUGDS/p1737139802201349?thread_ts=1736954357.317859&cid=C5FSPUGDS
- [Preview link](https://dev-portal-git-Vault003_quickfix-hashicorp.vercel.app/vault) 🔎
Added new cert 003 relative link to fix issue when deleting existing cert exam link

change collection slug to 003

---

src/pages/validated-patterns/index.tsx

Only return notfound when there's an error in retrieving the data for validated-patterns

only return notfound if theres an error in retrieving the data

---

src/pages/validated-patterns/[...tutorialSlug]/index.tsx
src/pages/validated-patterns/[collectionSlug].tsx
src/pages/validated-patterns/index.tsx

Only return notfound when there's an error in retrieving the data for validated-patterns (doing it for tutorials and collections view)

Only return notfound if theres an error in retrieving the data (tutorials and collections)

---

src/content/certifications/programs/infrastructure-automation.json

- [Preview link](https://dev-portal-git-TA003_version-hashicorp.vercel.app/certifications) 🔎
changed version tested

TA003 change version tested

---

src/content/validated-patterns/index.json

Update Validated Patterns description

---

src/lib/products.ts

Add validated patterns to product dropdown

---

src/lib/remark-plugins/remark-rewrite-assets.ts

Bug fix for breaking preview builds.

Reuse url variable in remark-rewrite-assets

---

config/unified-docs-sandbox.json

This PR updates the `unified_docs_migrated_repos` flag to only include plugin framework repos. I think we should create another `dev-portal:development` image for the team to test the other repos.
This lets us update the [`web-unified-docs`](https://github.com/hashicorp/web-unified-docs) repo to only include plugin framework content when we launch
- [Asana task](https://app.asana.com/0/1209152747858598/1209408966538828) 🎟️

Update config so UDR uses plugin framework only

---

src/views/docs-view/loaders/__tests__/remote-content.test.ts
src/views/docs-view/loaders/remote-content.ts

This fixes the broken previous versions reported by the team. It checks if the path exists before it splits it.
Tested it successfully locally.
1. Start dev-portal locally `npm run start`
2. Go to a product documentation ([Boundary](http://localhost:3000/boundary/docs))
3. Select a [previous version](http://localhost:3000/boundary/docs/v0.16.x) in the dropdown
4. Verify it loads

Fix broken previous versions

---

build-libs/__tests__/redirects.test.ts
build-libs/redirects.js
config/base.json
config/development.json
src/components/command-bar/commands/search/unified-search/components/dialog-body/index.tsx
src/lib/__tests__/docs-content-fields.test.ts
src/lib/remark-plugins/remark-rewrite-assets.ts
src/lib/sitemap/docs-content-fields.ts
src/views/docs-view/loaders/remote-content.ts
src/views/docs-view/render-page-mdx.ts

- [Preview link](https://dev-portal-git-leah-featprep-for-plugin-framework-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1209152747858598/task/1209557885083366) 🎟️
This PR preps the dev-portal repo for the UDR product launch for terraform-plugin-framework repo. It removes the check for the `HASHI_ENV="unified-docs-sandbox" from most places and updates the base config to include the migrated repo. I also updated tests to remove the UDR sandbox check as well.
1. Checkout this branch
2. Change `UNIFIED_DOCS_API` to `http://localhost:8080`
3. In the UDR project, run `npm run prebuild` and then `npm run dev`
4. Start the dev-portal project by running `npm start`
5. Once both are ready, go to [terraform framework …

feat: prep PR for terraform-plugin-framework UDR launch

---

.env

- [Asana task](https://app.asana.com/1/90955849329269/project/1209152747858598/task/1209570986205873) 🎟️
Update unified docs repo to point to other alias URL (instead of web-presence-experimental-docs)
---
- https://app.asana.com/0/0/1209570986205873

Update UDR URL to web-unified-docs instead of web-presence-experimental-docs

---

src/content/certifications/exam-faqs/vault-associate-003.mdx

- [Preview link](https://dev-portal-git-vault/update-003-landing-hashicorp.vercel.app/certifications/security-automation#vault-associate-(003)-details) 🔎
- [Jira task](https://hashicorp.atlassian.net/browse/SPE-1127?atlOrigin=eyJpIjoiNzhiMjhmYjg4NjMzNDE1ZGJmYmJmZjU2ZjM2NmQ1ZGQiLCJwIjoiaiJ9) 🎟️
Adds API to objectives

Update security-autoamtion 003 5g heading

---

eslint.config.js
src/components/open-api-page/partials/collapsible/index.tsx
src/lib/__tests__/clamp.test.ts
src/pages/api/auth/[...nextauth].ts
src/views/open-api-docs-preview/components/open-api-preview-inputs/index.tsx

This PR resolves linting issues related to the `no-unused-expressions` linting rule.
I'd like to call out the changes in [this file](https://github.com/hashicorp/dev-portal/compare/rm/fix-linting...rm/no-unused-expressions?expand=1#diff-2a18708c9cc39fe196caafd397b0d9335fc19f352dceaacdc0527a287e52fec5) as they add ignore rules to a couple of expressions that exist to (to quote the comments) "force a re-paint". I'm not sure they have any functional impact at all, and rather than simply ignore them I'd prefer to actually resolve the issue properly. I'd love to get input on if there's a better way to address …

@typescript-eslint/no-unused-expressions

---

package-lock.json
package.json
src/components/author-primitives/consul/config-entry-reference/index.jsx
src/components/author-primitives/packer/checklist/index.jsx
src/components/author-primitives/shared/placement-table/index.jsx
src/components/author-primitives/vault/columns/index.jsx
src/components/author-primitives/vault/inline-tag/index.jsx
src/pages/_error.jsx

This PR resolves linting issues related to the `react/prop-types` linting rule.

Add react prop types

---

src/data/terraform.json

- [Preview link](https://dev-portal-git-rln/update-terraform-docs-header-hashicorp.vercel.app/terraform/docs) 🔎
- [Slack Conversation](https://hashicorp.slack.com/archives/GPR88PGF5/p1741803752418569) 🎟️
Update header on Terraform Documentation landing page
Style.

Update H1 on /terraform/docs

---

build-libs/redirects.js
next.config.js

- [🎟️ Feature: Add preview redirect support](https://app.asana.com/0/1209399665311208/1209402819381995/f)
Enable redirects in UDR preview builds
This PR will have no effect on prod, as the code it runs is gated by 
[`if (isDeveloperBuild) {`](https://github.com/hashicorp/dev-portal/pull/2721/files#diff-00a4f13d760b82b998bcae3d31b5fbd8d2e9edf400c352dfa980ecb82fdf8024L86).
To test it the UDR PR should be tested: https://github.com/hashicorp/web-unified-docs/pull/221

Allow UDR preview builds to download redirects

---

src/components/dropdown-disclosure/components/list-item/index.tsx
src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
src/views/profile/account-view/index.tsx

- [Preview link](https://dev-portal-git-fix-posthog-capture-hashicorp.vercel.app/profile/account) 🔎
- [Asana task](https://app.asana.com/0/1209145071154849/1209865493752084/f) 🎟️
Masks user email and id in session replays.
Increased security measures
Using [posthog docs](https://posthog.com/docs/session-replay/privacy#other-elements) on hiding elements.

Fix posthog capture mask

---

src/hooks/bookmarks/use-bookmark-mutations.ts
src/lib/learn-client/api/bookmark/__tests__/create-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/delete-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-all-bookmarks.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-bookmark.test.ts
src/lib/learn-client/api/bookmark/__tests__/get-bookmarks-by-tutorial-ids.test.ts

- [Preview link](https://dev-portal-git-leah-fixtsfixme-bookmarks-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1209314279859096/1209744003484107/f) 🎟️
This PR fixes the $TSFixMe types for the bookmarks related files. 
1. Verify the tests for this PR pass
2. Checkout this branch and run `npm start`
3. Go to your profile and verify that bookmarks are working as expected

fix: update tsfixme types for bookmarks

---

scripts/docs-content-link-rewrites/helpers/fetch-nav-data-for-repo-and-base-path.ts
scripts/docs-content-link-rewrites/helpers/get-all-page-paths-for-base-path-and-repo.ts
scripts/docs-content-link-rewrites/helpers/get-paths-from-nav-data.ts
scripts/docs-content-link-rewrites/types.ts

- [Asana task](https://app.asana.com/0/1209314279859096/1209744003484105/f) 🎟️
This PR updates the $TSFixMe types in the docs-content-link-rewrites files. I got the types by logging what each unknown variable was while running `REPO=consul npm run test:e2e:linkRewrites:loadData` 
1. Run the e2e test suite that loads this data: `REPO=consul npm run test:e2e:linkRewrites:loadData` and verify that there are no errors

fix: update TSFixMe from docs-content-link-rewrites files

---

config/base.json
config/development.json
config/unified-docs-sandbox.json

Reverts hashicorp/dev-portal#2734

Revert "Set terraform-docs-agents to load from UDR"

---

config/base.json
config/development.json
config/unified-docs-sandbox.json

This reverts commit 771425c0b7972ab06a4a7b247ac7b6163ba73485.

Reapply "Set terraform-docs-agents to load from UDR" (#2735)

---

src/pages/hcp/api-docs/rbac/[[...page]].tsx

Added  a api doc page component to back the hcp APIs RBAC link
The HCP RBAC API link had gone live but was not rendering, this enables the doc page.

adding page component for HCP RBAC API docs

---

package-lock.json
package.json

- [Preview link](https://dev-portal-git-leah-choreaudit-io-components-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1208440225519245/task/1209887029335163?focus=true) 🎟️
This PR removes an unused package from the package.json and package-lock.json files. During the io shared component cleanup, it was discovered that this package is not being used in dev-portal so this PR removes it.
1. Go to [dev portal preview](https://dev-portal-git-leah-choreaudit-io-components-hashicorp.vercel.app/)
2. Verify everything is working normally

chore: audit io components

---

config/unified-docs-sandbox.json

This PR adds terraform-cdk to the unified-docs-sandbox env so it will show up on UDR preview links.

feat: update UDR sandbox env repos

---

config/base.json
config/development.json

- [Preview link](https://dev-portal-git-leah-featprep-terraform-cdk-udr-launch-hashicorp.vercel.app/terraform/cdktf) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1209399665311208/task/1210103056568499?focus=true) 🎟️
This PR preps the dev-portal repo for the UDR product launch for terraform-cdk. It updates the base and development config to include the migrated repo.
1. Go to [preview link](https://dev-portal-git-leah-featprep-terraform-cdk-udr-launch-hashicorp.vercel.app/terraform/cdktf)
2. Inspect the image on that page
3. Verify that the source is coming from web-unified-docs using the dev tools
4. Make sure the other pages/version selector/any other thing you want to test for terraform-cdk is working
5. Go to a [non-terraform …

feat: prep terraform-cdk udr launch

---

src/content/hcp/product-landing.json

- [Preview link](https://dev-portal-git-radar-highlight-ops-collection-hashicorp.vercel.app/hcp) 🔎
- [Jira task](https://hashicorp.atlassian.net/jira/software/c/projects/SPE/boards/682?quickFilter=1292&selectedIssue=SPE-1147) 🎟️
- Replace HVS quick start on landing page with Radar quick start
- Radar GA
-

Highlight quick start

---

src/pages/hcp/api-docs/hvn/[[...page]].tsx

- [Preview link](https://dev-portal-git-leah-feathvn-api-docs-hashicorp.vercel.app/hcp/api-docs/hvn) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1209314279859096/task/1210345451546962?focus=true) 🎟️
This PR adds HCP HVN api docs based off their [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-network/stable/2020-09-07/hcp.swagger.json). This page follows the conventions we have for other api-docs pages so it is mostly a copy/paste.
1. Go to [preview link](https://dev-portal-git-leah-feathvn-api-docs-hashicorp.vercel.app/hcp/api-docs/hvn)
2. Verify docs match [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-network/stable/2020-09-07/hcp.swagger.json)

feat: add hcp hvn api docs

---

src/content/hcp/docs-landing.json
src/content/hcp/product-landing.json
src/content/vault/docs-landing.json

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/hcp/) 🔎
- Remove HVS links from HCP and Vault landing pages
- HVS EOS announcement

Remove HVS links from landing pages

---

next.config.js
package-lock.json
package.json

- [Preview link](https://dev-portal-git-rn-add-udr-to-image-domains-hashicorp.vercel.app/terraform/docs/partnerships#terraform-enterprise-integrations) 🔎
Images loaded in an `ImageConfig` were not loading, due to not being allowlisted in the next config domains. This was happening on https://developer.hashicorp.com/terraform/docs/partnerships#terraform-enterprise-integrations.

Add UDR to image domains

---

src/pages/hcp/api-docs/operations/[[...page]].tsx

- [Preview link](https://dev-portal-git-leah-featcloud-op-api-docs-hashicorp.vercel.app/hcp/api-docs/operations) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1210414114001200/task/1210546864604061?focus=true) 🎟️
This PR adds HCP operations api docs based off their [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-operation/stable/2020-05-05/hcp.swagger.json). This page follows the conventions we have for other api-docs pages so it is mostly a copy/paste.
1. Go to [preview link](https://dev-portal-git-leah-featcloud-op-api-docs-hashicorp.vercel.app/hcp/api-docs/operations)
2. Verify docs match the [swagger spec](https://github.com/hashicorp/hcp-specs/blob/main/specs/cloud-operation/stable/2020-05-05/hcp.swagger.json)

feat: add hcp api docs for operations

---

config/base.json
config/development.json
src/hooks/use-authentication/index.ts

Vault has been migrated to udr
- [Asana task](https://app.asana.com/1/90955849329269/project/1210546436661486/task/1210755072083060?focus=true) 🎟️
Added vault to the config files
Flags are needed as vault has been moved to UDR
The config files have been updated with the correct flag for vault.

chore: added udr source

---

config/base.json
config/development.json
src/hooks/use-authentication/index.ts

Reverts hashicorp/dev-portal#2784

Revert "chore: added udr source"

---

src/components/mobile-menu-levels-generic/index.tsx
src/components/navigation-header/components/dropdown-menu/index.tsx
src/components/sidebar/index.tsx
src/pages/tutorials/library.tsx
src/views/profile/sidebar/index.tsx

- [Preview link](https://dev-portal-git-leah-chorecleanup-promo-experiment-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1210146125607813/task/1210847713365605?focus=true) 🎟️
The [promo placement experiment](https://eu.posthog.com/project/29987/experiments/59097) has finished and the variant (promo on top) won. This PR removes the experiment related code and updates it so the variant is active
1. Go to [preview link](https://dev-portal-git-leah-chorecleanup-promo-experiment-hashicorp.vercel.app/)
2. Open product dropdown
3. Verify the promo is at the top of the dropdown for desktop and mobile

chore: remove promo experiment code and ship variant

---

src/content/boundary/product-landing.json
src/content/consul/product-landing.json
src/content/nomad/product-landing.json
src/content/terraform/product-landing.json
src/content/vault/product-landing.json

This PR adds a "sandbox" section to each product landing page (where applicable). The goal of this PR is to increase discoverability and drive traffic to sandboxes. 
- [Terraform Preview link](https://dev-portal-git-add-sandbox-to-product-landing-hashicorp.vercel.app/terraform) 🔎
- [Nomad Preview link](https://dev-portal-git-add-sandbox-to-product-landing-hashicorp.vercel.app/nomad) 🔎
- [Vault Preview link](https://dev-portal-git-add-sandbox-to-product-landing-hashicorp.vercel.app/vault) 🔎
- [Boundary Preview link](https://dev-portal-git-add-sandbox-to-product-landing-hashicorp.vercel.app/boundary) 🔎

Add sandbox callouts to product landing page

---

src/content/certifications/README.md
src/content/certifications/registration.json
src/content/certifications/registration.mdx

- [Asana task](https://app.asana.com/1/90955849329269/project/1210146125607830/task/1210872810323234?focus=true) 🎟️
This PR adds the copy to be used for the certifications registration page (name still tbd). It will be used in another PR to render the content. This PR is getting merged into the certifications assembly branch so it can be merged right away. Any other updates to the copy will be made in other PRs but this should be enough to get development work moving along.
This does not need to be tested yet as it is not rendered anywhere yet.

feat: add content for certifications registration page

---

src/views/certifications/views/registration/index.tsx

- [Preview link](https://dev-portal-git-leah-featcert-reg-mdx-components-hashicorp.vercel.app/certifications/registration) 🔎
- [Asana task](https://app.asana.com/1/90955849329269/project/1206815131022336/task/1210872813172505?focus=true) 🎟️
This PR updates the mdx component used for the Tooltip for the cert reg page. It uses the `<InlineAlert />` component to keep consistency with existing styles on devdot.
1. Go to [preview link](https://dev-portal-git-leah-featcert-reg-mdx-components-hashicorp.vercel.app/certifications/registration)
2. Verify the tool tip in the second block matches the [figma designs](https://www.figma.com/design/scZQHUyaKbVnUEV8nCRdlB/Certifications-dot-com-%3C--%3E-dev-dot?node-id=3315-2618&m=dev)

feat: update component for tooltip for cert reg page

---

.env

- [Preview link](https://dev-portal-git-leah-fixupdate-algolia-search-key-hashicorp.vercel.app/) 🔎
- [Slack thread](https://hashicorp.slack.com/archives/C02T80JTNS2/p1754584715965199)
This PR updates the algolia public search key. This key is old and was refreshed a while ago. The reason there was not an issue with this old token is because we have the new one saved as a vercel env variable that overrides this file. This only is an issue for the dev-portal docker builds that do not have the new search key as an environment variable.
1. Go to [preview](https://dev-portal-git-leah-fixupdate-algolia-search-key-hashicorp.vercel.app/)
2. Click the search bar and type in something
3. Verify that you are seeing search results

fix: update algolia public search key

---

src/components/footer/footer.module.css
src/components/footer/index.tsx

Add message in footer to remind folks that stdin is not a tty
- [Preview link](https://dev-portal-git-vagrant-easter-egg-hashicorp.vercel.app/) 🔎

stdin is not a tty
